In [1]:
import pandas as pd
df_bm25 = pd.read_parquet("bm25_top10.parquet")
df_sen_transformer = pd.read_parquet("sen_transformer_top_10.parquet")

In [2]:
df_bm25

,123839,188629,13898,316959,515031,123783,4332,9591,114982,563603,...,66818,862773,11326,896124,12319,4421,296526,341793,270009,110149
0,806300,2185399,13898,1326263,888195,1210005,989116,2416624,2305139,390174,...,66818,1395771,2047737,906780,12319,566613,802604,1447150,empty,empty
1,123839,1990307,2213954,930698,887826,123783,1442076,908435,1341103,2207107,...,358047,1671141,11326,1720286,276196,567146,1930537,1901595,empty,empty
2,806326,188629,2108627,316959,515031,1209576,4332,138626,2305216,373237,...,1588006,1395725,1630363,1938239,1670681,1128206,561052,341793,empty,empty
3,836567,2191096,1921403,348869,1176215,1675282,1815319,390102,2444081,12846,...,889006,1395776,1224804,1500863,1778275,1438630,1584384,1596837,empty,empty
4,806075,1919943,1874948,1836641,1569953,1630942,1991105,1898638,1191721,349302,...,751723,1434303,1337294,1209146,1675166,2278146,128653,1534668,empty,empty
5,1793430,2304431,2216860,2156815,1125994,1214652,1090555,2250838,917379,563603,...,28752,1406415,2202318,380630,81009,1450334,1295704,398261,empty,empty
6,806263,1046396,1698181,881673,836749,2200269,1516841,143444,2303696,394294,...,309952,862773,1338231,1782146,2086809,381372,2195949,2240196,empty,empty
7,799188,2296288,1440180,2215542,832086,579503,116674,1966629,1672157,270469,...,359824,1551102,1137830,561358,1778752,1861483,2054046,585065,empty,empty
8,1727316,2129645,2248373,1525222,1382041,419894,1903340,1483036,2304325,1233547,...,386220,1395758,1542023,2312223,646010,920305,2089089,1542968,empty,empty
9,1901730,2290269,2336616,1465433,268224,810375,928308,1759147,empty,219324,...,552255,1377126,1768494,1900646,2086621,1630486,822322,581557,empty,empty

In [3]:
df_sen_transformer

,123839,188629,13898,316959,515031,123783,4332,9591,114982,563603,...,37970,2612,66818,862773,11326,896124,12319,4421,296526,341793
0,516871,188629,13898,316959,515031,2267777,4332,9591,725799,251631,...,37970,746818,66818,862773,1161272,747395,891422,1786733,1633820,341793
1,647478,251586,785960,562691,706326,421974,615358,143444,1454057,12846,...,580876,1137023,386220,1426706,11326,2054921,12319,1297589,718007,1857381
2,2129172,2397950,1382760,1326263,780987,1630942,1712050,1898638,1478113,273547,...,177545,2612,287026,865851,1517411,573381,276196,1111917,1901019,576283
3,806300,2061524,941146,2156815,832086,1209576,2361455,595391,2304325,563603,...,484539,1084496,2387535,2272303,623784,538460,2073704,365980,420896,2303264
4,2357011,272146,802532,687712,842375,2322923,1297050,1445185,294327,840695,...,736630,1963277,532111,189807,1636981,1038074,1119295,1554833,296526,576336
5,1222510,1948304,1048798,42143,860147,152040,1878340,2378793,2352224,2091601,...,154939,1089914,242676,1964415,1210930,561358,2086621,1224508,128653,2197644
6,806263,2437665,1989378,1639962,828931,116684,1438336,1472431,95752,2307963,...,208832,348197,309952,319262,1207519,2253573,1670681,1584239,1901020,1174734
7,2433706,1278316,1874948,1469362,833668,2117771,2342190,494103,2352254,2146572,...,2313722,1304252,1376367,2126545,272778,896124,373696,2271988,194498,876840
8,708880,1614942,2031249,729083,754830,1411855,774950,2021787,102670,2152054,...,1110574,858691,889006,275965,1901218,2121565,173798,2283929,1438397,576278
9,775424,1363774,462902,1422464,823332,123783,1913962,863960,2298231,1674515,...,718515,353802,775005,1653529,653832,2331828,2110002,1227506,1265304,355461

In [7]:
def formula(index: int) -> float:
    return 1 / (60 + index)

In [8]:
def reciprocal_rank_fusion(bm25: list, sen_transformer: list) -> list:
    set_of_examined = set()
    tuple_list = []

    for i,doc_id in enumerate(bm25):
        if doc_id != "empty":
            set_of_examined.add(doc_id)

            doc_score = 0

            doc_score += formula(i + 1)

            for j in range(len(sen_transformer)):
                if sen_transformer[j] == doc_id:
                    doc_score += formula(j + 1)
                    break

            tuple_list.append((doc_score, doc_id))

    for i in range(len(sen_transformer)):
        doc_id = sen_transformer[i]

        if doc_id not in set_of_examined:
            set_of_examined.add(doc_id)
            tuple_list.append((formula(i + 1), doc_id))

    tuple_list.sort(reverse=True)
    return tuple_list

In [9]:
import ir_datasets
dataset = ir_datasets.load("wikir/en1k/training")

In [10]:
query_ids = [query.query_id for query in dataset.queries_iter()]
query_ids

['123839',
 '188629',
 '13898',
 '316959',
 '515031',
 '123783',
 '4332',
 '9591',
 '114982',
 '563603',
 '104206',
 '1580851',
 '23678',
 '37480',
 '109454',
 '544250',
 '12519',
 '115015',
 '84287',
 '24998',
 '11925',
 '643',
 '113075',
 '1250387',
 '72012',
 '167865',
 '1425120',
 '24883',
 '27200',
 '136856',
 '6031',
 '1313191',
 '187115',
 '84110',
 '208234',
 '6431',
 '10799',
 '1417144',
 '32512',
 '677637',
 '97937',
 '113765',
 '12900',
 '1294909',
 '73745',
 '11692',
 '22173',
 '76662',
 '164301',
 '23344',
 '9367',
 '592217',
 '98546',
 '98175',
 '15189',
 '1256',
 '1815937',
 '1249076',
 '80274',
 '38489',
 '11311',
 '4754',
 '257711',
 '141668',
 '100895',
 '32945',
 '112321',
 '133725',
 '424464',
 '523456',
 '1327515',
 '12101',
 '9739',
 '189869',
 '143444',
 '78940',
 '12527',
 '327199',
 '7707',
 '97455',
 '1262433',
 '488875',
 '74026',
 '358108',
 '95179',
 '7862',
 '151797',
 '92980',
 '100876',
 '238228',
 '107755',
 '32539',
 '12953',
 '24843',
 '119528',
 '30765',
 '134772',
 '27711',
 '361260',
 '17874',
 '3524',
 '75902',
 '809894',
 '126362',
 '288208',
 '406254',
 '240663',
 '34848',
 '195113',
 '264822',
 '8387',
 '186363',
 '165761',
 '76875',
 '605155',
 '17836',
 '83566',
 '132697',
 '1563',
 '23924',
 '1433',
 '29737',
 '26758',
 '19717',
 '7870',
 '16093',
 '34844',
 '2234455',
 '382531',
 '12252',
 '11446',
 '21027',
 '1370698',
 '113657',
 '3348',
 '217425',
 '197576',
 '129397',
 '257126',
 '67592',
 '93136',
 '892237',
 '20605',
 '1219',
 '389032',
 '10656',
 '1778',
 '108160',
 '964897',
 '94266',
 '13744',
 '13539',
 '407598',
 '97620',
 '203795',
 '356090',
 '112731',
 '714608',
 '88181',
 '87960',
 '96791',
 '172084',
 '1836051',
 '14393',
 '1559299',
 '82801',
 '969771',
 '125685',
 '101336',
 '78856',
 '126985',
 '231130',
 '197161',
 '94693',
 '1339737',
 '273381',
 '73398',
 '179677',
 '90354',
 '1608685',
 '446634',
 '1595',
 '73102',
 '494392',
 '94832',
 '24349',
 '12374',
 '151391',
 '584158',
 '15282',
 '434927',
 '21969',
 '15987',
 '13776',
 '768304',
 '132575',
 '833105',
 '76345',
 '537',
 '181536',
 '4215',
 '17227',
 '97781',
 '1589',
 '119663',
 '1336894',
 '1568489',
 '133700',
 '147768',
 '674995',
 '1047896',
 '6368',
 '172053',
 '1045273',
 '80687',
 '1263864',
 '81739',
 '113925',
 '73285',
 '27399',
 '35101',
 '5570',
 '14758',
 '10792',
 '726995',
 '17814',
 '908',
 '85435',
 '79941',
 '140552',
 '145807',
 '107616',
 '13801',
 '357261',
 '34865',
 '2259',
 '6213',
 '72576',
 '163527',
 '75654',
 '29687',
 '1283640',
 '1703622',
 '324633',
 '37756',
 '1237543',
 '342167',
 '1058358',
 '248154',
 '330931',
 '163736',
 '488869',
 '20603',
 '8055',
 '109832',
 '9332',
 '204974',
 '339255',
 '22113',
 '94641',
 '10825',
 '71636',
 '2078947',
 '146007',
 '11481',
 '1282373',
 '605568',
 '276580',
 '190225',
 '26652',
 '14325',
 '23815',
 '119102',
 '17755',
 '29896',
 '26093',
 '1272415',
 '94442',
 '260160',
 '152382',
 '883324',
 '71191',
 '178216',
 '1408773',
 '6047',
 '1410732',
 '37218',
 '22295',
 '12601',
 '15200',
 '14027',
 '545390',
 '81411',
 '1324050',
 '8669',
 '21961',
 '612261',
 '389274',
 '39839',
 '90512',
 '185712',
 '302505',
 '2623',
 '1343759',
 '725960',
 '5554',
 '180826',
 '22170',
 '203549',
 '270009',
 '110384',
 '296861',
 '6835',
 '19342',
 '18363',
 '226344',
 '37955',
 '19145',
 '14445',
 '605066',
 '2228',
 '2613',
 '1742574',
 '28296',
 '100963',
 '561358',
 '13460',
 '85285',
 '4925',
 '104339',
 '183397',
 '156457',
 '284',
 '34937',
 '76048',
 '164182',
 '411597',
 '422208',
 '3522',
 '73430',
 '113428',
 '9399',
 '2243',
 '157351',
 '2842',
 '377416',
 '4855',
 '4397',
 '1846628',
 '75969',
 '635597',
 '2581',
 '20437',
 '76039',
 '9356',
 '22213',
 '1250',
 '70969',
 '1349',
 '6644',
 '103434',
 '384474',
 '1669212',
 '596568',
 '98507',
 '128283',
 '815972',
 '5816',
 '1344825',
 '11029',
 '82288',
 '639167',
 '80536',
 '254180',
 '97274',
 '4722',
 '159099',
 '25706',
 '104011',
 '6033',
 '14011',
 '4616',
 '6482',
 '310032',
 '25193',
 '27720',
 '21972',
 '633954',
 '37908',
 '1870966',
 '487985',
 '105462',
 '510206',
 '7560',
 '12705',
 '117619',
 '305484',
 '1090430',
 '1777480',
 '1268117',
 '1289085',
 '1338779',
 '1817436',
 '24242',
 '20898',
 '16880',
 '37945',
 '4085',
 '2130523',
 '18091',
 '19675',
 '78817',
 '5400',
 '32411',
 '1322',
 '188952',
 '4720',
 '25242',
 '763957',
 '84315',
 '107129',
 '7407',
 '83325',
 '526775',
 '5204',
 '1787',
 '112402',
 '92302',
 '2986',
 '161918',
 '71995',
 '18192',
 '85636',
 '26444',
 '6390',
 '134543',
 '923020',
 '834741',
 '184241',
 '88748',
 '391276',
 '8899',
 '26219',
 '8938',
 '166642',
 '24861',
 '1352',
 '16006',
 '473460',
 '210583',
 '75859',
 '6879',
 '152885',
 '238499',
 '473275',
 '196310',
 '5896',
 '5002',
 '226743',
 '110572',
 '543',
 '26103',
 '208058',
 '68416',
 '895072',
 '12773',
 '1182701',
 '13957',
 '28752',
 '6227',
 '119284',
 '273555',
 '17203',
 '609350',
 '117495',
 '1641154',
 '1705',
 '19435',
 '154661',
 '108269',
 '7026',
 '165900',
 '131685',
 '9643',
 '1515',
 '34957',
 '88458',
 '152413',
 '479595',
 '7647',
 '6264',
 '29411',
 '75908',
 '71994',
 '27795',
 '704769',
 '2274',
 '12626',
 '639949',
 '207327',
 '1274160',
 '10688',
 '24454',
 '128712',
 '181363',
 '80',
 '10413',
 '120973',
 '145081',
 '206583',
 '24782',
 '1365055',
 '317887',
 '740767',
 '73024',
 '25238',
 '56872',
 '5219',
 '42749',
 '1444121',
 '24145',
 '93598',
 '24066',
 '5065',
 '123063',
 '14451',
 '301383',
 '197016',
 '141405',
 '159773',
 '6138',
 '26051',
 '1712787',
 '73768',
 '12699',
 '121064',
 '681120',
 '81877',
 '197769',
 '173023',
 '194810',
 '370139',
 '21892',
 '77940',
 '108305',
 '10456',
 '243438',
 '352646',
 '23335',
 '4559',
 '762',
 '95338',
 '422214',
 '10221',
 '22149',
 '1403468',
 '9022',
 '70754',
 '7353',
 '79109',
 '9106',
 '2032420',
 '1270810',
 '102991',
 '366863',
 '750376',
 '98133',
 '1194068',
 '13415',
 '764844',
 '849899',
 '448622',
 '927392',
 '1063349',
 '128187',
 '1614640',
 '477200',
 '9748',
 '157369',
 '22800',
 '80219',
 '1403378',
 '146323',
 '97591',
 '80765',
 '125608',
 '351608',
 '81103',
 '4334',
 '21439',
 '113621',
 '90496',
 '2547',
 '488858',
 '217759',
 '189034',
 '90382',
 '814731',
 '14032',
 '75643',
 '1662573',
 '479233',
 '187769',
 '38035',
 '155722',
 '70941',
 '88077',
 '1683175',
 '30883',
 '289837',
 '28823',
 '34394',
 '19625',
 '110332',
 '92668',
 '11644',
 '133621',
 '86063',
 '1731034',
 '109201',
 '236830',
 '86499',
 '15015',
 '1467096',
 '518649',
 '1529682',
 '389454',
 '20213',
 '97540',
 '159101',
 '10524',
 '466077',
 '374708',
 '135038',
 '129387',
 '593570',
 '99196',
 '32938',
 '9755',
 '1421273',
 '13706',
 '226734',
 '100123',
 '1640988',
 '133233',
 '1608',
 '1264172',
 '1594725',
 '157511',
 '13850',
 '15277',
 '131074',
 '17237',
 '3249',
 '13326',
 '1814473',
 '1156870',
 '25280',
 '323708',
 '13016',
 '222183',
 '10968',
 '109940',
 '129732',
 '118690',
 '179517',
 '12198',
 '19019',
 '434541',
 '1248',
 '319553',
 '252889',
 '138439',
 '35022',
 '182032',
 '13954',
 '136151',
 '12030',
 '21583',
 '15741',
 '489',
 '11435',
 '6649',
 '14868',
 '37861',
 '248820',
 '1727920',
 '121664',
 '377463',
 '110662',
 '11420',
 '13685',
 '1685919',
 '1274158',
 '23083',
 '14139',
 '166211',
 '161907',
 '721863',
 '110381',
 '27264',
 '672596',
 '161341',
 '114943',
 '37957',
 '108695',
 '479110',
 '129109',
 '16266',
 '399420',
 '759288',
 '34119',
 '10963',
 '14608',
 '283712',
 '266655',
 '203968',
 '1313526',
 '7836',
 '119662',
 '140457',
 '1276229',
 '110281',
 '5195',
 '100816',
 '5103',
 '429845',
 '4088',
 '11072',
 '17962',
 '1254149',
 '8394',
 '305914',
 '665122',
 '13888',
 '126682',
 '133726',
 '154029',
 '1116',
 '172058',
 '55300',
 '374325',
 '23079',
 '2120001',
 '114890',
 '4831',
 '111289',
 '165585',
 '214810',
 '126571',
 '7755',
 '13630',
 '918270',
 '83187',
 '9865',
 '122086',
 '11428',
 '314278',
 '1062661',
 '503034',
 '155036',
 '446428',
 '10976',
 '20434',
 '3544',
 '25445',
 '717881',
 '71381',
 '117555',
 '682338',
 '245828',
 '35568',
 '20021',
 '606000',
 '38408',
 '114257',
 '332492',
 '15319',
 '229404',
 '5781',
 '20183',
 '9603',
 '192096',
 '79820',
 '411516',
 '77789',
 '1313521',
 '388950',
 '109985',
 '1585',
 '264823',
 '22226',
 '164723',
 '9041',
 '71649',
 '88210',
 '128218',
 '212288',
 '211013',
 '79',
 '438884',
 '1099352',
 '99045',
 '274498',
 '134029',
 '35023',
 '2402726',
 '13373',
 '2938',
 '103786',
 '88775',
 '809',
 '1032451',
 '35036',
 '89567',
 '170548',
 '22672',
 '82044',
 '123639',
 '20906',
 '7769',
 '385089',
 '24704',
 '2266',
 '677582',
 '90428',
 '9454',
 '211320',
 '161909',
 '1964',
 '115785',
 '409207',
 '232564',
 '9137',
 '9492',
 '497039',
 '78081',
 '2070217',
 '77289',
 '7611',
 '235972',
 '19574',
 '70946',
 '956',
 '179671',
 '11448',
 '805510',
 '36957',
 '228293',
 '23327',
 '19017',
 '344485',
 '1558158',
 '76587',
 '26910',
 '1148665',
 '1932345',
 '555050',
 '121447',
 '73560',
 '151629',
 '23266',
 '4647',
 '101622',
 '112935',
 '27673',
 '18788',
 '32955',
 '242902',
 '90776',
 '105401',
 '843489',
 '18207',
 '36683',
 '15712',
 '14076',
 '9681',
 '219237',
 '1031987',
 '6502',
 '106031',
 '225142',
 '15420',
 '84194',
 '133570',
 '6815',
 '1357000',
 '205081',
 '15850',
 '197853',
 '14293',
 '457924',
 '128345',
 '1407356',
 '103335',
 '23918',
 '269840',
 '161933',
 '20681',
 '90437',
 '114728',
 '129948',
 '126860',
 '9765',
 '2113',
 '748790',
 '17645',
 '120677',
 '108913',
 '88958',
 '15351',
 '396742',
 '182986',
 '10946',
 '35538',
 '14314',
 '479034',
 '22120',
 '488649',
 '7022',
 '133309',
 '37830',
 '102670',
 '233552',
 '92119',
 '79532',
 '146760',
 '15425',
 '8877',
 '448',
 '1117181',
 '132661',
 '2473',
 '164285',
 '11145',
 '1407349',
 '9379',
 '1909580',
 '111964',
 '10329',
 '18137',
 '13676',
 '26442',
 '6326',
 '75046',
 '746557',
 '11138',
 '15463',
 '22402',
 '23936',
 '32442',
 '7607',
 '103543',
 '1900776',
 '1973651',
 '7276',
 '1387',
 '5590',
 '9780',
 '8882',
 '81156',
 '189807',
 '87882',
 '17047',
 '864775',
 '167358',
 '97923',
 '25611',
 '1407055',
 '213595',
 '2175',
 '17512',
 '21907',
 '781',
 '1584920',
 '187188',
 '358658',
 '189862',
 '8610',
 '239821',
 '97945',
 '119644',
 '337441',
 '80187',
 '15355',
 '1310225',
 '254991',
 '91502',
 '1205882',
 '88824',
 '120183',
 '106926',
 '4383',
 '272146',
 '127768',
 '1313596',
 '1522224',
 '25771',
 '23005',
 '5326',
 ...]

In [11]:
from collections import defaultdict
query_and_hybrid_scores = defaultdict(list)

for query_id in query_ids:
    query_and_hybrid_scores[query_id] = reciprocal_rank_fusion(
        bm25=list(df_bm25[query_id]),
        sen_transformer=list(df_sen_transformer[query_id])
    )

query_and_hybrid_scores = dict(query_and_hybrid_scores)

In [12]:
query_and_hybrid_scores

{'123839': [(0.032018442622950824, '806300'),
  (0.029850746268656716, '806263'),
  (0.01639344262295082, '516871'),
  (0.016129032258064516, '647478'),
  (0.016129032258064516, '123839'),
  (0.015873015873015872, '806326'),
  (0.015873015873015872, '2129172'),
  (0.015625, '836567'),
  (0.015384615384615385, '806075'),
  (0.015384615384615385, '2357011'),
  (0.015151515151515152, '1793430'),
  (0.015151515151515152, '1222510'),
  (0.014705882352941176, '799188'),
  (0.014705882352941176, '2433706'),
  (0.014492753623188406, '708880'),
  (0.014492753623188406, '1727316'),
  (0.014285714285714285, '775424'),
  (0.014285714285714285, '1901730')],
 '188629': [(0.032266458495966696, '188629'),
  (0.01639344262295082, '2185399'),
  (0.016129032258064516, '251586'),
  (0.016129032258064516, '1990307'),
  (0.015873015873015872, '2397950'),
  (0.015625, '2191096'),
  (0.015625, '2061524'),
  (0.015384615384615385, '272146'),
  (0.015384615384615385, '1919943'),
  (0.015151515151515152, '2304431'),
  (0.015151515151515152, '1948304'),
  (0.014925373134328358, '2437665'),
  (0.014925373134328358, '1046396'),
  (0.014705882352941176, '2296288'),
  (0.014705882352941176, '1278316'),
  (0.014492753623188406, '2129645'),
  (0.014492753623188406, '1614942'),
  (0.014285714285714285, '2290269'),
  (0.014285714285714285, '1363774')],
 '13898': [(0.03278688524590164, '13898'),
  (0.030090497737556562, '1874948'),
  (0.016129032258064516, '785960'),
  (0.016129032258064516, '2213954'),
  (0.015873015873015872, '2108627'),
  (0.015873015873015872, '1382760'),
  (0.015625, '941146'),
  (0.015625, '1921403'),
  (0.015384615384615385, '802532'),
  (0.015151515151515152, '2216860'),
  (0.015151515151515152, '1048798'),
  (0.014925373134328358, '1989378'),
  (0.014925373134328358, '1698181'),
  (0.014705882352941176, '1440180'),
  (0.014492753623188406, '2248373'),
  (0.014492753623188406, '2031249'),
  (0.014285714285714285, '462902'),
  (0.014285714285714285, '2336616')],
 '316959': [(0.032266458495966696, '316959'),
  (0.032266458495966696, '1326263'),
  (0.030776515151515152, '2156815'),
  (0.016129032258064516, '930698'),
  (0.016129032258064516, '562691'),
  (0.015625, '348869'),
  (0.015384615384615385, '687712'),
  (0.015384615384615385, '1836641'),
  (0.015151515151515152, '42143'),
  (0.014925373134328358, '881673'),
  (0.014925373134328358, '1639962'),
  (0.014705882352941176, '2215542'),
  (0.014705882352941176, '1469362'),
  (0.014492753623188406, '729083'),
  (0.014492753623188406, '1525222'),
  (0.014285714285714285, '1465433'),
  (0.014285714285714285, '1422464')],
 '515031': [(0.032266458495966696, '515031'),
  (0.030330882352941176, '832086'),
  (0.01639344262295082, '888195'),
  (0.016129032258064516, '887826'),
  (0.016129032258064516, '706326'),
  (0.015873015873015872, '780987'),
  (0.015625, '1176215'),
  (0.015384615384615385, '842375'),
  (0.015384615384615385, '1569953'),
  (0.015151515151515152, '860147'),
  (0.015151515151515152, '1125994'),
  (0.014925373134328358, '836749'),
  (0.014925373134328358, '828931'),
  (0.014705882352941176, '833668'),
  (0.014492753623188406, '754830'),
  (0.014492753623188406, '1382041'),
  (0.014285714285714285, '823332'),
  (0.014285714285714285, '268224')],
 '123783': [(0.03149801587301587, '1209576'),
  (0.03125763125763126, '1630942'),
  (0.0304147465437788, '123783'),
  (0.01639344262295082, '2267777'),
  (0.01639344262295082, '1210005'),
  (0.016129032258064516, '421974'),
  (0.015625, '1675282'),
  (0.015384615384615385, '2322923'),
  (0.015151515151515152, '152040'),
  (0.015151515151515152, '1214652'),
  (0.014925373134328358, '2200269'),
  (0.014925373134328358, '116684'),
  (0.014705882352941176, '579503'),
  (0.014705882352941176, '2117771'),
  (0.014492753623188406, '419894'),
  (0.014492753623188406, '1411855'),
  (0.014285714285714285, '810375')],
 '4332': [(0.032266458495966696, '4332'),
  (0.01639344262295082, '989116'),
  (0.016129032258064516, '615358'),
  (0.016129032258064516, '1442076'),
  (0.015873015873015872, '1712050'),
  (0.015625, '2361455'),
  (0.015625, '1815319'),
  (0.015384615384615385, '1991105'),
  (0.015384615384615385, '1297050'),
  (0.015151515151515152, '1878340'),
  (0.015151515151515152, '1090555'),
  (0.014925373134328358, '1516841'),
  (0.014925373134328358, '1438336'),
  (0.014705882352941176, '2342190'),
  (0.014705882352941176, '116674'),
  (0.014492753623188406, '774950'),
  (0.014492753623188406, '1903340'),
  (0.014285714285714285, '928308'),
  (0.014285714285714285, '1913962')],
 '9591': [(0.03125763125763126, '1898638'),
  (0.031054405392392875, '143444'),
  (0.01639344262295082, '9591'),
  (0.01639344262295082, '2416624'),
  (0.016129032258064516, '908435'),
  (0.015873015873015872, '138626'),
  (0.015625, '595391'),
  (0.015625, '390102'),
  (0.015384615384615385, '1445185'),
  (0.015151515151515152, '2378793'),
  (0.015151515151515152, '2250838'),
  (0.014925373134328358, '1472431'),
  (0.014705882352941176, '494103'),
  (0.014705882352941176, '1966629'),
  (0.014492753623188406, '2021787'),
  (0.014492753623188406, '1483036'),
  (0.014285714285714285, '863960'),
  (0.014285714285714285, '1759147')],
 '114982': [(0.030117753623188408, '2304325'),
  (0.01639344262295082, '725799'),
  (0.01639344262295082, '2305139'),
  (0.016129032258064516, '1454057'),
  (0.016129032258064516, '1341103'),
  (0.015873015873015872, '2305216'),
  (0.015873015873015872, '1478113'),
  (0.015625, '2444081'),
  (0.015384615384615385, '294327'),
  (0.015384615384615385, '1191721'),
  (0.015151515151515152, '917379'),
  (0.015151515151515152, '2352224'),
  (0.014925373134328358, '95752'),
  (0.014925373134328358, '2303696'),
  (0.014705882352941176, '2352254'),
  (0.014705882352941176, '1672157'),
  (0.014492753623188406, '102670'),
  (0.014285714285714285, '2298231')],
 '563603': [(0.031754032258064516, '12846'),
  (0.030776515151515152, '563603'),
  (0.01639344262295082, '390174'),
  (0.01639344262295082, '251631'),
  (0.016129032258064516, '2207107'),
  (0.015873015873015872, '373237'),
  (0.015873015873015872, '273547'),
  (0.015384615384615385, '840695'),
  (0.015384615384615385, '349302'),
  (0.015151515151515152, '2091601'),
  (0.014925373134328358, '394294'),
  (0.014925373134328358, '2307963'),
  (0.014705882352941176, '270469'),
  (0.014705882352941176, '2146572'),
  (0.014492753623188406, '2152054'),
  (0.014492753623188406, '1233547'),
  (0.014285714285714285, '219324'),
  (0.014285714285714285, '1674515')],
 '104206': [(0.03200204813108039, '104018'),
  (0.031009615384615385, '1972988'),
  (0.01639344262295082, '480239'),
  (0.01639344262295082, '1281151'),
  (0.016129032258064516, '1444646'),
  (0.015873015873015872, '2096056'),
  (0.015625, '200511'),
  (0.015384615384615385, '2082579'),
  (0.015151515151515152, '997945'),
  (0.015151515151515152, '24476'),
  (0.014925373134328358, '2176846'),
  (0.014925373134328358, '1612069'),
  (0.014705882352941176, '2112778'),
  (0.014705882352941176, '1673999'),
  (0.014492753623188406, '149391'),
  (0.014492753623188406, '1330834'),
  (0.014285714285714285, '2101113'),
  (0.014285714285714285, '1301705')],
 '1580851': [(0.01639344262295082, '1549040'),
  (0.01639344262295082, '1375960'),
  (0.016129032258064516, '258957'),
  (0.016129032258064516, '2187550'),
  (0.015873015873015872, '62210'),
  (0.015873015873015872, '2218736'),
  (0.015625, '47266'),
  (0.015625, '1528190'),
  (0.015384615384615385, '1580851'),
  (0.015384615384615385, '1528857'),
  (0.015151515151515152, '31918'),
  (0.015151515151515152, '1736617'),
  (0.014925373134328358, '1989480'),
  (0.014925373134328358, '1962581'),
  (0.014705882352941176, '44994'),
  (0.014705882352941176, '354367'),
  (0.014492753623188406, '634184'),
  (0.014492753623188406, '1709916'),
  (0.014285714285714285, '65096'),
  (0.014285714285714285, '1566087')],
 '23678': [(0.03252247488101534, '936323'),
  (0.032266458495966696, '23678'),
  (0.0315136476426799, '342272'),
  (0.015873015873015872, '198918'),
  (0.015625, '608269'),
  (0.015625, '1799086'),
  (0.015384615384615385, '1815535'),
  (0.015151515151515152, '349822'),
  (0.015151515151515152, '1474293'),
  (0.014925373134328358, '2200763'),
  (0.014925373134328358, '1248120'),
  (0.014705882352941176, '18925'),
  (0.014705882352941176, '1771004'),
  (0.014492753623188406, '1708807'),
  (0.014492753623188406, '150071'),
  (0.014285714285714285, '593437'),
  (0.014285714285714285, '1856164')],
 '37480': [(0.032266458495966696, '305953'),
  (0.03128054740957967, '246157'),
  (0.028991596638655463, '1571906'),
  (0.01639344262295082, '37480'),
  (0.016129032258064516, '316436'),
  (0.015873015873015872, '1027733'),
  (0.015625, '77763'),
  (0.015625, '667358'),
  (0.015384615384615385, '2359021'),
  (0.015384615384615385, '1017336'),
  (0.015151515151515152, '154685'),
  (0.014925373134328358, '702790'),
  (0.014925373134328358, '1242459'),
  (0.014705882352941176, '1589436'),
  (0.014492753623188406, '845773'),
  (0.014492753623188406, '2281956'),
  (0.014285714285714285, '324049')],
 '109454': [(0.03252247488101534, '109454'),
  (0.03036576949620428, '2069260'),
  (0.030158730158730156, '1450531'),
  (0.01639344262295082, '2100641'),
  (0.016129032258064516, '99150'),
  (0.015625, '2387382'),
  (0.015625, '2045342'),
  (0.015384615384615385, '2170879'),
  (0.015384615384615385, '1450070'),
  (0.015151515151515152, '80519'),
  (0.015151515151515152, '1746976'),
  (0.014925373134328358, '31197'),
  (0.014925373134328358, '1280868'),
  (0.014705882352941176, '209508'),
  (0.014705882352941176, '1521334'),
  (0.014492753623188406, '38314'),
  (0.014285714285714285, '2380664')],
 '544250': [(0.03252247488101534, '544250'),
  (0.03200204813108039, '2095411'),
  (0.031544957774465976, '630265'),
  (0.031009615384615385, '682657'),
  (0.03055037313432836, '1937433'),
  (0.02877846790890269, '2347517'),
  (0.015873015873015872, '1825034'),
  (0.015384615384615385, '2347960'),
  (0.015151515151515152, '1322312'),
  (0.014925373134328358, '1880207'),
  (0.014705882352941176, '547913'),
  (0.014705882352941176, '2012111'),
  (0.014492753623188406, '1320765'),
  (0.014285714285714285, '730726')],
 '12519': [(0.032266458495966696, '1091625'),
  (0.03225806451612903, '1374322'),
  (0.03177805800756621, '1739665'),
  (0.03149801587301587, '869618'),
  (0.031009615384615385, '1005711'),
  (0.02964426877470356, '12519'),
  (0.028991596638655463, '175050'),
  (0.015151515151515152, '172843'),
  (0.014925373134328358, '82510'),
  (0.014925373134328358, '101187'),
  (0.014705882352941176, '2264749'),
  (0.014492753623188406, '943622'),
  (0.014285714285714285, '1741677')],
 '115015': [(0.03252247488101534, '115015'),
  (0.03200204813108039, '1351327'),
  (0.03177805800756621, '2202113'),
  (0.03055037313432836, '458160'),
  (0.015873015873015872, '443278'),
  (0.015625, '1978384'),
  (0.015384615384615385, '2315210'),
  (0.015151515151515152, '509726'),
  (0.015151515151515152, '1290856'),
  (0.014925373134328358, '2085509'),
  (0.014705882352941176, '484126'),
  (0.014705882352941176, '114943'),
  (0.014492753623188406, '57467'),
  (0.014492753623188406, '2133651'),
  (0.014285714285714285, '365856'),
  (0.014285714285714285, '1546751')],
 '84287': [(0.01639344262295082, '84287'),
  (0.01639344262295082, '527077'),
  (0.016129032258064516, '891543'),
  (0.016129032258064516, '1540254'),
  (0.015873015873015872, '1470924'),
  (0.015873015873015872, '1308897'),
  (0.015625, '890655'),
  (0.015625, '1422745'),
  (0.015384615384615385, '933294'),
  (0.015384615384615385, '1095591'),
  (0.015151515151515152, '2314024'),
  (0.015151515151515152, '1175650'),
  (0.014925373134328358, '833753'),
  (0.014925373134328358, '1434451'),
  (0.014705882352941176, '618398'),
  (0.014705882352941176, '1051685'),
  (0.014492753623188406, '1497720'),
  (0.014492753623188406, '1427890'),
  (0.014285714285714285, '1289573'),
  (0.014285714285714285, '1195783')],
 '24998': [(0.03278688524590164, '2339264'),
  (0.029877369007803793, '2429942'),
  (0.016129032258064516, '797556'),
  (0.016129032258064516, '1409082'),
  (0.015873015873015872, '24998'),
  (0.015873015873015872, '2149920'),
  (0.015625, '1782009'),
  (0.015625, '1394401'),
  (0.015384615384615385, '1793098'),
  (0.015151515151515152, '1941659'),
  (0.015151515151515152, '1273144'),
  (0.014925373134328358, '26989'),
  (0.014925373134328358, '1323056'),
  (0.014705882352941176, '917063'),
  (0.014705882352941176, '550651'),
  (0.014492753623188406, '59107'),
  (0.014285714285714285, '674239'),
  (0.014285714285714285, '1553086')],
 '11925': [(0.01639344262295082, '805834'),
  (0.01639344262295082, '580492'),
  (0.016129032258064516, '2108567'),
  (0.016129032258064516, '11925'),
  (0.015873015873015872, '761604'),
  (0.015873015873015872, '232799'),
  (0.015625, '1148523'),
  (0.015625, '1063548'),
  (0.015384615384615385, '975838'),
  (0.015384615384615385, '1822371'),
  (0.015151515151515152, '645673'),
  (0.015151515151515152, '2207088'),
  (0.014925373134328358, '555629'),
  (0.014925373134328358, '33853'),
  (0.014705882352941176, '33846'),
  (0.014705882352941176, '1355039'),
  (0.014492753623188406, '1844434'),
  (0.014492753623188406, '1687991'),
  (0.014285714285714285, '1920902'),
  (0.014285714285714285, '1595836')],
 '643': [(0.032266458495966696, '643'),
  (0.03200204813108039, '1115256'),
  (0.03131881575727918, '2246138'),
  (0.031009615384615385, '88810'),
  (0.030834914611005692, '1892260'),
  (0.015625, '33435'),
  (0.015384615384615385, '27862'),
  (0.015151515151515152, '832816'),
  (0.015151515151515152, '1769441'),
  (0.014925373134328358, '1495790'),
  (0.014705882352941176, '2075490'),
  (0.014492753623188406, '1786083'),
  (0.014492753623188406, '1672669'),
  (0.014285714285714285, '806900'),
  (0.014285714285714285, '143150')],
 '113075': [(0.03252247488101534, '113075'),
  (0.03200204813108039, '572485'),
  (0.01639344262295082, '1733437'),
  (0.015873015873015872, '46442'),
  (0.015625, '625621'),
  (0.015625, '178719'),
  (0.015384615384615385, '496935'),
  (0.015384615384615385, '1108946'),
  (0.015151515151515152, '60048'),
  (0.015151515151515152, '21628'),
  (0.014925373134328358, '1672942'),
  (0.014925373134328358, '100596'),
  (0.014705882352941176, '363175'),
  (0.014705882352941176, '1217819'),
  (0.014492753623188406, '536101'),
  (0.014492753623188406, '1039826'),
  (0.014285714285714285, '769187'),
  (0.014285714285714285, '221442')],
 '1250387': [(0.031746031746031744, '297902'),
  (0.031544957774465976, '1250387'),
  (0.030776515151515152, '2217046'),
  (0.0304147465437788, '95283'),
  (0.030117753623188408, '1268901'),
  (0.029411764705882353, '599253'),
  (0.01639344262295082, '1727869'),
  (0.016129032258064516, '2195293'),
  (0.015384615384615385, '1732479'),
  (0.015384615384615385, '1207201'),
  (0.014925373134328358, '707898'),
  (0.014925373134328358, '1683108'),
  (0.014492753623188406, '1794130'),
  (0.014285714285714285, '79211')],
 '72012': [(0.032266458495966696, '72012'),
  (0.03200204813108039, '111442'),
  (0.031754032258064516, '111443'),
  (0.031544957774465976, '111938'),
  (0.030776515151515152, '103174'),
  (0.029411764705882353, '2371473'),
  (0.015384615384615385, '88775'),
  (0.015384615384615385, '191745'),
  (0.014925373134328358, '941306'),
  (0.014925373134328358, '927787'),
  (0.014492753623188406, '863599'),
  (0.014492753623188406, '727793'),
  (0.014285714285714285, '661128'),
  (0.014285714285714285, '1806360')],
 '167865': [(0.03278688524590164, '167865'),
  (0.016129032258064516, '995221'),
  (0.016129032258064516, '1964134'),
  (0.015873015873015872, '385342'),
  (0.015873015873015872, '1155889'),
  (0.015625, '221442'),
  (0.015625, '1469500'),
  (0.015384615384615385, '1846426'),
  (0.015384615384615385, '1730916'),
  (0.015151515151515152, '410277'),
  (0.015151515151515152, '2229172'),
  (0.014925373134328358, '299025'),
  (0.014925373134328358, '1469315'),
  (0.014705882352941176, '2006878'),
  (0.014705882352941176, '1303512'),
  (0.014492753623188406, '737868'),
  (0.014492753623188406, '2345059'),
  (0.014285714285714285, '461641'),
  (0.014285714285714285, '1820245')],
 '1425120': [(0.03278688524590164, '2316655'),
  (0.0315136476426799, '1083694'),
  (0.03149801587301587, '1737940'),
  (0.030536130536130537, '1425120'),
  (0.029631255487269532, '12523'),
  (0.016129032258064516, '735915'),
  (0.015873015873015872, '836205'),
  (0.015625, '1641422'),
  (0.015151515151515152, '2198169'),
  (0.014925373134328358, '242943'),
  (0.014705882352941176, '546380'),
  (0.014492753623188406, '2428438'),
  (0.014492753623188406, '2348752'),
  (0.014285714285714285, '2147182'),
  (0.014285714285714285, '179529')],
 '24883': [(0.01639344262295082, '982243'),
  (0.01639344262295082, '2393527'),
  (0.016129032258064516, '24883'),
  (0.016129032258064516, '1346094'),
  (0.015873015873015872, '647047'),
  (0.015873015873015872, '1472358'),
  (0.015625, '2355895'),
  (0.015625, '1048454'),
  (0.015384615384615385, '1877437'),
  (0.015384615384615385, '1357456'),
  (0.015151515151515152, '2366040'),
  (0.015151515151515152, '1603081'),
  (0.014925373134328358, '370467'),
  (0.014925373134328358, '1394026'),
  (0.014705882352941176, '689411'),
  (0.014705882352941176, '2178291'),
  (0.014492753623188406, '2200660'),
  (0.014492753623188406, '2172776'),
  (0.014285714285714285, '1734607'),
  (0.014285714285714285, '1297674')],
 '27200': [(0.032266458495966696, '2389598'),
  (0.030309988518943745, '1834661'),
  (0.01639344262295082, '27200'),
  (0.016129032258064516, '1493043'),
  (0.016129032258064516, '143487'),
  (0.015873015873015872, '292569'),
  (0.015625, '353797'),
  (0.015625, '1627937'),
  (0.015384615384615385, '923643'),
  (0.015151515151515152, '621974'),
  (0.015151515151515152, '1833536'),
  (0.014925373134328358, '1570665'),
  (0.014705882352941176, '1536243'),
  (0.014705882352941176, '148043'),
  (0.014492753623188406, '821177'),
  (0.014492753623188406, '1352641'),
  (0.014285714285714285, '1674363'),
  (0.014285714285714285, '1409420')],
 '136856': [(0.03278688524590164, '136856'),
  (0.030798389007344232, '817838'),
  (0.016129032258064516, '2429792'),
  (0.016129032258064516, '1445582'),
  (0.015873015873015872, '1045080'),
  (0.015625, '2272554'),
  (0.015625, '12030'),
  (0.015384615384615385, '2398412'),
  (0.015384615384615385, '2037574'),
  (0.015151515151515152, '1738080'),
  (0.015151515151515152, '1714638'),
  (0.014925373134328358, '2312312'),
  (0.014705882352941176, '2059311'),
  (0.014705882352941176, '1018623'),
  (0.014492753623188406, '506684'),
  (0.014492753623188406, '1041737'),
  (0.014285714285714285, '2317285'),
  (0.014285714285714285, '1505618')],
 '6031': [(0.032266458495966696, '123675'),
  (0.03200204813108039, '23531'),
  (0.030776515151515152, '801082'),
  (0.01639344262295082, '6031'),
  (0.016129032258064516, '975229'),
  (0.015625, '117413'),
  (0.015384615384615385, '157645'),
  (0.015384615384615385, '1466349'),
  (0.015151515151515152, '2026699'),
  (0.014925373134328358, '978358'),
  (0.014925373134328358, '306781'),
  (0.014705882352941176, '825709'),
  (0.014705882352941176, '623176'),
  (0.014492753623188406, '268'),
  (0.014492753623188406, '101000'),
  (0.014285714285714285, '962864'),
  (0.014285714285714285, '241657')],
 '1313191': [(0.01639344262295082, '94675'),
  (0.01639344262295082, '1355235'),
  (0.016129032258064516, '765953'),
  (0.016129032258064516, '1313191'),
  (0.015873015873015872, '1582259'),
  (0.015873015873015872, '1198513'),
  (0.015625, '573024'),
  (0.015625, '216370'),
  (0.015384615384615385, '2183271'),
  (0.015384615384615385, '177180'),
  (0.015151515151515152, '66335'),
  (0.015151515151515152, '1867512'),
  (0.014925373134328358, '443142'),
  (0.014925373134328358, '201391'),
  (0.014705882352941176, '681010'),
  (0.014705882352941176, '435777'),
  (0.014492753623188406, '624381'),
  (0.014492753623188406, '2158753'),

In [13]:
query_and_hybrid_scores["123839"]

[(0.032018442622950824, '806300'),
 (0.029850746268656716, '806263'),
 (0.01639344262295082, '516871'),
 (0.016129032258064516, '647478'),
 (0.016129032258064516, '123839'),
 (0.015873015873015872, '806326'),
 (0.015873015873015872, '2129172'),
 (0.015625, '836567'),
 (0.015384615384615385, '806075'),
 (0.015384615384615385, '2357011'),
 (0.015151515151515152, '1793430'),
 (0.015151515151515152, '1222510'),
 (0.014705882352941176, '799188'),
 (0.014705882352941176, '2433706'),
 (0.014492753623188406, '708880'),
 (0.014492753623188406, '1727316'),
 (0.014285714285714285, '775424'),
 (0.014285714285714285, '1901730')]

In [15]:
len(query_and_hybrid_scores.keys())

1444

### Cross Encoder

In [14]:
from sentence_transformers import CrossEncoder
model = CrossEncoder('cross-encoder/ms-marco-MiniLM-L6-v2')

/run/media/tahas44/Yeni Birim/Technarts/Intern/NLP/InformationRetrieval/.venv/lib64/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 105/105 [00:00<00:00, 2754.10it/s]

In [16]:
query_id_vs_text = defaultdict(str)

for query in dataset.queries_iter():
    query_id_vs_text[query.query_id] = query.text

query_id_vs_text = dict(query_id_vs_text)

doc_id_vs_text = defaultdict(str)

for doc in dataset.docs_iter():
    doc_id_vs_text[doc.doc_id] = doc.text

doc_id_vs_text = dict(doc_id_vs_text)

In [17]:
query_doc_pairs = defaultdict(list)

for query_id in query_ids:
    for mytuple in query_and_hybrid_scores[query_id]:
        query_doc_pairs[query_id].append((query_id_vs_text[query_id], doc_id_vs_text[mytuple[1]]))

query_doc_pairs = dict(query_doc_pairs)

In [19]:
query_score_dict = defaultdict(list)

for query_id in query_ids:
    query_score_dict[query_id] = list(model.predict(query_doc_pairs[query_id]))

query_doc_pairs = dict(query_doc_pairs)

In [20]:
query_score_dict["123839"]

[np.float32(6.4627924),
 np.float32(4.384878),
 np.float32(-0.4506746),
 np.float32(-0.17859715),
 np.float32(6.419842),
 np.float32(4.9677753),
 np.float32(-0.33984625),
 np.float32(3.0357656),
 np.float32(5.5189123),
 np.float32(0.458524),
 np.float32(2.3268332),
 np.float32(2.2397873),
 np.float32(0.75131375),
 np.float32(1.5397115),
 np.float32(-2.3310945),
 np.float32(-3.6361036),
 np.float32(-1.3943533),
 np.float32(-4.7235107)]

In [22]:
retrieved_docs_with_scores = defaultdict(list)

for query_idx in range(len(query_ids)):
    tuple_list = []
    query_id = query_ids[query_idx]

    for doc_idx in range(len(query_and_hybrid_scores[query_id])):
        tuple_list.append((query_score_dict[query_id][doc_idx], query_and_hybrid_scores[query_id][doc_idx][1]))

    retrieved_docs_with_scores[query_id] = sorted(tuple_list, reverse=True)

retrieved_docs_with_scores = dict(retrieved_docs_with_scores)

In [24]:
most_related_10_with_scores = defaultdict(list)

for query_id in query_ids:
    most_related_10_with_scores[query_id] = retrieved_docs_with_scores[query_id][:10]

most_related_10_with_scores = dict(most_related_10_with_scores)

In [26]:
most_related_5_with_scores = defaultdict(list)

for query_id in query_ids:
    most_related_5_with_scores[query_id] = retrieved_docs_with_scores[query_id][:5]

most_related_5_with_scores = dict(most_related_5_with_scores)

In [27]:
qrels_dict = defaultdict(list)

for qrel in dataset.qrels_iter():
    qrels_dict[qrel.query_id].append(qrel.doc_id)

qrels_dict = dict(qrels_dict)

query_ids = [query.query_id for query in dataset.queries_iter()]

class Scoredoc:
    def __init__(self, doc_id, score):
        self.doc_id = doc_id
        self.score = score

score_doc_dict = defaultdict(list)

for scoreddoc in dataset.scoreddocs_iter():
    doc_id = scoreddoc.doc_id
    score = scoreddoc.score

    scoreddoc_object = Scoredoc(doc_id, score)

    score_doc_dict[scoreddoc.query_id].append(scoreddoc_object)

In [28]:
from collections import defaultdict
from sklearn.metrics import ndcg_score
import numpy as np
import pandas as pd

def recall(found_list: list, test_list: list) -> float:
    counter = 0

    test_set = set(test_list)

    for mytuple in found_list:
        if mytuple[1] in test_set:
            counter += 1

    return (counter / len(test_list)) * 100

def precision(found_list: list, test_list: list) -> float:
    if len(found_list) == 0:
        return 0

    counter = 0

    test_set = set(test_list)

    for mytuple in found_list:
        if mytuple[1] in test_set:
            counter += 1

    return (counter / len(found_list)) * 100

def precision_AP(found_docs: list, test_list: list) -> float:
    counter = 0

    test_set = set(test_list)

    for mytuple in found_docs:
        if mytuple[1] in test_set:
            counter += 1

    return counter / len(found_docs)

def AP(found_docs: list, test_list: list, value: int) -> float:
    total = 0

    for i in range(1, value + 1):
        if i < len(found_docs):
            precision_k = precision_AP(found_docs[:i], test_list)
            total += precision_k * (found_docs[i - 1][1] in set(test_list))

    return total / len(test_list)

def get_ndcg_list(most_dict: dict, value: int, query_ids: list, score_doc_dict: dict) -> list:
    doc_id_score_dict = defaultdict(float)
    ndcg_list = []

    for query_id in query_ids:
        scoredoc_object_list = score_doc_dict[query_id]

        for scoreddoc_object in scoredoc_object_list:
            doc_id_score_dict[scoreddoc_object.doc_id] = scoreddoc_object.score

        model_score_tuple_list = most_dict[query_id]
        y_score, y_true = [], []

        for mytuple in model_score_tuple_list:
            doc_id = mytuple[1]
            score = mytuple[0]

            y_score.append(score)
            y_true.append(doc_id_score_dict[doc_id])

        if len(y_score) == 0:
            ndcg_list.append(0.0)
            continue

        if len(y_score) == 1:
            y_true.append(0.0)
            y_score.append(0.0)

        if len(y_true) == len(y_score):
            ndcg_list.append(ndcg_score(np.asarray([y_true]), np.asarray([y_score]), k=value))
        else:
            print("There is a problem with query", query_id)

    return ndcg_list

- for top 10

In [29]:
recall_10_list = []

for query_id in query_ids:
    recall_10_list.append(recall(most_related_10_with_scores[query_id], qrels_dict[query_id]))

precision_10_list = []

for query_id in query_ids:
    precision_10_list.append(precision(most_related_10_with_scores[query_id], qrels_dict[query_id]))

AP_10_list = []

for query_id in query_ids:
    AP_10_list.append(AP(most_related_10_with_scores[query_id], qrels_dict[query_id], 10))

NDCG_10_list = get_ndcg_list(most_related_10_with_scores, 10, query_ids, score_doc_dict)

- for top 5

In [30]:
recall_5_list = []

for query_id in query_ids:
    recall_5_list.append(recall(most_related_5_with_scores[query_id], qrels_dict[query_id]))

precision_5_list = []

for query_id in query_ids:
    precision_5_list.append(precision(most_related_5_with_scores[query_id], qrels_dict[query_id]))

AP_5_list = []

for query_id in query_ids:
    AP_5_list.append(AP(most_related_5_with_scores[query_id], qrels_dict[query_id], 5))

NDCG_5_list = get_ndcg_list(most_related_5_with_scores, 5, query_ids, score_doc_dict)

In [31]:
def base_df(
        query_ids: list,
        recall_5: list,
        precision_5: list,
        AP_5: list,
        NDCG_5: list,
        recall_10: list,
        precision_10: list,
        AP_10: list,
        NDCG_10: list
) -> pd.DataFrame:

    df = pd.DataFrame({
        "Query_ID": query_ids,
        "recall_5": recall_5,
        "precision_5": precision_5,
        "AP_5": AP_5,
        "NDCG_5": NDCG_5,
        "recall_10": recall_10,
        "precision_10": precision_10,
        "AP_10": AP_10,
        "NDCG_10": NDCG_10
    })

    df["f_score_5"] = 2 * df["recall_5"] * df["precision_5"] / (df["recall_5"] + df["precision_5"])
    df["f_score_10"] = 2 * df["recall_10"] * df["precision_10"] / (df["recall_10"] + df["precision_10"])

    df["f_score_5"] = df["f_score_5"].fillna(0)
    df["f_score_10"] = df["f_score_10"].fillna(0)

    return df

In [32]:
df = base_df(
    query_ids=query_ids,
    recall_5=recall_5_list,
    precision_5=precision_5_list,
    AP_5=AP_5_list,
    NDCG_5=NDCG_5_list,
    recall_10=recall_10_list,
    precision_10=precision_10_list,
    AP_10=AP_10_list,
    NDCG_10=NDCG_10_list
)

df

,Query_ID,recall_5,precision_5,AP_5,NDCG_5,recall_10,precision_10,AP_10,NDCG_10,f_score_5,f_score_10
0,123839,66.666667,80.0,0.500000,0.998041,100.000000,60.0,0.915079,0.991199,72.727273,75.000000
1,188629,33.333333,40.0,0.277778,0.990272,33.333333,20.0,0.277778,0.987397,36.363636,25.000000
2,13898,50.000000,60.0,0.500000,0.000000,50.000000,30.0,0.500000,0.000000,54.545455,37.500000
3,316959,22.222222,40.0,0.222222,0.989511,22.222222,20.0,0.222222,0.987374,28.571429,21.052632
4,515031,7.142857,20.0,0.071429,0.688473,14.285714,20.0,0.087302,0.714439,10.526316,16.666667
...,...,...,...,...,...,...,...,...,...,...,...
1439,896124,25.000000,40.0,0.145833,0.970551,25.000000,20.0,0.145833,0.976072,30.769231,22.222222
1440,12319,4.545455,20.0,0.045455,0.877215,4.545455,10.0,0.045455,0.823364,7.407407,6.250000
1441,4421,0.000000,0.0,0.000000,0.986912,0.000000,0.0,0.000000,0.971606,0.000000,0.000000
1442,296526,10.000000,20.0,0.033333,0.898832,20.000000,20.0,0.033333,0.893007,13.333333,20.000000
1443,341793,14.285714,20.0,0.142857,1.000000,14.285714,10.0,0.142857,0.732695,16.666667,11.764706

In [33]:
df.isna().sum()

Query_ID        0
recall_5        0
precision_5     0
AP_5            0
NDCG_5          0
recall_10       0
precision_10    0
AP_10           0
NDCG_10         0
f_score_5       0
f_score_10      0
dtype: int64

In [34]:
def create_parquet_df(method_name: str, df: pd.DataFrame) -> pd.DataFrame:
    mydict = {
        "Method": method_name,
        "recall_5_mean": df["recall_5"].mean(),
        "recall_5_std": df["recall_5"].std(),
        "recall_5_max": df["recall_5"].max(),
        "recall_5_min": df["recall_5"].min(),
        "recall_10_mean": df["recall_10"].mean(),
        "recall_10_std": df["recall_10"].std(),
        "recall_10_max": df["recall_10"].max(),
        "recall_10_min": df["recall_10"].min(),
        "precision_5_mean": df["precision_5"].mean(),
        "precision_5_std": df["precision_5"].std(),
        "precision_5_max": df["precision_5"].max(),
        "precision_5_min": df["precision_5"].min(),
        "precision_10_mean": df["precision_10"].mean(),
        "precision_10_std": df["precision_10"].std(),
        "precision_10_max": df["precision_10"].max(),
        "precision_10_min": df["precision_10"].min(),
        "f_score_5_mean": df["f_score_5"].mean(),
        "f_score_5_std": df["f_score_5"].std(),
        "f_score_5_max": df["f_score_5"].max(),
        "f_score_5_min": df["f_score_5"].min(),
        "f_score_10_mean": df["f_score_10"].mean(),
        "f_score_10_std": df["f_score_10"].std(),
        "f_score_10_max": df["f_score_10"].max(),
        "f_score_10_min": df["f_score_10"].min(),
        "MAP_5": df["AP_5"].mean(),
        "MAP_10": df["AP_10"].mean(),
        "NDCG_5_mean": df["NDCG_5"].mean(),
        "NDCG_5_std": df["NDCG_5"].std(),
        "NDCG_5_max": df["NDCG_5"].max(),
        "NDCG_5_min": df["NDCG_5"].min(),
        "NDCG_10_mean": df["NDCG_10"].mean(),
        "NDCG_10_std": df["NDCG_10"].std(),
        "NDCG_10_max": df["NDCG_10"].max(),
        "NDCG_10_min": df["NDCG_10"].min()
    }

    df_parquet = pd.DataFrame(mydict, index=[0])

    return df_parquet

In [35]:
df_parquet = create_parquet_df("Hybrid Search", df)

In [36]:
df_parquet

,Method,recall_5_mean,recall_5_std,recall_5_max,recall_5_min,recall_10_mean,recall_10_std,recall_10_max,recall_10_min,precision_5_mean,...,MAP_5,MAP_10,NDCG_5_mean,NDCG_5_std,NDCG_5_max,NDCG_5_min,NDCG_10_mean,NDCG_10_std,NDCG_10_max,NDCG_10_min
0,Hybrid Search,17.071468,14.247436,83.333333,0.0,23.777552,20.117251,100.0,0.0,35.817175,...,0.131637,0.170402,0.784984,0.33035,1.0,0.0,0.789487,0.288096,1.0,0.0

In [37]:
df_parquet.to_parquet("hybrid_search.parquet")