In [2]:
import pandas as pd

df_1 = pd.read_parquet("parquets/BagofWordsPorterStemmerQueriesStemmed.parquet")
df_2 = pd.read_parquet("parquets/BagofWordsLemmatization.parquet")
df_3 = pd.read_parquet("parquets/TF-IDFPorterStemmerQueriesStemmed.parquet")
df_4 = pd.read_parquet("parquets/TF-IDFLemmatization.parquet")
df_5 = pd.read_parquet("parquets/BM25PorterStemmerQueriesStemmed.parquet")
df_6 = pd.read_parquet("parquets/BM25Lemmatization.parquet")

In [3]:
df_1

,Method,recall_5_mean,recall_5_std,recall_5_max,recall_5_min,recall_10_mean,recall_10_std,recall_10_max,recall_10_min,precision_5_mean,...,MAP_5,MAP_10,NDCG_5_mean,NDCG_5_std,NDCG_5_max,NDCG_5_min,NDCG_10_mean,NDCG_10_std,NDCG_10_max,NDCG_10_min
0,Bag of Words - Porter's Stemmer Queries Stemmed,10.287783,12.582727,83.333333,0.0,14.316609,16.52425,100.0,0.0,21.855956,...,0.07956,0.094823,0.432826,0.338533,1.0,0.0,0.429764,0.33532,1.0,0.0

In [4]:
df = pd.concat([df_1, df_2, df_3, df_4, df_5, df_6], ignore_index=True)
df

,Method,recall_5_mean,recall_5_std,recall_5_max,recall_5_min,recall_10_mean,recall_10_std,recall_10_max,recall_10_min,precision_5_mean,...,MAP_5,MAP_10,NDCG_5_mean,NDCG_5_std,NDCG_5_max,NDCG_5_min,NDCG_10_mean,NDCG_10_std,NDCG_10_max,NDCG_10_min
0,Bag of Words - Porter's Stemmer Queries Stemmed,10.287783,12.582727,83.333333,0.0,14.316609,16.524250,100.0,0.0,21.855956,...,0.079560,0.094823,0.432826,0.338533,1.0,0.0,0.429764,0.335320,1.0,0.0
1,Bag of Words - Lemmatization,10.360816,12.548836,83.333333,0.0,14.495339,16.820556,100.0,0.0,22.063712,...,0.080840,0.096886,0.432415,0.342429,1.0,0.0,0.430649,0.339678,1.0,0.0
2,TF-IDF - Porter's Stemmer Queries Stemmed,12.394036,13.796899,83.333333,0.0,17.063580,18.097022,100.0,0.0,25.720222,...,0.096138,0.115298,0.477876,0.338497,1.0,0.0,0.476669,0.331437,1.0,0.0
3,TF-IDF - Lemmatization,12.413277,13.835136,83.333333,0.0,17.267444,18.049535,100.0,0.0,25.761773,...,0.097513,0.117186,0.475983,0.344134,1.0,0.0,0.475855,0.336552,1.0,0.0
4,BM25 - Porter's Stemmer Queries Stemmed,14.478316,14.481887,83.333333,0.0,20.702477,19.543478,100.0,0.0,29.667590,...,0.114719,0.141490,0.508070,0.349112,1.0,0.0,0.508130,0.345892,1.0,0.0
5,BM25 - Lemmatization,14.593247,14.569564,83.333333,0.0,20.865220,19.584312,100.0,0.0,29.847645,...,0.116666,0.143757,0.505786,0.353880,1.0,0.0,0.506285,0.350688,1.0,0.0

In [5]:
df.to_parquet("overall_sparse_analysis.parquet")