In [1]:
import pandas as pd

df_1 = pd.read_parquet("parquets/BagofWordsPorterStemmerQueriesStemmed.parquet")
df_2 = pd.read_parquet("parquets/BagofWordsLemmatization.parquet")
df_3 = pd.read_parquet("parquets/TF-IDFPorterStemmerQueriesStemmed.parquet")
df_4 = pd.read_parquet("parquets/TF-IDFLemmatization.parquet")
df_5 = pd.read_parquet("parquets/BM25PorterStemmerQueriesStemmed.parquet")
df_6 = pd.read_parquet("parquets/BM25Lemmatization.parquet")
df_7 = pd.read_parquet("parquets/BM25-LemmatizationNumbersReplaced.parquet")
df_8 = pd.read_parquet("parquets/BM25LemmatizationNumbersDeleted.parquet")
df_9 = pd.read_parquet("parquets/BM25LemmatizationCrossEncoder.parquet")
df_10 = pd.read_parquet("parquets/BM25LemmatizationCrossEncoderWithQueryExpansion.parquet")
df_11 = pd.read_parquet("parquets/BM25PseudoRelevanceFeedback.parquet")

In [2]:
df = pd.concat([df_1, df_2, df_3, df_4, df_5, df_6, df_7, df_8, df_9, df_10, df_11], ignore_index=True)
df

,Method,recall_5_mean,recall_5_std,recall_5_max,recall_5_min,recall_10_mean,recall_10_std,recall_10_max,recall_10_min,precision_5_mean,...,MAP_5,MAP_10,NDCG_5_mean,NDCG_5_std,NDCG_5_max,NDCG_5_min,NDCG_10_mean,NDCG_10_std,NDCG_10_max,NDCG_10_min
0,Bag of Words - Porter's Stemmer Queries Stemmed,10.287783,12.582727,83.333333,0.0,14.316609,16.524250,100.0,0.0,21.855956,...,0.079560,0.094823,0.432826,0.338533,1.0,0.0,0.429764,0.335320,1.0,0.0
1,Bag of Words - Lemmatization,10.360816,12.548836,83.333333,0.0,14.495339,16.820556,100.0,0.0,22.063712,...,0.080840,0.096886,0.432415,0.342429,1.0,0.0,0.430649,0.339678,1.0,0.0
2,TF-IDF - Porter's Stemmer Queries Stemmed,12.394036,13.796899,83.333333,0.0,17.063580,18.097022,100.0,0.0,25.720222,...,0.096138,0.115298,0.477876,0.338497,1.0,0.0,0.476669,0.331437,1.0,0.0
3,TF-IDF - Lemmatization,12.413277,13.835136,83.333333,0.0,17.267444,18.049535,100.0,0.0,25.761773,...,0.097513,0.117186,0.475983,0.344134,1.0,0.0,0.475855,0.336552,1.0,0.0
4,BM25 - Porter's Stemmer Queries Stemmed,14.478316,14.481887,83.333333,0.0,20.702477,19.543478,100.0,0.0,29.667590,...,0.114719,0.141490,0.508070,0.349112,1.0,0.0,0.508130,0.345892,1.0,0.0
5,BM25 - Lemmatization,14.593247,14.569564,83.333333,0.0,20.865220,19.584312,100.0,0.0,29.847645,...,0.116666,0.143757,0.505786,0.353880,1.0,0.0,0.506285,0.350688,1.0,0.0
6,BM25 - Lemmatization Numbers Replaced,13.627131,14.542782,83.333333,0.0,19.451965,19.650279,100.0,0.0,27.950139,...,0.108940,0.134112,0.500102,0.358471,1.0,0.0,0.501126,0.356007,1.0,0.0
7,BM25 - Lemmatization Numbers Deleted,14.544665,14.487861,83.333333,0.0,20.671437,19.478079,100.0,0.0,29.721448,...,0.115245,0.141529,0.502118,0.354464,1.0,0.0,0.502874,0.351062,1.0,0.0
8,BM25 - Lemmatization Cross Encoder,15.759954,14.439942,83.333333,0.0,20.865220,19.584312,100.0,0.0,32.841644,...,0.122148,0.153571,0.804835,0.327528,1.0,0.0,0.811885,0.291716,1.0,0.0
9,BM25 - Lemmatization Cross Encoder With Query ...,15.642264,14.461900,83.333333,0.0,20.540319,19.448146,100.0,0.0,32.523084,...,0.121822,0.152152,0.804181,0.326229,1.0,0.0,0.811250,0.289479,1.0,0.0
10,BM25PseudoRelevanceFeedback,16.024472,14.739417,83.333333,0.0,21.604635,20.202779,100.0,0.0,33.067867,...,0.123887,0.157476,0.799510,0.331981,1.0,0.0,0.808502,0.291541,1.0,0.0

In [8]:
df["f_score_5_mean"]

0    12.915315
1    13.010022
2    15.507866
3    15.534353
4    18.079611
5    18.216890
6    17.023097
7    18.163435
8    19.776504
9    22.905529
Name: f_score_5_mean, dtype: float64

In [4]:
df_diff = pd.DataFrame(
    {
        "Difference": "Reranking Improvement"
    },
    index=[0]
)

In [9]:
df_diff

              Difference
0  Reranking Improvement

In [5]:
for column in df.columns:
    if column != "Method":
        column_name = column + "_improvement"

        if df.loc[8, column] != 0:            
            df_diff[column_name] = 100 * ((df.loc[9, column] - df.loc[8, column]) / df.loc[8, column])
        else:
            df_diff[column_name] = 0.0

In [6]:
df_diff

,Difference,recall_5_mean_improvement,recall_5_std_improvement,recall_5_max_improvement,recall_5_min_improvement,recall_10_mean_improvement,recall_10_std_improvement,recall_10_max_improvement,recall_10_min_improvement,precision_5_mean_improvement,...,MAP_5_improvement,MAP_10_improvement,NDCG_5_mean_improvement,NDCG_5_std_improvement,NDCG_5_max_improvement,NDCG_5_min_improvement,NDCG_10_mean_improvement,NDCG_10_std_improvement,NDCG_10_max_improvement,NDCG_10_min_improvement
0,Reranking Improvement,-0.746769,0.152061,4.000000e-07,0.0,-1.557143,-0.69528,0.0,0.0,-0.969988,...,-0.266573,-0.924295,-0.081208,-0.396587,0.0,0.0,-0.078198,-0.766901,0.0,0.0

In [18]:
df_diff.columns

Index(['Difference', 'recall_5_mean_improvement', 'recall_5_std_improvement',
       'recall_5_max_improvement', 'recall_5_min_improvement',
       'recall_10_mean_improvement', 'recall_10_std_improvement',
       'recall_10_max_improvement', 'recall_10_min_improvement',
       'precision_5_mean_improvement', 'precision_5_std_improvement',
       'precision_5_max_improvement', 'precision_5_min_improvement',
       'precision_10_mean_improvement', 'precision_10_std_improvement',
       'precision_10_max_improvement', 'precision_10_min_improvement',
       'f_score_5_mean_improvement', 'f_score_5_std_improvement',
       'f_score_5_max_improvement', 'f_score_5_min_improvement',
       'f_score_10_mean_improvement', 'f_score_10_std_improvement',
       'f_score_10_max_improvement', 'f_score_10_min_improvement',
       'MAP_5_improvement', 'MAP_10_improvement', 'NDCG_5_mean_improvement',
       'NDCG_5_std_improvement', 'NDCG_5_max_improvement',
       'NDCG_5_min_improvement', 'NDCG_10_mean_improvement',
       'NDCG_10_std_improvement', 'NDCG_10_max_improvement',
       'NDCG_10_min_improvement'],
      dtype='str')

In [7]:
metrics_dict = {
    "metric": [
        "recall_5_mean_improvement",
        "recall_10_mean_improvement",
        "precision_5_mean_improvement",
        "precision_10_mean_improvement",
        "f_score_5_mean_improvement",
        "f_score_10_mean_improvement",
        "MAP_5_improvement",
        "MAP_10_improvement",
        "NDCG_5_mean_improvement",
        "NDCG_10_mean_improvement"
    ],
    "value": [
        df_diff['recall_5_mean_improvement'].apply(lambda x: f"{x:.8f}")[0],
        df_diff['recall_10_mean_improvement'].apply(lambda x: f"{x:.8f}")[0],
        df_diff['precision_5_mean_improvement'].apply(lambda x: f"{x:.8f}")[0],
        df_diff['precision_10_mean_improvement'].apply(lambda x: f"{x:.8f}")[0],
        df_diff['f_score_5_mean_improvement'].apply(lambda x: f"{x:.8f}")[0],
        df_diff['f_score_10_mean_improvement'].apply(lambda x: f"{x:.8f}")[0],
        df_diff['MAP_5_improvement'].apply(lambda x: f"{x:.8f}")[0],
        df_diff['MAP_10_improvement'].apply(lambda x: f"{x:.8f}")[0],
        df_diff['NDCG_5_mean_improvement'].apply(lambda x: f"{x:.8f}")[0],
        df_diff['NDCG_10_mean_improvement'].apply(lambda x: f"{x:.8f}")[0]
    ]
}

df_metric = pd.DataFrame(metrics_dict)
df_metric

                          metric        value
0      recall_5_mean_improvement  -0.74676883
1     recall_10_mean_improvement  -1.55714257
2   precision_5_mean_improvement  -0.96998790
3  precision_10_mean_improvement  -1.14899538
4     f_score_5_mean_improvement  15.82193288
5    f_score_10_mean_improvement  -1.46349235
6              MAP_5_improvement  -0.26657333
7             MAP_10_improvement  -0.92429451
8        NDCG_5_mean_improvement  -0.08120841
9       NDCG_10_mean_improvement  -0.07819807