In [1]:
import ir_datasets
dataset = ir_datasets.load("wikir/en1k/training")

In [2]:
from helper import create_tokenized_word_list
tokenized = create_tokenized_word_list(dataset)

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/tahas44/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [3]:
from helper import create_tokenized_word_list_for_query
query_tokenized = create_tokenized_word_list_for_query(dataset)
print("Queries tokenized!")

Queries tokenized!

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/tahas44/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [4]:
query_text_based = []

for query_list in query_tokenized:
    query_text_based.append(" ".join(query_list))

In [4]:
from nltk.stem import PorterStemmer
porter_stemmer = PorterStemmer()
stemmed_texts = []

for word_list in tokenized:
    stemmed_words = [porter_stemmer.stem(word) for word in word_list]
    stemmed_texts.append(stemmed_words)

print("texts stemmed!")

texts stemmed!

In [5]:
stemmed_texts

[['use',
  'land',
  'craft',
  'world',
  'war',
  'ii',
  'use',
  'today',
  'privat',
  'boat',
  'train',
  'facil',
  '6',
  '71',
  'inlin',
  'six',
  'cylind',
  'diesel',
  'engin',
  '71',
  'refer',
  'displac',
  'cubic',
  'inch',
  'cylind',
  'fire',
  'order',
  'engin',
  '1',
  '5',
  '3',
  '6',
  '2',
  '4',
  'engin',
  'compress',
  'ratio',
  '18',
  '7',
  '1',
  '4',
  '250',
  'inch',
  'bore',
  '5',
  '00',
  'inch',
  'stroke',
  'engin',
  'weigh',
  '54',
  'inch',
  'long',
  '29',
  'inch',
  'wide',
  '41',
  'inch',
  'tall',
  '2',
  '100',
  'revolut',
  'per',
  'minut',
  'engin',
  'capabl',
  'produc',
  '230',
  'hors',
  'power',
  '172',
  'kilowatt',
  'v',
  'type',
  'version',
  '71',
  'seri',
  'develop',
  '1957',
  '6',
  '71',
  'two',
  'stroke',
  'engin',
  'engin',
  'natur',
  'aspir',
  'air',
  'provid',
  'via',
  'root',
  'type',
  'blower',
  'howev',
  '6',
  '71t',
  'model',
  'turbocharg',
  'supercharg',
  'util',
  'fuel',
  'provid',
  'unit',
  'injector',
  'one',
  'per',
  'cylind',
  'amount',
  'fuel',
  'inject',
  'engin',
  'control',
  'engin',
  'governor',
  'engin',
  'cool',
  'via',
  'liquid',
  'water',
  'jacket',
  'boat',
  'cool',
  'extern',
  'water',
  'pump',
  'engin'],
 ['reject',
  'offer',
  'cambridg',
  'univers',
  'move',
  'london',
  '1954',
  'work',
  'mayfair',
  'advertis',
  'agenc',
  'moonlight',
  'hat',
  'check',
  'girl',
  'night',
  'club',
  'le',
  'club',
  'contemporain',
  'work',
  'royal',
  'colleg',
  'art',
  'met',
  'painter',
  'frank',
  'bowl',
  'still',
  'student',
  'marri',
  '1960',
  'one',
  'son',
  'kitchen',
  'one',
  'women',
  'interview',
  'nell',
  'dunn',
  'talk',
  'women',
  '1965',
  'divorc',
  'bowl',
  'late',
  'sixti',
  'kitchen',
  'went',
  'live',
  'later',
  'marri',
  'writer',
  'dulan',
  'barber',
  'continu',
  'write',
  'novel',
  'also',
  'began',
  'write',
  'non',
  'fiction',
  'biographi',
  'patrick',
  'gedd',
  'gerard',
  'manley',
  'hopkin',
  'later',
  'life',
  'bought',
  'hous',
  'barnwel',
  'northamptonshir',
  'becam',
  'subject',
  'book',
  'name',
  'die',
  '23',
  'novemb',
  '2005',
  'novelist',
  'bessi',
  'head',
  'close',
  'friend',
  'pair',
  'correspond',
  '1969',
  'head',
  'death',
  '1986',
  'rang',
  'subject',
  'includ',
  'head',
  'novel',
  'question',
  'power'],
 ['mat',
  'zan',
  'coach',
  'kuala',
  'lumpur',
  'fa',
  '1999',
  'malaysia',
  'fa',
  'cup',
  '1999',
  'chariti',
  'cup',
  '2000',
  '2001',
  'mat',
  'zan',
  'move',
  'head',
  'coach',
  'terengganu',
  'fa',
  '2001',
  'malaysia',
  'cup',
  '2001',
  'malaysia',
  'chariti',
  'cup',
  'second',
  'place',
  'malaysia',
  'leagu',
  'plu',
  'f',
  'c',
  '2008',
  'took',
  '2nd',
  'place',
  'premier',
  'leagu',
  'automat',
  'promot',
  'malaysia',
  'super',
  'leagu',
  '2012',
  'comeback',
  'terengganu',
  'fa',
  'go',
  'fa',
  'cup',
  'semi',
  'final',
  'round',
  'two',
  'afc',
  'cup',
  '2015',
  'mat',
  'zan',
  'move',
  'melaka',
  'unit',
  '2015',
  'malaysia',
  'fam',
  'leagu',
  '2016',
  'malaysia',
  'premier',
  'leagu',
  'contract',
  'renew',
  'melaka',
  'end',
  '2016',
  'appoint',
  'new',
  'head',
  'coach',
  'airasia',
  'allstar',
  'fc',
  'renam',
  'petal',
  'jaya',
  'ranger',
  'f',
  'c',
  '2017',
  'season',
  'sign',
  '1',
  'year',
  'contract',
  'negeri',
  'sembilan',
  'form',
  '2019',
  'season',
  'mat',
  'zan',
  'also',
  'coach',
  'club',
  'side',
  'malaysia',
  'u',
  '21',
  'squad',
  'harimau',
  'muda',
  'b',
  'plate',
  'winner',
  'singapor',
  'starhub',
  'leagu',
  'cup',
  'thanj',
  'nien',
  'newspap',
  'cup',
  'vietnam',
  '3rd',
  'place',
  'hassan',
  'bolkiah',
  'cup',
  'brunei',
  '3rd',
  'place'],
 ['barcod',
  'machin',
  'readabl',
  'optic',
  'label',
  'contain',
  'inform',
  'item',
  'attach',
  'practic',
  'qr',
  'code',
  'often',
  'contain',
  'data',
  'locat',
  'identifi',
  'tracker',
  'point',
  'websit',
  'applic',
  'qr',
  'code',
  'use',
  'four',
  'standard',
  'encod',
  'mode',
  'numer',
  'alphanumer',
  'byte',
  'binari',
  'kanji',
  'store',
  'data',
  'effici',
  'extens',
  'may',
  'also',
  'use',
  'quick',
  'respons',
  'system',
  'becam',
  'popular',
  'outsid',
  'automot',
  'industri',
  'due',
  'fast',
  'readabl',
  'greater',
  'storag',
  'capac',
  'compar',
  'standard',
  'upc',
  'barcod',
  'applic',
  'includ',
  'product',
  'track',
  'item',
  'identif',
  'time',
  'track',
  'document',
  'manag',
  'gener',
  'market',
  'qr',
  'code',
  'consist',
  'black',
  'squar',
  'arrang',
  'squar',
  'grid',
  'white',
  'background',
  'read',
  'imag',
  'devic',
  'camera',
  'process',
  'use',
  'reed',
  'solomon',
  'error',
  'correct',
  'imag',
  'appropri',
  'interpret',
  'requir',
  'data',
  'extract',
  'pattern',
  'present',
  'horizont',
  'vertic',
  'compon',
  'imag',
  'qr',
  'code',
  'system',
  'invent',
  '1994',
  'japanes',
  'compani',
  'denso',
  'wave',
  'purpos',
  'track',
  'vehicl',
  'manufactur',
  'design',
  'allow',
  'high',
  'speed',
  'compon',
  'scan',
  'qr',
  'code',
  'use',
  'much'],
 ['sinc',
  'subordin',
  'monarchi',
  'parliament',
  'increasingli',
  'democrat',
  'method',
  'parliamentari',
  'govern',
  'question',
  'whether',
  'parliament',
  'hold',
  'suprem',
  'abil',
  'legisl',
  'whether',
  'tradit',
  'view',
  'put',
  'forward',
  'v',
  'dicey',
  'parliament',
  'power',
  'make',
  'law',
  'except',
  'law',
  'bound',
  'successor',
  'reconsid',
  'constitut',
  'theorist',
  'includ',
  'sir',
  'william',
  'wade',
  'trevor',
  'allan',
  'light',
  'european',
  'commun',
  'act',
  '1972',
  'provis',
  'relat',
  'europ',
  'posit',
  'human',
  'right',
  'act',
  '1998',
  'attempt',
  'make',
  'legisl',
  'entrench',
  'issu',
  'remain',
  'contest',
  'parliamentari',
  'sovereignti',
  'descript',
  'extent',
  'parliament',
  'unit',
  'kingdom',
  'absolut',
  'unlimit',
  'power',
  'frame',
  'term',
  'extent',
  'author',
  'parliament',
  'hold',
  'whether',
  'sort',
  'law',
  'pass',
  'countri',
  'written',
  'constitut',
  'often',
  'bind',
  'parliament',
  'act',
  'certain',
  'way',
  'written',
  'constitut',
  'unit',
  'kingdom',
  'unit',
  'kingdom',
  'parliament',
  'central',
  'institut',
  'state',
  'term'],
 ['tournament',
  'brought',
  'togeth',
  'club',
  'champion',
  'mani',
  'domest',
  'beach',
  'soccer',
  'leagu',
  'across',
  'europ',
  'almost',
  'vein',
  'uefa',
  'champion',
  'leagu',
  'twenti',
  'team',
  'confirm',
  'particip',
  'inaugur',
  'tournament',
  'first',
  'beach',
  'soccer',
  'winner',
  'cup',
  'held',
  'sand',
  'san',
  'benedetto',
  'del',
  'tronto',
  'rive',
  'dell',
  'palm',
  'locat',
  'ascoli',
  'itali',
  '15',
  '19',
  'may',
  '2013',
  'cup',
  'involv',
  'champion',
  'differ',
  'offici',
  'nation',
  'leagu',
  'across',
  'old',
  'contin',
  '18',
  'differ',
  'countri',
  'repres',
  'tournament',
  'first',
  'stage',
  'eighteen',
  'champion',
  'offici',
  'sanction',
  'beach',
  'soccer',
  'nation',
  'championship',
  'plu',
  'host',
  'italian',
  'runner',
  'got',
  'distribut',
  'five',
  'group',
  'yet',
  'offer',
  'interest',
  'battl',
  'power',
  'team',
  'compet',
  'head',
  'group',
  'side',
  'top',
  'group',
  'grant',
  'ticket',
  'quarterfin',
  'stage',
  'accompani',
  'three',
  'best',
  'second',
  'rank',
  'team',
  'stadium',
  'use',
  'call',
  'umpi',
  'smart',
  'beach',
  'arena',
  'new',
  'state',
  'art',
  'facil',
  'intend',
  'maxim',
  'technolog',
  'environment',
  'conscious',
  'direct',
  'creat',
  'stadium',
  'offer',
  '360',
  'degre',
  'amus',
  'possibl',
  'citizen'],
 ['januari',
  '1948',
  'ballen',
  'acquir',
  'interest',
  'good',
  'becam',
  'sole',
  'owner',
  'move',
  'compani',
  'philadelphia',
  'pennsylvania',
  'label',
  'base',
  'rest',
  'exist',
  '1956',
  'label',
  'special',
  'rhythm',
  'blue',
  'ivin',
  'ballen',
  'die',
  'miami',
  'beach',
  'florida',
  'februari',
  '1978',
  'gotham',
  'notabl',
  'contribut',
  'american',
  'music',
  'releas',
  'record',
  'acoust',
  'bluesman',
  'dan',
  'pickett',
  'origin',
  'record',
  '1949',
  'anoth',
  'artist',
  'record',
  'gotham',
  'includ',
  'doug',
  'quattlebaum',
  'song',
  'lizzi',
  'lou',
  'one',
  'last',
  'releas',
  'label',
  'dori',
  'brown',
  'singer',
  'around',
  '1949',
  '1950',
  'period',
  'perform',
  'weekli',
  'show',
  'broadcast',
  'wpen',
  'philadelphia',
  'hour',
  'long',
  'show',
  'call',
  'parisian',
  'tailor',
  'kiddi',
  'hour',
  '1953',
  'label',
  'appear',
  'keen',
  'push',
  'brown',
  'profil',
  'singl',
  'pleas',
  'believ',
  'bw',
  'oh',
  'babi',
  'back',
  'doc',
  'bagbi',
  'record',
  'also',
  'back',
  'singl',
  'end',
  'time',
  'bw',
  'love',
  'gotham',
  'g',
  '296',
  'anoth',
  'record',
  'game',
  'love',
  'bw',
  'cheri'],
 ['particularli',
  'notabl',
  'associ',
  'sever',
  'canada',
  'lead',
  'blue',
  'singer',
  'includ',
  'richard',
  'hock',
  'walsh',
  'toni',
  'flaim',
  'chuck',
  'jackson',
  'also',
  'associ',
  'downchild',
  'blue',
  'band',
  'band',
  'name',
  'cameo',
  'loung',
  'toronto',
  'hotel',
  'isabella',
  '1970',
  '1980',
  'cameo',
  'loung',
  'featur',
  'primarili',
  'local',
  'blue',
  'artist',
  '1978',
  'regular',
  'hous',
  'band',
  'initi',
  'led',
  'richard',
  'hock',
  'walsh',
  'one',
  'sever',
  'period',
  'walsh',
  'either',
  'fire',
  'quit',
  'lead',
  'singer',
  'downchild',
  'blue',
  'band',
  'walsh',
  'soon',
  'join',
  'former',
  'crowbar',
  'keyboard',
  'player',
  'rabbit',
  'ray',
  'harrison',
  'along',
  'guitarist',
  'john',
  'bride',
  'becam',
  'core',
  'group',
  'three',
  'decad',
  'histori',
  'initi',
  'band',
  'member',
  'includ',
  'billi',
  'bryan',
  'later',
  'parachut',
  'club',
  'drum',
  'omar',
  'tunnock',
  'later',
  'funk',
  'blue',
  'band',
  'fathead',
  'bass',
  'hock',
  'walsh',
  'soon',
  'left',
  'band',
  'return',
  'downchild',
  'briefli',
  'replac',
  'fraser',
  'finlayson',
  'band',
  'cuebal',
  'prior',
  'band',
  'find',
  'replac',
  'toni',
  'flaim',
  'hock',
  'walsh',
  'replac',
  'downchild',
  'billi',
  'bryan',
  'replac'],
 ['also',
  'known',
  'wamba',
  'wamba',
  'wemba',
  'wemba',
  'bear',
  'strong',
  'similar',
  'woiwurrung',
  'moravian',
  'missionari',
  'came',
  'start',
  'learn',
  'languag',
  'wembawemba',
  'territori',
  'archibald',
  'macarthur',
  'camppbel',
  'gannawarra',
  'station',
  'quickli',
  'note',
  'nativ',
  'perceiv',
  'understood',
  'slip',
  'use',
  'anoth',
  'languag',
  'will',
  'allow',
  'cultur',
  'conquest',
  'enabl',
  'whitemen',
  'learn',
  'matter',
  'wish',
  'keep',
  'secret',
  'outsid',
  'european',
  'settlement',
  'nineteenth',
  'centuri',
  'wemba',
  'wemba',
  'occupi',
  'area',
  'around',
  'loddon',
  'river',
  'reach',
  'northward',
  'kerang',
  'victoria',
  'swan',
  'hill',
  'includ',
  'area',
  'avoca',
  'river',
  'southward',
  'toward',
  'quambatook',
  'northeasterli',
  'direct',
  'territori',
  'ran',
  'new',
  'south',
  'wale',
  'victorian',
  'border',
  'boorrorban',
  'moulamein',
  'extend',
  'vicin',
  'barham',
  'lake',
  'boga',
  'boora',
  'victoria',
  'also',
  'fell',
  'within',
  'domain',
  'overal',
  'extens',
  'territori',
  'calcul',
  'norman',
  'tindal',
  'roughli',
  'wembawemba',
  'regist',
  'consist',
  'five',
  'hord',
  'stone',
  'list',
  'hord',
  'resid',
  'around',
  'towaninni',
  'meelool',
  'station',
  'name',
  'indic',
  'thought',
  'quarrelsom',
  'lake',
  'boga',
  'gonn',
  'murray',
  'river',
  'call',
  'dietjenbaluk',
  'alway'],
 ['move',
  'south',
  'england',
  'cannock',
  'staffordshir',
  'form',
  'balaam',
  'angel',
  'initi',
  'band',
  'self',
  'releas',
  'seri',
  'ep',
  'album',
  'entitl',
  'sun',
  'famili',
  'via',
  'chapter',
  '22',
  'label',
  'play',
  'tour',
  'date',
  'open',
  'cult',
  'caught',
  'attent',
  'virgin',
  'record',
  'sign',
  'releas',
  'debut',
  'album',
  'greatest',
  'stori',
  'ever',
  'told',
  'peak',
  '67',
  'uk',
  'album',
  'chart',
  'august',
  '1986',
  'tour',
  'unit',
  'state',
  'mission',
  'kiss',
  'label',
  'mate',
  'iggi',
  'pop',
  'second',
  'guitarist',
  'first',
  'non',
  'sibl',
  'ian',
  'mckean',
  'twenti',
  'flight',
  'rocker',
  'ad',
  'band',
  '1988',
  'band',
  'began',
  'move',
  'away',
  'gothic',
  'rock',
  'music',
  'style',
  'sound',
  'common',
  'hard',
  'rock',
  'new',
  'found',
  'style',
  'record',
  'album',
  'live',
  'free',
  'die',
  'soon',
  'follow',
  'similar',
  'style',
  'record',
  'day',
  'mad',
  'leav',
  'virgin',
  'record',
  'song',
  'show',
  'someth',
  'special',
  'appear',
  'soundtrack',
  'film',
  'plane',
  'train',
  'automobil',
  'presenc',
  'larg',
  'ignor',
  'time',
  '1993',
  'album',
  'prime'],
 ['farm',
  'forestri',
  'remain',
  'central',
  'rural',
  'economi',
  'rural',
  'develop',
  'also',
  'focus',
  'revitalis',
  'rural',
  'area',
  'way',
  'furthermor',
  'issu',
  'climat',
  'chang',
  'renew',
  'energi',
  'biodivers',
  'water',
  'manag',
  'becom',
  'increasingli',
  'import',
  'aspect',
  'eu',
  'rural',
  'develop',
  'polici',
  '200',
  'billion',
  'fund',
  'avail',
  'support',
  'implement',
  '94',
  'rdp',
  'across',
  'eu',
  'program',
  'period',
  '2007',
  '2013',
  'almost',
  'half',
  'money',
  'provid',
  'eafrd',
  'overseen',
  'european',
  'commiss',
  'director',
  'gener',
  'agricultur',
  'rural',
  'develop',
  'eafrd',
  'budget',
  'rdp',
  'use',
  'achiev',
  'varieti',
  'rural',
  'develop',
  'goal',
  'includ',
  'improv',
  'competit',
  'farm',
  'forest',
  'agri',
  'food',
  'busi',
  'help',
  'protect',
  'natur',
  'environ',
  'support',
  'rural',
  'economi',
  'assist',
  'qualiti',
  'life',
  'rural',
  'area'],
 ['die',
  'work',
  'project',
  'great',
  'storm',
  '1703',
  'born',
  'saffron',
  'walden',
  'essex',
  'baptis',
  '31',
  'march',
  '1644',
  'father',
  'henri',
  'becam',
  'land',
  'steward',
  'earl',
  'suffolk',
  'owner',
  'audley',
  'end',
  'hous',
  '1652',
  'young',
  'henri',
  'also',
  'work',
  'audley',
  'end',
  'first',
  'porter',
  'secretari',
  '1666',
  'audley',
  'end',
  'hous',
  'bought',
  'charl',
  'ii',
  'use',
  'base',
  'attend',
  'newmarket',
  'race',
  'becam',
  'effect',
  'royal',
  'palac',
  'winstanley',
  'develop',
  'interest',
  'engrav',
  'grand',
  'tour',
  'europ',
  '1669',
  '1674',
  'impress',
  'continent',
  'architectur',
  'engrav',
  'portray',
  'return',
  'believ',
  'studi',
  'engrav',
  'wencesla',
  'hollar',
  'employ',
  'audley',
  'end',
  'hous',
  'assist',
  'clerk',
  'work',
  '1676',
  'embark',
  'detail',
  'set',
  'architectur',
  'engrav',
  'audley',
  'end',
  'hous',
  'took',
  'ten',
  'year',
  'complet',
  'surviv',
  'import',
  'earli',
  'record',
  'english',
  'manor',
  'hous',
  'architectur',
  'also',
  'design',
  'set',
  'play',
  'card',
  'becam',
  'popular',
  'sold',
  'well',
  'appoint',
  'clerk'],
 ['grade',
  'list',
  'build',
  'written',
  'histori',
  'denton',
  'goe',
  'back',
  'least',
  '1253',
  'owner',
  'one',
  'athelstan',
  'confus',
  'king',
  'name',
  'made',
  'estat',
  'see',
  'york',
  'alreadi',
  'own',
  'manori',
  'right',
  'nearbi',
  'otley',
  'subinfeud',
  'sub',
  'let',
  'earli',
  'date',
  'vavasour',
  '1284',
  'maugeru',
  'le',
  'vavasur',
  'held',
  'town',
  'fourth',
  'part',
  'knight',
  'fee',
  'archbishop',
  'york',
  'continu',
  'lord',
  'paramount',
  '1379',
  'accord',
  'poll',
  'tax',
  'return',
  'one',
  'adam',
  'wayt',
  'appear',
  'farm',
  'manor',
  'time',
  'denton',
  'ordinari',
  'reput',
  'cloth',
  'make',
  'draperi',
  'good',
  'estat',
  'pass',
  'ownership',
  'thwait',
  'famili',
  'elizabeth',
  'daughter',
  'henri',
  'thwait',
  'marri',
  'john',
  'vavasour',
  'weston',
  'die',
  '1482',
  'record',
  'show',
  'thwait',
  'famili',
  'resid',
  'denton',
  'villag',
  'earlier',
  'time',
  'marriag',
  '1515',
  'estat',
  'pass',
  'fairfax',
  'famili',
  'time',
  'thoma',
  'fairfax',
  '1st',
  'lord',
  'fairfax',
  'cameron',
  'denton',
  'hall',
  'reput',
  'hous',
  'one',
  'best',
  'librari'],
 ['elect',
  'hous',
  'repres',
  'nigeria',
  '2007',
  'repres',
  'ebonyi',
  'ohaukwu',
  'feder',
  'constitu',
  'elect',
  'platform',
  'peopl',
  'democrat',
  'parti',
  'pdp',
  'hon',
  'elizabeth',
  'ogbaga',
  'member',
  'follow',
  'committe',
  'decemb',
  '2009',
  'hon',
  'elizabeth',
  'ogbaga',
  'express',
  'dissatisfact',
  'call',
  'low',
  'level',
  'implement',
  'project',
  'contain',
  '2009',
  'budget',
  'sponsor',
  'numer',
  'bill',
  'motion',
  'often',
  'decri',
  'low',
  'particip',
  'women',
  'polit',
  'state',
  'affect',
  'democraci',
  'hon',
  'elizabeth',
  'ogbaga',
  'attract',
  'variou',
  'project',
  'oxygen',
  'plant',
  'mammogram',
  'machin',
  'feder',
  'medic',
  'centr',
  'abakaliki',
  'free',
  'antenat',
  'care',
  'servic',
  'pregnant',
  'mother',
  'ebonyi',
  'ohaukwu',
  'feder',
  'constitu',
  'construct',
  'sever',
  '3',
  'classroom',
  'block',
  'hand',
  'pump',
  'borehol',
  'onuenyim',
  'ishiek',
  'ndiofia',
  'nkalek',
  'igweledoha',
  'ogbala',
  'parish',
  'effenyim',
  'ongo',
  'oterufi',
  'nkalek',
  'ndiechi',
  'ndiugo',
  'isophumini',
  'mbeke',
  'isophumini',
  'st',
  'michael',
  'parish',
  'mbeke',
  'ishiek',
  'nwonuewo',
  'effium',
  'ohaukwu',
  'ogen',
  'ohaukwu',
  'umugadu',
  'commun',
  'secondari',
  'school',
  'also',
  'construct',
  'nation',
  'health',
  'care',
  'centr',
  'izenyi',
  'agbaja',
  'izzi',
  'lga',
  'ohagelod',
  'ongo',
  'train',
  '50',
  'youth',
  'ict',
  'well',
  'provid',
  'comput',
  'accessori',
  'hon',
  'elizabeth',
  'ogbaga',
  'construct',
  'bridg',
  'across',
  'ebonyi',
  'river'],
 ['held',
  'annual',
  'sinc',
  '2007',
  'southern',
  'bank',
  'lake',
  'balaton',
  'hungari',
  'featur',
  'live',
  'act',
  'dj',
  'around',
  'world',
  'establish',
  'artist',
  'new',
  'name',
  'event',
  'co',
  'creat',
  'organ',
  'sziget',
  'festiv',
  'festiv',
  'get',
  'famou',
  'popular',
  'year',
  'ticket',
  'usual',
  'sold',
  'go',
  'sale',
  'offici',
  'ticket',
  'vendor',
  'event',
  'set',
  'new',
  'attend',
  'record',
  'yearli',
  'first',
  'balaton',
  'sound',
  'festiv',
  'held',
  '12',
  'juli',
  '15',
  'juli',
  '2007',
  'fact',
  'event',
  'held',
  'shore',
  'largest',
  'lake',
  'central',
  'europ',
  'mid',
  'summer',
  'twenti',
  'hour',
  'music',
  'schedul',
  'line',
  'gain',
  'signific',
  'public',
  'interest',
  'festiv',
  'locat',
  'west',
  'part',
  'zam',
  'rdi',
  'cross',
  'panor',
  'z',
  'ldfa',
  'utca',
  'street',
  'insid',
  'festiv',
  'area',
  'variabl',
  'stage',
  'loung',
  'tent',
  'establish',
  'perform',
  'sponsor',
  'festiv',
  'creat',
  'luxuri',
  'chill',
  'facil',
  'hammock',
  'bean',
  'bag',
  'easi',
  'chair',
  'visitor',
  'balaton',
  'sound',
  'stay',
  'special',
  'campsit',
  'sever',
  'pub',
  'cocktail',
  'bar',
  'restaur',
  'equip',
  'accoutr',
  'absent',
  'hungari',
  'summer',
  'music'],
 ['co',
  'found',
  'phillip',
  'collect',
  'husband',
  'duncan',
  'phillip',
  'born',
  'marjori',
  'acker',
  'bourbon',

In [6]:
from rank_bm25 import BM25Okapi
bm25 = BM25Okapi(stemmed_texts)

In [8]:
scores_of_all_queries = []

for query in query_tokenized:
    scores_of_all_queries.append(bm25.get_scores(query))

In [10]:
len(scores_of_all_queries)

1444

In [13]:
from collections import defaultdict
from helper import Scoredoc

doc_dict = defaultdict(str)

for i, doc in enumerate(dataset.docs_iter()):
    doc_dict[i] = doc.doc_id

doc_dict = dict(doc_dict)

qrels_dict = defaultdict(list)

for qrel in dataset.qrels_iter():
    qrels_dict[qrel.query_id].append(qrel.doc_id)

qrels_dict = dict(qrels_dict)

score_doc_dict = defaultdict(list)

for scoreddoc in dataset.scoreddocs_iter():
    doc_id = scoreddoc.doc_id
    score = scoreddoc.score

    scoreddoc_object = Scoredoc(doc_id, score)

    score_doc_dict[scoreddoc.query_id].append(scoreddoc_object)

score_doc_dict = dict(score_doc_dict)

print("Necessary dicts created!")

Necessary dicts created!

In [12]:
import pandas as pd
query_ids = [query.query_id for query in dataset.queries_iter()]
df = pd.DataFrame(query_ids, columns=["Query_ID"])
df

     Query_ID
0      123839
1      188629
2       13898
3      316959
4      515031
...       ...
1439   896124
1440    12319
1441     4421
1442   296526
1443   341793

[1444 rows x 1 columns]

In [13]:
from helper import create_AP, create_ndcg, create_statistical_columns
df = create_statistical_columns(df, qrels_dict, doc_dict, scores_of_all_queries)
df = create_AP(df, qrels_dict, doc_dict, scores_of_all_queries)
df = create_ndcg(df, doc_dict, scores_of_all_queries, score_doc_dict)

In [14]:
df

,Query_ID,recall_5,recall_10,precision_5,precision_10,f_score_5,f_score_10,AP_5,AP_10,NDCG_5,NDCG_10
0,123839,50.000000,100.000000,60.0,60.0,54.545455,75.000000,0.458333,0.768849,0.883923,0.852981
1,188629,33.333333,33.333333,40.0,20.0,36.363636,25.000000,0.333333,0.333333,0.889669,0.918338
2,13898,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.188244,0.238403
3,316959,11.111111,22.222222,20.0,20.0,14.285714,21.052632,0.111111,0.148148,1.000000,0.998975
4,515031,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.892079,0.924320
...,...,...,...,...,...,...,...,...,...,...,...
1439,896124,12.500000,12.500000,20.0,10.0,15.384615,11.111111,0.125000,0.125000,0.464253,0.502333
1440,12319,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.197367,0.189544
1441,4421,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.495470,0.468331
1442,296526,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.093400
1443,341793,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.575369,0.584886

In [15]:
mydict = {
    "Method": "BM25 - Porter's Stemmer",
    "recall_5_mean": df["recall_5"].mean(),
    "recall_5_std": df["recall_5"].std(),
    "recall_5_max": df["recall_5"].max(),
    "recall_5_min": df["recall_5"].min(),
    "recall_10_mean": df["recall_10"].mean(),
    "recall_10_std": df["recall_10"].std(),
    "recall_10_max": df["recall_10"].max(),
    "recall_10_min": df["recall_10"].min(),
    "precision_5_mean": df["precision_5"].mean(),
    "precision_5_std": df["precision_5"].std(),
    "precision_5_max": df["precision_5"].max(),
    "precision_5_min": df["precision_5"].min(),
    "precision_10_mean": df["precision_10"].mean(),
    "precision_10_std": df["precision_10"].std(),
    "precision_10_max": df["precision_10"].max(),
    "precision_10_min": df["precision_10"].min(),
    "f_score_5_mean": df["f_score_5"].mean(),
    "f_score_5_std": df["f_score_5"].std(),
    "f_score_5_max": df["f_score_5"].max(),
    "f_score_5_min": df["f_score_5"].min(),
    "f_score_10_mean": df["f_score_10"].mean(),
    "f_score_10_std": df["f_score_10"].std(),
    "f_score_10_max": df["f_score_10"].max(),
    "f_score_10_min": df["f_score_10"].min(),
    "MAP_5": df["AP_5"].mean(),
    "MAP_10": df["AP_10"].mean(),
    "NDCG_5_mean": df["NDCG_5"].mean(),
    "NDCG_5_std": df["NDCG_5"].std(),
    "NDCG_5_max": df["NDCG_5"].max(),
    "NDCG_5_min": df["NDCG_5"].min(),
    "NDCG_10_mean": df["NDCG_10"].mean(),
    "NDCG_10_std": df["NDCG_10"].std(),
    "NDCG_10_max": df["NDCG_10"].max(),
    "NDCG_10_min": df["NDCG_10"].min()
}

In [16]:
df_csv = pd.DataFrame(mydict, index=[0])
df_csv

,Method,recall_5_mean,recall_5_std,recall_5_max,recall_5_min,recall_10_mean,recall_10_std,recall_10_max,recall_10_min,precision_5_mean,...,MAP_5,MAP_10,NDCG_5_mean,NDCG_5_std,NDCG_5_max,NDCG_5_min,NDCG_10_mean,NDCG_10_std,NDCG_10_max,NDCG_10_min
0,BM25 - Porter's Stemmer,9.35294,13.872295,83.333333,0.0,13.876176,19.458257,100.0,0.0,19.044321,...,0.072112,0.091605,0.541213,0.369604,1.0,0.0,0.548739,0.365356,1.0,0.0

In [17]:
df_csv.to_parquet("BM25PorterStemmer.parquet")
print("Parquet dosyası kaydedildi!")

Parquet dosyası kaydedildi!

### Stem the Query vectors

In [7]:
stemmed_queries = []

for query_list in query_tokenized:
    stemmed_query_words = [porter_stemmer.stem(word) for word in query_list]
    stemmed_queries.append(stemmed_query_words)

print("Queries stemmed!")

Queries stemmed!

In [8]:
stemmed_queries

[['yanni'],
 ['k', 'pop'],
 ['venic', 'film', 'festiv'],
 ['downtown', 'brooklyn'],
 ['pennsylvania', 'hous', 'repres'],
 ['northern', 'premier', 'leagu'],
 ['first', 'nation', 'pictur'],
 ['poland'],
 ['cyperacea'],
 ['trinidad', 'tobago'],
 ['normandi', 'land'],
 ['perri', 'index'],
 ['arm', 'architectur'],
 ['mi5'],
 ['patriarch', 'antioch'],
 ['nashik', 'district'],
 ['semiot'],
 ['santa', 'cruz', 'de', 'tenerif'],
 ['gastropoda'],
 ['zaragoza'],
 ['south', 'carolina'],
 ['augustin', 'hippo'],
 ['canton', 'geneva'],
 ['leo', 'tolstoy'],
 ['riemannian', 'manifold'],
 ['tuzla'],
 ['subaru'],
 ['tomsk'],
 ['unit', 'state', 'depart', 'agricultur'],
 ['north', 'borneo'],
 ['isaac', 'asimov'],
 ['hilbert', 'space'],
 ['chechen'],
 ['arunach', 'pradesh'],
 ['central', 'otago'],
 ['ira', 'gershwin'],
 ['rock', 'roll'],
 ['fiba'],
 ['east', 'coast', 'unit', 'state'],
 ['wikipedia'],
 ['pernambuco'],
 ['west', 'coast', 'eagl'],
 ['twin', 'peak'],
 ['dutch', 'languag'],
 ['liber', 'parti', 'canada'],
 ['spratli', 'island'],
 ['kampala'],
 ['nation', 'film', 'board', 'canada'],
 ['turkish', 'war', 'independ'],
 ['chania'],
 ['oakland', 'raider'],
 ['krishnagiri', 'district'],
 ['vr', 'group'],
 ['trade', 'name'],
 ['anglo', 'saxon'],
 ['bermuda'],
 ['paradox', 'develop', 'studio'],
 ['usenet'],
 ['bbc', 'radio'],
 ['wallac', 'steven'],
 ['spain'],
 ['franchis'],
 ['unit', 'artist', 'record'],
 ['royal', 'corp', 'signal'],
 ['palawan'],
 ['sein', 'et', 'marn'],
 ['west', 'countri'],
 ['bailiwick', 'guernsey'],
 ['pleuronectida'],
 ['incom', 'tax', 'unit', 'state'],
 ['gp3', 'seri'],
 ['septimiu', 'severu'],
 ['pharaoh'],
 ['metropolitan', 'borough', 'doncast'],
 ['histori', 'jew', 'poland'],
 ['erasur'],
 ['suez', 'canal'],
 ['naval', 'air', 'station', 'lemoor'],
 ['lower', 'saxoni'],
 ['robert', 'stack'],
 ['boe'],
 ['wexford', 'gaa'],
 ['miss', 'univers'],
 ['sydney', 'central', 'busi', 'district'],
 ['keweenaw', 'peninsula'],
 ['music'],
 ['nba', 'g', 'leagu'],
 ['makati'],
 ['genr', 'art'],
 ['aintre', 'racecours'],
 ['colchest'],
 ['christian', 'rock'],
 ['clash'],
 ['friedrich', 'schiller'],
 ['comedi', 'drama'],
 ['tiberia'],
 ['fc', 'basel'],
 ['new', 'york', 'knick'],
 ['perm', 'krai'],
 ['dordogn'],
 ['dutch', 'west', 'india', 'compani'],
 ['titian'],
 ['victorian', 'burlesqu'],
 ['tvb'],
 ['murida'],
 ['tvxq'],
 ['kenneth', 'cope'],
 ['london', 'borough', 'islington'],
 ['top', 'cow', 'product'],
 ['bradford', 'bull'],
 ['mike', 'oldfield'],
 ['shooter', 'game'],
 ['hull', 'kingston', 'rover'],
 ['nation', 'scienc', 'foundat'],
 ['grau'],
 ['dannii', 'minogu'],
 ['christoph', 'nolan'],
 ['moscow', 'oblast'],
 ['british', 'nation', 'parti'],
 ['balochi', 'languag'],
 ['benjamin', 'franklin'],
 ['big', 'south', 'confer'],
 ['cantabria'],
 ['alic', 'chain'],
 ['michigan'],
 ['soundgarden'],
 ['bermondsey'],
 ['2017', 'ncaa', 'divis', 'fb', 'footbal', 'season'],
 ['northwestern', 'unit', 'state'],
 ['southeast', 'asia'],
 ['social', 'psycholog'],
 ['john', 'coltran'],
 ['roll', 'distinguish', 'philatelist'],
 ['restor', 'movement'],
 ['danni', 'elfman'],
 ['konkani', 'languag'],
 ['dungannon'],
 ['unit', 'soccer', 'leagu'],
 ['chapter', 'vers', 'bibl'],
 ['isl', 'man', 'tt'],
 ['eth', 'zurich'],
 ['emir', 'abu', 'dhabi'],
 ['delawar', 'river'],
 ['black', 'sea'],
 ['antigua'],
 ['primari', 'school'],
 ['berber', 'languag'],
 ['loch', 'lomond'],
 ['african', 'union'],
 ['north', 'american', 'number', 'plan'],
 ['ural', 'mountain'],
 ['utah'],
 ['algarv', 'cup'],
 ['mix', 'martial', 'art'],
 ['jaxa'],
 ['plateau', 'state'],
 ['albanian', 'nation', 'awaken'],
 ['unionida'],
 ['mysteri', 'fiction'],
 ['metropolitan', 'polic', 'servic'],
 ['bukovina'],
 ['wilbert', 'awdri'],
 ['american'],
 ['western', 'bulldog'],
 ['christian', 'theolog'],
 ['patriarch'],
 ['skanderbeg'],
 ['korea', 'japanes', 'rule'],
 ['major', 'leagu', 'lacross'],
 ['perak'],
 ['graduat', 'school'],
 ['master', 'fine', 'art'],
 ['littl', 'leagu', 'world', 'seri'],
 ['tugboat'],
 ['2016', 'unit', 'state', 'presidenti', 'elect'],
 ['unit', 'state', 'nation', 'rugbi', 'union', 'team'],
 ['1906', 'intercal', 'game'],
 ['boca', 'del', 'toro', 'provinc'],
 ['inlin', 'four', 'engin'],
 ['english', 'feudal', 'baroni'],
 ['royal', 'guelphic', 'order'],
 ['bodybuild'],
 ['dusti', 'springfield'],
 ['caserta'],
 ['northrop', 'grumman'],
 ['bourbon', 'restor'],
 ['sql'],
 ['south', 'cambridgeshir'],
 ['alappuzha'],
 ['unit', 'state', 'nation', 'guard'],
 ['korean', 'drama'],
 ['thiruvananthapuram'],
 ['collect'],
 ['uzbek'],
 ['vicker', 'limit'],
 ['lui', 'miguel'],
 ['ottoman', 'navi'],
 ['truman', 'capot'],
 ['arnold', 'schwarzenegg'],
 ['tauru', 'mountain'],
 ['easter', 'rise'],
 ['henri', 'david', 'thoreau'],
 ['georg', 'jone'],
 ['bbc', 'radio', '1'],
 ['craven'],
 ['architectur'],
 ['sega'],
 ['second', 'sea', 'lord'],
 ['stena', 'line'],
 ['wingecarribe', 'shire'],
 ['fraser', 'coast', 'region'],
 ['intellivis'],
 ['gridiron', 'footbal'],
 ['moreton', 'bay', 'region'],
 ['ultim', 'play', 'game'],
 ['literatur'],
 ['podgorica'],
 ['lugano'],
 ['smokey', 'robinson'],
 ['major', 'leagu', 'soccer'],
 ['london', 'borough', 'redbridg'],
 ['roman', 'britain'],
 ['budapest'],
 ['rugbi', 'footbal'],
 ['archbishop', 'york'],
 ['edward', 'ii', 'england'],
 ['ajmer'],
 ['yamaguchi', 'prefectur'],
 ['jaipur'],
 ['indonesian', 'cuisin'],
 ['port', 'lo', 'angel'],
 ['british', 'academi'],
 ['unit', 'methodist', 'church'],
 ['independ', 'music'],
 ['chiswick'],
 ['celebr'],
 ['ivi', 'leagu'],
 ['na'],
 ['provinc', 'massachusett', 'bay'],
 ['christma', 'carol'],
 ['aix', 'en', 'provenc'],
 ['black', 'hill'],
 ['willamett', 'valley'],
 ['master', 'wine'],
 ['carl', 'reiner'],
 ['podlaski', 'voivodeship'],
 ['princess'],
 ['collin', 'crime', 'club'],
 ['romanian', 'naval', 'forc'],
 ['poxvirida'],
 ['koper'],
 ['limerick', 'gaa'],
 ['ancona'],
 ['mauritiu'],
 ['clark', 'univers'],
 ['ohio'],
 ['ludwigsburg'],
 ['provinc', 'chile'],
 ['right', 'wing', 'polit'],
 ['horticultur'],
 ['richard', 'nixon'],
 ['indi', 'rock'],
 ['samsung'],
 ['virginia', 'gener', 'assembl'],
 ['schutzstaffel'],
 ['cloud', 'comput'],
 ['upper', 'carniola'],
 ['crown', 'coloni'],
 ['metropolitan', 'borough', 'solihul'],
 ['valladolid'],
 ['william', 'goldman'],
 ['socialist', 'uniti', 'parti', 'germani'],
 ['irem'],
 ['turkic', 'peopl'],
 ['coldplay'],
 ['prunu'],
 ['odin'],
 ['vh1'],
 ['twelfth', 'grade'],
 ['faversham'],
 ['citi', 'townsvil'],
 ['triniti', 'colleg', 'dublin'],
 ['tasmanian', 'hous', 'assembl'],
 ['kgb'],
 ['idaho'],
 ['liao', 'dynasti'],
 ['gascon', 'languag'],
 ['luxembourg', 'citi'],
 ['saddam', 'hussein'],
 ['ovid'],
 ['venu'],
 ['srikakulam', 'district'],
 ['vest', 'agder'],
 ['comedi'],
 ['megadeth'],
 ['sioux'],
 ['baie', 'jame'],
 ['frontier', 'martial', 'art', 'wrestl'],
 ['east', 'lothian'],
 ['indomalayan', 'realm'],
 ['albacet'],
 ['richard', 'fleischer'],
 ['cincinnati', 'red'],
 ['vyborg'],
 ['provinci', 'assembl', 'punjab'],
 ['hamburg'],
 ['ku', 'ring', 'gai', 'council'],
 ['hanoi'],
 ['northern', 'england'],
 ['nonpartisan'],
 ['reserv', 'bank', 'india'],
 ['toni', 'hatch'],
 ['joan', 'arc'],
 ['chines', 'american'],
 ['fox', 'broadcast', 'compani'],
 ['parramatta', 'eel'],
 ['duisburg'],
 ['oxford', 'univers', 'press'],
 ['yukon'],
 ['tenant', 'purchas', 'scheme'],
 ['cthulhu', 'mytho'],
 ['cape', 'town'],
 ['phoenicia'],
 ['equestrian'],
 ['taunton'],
 ['1947', 'ceylones', 'parliamentari', 'elect'],
 ['triathlon'],
 ['west', 'coast', 'main', 'line'],
 ['ghana'],
 ['manchest', 'metrolink'],
 ['darfur'],
 ['jim', 'crockett', 'promot'],
 ['antoninu', 'piu'],
 ['isl', 'dog'],
 ['smith'],
 ['dewan', 'rakyat'],
 ['jennif', 'row'],
 ['kaduna', 'state'],
 ['dahomey'],
 ['nakskov'],
 ['ciutat', 'vella'],
 ['ohio', 'river'],
 ['civil', 'engin'],
 ['kaluga', 'oblast'],
 ['london', 'borough', 'croydon'],
 ['guillermo', 'del', 'toro'],
 ['germani'],
 ['french', 'polynesia'],
 ['chvrche'],
 ['mark', 'twain'],
 ['shahe', 'bhagat', 'singh', 'nagar', 'district'],
 ['cyclad'],
 ['strabo'],
 ['milton', 'bradley', 'compani'],
 ['occitan', 'languag'],
 ['yenisei', 'river'],
 ['bangladesh'],
 ['lake', 'taho'],
 ['brandenburg'],
 ['jacob'],
 ['franc', 'nation', 'footbal', 'team'],
 ['veikkausliiga'],
 ['2015', 'canadian', 'feder', 'elect'],
 ['kurdistan', 'region'],
 ['snk'],
 ['bbc', 'televis'],
 ['unit', 'state', 'depart', 'defens'],
 ['princ', 'elector'],
 ['new', 'england'],
 ['rca'],
 ['qinghai'],
 ['chilean', 'war', 'independ'],
 ['daft', 'punk'],
 ['ghana', 'nation', 'footbal', 'team'],
 ['chines', 'buddhism'],
 ['florenc'],
 ['samara', 'oblast'],
 ['yekaterinburg'],
 ['connecticut', 'river'],
 ['indonesia'],
 ['vancouv'],
 ['miami', 'marlin'],
 ['joseph', 'stalin'],
 ['travel', 'literatur'],
 ['christian', 'democrat', 'appeal'],
 ['detroit', 'piston'],
 ['taranto'],
 ['port', 'washington', 'branch'],
 ['yellowknif'],
 ['sahrawi', 'arab', 'democrat', 'republ'],
 ['derri', 'gaa'],
 ['union', 'ireland'],
 ['soviet', 'arm', 'forc'],
 ['lo', 'angel'],
 ['thoma', 'jefferson'],
 ['hal', 'roach'],
 ['cardiff', 'rfc'],
 ['govern', 'kerala'],
 ['regent'],
 ['british', 'peopl'],
 ['american'],
 ['bell', 'system'],
 ['sabrina', 'carpent'],
 ['daniel', 'steel'],
 ['lincolnshir'],
 ['printmak'],
 ['vicenza'],
 ['eric', 'clapton'],
 ['dj', 'khale'],
 ['counti', 'doneg'],
 ['lockhe', 'corpor'],
 ['southern', 'rock'],
 ['georg', 'gershwin'],
 ['salvat', 'armi'],
 ['bell', 'lab'],
 ['list', 'north', 'carolina', 'state', 'park'],
 ['falkland', 'war'],
 ['gustav', 'mahler'],
 ['monster', 'movi'],
 ['cheap', 'trick'],
 ['chines', 'taipei'],
 ['liechtenstein'],
 ['daili', 'mail'],
 ['solan', 'district'],
 ['goth'],
 ['british', 'empir'],
 ['scholast', 'corpor'],
 ['ten', 'pin', 'bowl'],
 ['citi', 'univers', 'new', 'york'],
 ['vinnytsia', 'oblast'],
 ['centr', 'nation', 'de', 'la', 'recherch', 'scientifiqu'],
 ['opeth'],
 ['neuwi'],
 ['tamper'],
 ['intern', 'brigad'],
 ['north', 'london'],
 ['serbian', 'cyril', 'alphabet'],
 ['northeastern', 'ontario'],
 ['hackensack', 'river'],
 ['old', 'world', 'warbler'],
 ['danish', 'superliga'],
 ['niue'],
 ['puducherri'],
 ['namibia'],
 ['royal', 'rumbl'],
 ['atlant', 'leagu', 'profession', 'basebal'],
 ['bornholm'],
 ['alappuzha', 'district'],
 ['spongebob', 'squarep'],
 ['royal', 'caribbean', 'intern'],
 ['kim', 'jong', 'il'],
 ['keanu', 'reev'],
 ['argentina', 'nation', 'footbal', 'team'],
 ['lloyd', 'bacon'],
 ['annett', 'andr'],
 ['british', 'film', 'institut'],
 ['second', 'polish', 'republ'],
 ['geolog'],
 ['adventur', 'film'],
 ['jeddah'],
 ['amitabh', 'bachchan'],
 ['london', 'school', 'econom'],
 ['buryatia'],
 ['great', 'purg'],
 ['bandai', 'namco', 'entertain'],
 ['trojan', 'war'],
 ['kati', 'perri'],
 ['vincent', 'van', 'gogh'],
 ['disneyland', 'pari'],
 ['islam'],
 ['thor'],
 ['mersin'],
 ['clint', 'eastwood'],
 ['bulgarian', 'cup'],
 ['gauteng'],
 ['team17'],
 ['babur'],
 ['dili'],
 ['arab', 'literatur'],
 ['tradit', 'chines', 'charact'],
 ['knight'],
 ['vadodara'],
 ['javanes', 'languag'],
 ['pope'],
 ['botani'],
 ['limehous'],
 ['intern', 'secur', 'assist', 'forc'],
 ['barranquilla'],
 ['met', 'mother'],
 ['long', 'island'],
 ['infantri'],
 ['develop', 'countri'],
 ['carmarthenshir'],
 ['provinc', 'sweden'],
 ['minnesota', 'wild'],
 ['roll', 'royc', 'limit'],
 ['counti', 'fermanagh'],
 ['steve', 'ditko'],
 ['parthian', 'empir'],
 ['toyota', 'corolla'],
 ['great', 'depress'],
 ['postag', 'stamp'],
 ['napoleon', 'iii'],
 ['univers', 'leicest'],
 ['master', 'univers'],
 ['albert', 'einstein'],
 ['patriot'],
 ['intern', 'box', 'organ'],
 ['massif', 'central'],
 ['perenni', 'plant'],
 ['fredric', 'march'],
 ['malagasi', 'languag'],
 ['torah', 'read'],
 ['union', 'navi'],
 ['nascar', 'xfiniti', 'seri'],
 ['tahiti'],
 ['lahor'],
 ['galoi', 'group'],
 ['key', 'west'],
 ['john', 'b'],
 ['nagoya'],
 ['surabaya'],
 ['ecumen', 'patriarch', 'constantinopl'],
 ['guadeloup'],
 ['welsh', 'govern'],
 ['yugoslavia'],
 ['plain', 'indian'],
 ['australian', 'hip', 'hop'],
 ['peerag', 'scotland'],
 ['gambino', 'crime', 'famili'],
 ['ice', 'hockey'],
 ['australian', 'defenc', 'forc'],
 ['korean', 'state', 'railway'],
 ['monash', 'univers'],
 ['televis', 'channel'],
 ['italian', 'renaiss'],
 ['hell'],
 ['fc', 'porto'],
 ['south', 'india'],
 ['govern', 'ireland'],
 ['legisl', 'assembl', 'ontario'],
 ['region', 'southern', 'denmark'],
 ['zagreb'],
 ['coahuila'],
 ['assyrian', 'peopl'],
 ['percuss', 'instrument'],
 ['tuam'],
 ['privat', 'univers'],
 ['alicia', 'key'],
 ['fox', 'news'],
 ['arama'],
 ['quebec', 'major', 'junior', 'hockey', 'leagu'],
 ['osun', 'state'],
 ['pablo', 'picasso'],
 ['bangkok'],
 ['adriat', 'sea'],
 ['niger', 'river'],
 ['local', 'govern', 'area', 'western', 'australia'],
 ['lao'],
 ['carnat', 'music'],
 ['new', 'mexico'],
 ['bangalor'],
 ['donald', 'duck'],
 ['minist', 'state'],
 ['royal', 'colleg', 'surgeon', 'ireland'],
 ['3000', 'metr', 'steeplechas'],
 ['lenap'],
 ['david', 'weber'],
 ['tagalog', 'languag'],
 ['oklahoma', 'sooner', 'footbal'],
 ['univers', 'toronto'],
 ['pari', 'foreign', 'mission', 'societi'],
 ['directv'],
 ['hawthorn', 'footbal', 'club'],
 ['bromsgrov'],
 ['durham', 'univers'],
 ['badulla'],
 ['posix'],
 ['altai', 'krai'],
 ['hmong', 'peopl'],
 ['motown'],
 ['freestyl', 'swim'],
 ['kutaisi'],
 ['futurama'],
 ['thane'],
 ['order', 'st', 'michael', 'st', 'georg'],
 ['royal', 'colleg', 'physician', 'edinburgh'],
 ['20th', 'centuri', 'fox'],
 ['finland'],
 ['tina', 'arena'],
 ['internet', 'forum'],
 ['muromachi', 'period'],
 ['counti', 'dublin'],
 ['meath', 'gaa'],
 ['latvian', 'higher', 'leagu'],
 ['ecclesiast', 'latin'],
 ['spiritu'],
 ['akb48'],
 ['vice', 'presid', 'unit', 'state'],
 ['west', 'german', 'languag'],
 ['tauranga'],
 ['1500', 'metr'],
 ['chukchi', 'sea'],
 ['video', 'game', 'publish'],
 ['al', 'anbar', 'governor'],
 ['grozni'],
 ['bryan', 'adam'],
 ['wwe', 'network'],
 ['aub'],
 ['stephen', 'hillenburg'],
 ['gasconi'],
 ['rashtriya', 'swayamsevak', 'sangh'],
 ['abbasid', 'caliph'],
 ['bbc', 'america'],
 ['reba', 'mcentir'],
 ['singapor'],
 ['keio', 'univers'],
 ['antioquia', 'depart'],
 ['koin', 'greek'],
 ['northern', 'cypru'],
 ['travel', 'channel'],
 ['slade'],
 ['eastern', 'europ'],
 ['univers', 'nottingham'],
 ['cinema', 'philippin'],
 ['cumbernauld'],
 ['congreg', 'christian', 'brother'],
 ['montreux'],
 ['davi', 'cup'],
 ['ulyanovsk', 'oblast'],
 ['persian', 'gulf'],
 ['planetari', 'habit'],
 ['centr', 'right', 'polit'],
 ['order', 'ontario'],
 ['role', 'play', 'video', 'game'],
 ['dutch', 'golden', 'age', 'paint'],
 ['herbac', 'plant'],
 ['ba', 'rhin'],
 ['physician'],
 ['gro', 'de', 'vaud', 'district'],
 ['usb'],
 ['tom', 'jerri'],
 ['mendoza', 'provinc'],
 ['exet', 'chief'],
 ['cupressacea'],
 ['book', 'judg'],
 ['english', 'studi'],
 ['mystic'],
 ['moravian', 'silesian', 'region'],
 ['volvo'],
 ['belarusian'],
 ['philippin', 'basketbal', 'associ'],
 ['sui', 'dynasti'],
 ['dalai', 'lama'],
 ['tigri'],
 ['rigveda'],
 ['polit', 'radic'],
 ['apocalypt', 'post', 'apocalypt', 'fiction'],
 ['chines', 'folk', 'religion'],
 ['trajan'],
 ['mark', 'millar'],
 ['romeo', 'juliet'],
 ['grand', 'cayman'],
 ['witney'],
 ['palmerston', 'north'],
 ['colleg', 'board'],
 ['sam', 'raimi'],
 ['berber'],
 ['def', 'jam', 'record'],
 ['bahama'],
 ['old', 'irish'],
 ['stockholm', 'municip'],
 ['szege'],
 ['london', 'borough', 'haringey'],
 ['ahvaz'],
 ['vilniu'],
 ['nanchang'],
 ['sarawak'],
 ['mainland', 'china'],
 ['telugu', 'languag'],
 ['amazon', 'river'],
 ['san', 'francisco', 'bay'],
 ['john', 'baptist'],
 ['civil', 'polit', 'right'],
 ['gaeltacht'],
 ['palatin', 'hungari'],
 ['malacca'],
 ['sahara'],
 ['rascal', 'flatt'],
 ['eastern', 'wu'],
 ['steven', 'spielberg'],
 ['univers', 'texa', 'austin'],
 ['subroutin'],
 ['nelson', 'rockefel'],
 ['hiroshima'],
 ['w'],
 ['canterburi', 'bankstown', 'bulldog'],
 ['luhansk', 'oblast'],
 ['gracillariida'],
 ['mendip', 'hill'],
 ['derbyshir'],
 ['free', 'state', 'prussia'],
 ['olympiqu', 'de', 'marseil'],
 ['la', 'palma'],
 ['smolensk'],
 ['cuban', 'revolut'],
 ['fa', 'cup', 'final'],
 ['distinguish', 'servic', 'order'],
 ['luc', 'besson'],
 ['mid', 'north'],
 ['sarah', 'jane', 'adventur'],
 ['island', 'record'],
 ['rice', 'univers'],
 ['thirteen', 'coloni'],
 ['treat', 'william'],
 ['riversid', 'record'],
 ['greater', 'western', 'sydney'],
 ['babylon'],
 ['lleida'],
 ['depart', 'hondura'],
 ['volhynia'],
 ['guin'],
 ['new', 'york', 'harbor'],
 ['gothic', 'fiction'],
 ['world', 'hockey', 'associ'],
 ['gang'],
 ['ypre', 'salient'],
 ['episcop', 'politi'],
 ['royal', 'navi'],
 ['korn'],
 ['unit', 'state', 'dollar'],
 ['minnesota', 'twin'],
 ['prussian', 'navi'],
 ['l'],
 ['vang'],
 ['virginia', 'militari', 'institut'],
 ['northern', 'ireland', 'execut'],
 ['deccan', 'plateau'],
 ['akira', 'toriyama'],
 ['action', 'adventur', 'game'],
 ['progress', 'conserv', 'parti', 'canada'],
 ['morob', 'provinc'],
 ['queensland'],
 ['miyagi', 'prefectur'],
 ['senat', 'philippin'],
 ['federico', 'fellini'],
 ['australian', 'nation', 'univers'],
 ['rebellion'],
 ['biograph', 'film'],
 ['lublin', 'voivodeship'],
 ['loui', 'xiv', 'franc'],
 ['unit', 'state', 'declar', 'independ'],
 ['bremen'],
 ['duke', 'aquitain'],
 ['plymouth'],
 ['ian', 'mcewan'],
 ['stephen', 'king'],
 ['profession', 'dart', 'corpor'],
 ['intern', 'wrestl', 'revolut', 'group'],
 ['carnian'],
 ['tver', 'oblast'],
 ['bhutan'],
 ['ringo', 'starr'],
 ['algonquian', 'languag'],
 ['doubl', 'bass'],
 ['ellesmer', 'island'],
 ['albert', 'pyun'],
 ['faith'],
 ['new', 'york', 'metropolitan', 'area'],
 ['fc', 'dalla'],
 ['olympiqu', 'lyonnai'],
 ['edmonton'],
 ['braunschweig'],
 ['cieszyn', 'counti'],
 ['bill', 'murray'],
 ['kingdom', 'romania'],
 ['armour', 'warfar'],
 ['jagiellonian', 'univers'],
 ['swiss', 'air', 'forc'],
 ['hawick'],
 ['poitier'],
 ['polish', 'languag'],
 ['middl', 'tennesse'],
 ['jewish', 'philosophi'],
 ['greek', 'resist'],
 ['mississauga'],
 ['south', 'lo', 'angel'],
 ['river', 'state'],
 ['binghamton', 'univers'],
 ['boston', 'red', 'sox'],
 ['leed', 'rhino'],
 ['altai', 'mountain'],
 ['piedmont', 'triad'],
 ['nairobi'],
 ['east', 'dunbartonshir'],
 ['hampton', 'road'],
 ['hungarian', 'revolut', '1956'],
 ['social', 'liber'],
 ['england', 'cricket', 'team'],
 ['actinopterygii'],
 ['downtown', 'calgari'],
 ['greyhound', 'race', 'unit', 'kingdom'],
 ['puntland'],
 ['sierra', 'madr', 'occident'],
 ['parliament', 'england'],
 ['streatham'],
 ['tampa', 'bay', 'viper'],
 ['tristan', 'da', 'cunha'],
 ['charl', 'england'],
 ['presid', 'colombia'],
 ['riemannian', 'geometri'],
 ['australian', 'rule', 'footbal'],
 ['english', 'rugbi', 'union', 'system'],
 ['twickenham'],
 ['felix', 'cat'],
 ['univers', 'denver'],
 ['epiphyt'],
 ['wall', 'street', 'journal'],
 ['daraa'],
 ['lepidoptera'],
 ['lusitania'],
 ['eerst', 'divisi'],
 ['columbida'],
 ['cenozo'],
 ['hillari', 'clinton'],
 ['woodi', 'woodpeck'],
 ['oakland', 'athlet'],
 ['lake', 'district', 'nation', 'park'],
 ['dnipropetrovsk', 'oblast'],
 ['chemistri'],
 ['buffalo', 'soldier'],
 ['local', 'govern', 'republ', 'ireland'],
 ['british', 'indian', 'armi'],
 ['new', 'orlean', 'saint'],
 ['oxford', 'english', 'dictionari'],
 ['primera', 'b', 'nacion'],
 ['nfl', 'europ'],
 ['nintendo', 'switch'],
 ['oviedo'],
 ['larri', 'niven'],
 ['hallmark', 'channel'],
 ['sussex'],
 ['opu', 'number'],
 ['arabian', 'sea'],
 ['kranj'],
 ['scotland'],
 ['wexford', 'senior', 'hurl', 'championship'],
 ['piraeu'],
 ['northern', 'thailand'],
 ['toshiba'],
 ['alsac'],
 ['public', 'univers'],
 ['mahayana'],
 ['super', 'furri', 'anim'],
 ['mysor'],
 ['2015', 'pan', 'american', 'game'],
 ['indian', 'super', 'leagu'],
 ['maltes', 'peopl'],
 ['cambuslang'],
 ['voivod'],
 ['carpathian', 'ruthenia'],
 ['penang'],
 ['frank', 'capra'],
 ['brandenburg', 'prussia'],
 ['callichthyida'],
 ['kumbakonam'],
 ['ame', 'research', 'center'],
 ['bananarama'],
 ['eastern', 'shore', 'virginia'],

In [9]:
query_tokenized

[['yanni'],
 ['k', 'pop'],
 ['venice', 'film', 'festival'],
 ['downtown', 'brooklyn'],
 ['pennsylvania', 'house', 'representatives'],
 ['northern', 'premier', 'league'],
 ['first', 'national', 'pictures'],
 ['poland'],
 ['cyperaceae'],
 ['trinidad', 'tobago'],
 ['normandy', 'landings'],
 ['perry', 'index'],
 ['arm', 'architecture'],
 ['mi5'],
 ['patriarch', 'antioch'],
 ['nashik', 'district'],
 ['semiotics'],
 ['santa', 'cruz', 'de', 'tenerife'],
 ['gastropoda'],
 ['zaragoza'],
 ['south', 'carolina'],
 ['augustine', 'hippo'],
 ['canton', 'geneva'],
 ['leo', 'tolstoy'],
 ['riemannian', 'manifold'],
 ['tuzla'],
 ['subaru'],
 ['tomsk'],
 ['united', 'states', 'department', 'agriculture'],
 ['north', 'borneo'],
 ['isaac', 'asimov'],
 ['hilbert', 'space'],
 ['chechens'],
 ['arunachal', 'pradesh'],
 ['central', 'otago'],
 ['ira', 'gershwin'],
 ['rock', 'roll'],
 ['fiba'],
 ['east', 'coast', 'united', 'states'],
 ['wikipedia'],
 ['pernambuco'],
 ['west', 'coast', 'eagles'],
 ['twin', 'peaks'],
 ['dutch', 'language'],
 ['liberal', 'party', 'canada'],
 ['spratly', 'islands'],
 ['kampala'],
 ['national', 'film', 'board', 'canada'],
 ['turkish', 'war', 'independence'],
 ['chania'],
 ['oakland', 'raiders'],
 ['krishnagiri', 'district'],
 ['vr', 'group'],
 ['trade', 'name'],
 ['anglo', 'saxons'],
 ['bermuda'],
 ['paradox', 'development', 'studio'],
 ['usenet'],
 ['bbc', 'radio'],
 ['wallace', 'stevens'],
 ['spain'],
 ['franchising'],
 ['united', 'artists', 'records'],
 ['royal', 'corps', 'signals'],
 ['palawan'],
 ['seine', 'et', 'marne'],
 ['west', 'country'],
 ['bailiwick', 'guernsey'],
 ['pleuronectidae'],
 ['income', 'tax', 'united', 'states'],
 ['gp3', 'series'],
 ['septimius', 'severus'],
 ['pharaoh'],
 ['metropolitan', 'borough', 'doncaster'],
 ['history', 'jews', 'poland'],
 ['erasure'],
 ['suez', 'canal'],
 ['naval', 'air', 'station', 'lemoore'],
 ['lower', 'saxony'],
 ['robert', 'stack'],
 ['boeing'],
 ['wexford', 'gaa'],
 ['miss', 'universe'],
 ['sydney', 'central', 'business', 'district'],
 ['keweenaw', 'peninsula'],
 ['music'],
 ['nba', 'g', 'league'],
 ['makati'],
 ['genre', 'art'],
 ['aintree', 'racecourse'],
 ['colchester'],
 ['christian', 'rock'],
 ['clash'],
 ['friedrich', 'schiller'],
 ['comedy', 'drama'],
 ['tiberias'],
 ['fc', 'basel'],
 ['new', 'york', 'knicks'],
 ['perm', 'krai'],
 ['dordogne'],
 ['dutch', 'west', 'india', 'company'],
 ['titian'],
 ['victorian', 'burlesque'],
 ['tvb'],
 ['muridae'],
 ['tvxq'],
 ['kenneth', 'cope'],
 ['london', 'borough', 'islington'],
 ['top', 'cow', 'productions'],
 ['bradford', 'bulls'],
 ['mike', 'oldfield'],
 ['shooter', 'game'],
 ['hull', 'kingston', 'rovers'],
 ['national', 'science', 'foundation'],
 ['grau'],
 ['dannii', 'minogue'],
 ['christopher', 'nolan'],
 ['moscow', 'oblast'],
 ['british', 'national', 'party'],
 ['balochi', 'language'],
 ['benjamin', 'franklin'],
 ['big', 'south', 'conference'],
 ['cantabria'],
 ['alice', 'chains'],
 ['michigan'],
 ['soundgarden'],
 ['bermondsey'],
 ['2017', 'ncaa', 'division', 'fbs', 'football', 'season'],
 ['northwestern', 'united', 'states'],
 ['southeast', 'asia'],
 ['social', 'psychology'],
 ['john', 'coltrane'],
 ['roll', 'distinguished', 'philatelists'],
 ['restoration', 'movement'],
 ['danny', 'elfman'],
 ['konkani', 'language'],
 ['dungannon'],
 ['united', 'soccer', 'league'],
 ['chapters', 'verses', 'bible'],
 ['isle', 'man', 'tt'],
 ['eth', 'zurich'],
 ['emirate', 'abu', 'dhabi'],
 ['delaware', 'river'],
 ['black', 'sea'],
 ['antigua'],
 ['primary', 'school'],
 ['berber', 'languages'],
 ['loch', 'lomond'],
 ['african', 'union'],
 ['north', 'american', 'numbering', 'plan'],
 ['ural', 'mountains'],
 ['utah'],
 ['algarve', 'cup'],
 ['mixed', 'martial', 'arts'],
 ['jaxa'],
 ['plateau', 'state'],
 ['albanian', 'national', 'awakening'],
 ['unionidae'],
 ['mystery', 'fiction'],
 ['metropolitan', 'police', 'service'],
 ['bukovina'],
 ['wilbert', 'awdry'],
 ['americans'],
 ['western', 'bulldogs'],
 ['christian', 'theology'],
 ['patriarch'],
 ['skanderbeg'],
 ['korea', 'japanese', 'rule'],
 ['major', 'league', 'lacrosse'],
 ['perak'],
 ['graduate', 'school'],
 ['master', 'fine', 'arts'],
 ['little', 'league', 'world', 'series'],
 ['tugboat'],
 ['2016', 'united', 'states', 'presidential', 'election'],
 ['united', 'states', 'national', 'rugby', 'union', 'team'],
 ['1906', 'intercalated', 'games'],
 ['bocas', 'del', 'toro', 'province'],
 ['inline', 'four', 'engine'],
 ['english', 'feudal', 'barony'],
 ['royal', 'guelphic', 'order'],
 ['bodybuilding'],
 ['dusty', 'springfield'],
 ['caserta'],
 ['northrop', 'grumman'],
 ['bourbon', 'restoration'],
 ['sql'],
 ['south', 'cambridgeshire'],
 ['alappuzha'],
 ['united', 'states', 'national', 'guard'],
 ['korean', 'drama'],
 ['thiruvananthapuram'],
 ['collecting'],
 ['uzbeks'],
 ['vickers', 'limited'],
 ['luis', 'miguel'],
 ['ottoman', 'navy'],
 ['truman', 'capote'],
 ['arnold', 'schwarzenegger'],
 ['taurus', 'mountains'],
 ['easter', 'rising'],
 ['henry', 'david', 'thoreau'],
 ['george', 'jones'],
 ['bbc', 'radio', '1'],
 ['craven'],
 ['architecture'],
 ['sega'],
 ['second', 'sea', 'lord'],
 ['stena', 'line'],
 ['wingecarribee', 'shire'],
 ['fraser', 'coast', 'region'],
 ['intellivision'],
 ['gridiron', 'football'],
 ['moreton', 'bay', 'region'],
 ['ultimate', 'play', 'game'],
 ['literature'],
 ['podgorica'],
 ['lugano'],
 ['smokey', 'robinson'],
 ['major', 'league', 'soccer'],
 ['london', 'borough', 'redbridge'],
 ['roman', 'britain'],
 ['budapest'],
 ['rugby', 'football'],
 ['archbishop', 'york'],
 ['edward', 'ii', 'england'],
 ['ajmer'],
 ['yamaguchi', 'prefecture'],
 ['jaipur'],
 ['indonesian', 'cuisine'],
 ['port', 'los', 'angeles'],
 ['british', 'academy'],
 ['united', 'methodist', 'church'],
 ['independent', 'music'],
 ['chiswick'],
 ['celebrity'],
 ['ivy', 'league'],
 ['nas'],
 ['province', 'massachusetts', 'bay'],
 ['christmas', 'carol'],
 ['aix', 'en', 'provence'],
 ['black', 'hills'],
 ['willamette', 'valley'],
 ['master', 'wine'],
 ['carl', 'reiner'],
 ['podlaskie', 'voivodeship'],
 ['princess'],
 ['collins', 'crime', 'club'],
 ['romanian', 'naval', 'forces'],
 ['poxviridae'],
 ['koper'],
 ['limerick', 'gaa'],
 ['ancona'],
 ['mauritius'],
 ['clark', 'university'],
 ['ohio'],
 ['ludwigsburg'],
 ['provinces', 'chile'],
 ['right', 'wing', 'politics'],
 ['horticulture'],
 ['richard', 'nixon'],
 ['indie', 'rock'],
 ['samsung'],
 ['virginia', 'general', 'assembly'],
 ['schutzstaffel'],
 ['cloud', 'computing'],
 ['upper', 'carniola'],
 ['crown', 'colony'],
 ['metropolitan', 'borough', 'solihull'],
 ['valladolid'],
 ['william', 'goldman'],
 ['socialist', 'unity', 'party', 'germany'],
 ['irem'],
 ['turkic', 'peoples'],
 ['coldplay'],
 ['prunus'],
 ['odin'],
 ['vh1'],
 ['twelfth', 'grade'],
 ['faversham'],
 ['city', 'townsville'],
 ['trinity', 'college', 'dublin'],
 ['tasmanian', 'house', 'assembly'],
 ['kgb'],
 ['idaho'],
 ['liao', 'dynasty'],
 ['gascon', 'language'],
 ['luxembourg', 'city'],
 ['saddam', 'hussein'],
 ['ovid'],
 ['venus'],
 ['srikakulam', 'district'],
 ['vest', 'agder'],
 ['comedy'],
 ['megadeth'],
 ['sioux'],
 ['baie', 'james'],
 ['frontier', 'martial', 'arts', 'wrestling'],
 ['east', 'lothian'],
 ['indomalayan', 'realm'],
 ['albacete'],
 ['richard', 'fleischer'],
 ['cincinnati', 'reds'],
 ['vyborg'],
 ['provincial', 'assembly', 'punjab'],
 ['hamburg'],
 ['ku', 'ring', 'gai', 'council'],
 ['hanoi'],
 ['northern', 'england'],
 ['nonpartisanism'],
 ['reserve', 'bank', 'india'],
 ['tony', 'hatch'],
 ['joan', 'arc'],
 ['chinese', 'americans'],
 ['fox', 'broadcasting', 'company'],
 ['parramatta', 'eels'],
 ['duisburg'],
 ['oxford', 'university', 'press'],
 ['yukon'],
 ['tenants', 'purchase', 'scheme'],
 ['cthulhu', 'mythos'],
 ['cape', 'town'],
 ['phoenicia'],
 ['equestrianism'],
 ['taunton'],
 ['1947', 'ceylonese', 'parliamentary', 'election'],
 ['triathlon'],
 ['west', 'coast', 'main', 'line'],
 ['ghana'],
 ['manchester', 'metrolink'],
 ['darfur'],
 ['jim', 'crockett', 'promotions'],
 ['antoninus', 'pius'],
 ['isle', 'dogs'],
 ['smith'],
 ['dewan', 'rakyat'],
 ['jennifer', 'rowe'],
 ['kaduna', 'state'],
 ['dahomey'],
 ['nakskov'],
 ['ciutat', 'vella'],
 ['ohio', 'river'],
 ['civil', 'engineering'],
 ['kaluga', 'oblast'],
 ['london', 'borough', 'croydon'],
 ['guillermo', 'del', 'toro'],
 ['germany'],
 ['french', 'polynesia'],
 ['chvrches'],
 ['mark', 'twain'],
 ['shaheed', 'bhagat', 'singh', 'nagar', 'district'],
 ['cyclades'],
 ['strabo'],
 ['milton', 'bradley', 'company'],
 ['occitan', 'language'],
 ['yenisei', 'river'],
 ['bangladesh'],
 ['lake', 'tahoe'],
 ['brandenburg'],
 ['jacob'],
 ['france', 'national', 'football', 'team'],
 ['veikkausliiga'],
 ['2015', 'canadian', 'federal', 'election'],
 ['kurdistan', 'region'],
 ['snk'],
 ['bbc', 'television'],
 ['united', 'states', 'department', 'defense'],
 ['prince', 'elector'],
 ['new', 'england'],
 ['rca'],
 ['qinghai'],
 ['chilean', 'war', 'independence'],
 ['daft', 'punk'],
 ['ghana', 'national', 'football', 'team'],
 ['chinese', 'buddhism'],
 ['florence'],
 ['samara', 'oblast'],
 ['yekaterinburg'],
 ['connecticut', 'river'],
 ['indonesia'],
 ['vancouver'],
 ['miami', 'marlins'],
 ['joseph', 'stalin'],
 ['travel', 'literature'],
 ['christian', 'democratic', 'appeal'],
 ['detroit', 'pistons'],
 ['taranto'],
 ['port', 'washington', 'branch'],
 ['yellowknife'],
 ['sahrawi', 'arab', 'democratic', 'republic'],
 ['derry', 'gaa'],
 ['unionism', 'ireland'],
 ['soviet', 'armed', 'forces'],
 ['los', 'angeles'],
 ['thomas', 'jefferson'],
 ['hal', 'roach'],
 ['cardiff', 'rfc'],
 ['government', 'kerala'],
 ['regent'],
 ['british', 'people'],
 ['americans'],
 ['bell', 'system'],
 ['sabrina', 'carpenter'],
 ['danielle', 'steel'],
 ['lincolnshire'],
 ['printmaking'],
 ['vicenza'],
 ['eric', 'clapton'],
 ['dj', 'khaled'],
 ['county', 'donegal'],
 ['lockheed', 'corporation'],
 ['southern', 'rock'],
 ['george', 'gershwin'],
 ['salvation', 'army'],
 ['bell', 'labs'],
 ['list', 'north', 'carolina', 'state', 'parks'],
 ['falklands', 'war'],
 ['gustav', 'mahler'],
 ['monster', 'movie'],
 ['cheap', 'trick'],
 ['chinese', 'taipei'],
 ['liechtenstein'],
 ['daily', 'mail'],
 ['solan', 'district'],
 ['goths'],
 ['british', 'empire'],
 ['scholastic', 'corporation'],
 ['ten', 'pin', 'bowling'],
 ['city', 'university', 'new', 'york'],
 ['vinnytsia', 'oblast'],
 ['centre', 'national', 'de', 'la', 'recherche', 'scientifique'],
 ['opeth'],
 ['neuwied'],
 ['tampere'],
 ['international', 'brigades'],
 ['north', 'london'],
 ['serbian', 'cyrillic', 'alphabet'],
 ['northeastern', 'ontario'],
 ['hackensack', 'river'],
 ['old', 'world', 'warbler'],
 ['danish', 'superliga'],
 ['niue'],
 ['puducherry'],
 ['namibia'],
 ['royal', 'rumble'],
 ['atlantic', 'league', 'professional', 'baseball'],
 ['bornholm'],
 ['alappuzha', 'district'],
 ['spongebob', 'squarepants'],
 ['royal', 'caribbean', 'international'],
 ['kim', 'jong', 'il'],
 ['keanu', 'reeves'],
 ['argentina', 'national', 'football', 'team'],
 ['lloyd', 'bacon'],
 ['annette', 'andre'],
 ['british', 'film', 'institute'],
 ['second', 'polish', 'republic'],
 ['geology'],
 ['adventure', 'film'],
 ['jeddah'],
 ['amitabh', 'bachchan'],
 ['london', 'school', 'economics'],
 ['buryatia'],
 ['great', 'purge'],
 ['bandai', 'namco', 'entertainment'],
 ['trojan', 'war'],
 ['katy', 'perry'],
 ['vincent', 'van', 'gogh'],
 ['disneyland', 'paris'],
 ['islamism'],
 ['thor'],
 ['mersin'],
 ['clint', 'eastwood'],
 ['bulgarian', 'cup'],
 ['gauteng'],
 ['team17'],
 ['babur'],
 ['dili'],
 ['arabic', 'literature'],
 ['traditional', 'chinese', 'characters'],
 ['knight'],
 ['vadodara'],
 ['javanese', 'language'],
 ['pope'],
 ['botany'],
 ['limehouse'],
 ['international', 'security', 'assistance', 'force'],
 ['barranquilla'],
 ['met', 'mother'],
 ['long', 'island'],
 ['infantry'],
 ['developing', 'country'],
 ['carmarthenshire'],
 ['provinces', 'sweden'],
 ['minnesota', 'wild'],
 ['rolls', 'royce', 'limited'],
 ['county', 'fermanagh'],
 ['steve', 'ditko'],
 ['parthian', 'empire'],
 ['toyota', 'corolla'],
 ['great', 'depression'],
 ['postage', 'stamp'],
 ['napoleon', 'iii'],
 ['university', 'leicester'],
 ['masters', 'universe'],
 ['albert', 'einstein'],
 ['patriotism'],
 ['international', 'boxing', 'organization'],
 ['massif', 'central'],
 ['perennial', 'plant'],
 ['fredric', 'march'],
 ['malagasy', 'language'],
 ['torah', 'reading'],
 ['union', 'navy'],
 ['nascar', 'xfinity', 'series'],
 ['tahiti'],
 ['lahore'],
 ['galois', 'group'],
 ['key', 'west'],
 ['john', 'b'],
 ['nagoya'],
 ['surabaya'],
 ['ecumenical', 'patriarch', 'constantinople'],
 ['guadeloupe'],
 ['welsh', 'government'],
 ['yugoslavia'],
 ['plains', 'indians'],
 ['australian', 'hip', 'hop'],
 ['peerage', 'scotland'],
 ['gambino', 'crime', 'family'],
 ['ice', 'hockey'],
 ['australian', 'defence', 'force'],
 ['korean', 'state', 'railway'],
 ['monash', 'university'],
 ['television', 'channel'],
 ['italian', 'renaissance'],
 ['hell'],
 ['fc', 'porto'],
 ['south', 'india'],
 ['government', 'ireland'],
 ['legislative', 'assembly', 'ontario'],
 ['region', 'southern', 'denmark'],
 ['zagreb'],
 ['coahuila'],
 ['assyrian', 'people'],
 ['percussion', 'instrument'],
 ['tuam'],
 ['private', 'university'],
 ['alicia', 'keys'],
 ['fox', 'news'],
 ['aramaic'],
 ['quebec', 'major', 'junior', 'hockey', 'league'],
 ['osun', 'state'],
 ['pablo', 'picasso'],
 ['bangkok'],
 ['adriatic', 'sea'],
 ['niger', 'river'],
 ['local', 'government', 'areas', 'western', 'australia'],
 ['laos'],
 ['carnatic', 'music'],
 ['new', 'mexico'],
 ['bangalore'],
 ['donald', 'duck'],
 ['minister', 'state'],
 ['royal', 'college', 'surgeons', 'ireland'],
 ['3000', 'metres', 'steeplechase'],
 ['lenape'],
 ['david', 'weber'],
 ['tagalog', 'language'],
 ['oklahoma', 'sooners', 'football'],
 ['university', 'toronto'],
 ['paris', 'foreign', 'missions', 'society'],
 ['directv'],
 ['hawthorn', 'football', 'club'],
 ['bromsgrove'],
 ['durham', 'university'],
 ['badulla'],
 ['posix'],
 ['altai', 'krai'],
 ['hmong', 'people'],
 ['motown'],
 ['freestyle', 'swimming'],
 ['kutaisi'],
 ['futurama'],
 ['thane'],
 ['order', 'st', 'michael', 'st', 'george'],
 ['royal', 'college', 'physicians', 'edinburgh'],
 ['20th', 'century', 'fox'],
 ['finland'],
 ['tina', 'arena'],
 ['internet', 'forum'],
 ['muromachi', 'period'],
 ['county', 'dublin'],
 ['meath', 'gaa'],
 ['latvian', 'higher', 'league'],
 ['ecclesiastical', 'latin'],
 ['spiritualism'],
 ['akb48'],
 ['vice', 'president', 'united', 'states'],
 ['west', 'germanic', 'languages'],
 ['tauranga'],
 ['1500', 'metres'],
 ['chukchi', 'sea'],
 ['video', 'game', 'publisher'],
 ['al', 'anbar', 'governorate'],
 ['grozny'],
 ['bryan', 'adams'],
 ['wwe', 'network'],
 ['aube'],
 ['stephen', 'hillenburg'],
 ['gascony'],
 ['rashtriya', 'swayamsevak', 'sangh'],
 ['abbasid', 'caliphate'],
 ['bbc', 'america'],
 ['reba', 'mcentire'],
 ['singapore'],
 ['keio', 'university'],
 ['antioquia', 'department'],
 ['koine', 'greek'],
 ['northern', 'cyprus'],
 ['travel', 'channel'],
 ['slade'],
 ['eastern', 'europe'],
 ['university', 'nottingham'],
 ['cinema', 'philippines'],
 ['cumbernauld'],
 ['congregation', 'christian', 'brothers'],
 ['montreux'],
 ['davis', 'cup'],
 ['ulyanovsk', 'oblast'],
 ['persian', 'gulf'],
 ['planetary', 'habitability'],
 ['centre', 'right', 'politics'],
 ['order', 'ontario'],
 ['role', 'playing', 'video', 'game'],
 ['dutch', 'golden', 'age', 'painting'],
 ['herbaceous', 'plant'],
 ['bas', 'rhin'],
 ['physician'],
 ['gros', 'de', 'vaud', 'district'],
 ['usb'],
 ['tom', 'jerry'],
 ['mendoza', 'province'],
 ['exeter', 'chiefs'],
 ['cupressaceae'],
 ['book', 'judges'],
 ['english', 'studies'],
 ['mysticism'],
 ['moravian', 'silesian', 'region'],
 ['volvo'],
 ['belarusians'],
 ['philippine', 'basketball', 'association'],
 ['sui', 'dynasty'],
 ['dalai', 'lama'],
 ['tigris'],
 ['rigveda'],
 ['political', 'radicalism'],
 ['apocalyptic', 'post', 'apocalyptic', 'fiction'],
 ['chinese', 'folk', 'religion'],
 ['trajan'],
 ['mark', 'millar'],
 ['romeo', 'juliet'],
 ['grand', 'cayman'],
 ['witney'],
 ['palmerston', 'north'],
 ['college', 'board'],
 ['sam', 'raimi'],
 ['berbers'],
 ['def', 'jam', 'recordings'],
 ['bahamas'],
 ['old', 'irish'],
 ['stockholm', 'municipality'],
 ['szeged'],
 ['london', 'borough', 'haringey'],
 ['ahvaz'],
 ['vilnius'],
 ['nanchang'],
 ['sarawak'],
 ['mainland', 'china'],
 ['telugu', 'language'],
 ['amazon', 'river'],
 ['san', 'francisco', 'bay'],
 ['john', 'baptist'],
 ['civil', 'political', 'rights'],
 ['gaeltacht'],
 ['palatine', 'hungary'],
 ['malacca'],
 ['sahara'],
 ['rascal', 'flatts'],
 ['eastern', 'wu'],
 ['steven', 'spielberg'],
 ['university', 'texas', 'austin'],
 ['subroutine'],
 ['nelson', 'rockefeller'],
 ['hiroshima'],
 ['w'],
 ['canterbury', 'bankstown', 'bulldogs'],
 ['luhansk', 'oblast'],
 ['gracillariidae'],
 ['mendip', 'hills'],
 ['derbyshire'],
 ['free', 'state', 'prussia'],
 ['olympique', 'de', 'marseille'],
 ['la', 'palma'],
 ['smolensk'],
 ['cuban', 'revolution'],
 ['fa', 'cup', 'final'],
 ['distinguished', 'service', 'order'],
 ['luc', 'besson'],
 ['mid', 'north'],
 ['sarah', 'jane', 'adventures'],
 ['island', 'records'],
 ['rice', 'university'],
 ['thirteen', 'colonies'],
 ['treat', 'williams'],
 ['riverside', 'records'],
 ['greater', 'western', 'sydney'],
 ['babylon'],
 ['lleida'],
 ['departments', 'honduras'],
 ['volhynia'],
 ['guinness'],
 ['new', 'york', 'harbor'],
 ['gothic', 'fiction'],
 ['world', 'hockey', 'association'],
 ['ganges'],
 ['ypres', 'salient'],
 ['episcopal', 'polity'],
 ['royal', 'navy'],
 ['korn'],
 ['united', 'states', 'dollar'],
 ['minnesota', 'twins'],
 ['prussian', 'navy'],
 ['l'],
 ['vangelis'],
 ['virginia', 'military', 'institute'],
 ['northern', 'ireland', 'executive'],
 ['deccan', 'plateau'],
 ['akira', 'toriyama'],
 ['action', 'adventure', 'game'],
 ['progressive', 'conservative', 'party', 'canada'],
 ['morobe', 'province'],
 ['queensland'],
 ['miyagi', 'prefecture'],
 ['senate', 'philippines'],
 ['federico', 'fellini'],
 ['australian', 'national', 'university'],
 ['rebellion'],
 ['biographical', 'film'],
 ['lublin', 'voivodeship'],
 ['louis', 'xiv', 'france'],
 ['united', 'states', 'declaration', 'independence'],
 ['bremen'],
 ['duke', 'aquitaine'],
 ['plymouth'],
 ['ian', 'mcewan'],
 ['stephen', 'king'],
 ['professional', 'darts', 'corporation'],
 ['international', 'wrestling', 'revolution', 'group'],
 ['carnian'],
 ['tver', 'oblast'],
 ['bhutan'],
 ['ringo', 'starr'],
 ['algonquian', 'languages'],
 ['double', 'bass'],
 ['ellesmere', 'island'],
 ['albert', 'pyun'],
 ['faith'],
 ['new', 'york', 'metropolitan', 'area'],
 ['fc', 'dallas'],
 ['olympique', 'lyonnais'],
 ['edmonton'],
 ['braunschweig'],
 ['cieszyn', 'county'],
 ['bill', 'murray'],
 ['kingdom', 'romania'],
 ['armoured', 'warfare'],
 ['jagiellonian', 'university'],
 ['swiss', 'air', 'force'],
 ['hawick'],
 ['poitiers'],
 ['polish', 'language'],
 ['middle', 'tennessee'],
 ['jewish', 'philosophy'],
 ['greek', 'resistance'],
 ['mississauga'],
 ['south', 'los', 'angeles'],
 ['rivers', 'state'],
 ['binghamton', 'university'],
 ['boston', 'red', 'sox'],
 ['leeds', 'rhinos'],
 ['altai', 'mountains'],
 ['piedmont', 'triad'],
 ['nairobi'],
 ['east', 'dunbartonshire'],
 ['hampton', 'roads'],
 ['hungarian', 'revolution', '1956'],
 ['social', 'liberalism'],
 ['england', 'cricket', 'team'],
 ['actinopterygii'],
 ['downtown', 'calgary'],
 ['greyhound', 'racing', 'united', 'kingdom'],
 ['puntland'],
 ['sierra', 'madre', 'occidental'],
 ['parliament', 'england'],
 ['streatham'],
 ['tampa', 'bay', 'vipers'],
 ['tristan', 'da', 'cunha'],
 ['charles', 'england'],
 ['president', 'colombia'],
 ['riemannian', 'geometry'],
 ['australian', 'rules', 'football'],
 ['english', 'rugby', 'union', 'system'],
 ['twickenham'],
 ['felix', 'cat'],
 ['university', 'denver'],
 ['epiphyte'],
 ['wall', 'street', 'journal'],
 ['daraa'],
 ['lepidoptera'],
 ['lusitania'],
 ['eerste', 'divisie'],
 ['columbidae'],
 ['cenozoic'],
 ['hillary', 'clinton'],
 ['woody', 'woodpecker'],

In [25]:
len(stemmed_queries)

1444

In [10]:
scores_of_all_queries_queries_stemmed = []

for query in stemmed_queries:
    scores_of_all_queries_queries_stemmed.append(bm25.get_scores(query))

In [11]:
scores_of_all_queries_queries_stemmed

[array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 2.32798045, 0.        , ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([ 0.        ,  0.        , 10.41618338, ...,  0.        ,
         0.        ,  0.        ], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.43415237, 1.6423582 ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([2.51402525, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        2.73308386], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([1.61291043, 0.        , 1.56086029, ..., 0.        , 1.19988749,
        1.19537474], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 2.12023869,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([1.61291043, 0.        , 1.56086029, ..., 0.        , 1.19988749,
        1.19537474], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        2.91551711], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.       , 0.       , 0.       , ..., 0.       , 1.6423582,
        0.       ], shape=(369721,)),
 array([2.03508896, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        2.73308386], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 1.39256034, 0.        , ..., 0.        , 1.28741727,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([2.05079993, 0.        , 0.        , ..., 2.05842688, 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([1.61291043, 0.        , 1.56086029, ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0.       , 3.3014372, 0.       , ..., 0.       , 0.       ,
        0.       ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([1.61291043, 0.        , 1.56086029, ..., 0.        , 1.19988749,
        1.19537474], shape=(369721,)),
 array([2.39762671, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([2.85035895, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 1.78020325, 0.        , ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        2.73308386], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 5.46520413, ..., 3.27593654, 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 2.78735079, 0.        , ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 4.56399193, ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0.        , 0.        , 1.08655115, ..., 0.        , 1.14397799,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        3.44702094], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.       , 3.1025827, 0.       , ..., 0.       , 0.       ,
        0.       ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 3.03528247, 1.6423582 ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 1.6423582 ,
        2.91551711], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.       , 0.       , 6.1557733, ..., 0.       , 0.       ,
        0.       ], shape=(369721,)),
 array([1.61291043, 0.        , 1.56086029, ..., 0.        , 1.19988749,
        1.19537474], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        4.62938576], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([1.61291043, 0.        , 7.02606442, ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 4.60850021,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.57384952], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 2.12023869,
        0.        ], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 3.55376568,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 7.16163518, ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0.        , 2.78735079, 0.        , ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 1.19988749,
        1.19537474], shape=(369721,)),
 array([0.       , 0.       , 0.       , ..., 0.       , 1.6423582,
        0.       ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 4.54136553, 0.        , ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 5.46520413, ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.57384952], shape=(369721,)),
 array([0.        , 2.78735079, 0.        , ..., 0.        , 0.        ,
        3.21917206], shape=(369721,)),
 array([4.09945756, 0.        , 5.46520413, ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([1.61291043, 0.        , 5.65004555, ..., 0.        , 1.19988749,
        3.86377857], shape=(369721,)),
 array([1.61291043, 0.        , 1.56086029, ..., 0.        , 2.84224568,
        1.19537474], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([13.78920972,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([2.57894339, 3.3014372 , 0.        , ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([1.61291043, 0.        , 1.56086029, ..., 0.        , 2.84224568,
        1.19537474], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 3.55376568,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 3.14097146,
        0.        ], shape=(369721,)),
 array([2.36099377, 0.        , 1.58535433, ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 1.71050232, ..., 1.7741161 , 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 5.46520413, ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0.       , 3.1025827, 0.       , ..., 0.       , 0.       ,
        0.       ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([2.78831958, 0.        , 0.        , ..., 2.79868937, 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([1.61291043, 0.        , 1.56086029, ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 5.46520413, ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 4.87515227,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        3.21917206], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 4.0511628 , 2.53868873, ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 1.78020325, 0.        , ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 1.9145944 , 0.        ,
        5.42355772], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        2.91551711], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 1.78321164,
        1.77650503], shape=(369721,)),
 array([0.        , 2.39484835, 0.        , ..., 0.        , 0.        ,
        2.20570219], shape=(369721,)),
 array([0.        , 2.32798045, 0.        , ..., 0.        , 0.        ,
        5.42355772], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 1.78321164,

In [12]:
len(scores_of_all_queries_queries_stemmed)

1444

In [14]:
import pandas as pd
query_ids = [query.query_id for query in dataset.queries_iter()]
df_new = pd.DataFrame(query_ids, columns=["Query_ID"])
df_new

     Query_ID
0      123839
1      188629
2       13898
3      316959
4      515031
...       ...
1439   896124
1440    12319
1441     4421
1442   296526
1443   341793

[1444 rows x 1 columns]

In [15]:
from helper import create_AP, create_ndcg, create_statistical_columns
df_new = create_statistical_columns(df_new, qrels_dict, doc_dict, scores_of_all_queries_queries_stemmed)
df_new = create_AP(df_new, qrels_dict, doc_dict, scores_of_all_queries_queries_stemmed)
df_new = create_ndcg(df_new, doc_dict, scores_of_all_queries_queries_stemmed, score_doc_dict)

In [16]:
df_new

,Query_ID,recall_5,recall_10,precision_5,precision_10,f_score_5,f_score_10,AP_5,AP_10,NDCG_5,NDCG_10
0,123839,50.000000,100.000000,60.0,60.0,54.545455,75.000000,0.458333,0.768849,0.883923,0.852981
1,188629,33.333333,33.333333,40.0,20.0,36.363636,25.000000,0.333333,0.333333,0.889669,0.918338
2,13898,33.333333,33.333333,40.0,20.0,36.363636,25.000000,0.333333,0.333333,0.000000,0.000000
3,316959,11.111111,22.222222,20.0,20.0,14.285714,21.052632,0.111111,0.148148,1.000000,0.998975
4,515031,0.000000,14.285714,0.0,20.0,0.000000,16.666667,0.000000,0.027778,0.551929,0.471942
...,...,...,...,...,...,...,...,...,...,...,...
1439,896124,12.500000,12.500000,20.0,10.0,15.384615,11.111111,0.125000,0.125000,0.464253,0.502333
1440,12319,4.545455,4.545455,20.0,10.0,7.407407,6.250000,0.045455,0.045455,0.197103,0.200593
1441,4421,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.495470,0.468331
1442,296526,10.000000,10.000000,20.0,10.0,13.333333,10.000000,0.050000,0.050000,0.535444,0.561980
1443,341793,14.285714,14.285714,20.0,10.0,16.666667,11.764706,0.142857,0.142857,0.211423,0.174632

In [18]:
mydict = {
    "Method": "BM25 - Porter's Stemmer Queries Stemmed",
    "recall_5_mean": df_new["recall_5"].mean(),
    "recall_5_std": df_new["recall_5"].std(),
    "recall_5_max": df_new["recall_5"].max(),
    "recall_5_min": df_new["recall_5"].min(),
    "recall_10_mean": df_new["recall_10"].mean(),
    "recall_10_std": df_new["recall_10"].std(),
    "recall_10_max": df_new["recall_10"].max(),
    "recall_10_min": df_new["recall_10"].min(),
    "precision_5_mean": df_new["precision_5"].mean(),
    "precision_5_std": df_new["precision_5"].std(),
    "precision_5_max": df_new["precision_5"].max(),
    "precision_5_min": df_new["precision_5"].min(),
    "precision_10_mean": df_new["precision_10"].mean(),
    "precision_10_std": df_new["precision_10"].std(),
    "precision_10_max": df_new["precision_10"].max(),
    "precision_10_min": df_new["precision_10"].min(),
    "f_score_5_mean": df_new["f_score_5"].mean(),
    "f_score_5_std": df_new["f_score_5"].std(),
    "f_score_5_max": df_new["f_score_5"].max(),
    "f_score_5_min": df_new["f_score_5"].min(),
    "f_score_10_mean": df_new["f_score_10"].mean(),
    "f_score_10_std": df_new["f_score_10"].std(),
    "f_score_10_max": df_new["f_score_10"].max(),
    "f_score_10_min": df_new["f_score_10"].min(),
    "MAP_5": df_new["AP_5"].mean(),
    "MAP_10": df_new["AP_10"].mean(),
    "NDCG_5_mean": df_new["NDCG_5"].mean(),
    "NDCG_5_std": df_new["NDCG_5"].std(),
    "NDCG_5_max": df_new["NDCG_5"].max(),
    "NDCG_5_min": df_new["NDCG_5"].min(),
    "NDCG_10_mean": df_new["NDCG_10"].mean(),
    "NDCG_10_std": df_new["NDCG_10"].std(),
    "NDCG_10_max": df_new["NDCG_10"].max(),
    "NDCG_10_min": df_new["NDCG_10"].min()
}

In [19]:
df_parquet = pd.DataFrame(mydict, index=[0])
df_parquet

,Method,recall_5_mean,recall_5_std,recall_5_max,recall_5_min,recall_10_mean,recall_10_std,recall_10_max,recall_10_min,precision_5_mean,...,MAP_5,MAP_10,NDCG_5_mean,NDCG_5_std,NDCG_5_max,NDCG_5_min,NDCG_10_mean,NDCG_10_std,NDCG_10_max,NDCG_10_min
0,BM25 - Porter's Stemmer Queries Stemmed,14.478316,14.481887,83.333333,0.0,20.702477,19.543478,100.0,0.0,29.66759,...,0.114719,0.14149,0.50807,0.349112,1.0,0.0,0.50813,0.345892,1.0,0.0

In [20]:
df_parquet.to_parquet("BM25PorterStemmerQueriesStemmed.parquet")
print("Parquet!")

Parquet!