In [1]:
import ir_datasets
from nltk.stem import WordNetLemmatizer
import nltk
from helper import create_tokenized_word_list

dataset = ir_datasets.load("wikir/en1k/training")
tokenized = create_tokenized_word_list(dataset)

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/tahas44/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [2]:
nltk.download("punkt_tab")
nltk.download("wordnet")

[nltk_data] Downloading package punkt_tab to
[nltk_data]     /home/tahas44/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package wordnet to /home/tahas44/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [3]:
lemmatized_tokenized_docs = []
lematizer = WordNetLemmatizer()

for query_list in tokenized:
    lemmatized_words = [lematizer.lemmatize(word) for word in query_list]
    lemmatized_tokenized_docs.append(lemmatized_words)

print("Docs lemmatized")

Docs lemmatized

In [4]:
from helper import create_tokenized_word_list_for_query
query_tokenized = create_tokenized_word_list_for_query(dataset)
print("Queries tokenized!")

Queries tokenized!

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/tahas44/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [5]:
lemmatized_tokenized_queries = []

for query_list in query_tokenized:
    lemmatized_words = [lematizer.lemmatize(words) for words in query_list]
    lemmatized_tokenized_queries.append(lemmatized_words)

print("Queries lemmatized")

Queries lemmatized

In [6]:
lemmatized_tokenized_queries

[['yanni'],
 ['k', 'pop'],
 ['venice', 'film', 'festival'],
 ['downtown', 'brooklyn'],
 ['pennsylvania', 'house', 'representative'],
 ['northern', 'premier', 'league'],
 ['first', 'national', 'picture'],
 ['poland'],
 ['cyperaceae'],
 ['trinidad', 'tobago'],
 ['normandy', 'landing'],
 ['perry', 'index'],
 ['arm', 'architecture'],
 ['mi5'],
 ['patriarch', 'antioch'],
 ['nashik', 'district'],
 ['semiotics'],
 ['santa', 'cruz', 'de', 'tenerife'],
 ['gastropoda'],
 ['zaragoza'],
 ['south', 'carolina'],
 ['augustine', 'hippo'],
 ['canton', 'geneva'],
 ['leo', 'tolstoy'],
 ['riemannian', 'manifold'],
 ['tuzla'],
 ['subaru'],
 ['tomsk'],
 ['united', 'state', 'department', 'agriculture'],
 ['north', 'borneo'],
 ['isaac', 'asimov'],
 ['hilbert', 'space'],
 ['chechen'],
 ['arunachal', 'pradesh'],
 ['central', 'otago'],
 ['ira', 'gershwin'],
 ['rock', 'roll'],
 ['fiba'],
 ['east', 'coast', 'united', 'state'],
 ['wikipedia'],
 ['pernambuco'],
 ['west', 'coast', 'eagle'],
 ['twin', 'peak'],
 ['dutch', 'language'],
 ['liberal', 'party', 'canada'],
 ['spratly', 'island'],
 ['kampala'],
 ['national', 'film', 'board', 'canada'],
 ['turkish', 'war', 'independence'],
 ['chania'],
 ['oakland', 'raider'],
 ['krishnagiri', 'district'],
 ['vr', 'group'],
 ['trade', 'name'],
 ['anglo', 'saxon'],
 ['bermuda'],
 ['paradox', 'development', 'studio'],
 ['usenet'],
 ['bbc', 'radio'],
 ['wallace', 'stevens'],
 ['spain'],
 ['franchising'],
 ['united', 'artist', 'record'],
 ['royal', 'corp', 'signal'],
 ['palawan'],
 ['seine', 'et', 'marne'],
 ['west', 'country'],
 ['bailiwick', 'guernsey'],
 ['pleuronectidae'],
 ['income', 'tax', 'united', 'state'],
 ['gp3', 'series'],
 ['septimius', 'severus'],
 ['pharaoh'],
 ['metropolitan', 'borough', 'doncaster'],
 ['history', 'jew', 'poland'],
 ['erasure'],
 ['suez', 'canal'],
 ['naval', 'air', 'station', 'lemoore'],
 ['lower', 'saxony'],
 ['robert', 'stack'],
 ['boeing'],
 ['wexford', 'gaa'],
 ['miss', 'universe'],
 ['sydney', 'central', 'business', 'district'],
 ['keweenaw', 'peninsula'],
 ['music'],
 ['nba', 'g', 'league'],
 ['makati'],
 ['genre', 'art'],
 ['aintree', 'racecourse'],
 ['colchester'],
 ['christian', 'rock'],
 ['clash'],
 ['friedrich', 'schiller'],
 ['comedy', 'drama'],
 ['tiberias'],
 ['fc', 'basel'],
 ['new', 'york', 'knicks'],
 ['perm', 'krai'],
 ['dordogne'],
 ['dutch', 'west', 'india', 'company'],
 ['titian'],
 ['victorian', 'burlesque'],
 ['tvb'],
 ['muridae'],
 ['tvxq'],
 ['kenneth', 'cope'],
 ['london', 'borough', 'islington'],
 ['top', 'cow', 'production'],
 ['bradford', 'bull'],
 ['mike', 'oldfield'],
 ['shooter', 'game'],
 ['hull', 'kingston', 'rover'],
 ['national', 'science', 'foundation'],
 ['grau'],
 ['dannii', 'minogue'],
 ['christopher', 'nolan'],
 ['moscow', 'oblast'],
 ['british', 'national', 'party'],
 ['balochi', 'language'],
 ['benjamin', 'franklin'],
 ['big', 'south', 'conference'],
 ['cantabria'],
 ['alice', 'chain'],
 ['michigan'],
 ['soundgarden'],
 ['bermondsey'],
 ['2017', 'ncaa', 'division', 'fbs', 'football', 'season'],
 ['northwestern', 'united', 'state'],
 ['southeast', 'asia'],
 ['social', 'psychology'],
 ['john', 'coltrane'],
 ['roll', 'distinguished', 'philatelist'],
 ['restoration', 'movement'],
 ['danny', 'elfman'],
 ['konkani', 'language'],
 ['dungannon'],
 ['united', 'soccer', 'league'],
 ['chapter', 'verse', 'bible'],
 ['isle', 'man', 'tt'],
 ['eth', 'zurich'],
 ['emirate', 'abu', 'dhabi'],
 ['delaware', 'river'],
 ['black', 'sea'],
 ['antigua'],
 ['primary', 'school'],
 ['berber', 'language'],
 ['loch', 'lomond'],
 ['african', 'union'],
 ['north', 'american', 'numbering', 'plan'],
 ['ural', 'mountain'],
 ['utah'],
 ['algarve', 'cup'],
 ['mixed', 'martial', 'art'],
 ['jaxa'],
 ['plateau', 'state'],
 ['albanian', 'national', 'awakening'],
 ['unionidae'],
 ['mystery', 'fiction'],
 ['metropolitan', 'police', 'service'],
 ['bukovina'],
 ['wilbert', 'awdry'],
 ['american'],
 ['western', 'bulldog'],
 ['christian', 'theology'],
 ['patriarch'],
 ['skanderbeg'],
 ['korea', 'japanese', 'rule'],
 ['major', 'league', 'lacrosse'],
 ['perak'],
 ['graduate', 'school'],
 ['master', 'fine', 'art'],
 ['little', 'league', 'world', 'series'],
 ['tugboat'],
 ['2016', 'united', 'state', 'presidential', 'election'],
 ['united', 'state', 'national', 'rugby', 'union', 'team'],
 ['1906', 'intercalated', 'game'],
 ['bocas', 'del', 'toro', 'province'],
 ['inline', 'four', 'engine'],
 ['english', 'feudal', 'barony'],
 ['royal', 'guelphic', 'order'],
 ['bodybuilding'],
 ['dusty', 'springfield'],
 ['caserta'],
 ['northrop', 'grumman'],
 ['bourbon', 'restoration'],
 ['sql'],
 ['south', 'cambridgeshire'],
 ['alappuzha'],
 ['united', 'state', 'national', 'guard'],
 ['korean', 'drama'],
 ['thiruvananthapuram'],
 ['collecting'],
 ['uzbek'],
 ['vickers', 'limited'],
 ['luis', 'miguel'],
 ['ottoman', 'navy'],
 ['truman', 'capote'],
 ['arnold', 'schwarzenegger'],
 ['taurus', 'mountain'],
 ['easter', 'rising'],
 ['henry', 'david', 'thoreau'],
 ['george', 'jones'],
 ['bbc', 'radio', '1'],
 ['craven'],
 ['architecture'],
 ['sega'],
 ['second', 'sea', 'lord'],
 ['stena', 'line'],
 ['wingecarribee', 'shire'],
 ['fraser', 'coast', 'region'],
 ['intellivision'],
 ['gridiron', 'football'],
 ['moreton', 'bay', 'region'],
 ['ultimate', 'play', 'game'],
 ['literature'],
 ['podgorica'],
 ['lugano'],
 ['smokey', 'robinson'],
 ['major', 'league', 'soccer'],
 ['london', 'borough', 'redbridge'],
 ['roman', 'britain'],
 ['budapest'],
 ['rugby', 'football'],
 ['archbishop', 'york'],
 ['edward', 'ii', 'england'],
 ['ajmer'],
 ['yamaguchi', 'prefecture'],
 ['jaipur'],
 ['indonesian', 'cuisine'],
 ['port', 'los', 'angeles'],
 ['british', 'academy'],
 ['united', 'methodist', 'church'],
 ['independent', 'music'],
 ['chiswick'],
 ['celebrity'],
 ['ivy', 'league'],
 ['na'],
 ['province', 'massachusetts', 'bay'],
 ['christmas', 'carol'],
 ['aix', 'en', 'provence'],
 ['black', 'hill'],
 ['willamette', 'valley'],
 ['master', 'wine'],
 ['carl', 'reiner'],
 ['podlaskie', 'voivodeship'],
 ['princess'],
 ['collins', 'crime', 'club'],
 ['romanian', 'naval', 'force'],
 ['poxviridae'],
 ['koper'],
 ['limerick', 'gaa'],
 ['ancona'],
 ['mauritius'],
 ['clark', 'university'],
 ['ohio'],
 ['ludwigsburg'],
 ['province', 'chile'],
 ['right', 'wing', 'politics'],
 ['horticulture'],
 ['richard', 'nixon'],
 ['indie', 'rock'],
 ['samsung'],
 ['virginia', 'general', 'assembly'],
 ['schutzstaffel'],
 ['cloud', 'computing'],
 ['upper', 'carniola'],
 ['crown', 'colony'],
 ['metropolitan', 'borough', 'solihull'],
 ['valladolid'],
 ['william', 'goldman'],
 ['socialist', 'unity', 'party', 'germany'],
 ['irem'],
 ['turkic', 'people'],
 ['coldplay'],
 ['prunus'],
 ['odin'],
 ['vh1'],
 ['twelfth', 'grade'],
 ['faversham'],
 ['city', 'townsville'],
 ['trinity', 'college', 'dublin'],
 ['tasmanian', 'house', 'assembly'],
 ['kgb'],
 ['idaho'],
 ['liao', 'dynasty'],
 ['gascon', 'language'],
 ['luxembourg', 'city'],
 ['saddam', 'hussein'],
 ['ovid'],
 ['venus'],
 ['srikakulam', 'district'],
 ['vest', 'agder'],
 ['comedy'],
 ['megadeth'],
 ['sioux'],
 ['baie', 'james'],
 ['frontier', 'martial', 'art', 'wrestling'],
 ['east', 'lothian'],
 ['indomalayan', 'realm'],
 ['albacete'],
 ['richard', 'fleischer'],
 ['cincinnati', 'red'],
 ['vyborg'],
 ['provincial', 'assembly', 'punjab'],
 ['hamburg'],
 ['ku', 'ring', 'gai', 'council'],
 ['hanoi'],
 ['northern', 'england'],
 ['nonpartisanism'],
 ['reserve', 'bank', 'india'],
 ['tony', 'hatch'],
 ['joan', 'arc'],
 ['chinese', 'american'],
 ['fox', 'broadcasting', 'company'],
 ['parramatta', 'eel'],
 ['duisburg'],
 ['oxford', 'university', 'press'],
 ['yukon'],
 ['tenant', 'purchase', 'scheme'],
 ['cthulhu', 'mythos'],
 ['cape', 'town'],
 ['phoenicia'],
 ['equestrianism'],
 ['taunton'],
 ['1947', 'ceylonese', 'parliamentary', 'election'],
 ['triathlon'],
 ['west', 'coast', 'main', 'line'],
 ['ghana'],
 ['manchester', 'metrolink'],
 ['darfur'],
 ['jim', 'crockett', 'promotion'],
 ['antoninus', 'pius'],
 ['isle', 'dog'],
 ['smith'],
 ['dewan', 'rakyat'],
 ['jennifer', 'rowe'],
 ['kaduna', 'state'],
 ['dahomey'],
 ['nakskov'],
 ['ciutat', 'vella'],
 ['ohio', 'river'],
 ['civil', 'engineering'],
 ['kaluga', 'oblast'],
 ['london', 'borough', 'croydon'],
 ['guillermo', 'del', 'toro'],
 ['germany'],
 ['french', 'polynesia'],
 ['chvrches'],
 ['mark', 'twain'],
 ['shaheed', 'bhagat', 'singh', 'nagar', 'district'],
 ['cyclades'],
 ['strabo'],
 ['milton', 'bradley', 'company'],
 ['occitan', 'language'],
 ['yenisei', 'river'],
 ['bangladesh'],
 ['lake', 'tahoe'],
 ['brandenburg'],
 ['jacob'],
 ['france', 'national', 'football', 'team'],
 ['veikkausliiga'],
 ['2015', 'canadian', 'federal', 'election'],
 ['kurdistan', 'region'],
 ['snk'],
 ['bbc', 'television'],
 ['united', 'state', 'department', 'defense'],
 ['prince', 'elector'],
 ['new', 'england'],
 ['rca'],
 ['qinghai'],
 ['chilean', 'war', 'independence'],
 ['daft', 'punk'],
 ['ghana', 'national', 'football', 'team'],
 ['chinese', 'buddhism'],
 ['florence'],
 ['samara', 'oblast'],
 ['yekaterinburg'],
 ['connecticut', 'river'],
 ['indonesia'],
 ['vancouver'],
 ['miami', 'marlin'],
 ['joseph', 'stalin'],
 ['travel', 'literature'],
 ['christian', 'democratic', 'appeal'],
 ['detroit', 'piston'],
 ['taranto'],
 ['port', 'washington', 'branch'],
 ['yellowknife'],
 ['sahrawi', 'arab', 'democratic', 'republic'],
 ['derry', 'gaa'],
 ['unionism', 'ireland'],
 ['soviet', 'armed', 'force'],
 ['los', 'angeles'],
 ['thomas', 'jefferson'],
 ['hal', 'roach'],
 ['cardiff', 'rfc'],
 ['government', 'kerala'],
 ['regent'],
 ['british', 'people'],
 ['american'],
 ['bell', 'system'],
 ['sabrina', 'carpenter'],
 ['danielle', 'steel'],
 ['lincolnshire'],
 ['printmaking'],
 ['vicenza'],
 ['eric', 'clapton'],
 ['dj', 'khaled'],
 ['county', 'donegal'],
 ['lockheed', 'corporation'],
 ['southern', 'rock'],
 ['george', 'gershwin'],
 ['salvation', 'army'],
 ['bell', 'lab'],
 ['list', 'north', 'carolina', 'state', 'park'],
 ['falklands', 'war'],
 ['gustav', 'mahler'],
 ['monster', 'movie'],
 ['cheap', 'trick'],
 ['chinese', 'taipei'],
 ['liechtenstein'],
 ['daily', 'mail'],
 ['solan', 'district'],
 ['goth'],
 ['british', 'empire'],
 ['scholastic', 'corporation'],
 ['ten', 'pin', 'bowling'],
 ['city', 'university', 'new', 'york'],
 ['vinnytsia', 'oblast'],
 ['centre', 'national', 'de', 'la', 'recherche', 'scientifique'],
 ['opeth'],
 ['neuwied'],
 ['tampere'],
 ['international', 'brigade'],
 ['north', 'london'],
 ['serbian', 'cyrillic', 'alphabet'],
 ['northeastern', 'ontario'],
 ['hackensack', 'river'],
 ['old', 'world', 'warbler'],
 ['danish', 'superliga'],
 ['niue'],
 ['puducherry'],
 ['namibia'],
 ['royal', 'rumble'],
 ['atlantic', 'league', 'professional', 'baseball'],
 ['bornholm'],
 ['alappuzha', 'district'],
 ['spongebob', 'squarepants'],
 ['royal', 'caribbean', 'international'],
 ['kim', 'jong', 'il'],
 ['keanu', 'reef'],
 ['argentina', 'national', 'football', 'team'],
 ['lloyd', 'bacon'],
 ['annette', 'andre'],
 ['british', 'film', 'institute'],
 ['second', 'polish', 'republic'],
 ['geology'],
 ['adventure', 'film'],
 ['jeddah'],
 ['amitabh', 'bachchan'],
 ['london', 'school', 'economics'],
 ['buryatia'],
 ['great', 'purge'],
 ['bandai', 'namco', 'entertainment'],
 ['trojan', 'war'],
 ['katy', 'perry'],
 ['vincent', 'van', 'gogh'],
 ['disneyland', 'paris'],
 ['islamism'],
 ['thor'],
 ['mersin'],
 ['clint', 'eastwood'],
 ['bulgarian', 'cup'],
 ['gauteng'],
 ['team17'],
 ['babur'],
 ['dili'],
 ['arabic', 'literature'],
 ['traditional', 'chinese', 'character'],
 ['knight'],
 ['vadodara'],
 ['javanese', 'language'],
 ['pope'],
 ['botany'],
 ['limehouse'],
 ['international', 'security', 'assistance', 'force'],
 ['barranquilla'],
 ['met', 'mother'],
 ['long', 'island'],
 ['infantry'],
 ['developing', 'country'],
 ['carmarthenshire'],
 ['province', 'sweden'],
 ['minnesota', 'wild'],
 ['roll', 'royce', 'limited'],
 ['county', 'fermanagh'],
 ['steve', 'ditko'],
 ['parthian', 'empire'],
 ['toyota', 'corolla'],
 ['great', 'depression'],
 ['postage', 'stamp'],
 ['napoleon', 'iii'],
 ['university', 'leicester'],
 ['master', 'universe'],
 ['albert', 'einstein'],
 ['patriotism'],
 ['international', 'boxing', 'organization'],
 ['massif', 'central'],
 ['perennial', 'plant'],
 ['fredric', 'march'],
 ['malagasy', 'language'],
 ['torah', 'reading'],
 ['union', 'navy'],
 ['nascar', 'xfinity', 'series'],
 ['tahiti'],
 ['lahore'],
 ['galois', 'group'],
 ['key', 'west'],
 ['john', 'b'],
 ['nagoya'],
 ['surabaya'],
 ['ecumenical', 'patriarch', 'constantinople'],
 ['guadeloupe'],
 ['welsh', 'government'],
 ['yugoslavia'],
 ['plain', 'indian'],
 ['australian', 'hip', 'hop'],
 ['peerage', 'scotland'],
 ['gambino', 'crime', 'family'],
 ['ice', 'hockey'],
 ['australian', 'defence', 'force'],
 ['korean', 'state', 'railway'],
 ['monash', 'university'],
 ['television', 'channel'],
 ['italian', 'renaissance'],
 ['hell'],
 ['fc', 'porto'],
 ['south', 'india'],
 ['government', 'ireland'],
 ['legislative', 'assembly', 'ontario'],
 ['region', 'southern', 'denmark'],
 ['zagreb'],
 ['coahuila'],
 ['assyrian', 'people'],
 ['percussion', 'instrument'],
 ['tuam'],
 ['private', 'university'],
 ['alicia', 'key'],
 ['fox', 'news'],
 ['aramaic'],
 ['quebec', 'major', 'junior', 'hockey', 'league'],
 ['osun', 'state'],
 ['pablo', 'picasso'],
 ['bangkok'],
 ['adriatic', 'sea'],
 ['niger', 'river'],
 ['local', 'government', 'area', 'western', 'australia'],
 ['lao'],
 ['carnatic', 'music'],
 ['new', 'mexico'],
 ['bangalore'],
 ['donald', 'duck'],
 ['minister', 'state'],
 ['royal', 'college', 'surgeon', 'ireland'],
 ['3000', 'metre', 'steeplechase'],
 ['lenape'],
 ['david', 'weber'],
 ['tagalog', 'language'],
 ['oklahoma', 'sooner', 'football'],
 ['university', 'toronto'],
 ['paris', 'foreign', 'mission', 'society'],
 ['directv'],
 ['hawthorn', 'football', 'club'],
 ['bromsgrove'],
 ['durham', 'university'],
 ['badulla'],
 ['posix'],
 ['altai', 'krai'],
 ['hmong', 'people'],
 ['motown'],
 ['freestyle', 'swimming'],
 ['kutaisi'],
 ['futurama'],
 ['thane'],
 ['order', 'st', 'michael', 'st', 'george'],
 ['royal', 'college', 'physician', 'edinburgh'],
 ['20th', 'century', 'fox'],
 ['finland'],
 ['tina', 'arena'],
 ['internet', 'forum'],
 ['muromachi', 'period'],
 ['county', 'dublin'],
 ['meath', 'gaa'],
 ['latvian', 'higher', 'league'],
 ['ecclesiastical', 'latin'],
 ['spiritualism'],
 ['akb48'],
 ['vice', 'president', 'united', 'state'],
 ['west', 'germanic', 'language'],
 ['tauranga'],
 ['1500', 'metre'],
 ['chukchi', 'sea'],
 ['video', 'game', 'publisher'],
 ['al', 'anbar', 'governorate'],
 ['grozny'],
 ['bryan', 'adam'],
 ['wwe', 'network'],
 ['aube'],
 ['stephen', 'hillenburg'],
 ['gascony'],
 ['rashtriya', 'swayamsevak', 'sangh'],
 ['abbasid', 'caliphate'],
 ['bbc', 'america'],
 ['reba', 'mcentire'],
 ['singapore'],
 ['keio', 'university'],
 ['antioquia', 'department'],
 ['koine', 'greek'],
 ['northern', 'cyprus'],
 ['travel', 'channel'],
 ['slade'],
 ['eastern', 'europe'],
 ['university', 'nottingham'],
 ['cinema', 'philippine'],
 ['cumbernauld'],
 ['congregation', 'christian', 'brother'],
 ['montreux'],
 ['davis', 'cup'],
 ['ulyanovsk', 'oblast'],
 ['persian', 'gulf'],
 ['planetary', 'habitability'],
 ['centre', 'right', 'politics'],
 ['order', 'ontario'],
 ['role', 'playing', 'video', 'game'],
 ['dutch', 'golden', 'age', 'painting'],
 ['herbaceous', 'plant'],
 ['ba', 'rhin'],
 ['physician'],
 ['gros', 'de', 'vaud', 'district'],
 ['usb'],
 ['tom', 'jerry'],
 ['mendoza', 'province'],
 ['exeter', 'chief'],
 ['cupressaceae'],
 ['book', 'judge'],
 ['english', 'study'],
 ['mysticism'],
 ['moravian', 'silesian', 'region'],
 ['volvo'],
 ['belarusian'],
 ['philippine', 'basketball', 'association'],
 ['sui', 'dynasty'],
 ['dalai', 'lama'],
 ['tigris'],
 ['rigveda'],
 ['political', 'radicalism'],
 ['apocalyptic', 'post', 'apocalyptic', 'fiction'],
 ['chinese', 'folk', 'religion'],
 ['trajan'],
 ['mark', 'millar'],
 ['romeo', 'juliet'],
 ['grand', 'cayman'],
 ['witney'],
 ['palmerston', 'north'],
 ['college', 'board'],
 ['sam', 'raimi'],
 ['berber'],
 ['def', 'jam', 'recording'],
 ['bahamas'],
 ['old', 'irish'],
 ['stockholm', 'municipality'],
 ['szeged'],
 ['london', 'borough', 'haringey'],
 ['ahvaz'],
 ['vilnius'],
 ['nanchang'],
 ['sarawak'],
 ['mainland', 'china'],
 ['telugu', 'language'],
 ['amazon', 'river'],
 ['san', 'francisco', 'bay'],
 ['john', 'baptist'],
 ['civil', 'political', 'right'],
 ['gaeltacht'],
 ['palatine', 'hungary'],
 ['malacca'],
 ['sahara'],
 ['rascal', 'flatts'],
 ['eastern', 'wu'],
 ['steven', 'spielberg'],
 ['university', 'texas', 'austin'],
 ['subroutine'],
 ['nelson', 'rockefeller'],
 ['hiroshima'],
 ['w'],
 ['canterbury', 'bankstown', 'bulldog'],
 ['luhansk', 'oblast'],
 ['gracillariidae'],
 ['mendip', 'hill'],
 ['derbyshire'],
 ['free', 'state', 'prussia'],
 ['olympique', 'de', 'marseille'],
 ['la', 'palma'],
 ['smolensk'],
 ['cuban', 'revolution'],
 ['fa', 'cup', 'final'],
 ['distinguished', 'service', 'order'],
 ['luc', 'besson'],
 ['mid', 'north'],
 ['sarah', 'jane', 'adventure'],
 ['island', 'record'],
 ['rice', 'university'],
 ['thirteen', 'colony'],
 ['treat', 'williams'],
 ['riverside', 'record'],
 ['greater', 'western', 'sydney'],
 ['babylon'],
 ['lleida'],
 ['department', 'honduras'],
 ['volhynia'],
 ['guinness'],
 ['new', 'york', 'harbor'],
 ['gothic', 'fiction'],
 ['world', 'hockey', 'association'],
 ['ganges'],
 ['ypres', 'salient'],
 ['episcopal', 'polity'],
 ['royal', 'navy'],
 ['korn'],
 ['united', 'state', 'dollar'],
 ['minnesota', 'twin'],
 ['prussian', 'navy'],
 ['l'],
 ['vangelis'],
 ['virginia', 'military', 'institute'],
 ['northern', 'ireland', 'executive'],
 ['deccan', 'plateau'],
 ['akira', 'toriyama'],
 ['action', 'adventure', 'game'],
 ['progressive', 'conservative', 'party', 'canada'],
 ['morobe', 'province'],
 ['queensland'],
 ['miyagi', 'prefecture'],
 ['senate', 'philippine'],
 ['federico', 'fellini'],
 ['australian', 'national', 'university'],
 ['rebellion'],
 ['biographical', 'film'],
 ['lublin', 'voivodeship'],
 ['louis', 'xiv', 'france'],
 ['united', 'state', 'declaration', 'independence'],
 ['bremen'],
 ['duke', 'aquitaine'],
 ['plymouth'],
 ['ian', 'mcewan'],
 ['stephen', 'king'],
 ['professional', 'dart', 'corporation'],
 ['international', 'wrestling', 'revolution', 'group'],
 ['carnian'],
 ['tver', 'oblast'],
 ['bhutan'],
 ['ringo', 'starr'],
 ['algonquian', 'language'],
 ['double', 'bass'],
 ['ellesmere', 'island'],
 ['albert', 'pyun'],
 ['faith'],
 ['new', 'york', 'metropolitan', 'area'],
 ['fc', 'dallas'],
 ['olympique', 'lyonnais'],
 ['edmonton'],
 ['braunschweig'],
 ['cieszyn', 'county'],
 ['bill', 'murray'],
 ['kingdom', 'romania'],
 ['armoured', 'warfare'],
 ['jagiellonian', 'university'],
 ['swiss', 'air', 'force'],
 ['hawick'],
 ['poitier'],
 ['polish', 'language'],
 ['middle', 'tennessee'],
 ['jewish', 'philosophy'],
 ['greek', 'resistance'],
 ['mississauga'],
 ['south', 'los', 'angeles'],
 ['river', 'state'],
 ['binghamton', 'university'],
 ['boston', 'red', 'sox'],
 ['leeds', 'rhino'],
 ['altai', 'mountain'],
 ['piedmont', 'triad'],
 ['nairobi'],
 ['east', 'dunbartonshire'],
 ['hampton', 'road'],
 ['hungarian', 'revolution', '1956'],
 ['social', 'liberalism'],
 ['england', 'cricket', 'team'],
 ['actinopterygii'],
 ['downtown', 'calgary'],
 ['greyhound', 'racing', 'united', 'kingdom'],
 ['puntland'],
 ['sierra', 'madre', 'occidental'],
 ['parliament', 'england'],
 ['streatham'],
 ['tampa', 'bay', 'viper'],
 ['tristan', 'da', 'cunha'],
 ['charles', 'england'],
 ['president', 'colombia'],
 ['riemannian', 'geometry'],
 ['australian', 'rule', 'football'],
 ['english', 'rugby', 'union', 'system'],
 ['twickenham'],
 ['felix', 'cat'],
 ['university', 'denver'],
 ['epiphyte'],
 ['wall', 'street', 'journal'],
 ['daraa'],
 ['lepidoptera'],
 ['lusitania'],
 ['eerste', 'divisie'],
 ['columbidae'],
 ['cenozoic'],
 ['hillary', 'clinton'],
 ['woody', 'woodpecker'],
 ['oakland', 'athletics'],
 ['lake', 'district', 'national', 'park'],
 ['dnipropetrovsk', 'oblast'],
 ['chemistry'],

In [7]:
from nltk.wsd import lesk

lesked_queries = []

for query_list in lemmatized_tokenized_queries:
    query_weighted_lesk = []
    none_lesk_list = []
    isLesk = False

    for word in query_list:
        temp = lesk(query_list, word)

        if temp is None:
            none_lesk_list.append(word)
        else:
            isLesk = True
            query_weighted_lesk.extend([word] * 2)
            cleaned_lemmas = [lemma.replace('_', ' ') for lemma in temp.lemma_names()]
            query_weighted_lesk.extend(cleaned_lemmas)

    if none_lesk_list:
        if isLesk:
            for anyword in none_lesk_list:
                query_weighted_lesk.extend([anyword] * 2)
        else:
            query_weighted_lesk.extend(none_lesk_list)

    lesked_queries.append(query_weighted_lesk)

In [8]:
lesked_queries

[['yanni'],
 ['k', 'k', 'kelvin', 'K', 'pop', 'pop', 'pop'],
 ['venice',
  'venice',
  'Venice',
  'Venezia',
  'film',
  'film',
  'film',
  'shoot',
  'take',
  'festival',
  'festival',
  'festival'],
 ['downtown',
  'downtown',
  'business district',
  'downtown',
  'brooklyn',
  'brooklyn',
  'Brooklyn'],
 ['pennsylvania',
  'pennsylvania',
  'Pennsylvania',
  'Keystone State',
  'PA',
  'house',
  'house',
  'house',
  'representative',
  'representative',
  'representative'],
 ['northern',
  'northern',
  'Northern',
  'premier',
  'premier',
  'Prime Minister',
  'PM',
  'premier',
  'league',
  'league',
  'league'],
 ['first',
  'first',
  'first',
  'number one',
  'national',
  'national',
  'national',
  'picture',
  'picture',
  'picture',
  'depict',
  'render',
  'show'],
 ['poland', 'poland', 'Poland', 'Republic of Poland', 'Polska'],
 ['cyperaceae',
  'cyperaceae',
  'Cyperaceae',
  'family Cyperaceae',
  'sedge family'],
 ['trinidad', 'trinidad', 'Trinidad', 'tobago', 'tobago', 'Tobago'],
 ['normandy',
  'normandy',
  'Normandie',
  'Normandy',
  'landing',
  'landing',
  'landing'],
 ['perry', 'perry', 'Perry', 'Ralph Barton Perry', 'index', 'index', 'index'],
 ['arm',
  'arm',
  'arm',
  'branch',
  'limb',
  'architecture',
  'architecture',
  'architecture'],
 ['mi5'],
 ['patriarch',
  'patriarch',
  'patriarch',
  'antioch',
  'antioch',
  'Antioch',
  'Antakya',
  'Antakiya'],
 ['district',
  'district',
  'district',
  'territory',
  'territorial dominion',
  'dominion',
  'nashik',
  'nashik'],
 ['semiotics', 'semiotics', 'semiotics', 'semiology'],
 ['santa',
  'santa',
  'Santa Claus',
  'Santa',
  'Kriss Kringle',
  'Father Christmas',
  'Saint Nicholas',
  'Saint Nick',
  'St. Nick',
  'de',
  'de',
  'Delaware',
  'Diamond State',
  'First State',
  'DE',
  'tenerife',
  'tenerife',
  'Tenerife',
  'cruz',
  'cruz'],
 ['gastropoda',
  'gastropoda',
  'Gastropoda',
  'class Gastropoda',
  'Gasteropoda',
  'class Gasteropoda'],
 ['zaragoza', 'zaragoza', 'Zaragoza', 'Saragossa'],
 ['south', 'south', 'South', 'carolina', 'carolina', 'Carolina', 'Carolinas'],
 ['augustine',
  'augustine',
  'Augustine',
  'Saint Augustine',
  'St. Augustine',
  'Augustine of Hippo',
  'hippo',
  'hippo',
  'Hippo',
  'Hippo Regius'],
 ['canton',
  'canton',
  'Guangzhou',
  'Kuangchou',
  'Kwangchow',
  'Canton',
  'geneva',
  'geneva',
  'Geneva',
  'Geneve',
  'Genf'],
 ['leo',
  'leo',
  'Leo',
  'Lion',
  'tolstoy',
  'tolstoy',
  'Tolstoy',
  'Leo Tolstoy',
  'Count Lev Nikolayevitch Tolstoy'],
 ['riemannian',
  'riemannian',
  'Riemannian',
  'manifold',
  'manifold',
  'manifold'],
 ['tuzla'],
 ['subaru'],
 ['tomsk'],
 ['united',
  'united',
  'connect',
  'link',
  'link up',
  'join',
  'unite',
  'state',
  'state',
  'state',
  'department',
  'department',
  'department',
  'section',
  'agriculture',
  'agriculture',
  'Department of Agriculture',
  'Agriculture Department',
  'Agriculture',
  'USDA'],
 ['north', 'north', 'North', 'borneo', 'borneo', 'Borneo', 'Kalimantan'],
 ['isaac', 'isaac', 'Isaac', 'asimov', 'asimov', 'Asimov', 'Isaac Asimov'],
 ['hilbert',
  'hilbert',
  'Hilbert',
  'David Hilbert',
  'space',
  'space',
  'space',
  'infinite'],
 ['chechen', 'chechen', 'Chechen'],
 ['arunachal', 'pradesh'],
 ['central',
  'central',
  'central',
  'telephone exchange',
  'exchange',
  'otago',
  'otago'],
 ['ira',
  'ira',
  'Irish Republican Army',
  'IRA',
  'Provisional Irish Republican Army',
  'Provisional IRA',
  'Provos',
  'gershwin',
  'gershwin',
  'Gershwin',
  'Ira Gershwin'],
 ['rock', 'rock', 'rock', 'stone', 'roll', 'roll', 'bankroll', 'roll'],
 ['fiba'],
 ['east',
  'east',
  'East',
  'eastern United States',
  'coast',
  'coast',
  'coast',
  'united',
  'united',
  'connect',
  'link',
  'link up',
  'join',
  'unite',
  'state',
  'state',
  'state'],
 ['wikipedia'],
 ['pernambuco', 'pernambuco', 'Recife', 'Pernambuco'],
 ['west',
  'west',
  'West',
  'western United States',
  'coast',
  'coast',
  'coast',
  'eagle',
  'eagle',
  'eagle',
  'bird of Jove'],
 ['twin', 'twin', 'twin', 'peak', 'peak', 'extremum', 'peak'],
 ['dutch',
  'dutch',
  'Dutch',
  'language',
  'language',
  'language',
  'linguistic communication'],
 ['liberal',
  'liberal',
  'liberal',
  'liberalist',
  'progressive',
  'party',
  'party',
  'party',
  'canada',
  'canada',
  'Canada'],
 ['island', 'island', 'island', 'spratly', 'spratly'],
 ['kampala', 'kampala', 'Kampala', 'capital of Uganda'],
 ['national',
  'national',
  'national',
  'film',
  'film',
  'film',
  'shoot',
  'take',
  'board',
  'board',
  'board',
  'gameboard',
  'canada',
  'canada',
  'Canada'],
 ['turkish',
  'turkish',
  'Turkish',
  'war',
  'war',
  'war',
  'state of war',
  'independence',
  'independence',
  'independence',
  'independency'],
 ['chania'],
 ['oakland',
  'oakland',
  'Oakland',
  'raider',
  'raider',
  'plunderer',
  'pillager',
  'looter',
  'spoiler',
  'despoiler',
  'raider',
  'freebooter'],
 ['district',
  'district',
  'district',
  'territory',
  'territorial dominion',
  'dominion',
  'krishnagiri',
  'krishnagiri'],
 ['group', 'group', 'group', 'vr', 'vr'],
 ['trade', 'trade', 'trade', 'merchandise', 'name', 'name', 'name', 'call'],
 ['saxon', 'saxon', 'Saxon', 'anglo', 'anglo'],
 ['bermuda', 'bermuda', 'Bermuda', 'Bermudas'],
 ['paradox',
  'paradox',
  'paradox',
  'development',
  'development',
  'development',
  'studio',
  'studio',
  'studio'],
 ['usenet'],
 ['radio', 'radio', 'radio', 'bbc', 'bbc'],
 ['wallace',
  'wallace',
  'Wallace',
  'Sir William Wallace',
  'stevens',
  'stevens',
  'Stevens',
  'Smitty Stevens',
  'S. Smith Stevens',
  'Stanley Smith Stevens'],
 ['spain', 'spain', 'Spain', 'Kingdom of Spain', 'Espana'],
 ['franchising', 'franchising', 'franchise'],
 ['united',
  'united',
  'connect',
  'link',
  'link up',
  'join',
  'unite',
  'artist',
  'artist',
  'artist',
  'creative person',
  'record',
  'record',
  'record'],
 ['royal',
  'royal',
  'royal',
  'corp',
  'corp',
  'corporation',
  'corp',
  'signal',
  'signal',
  'bespeak',
  'betoken',
  'indicate',
  'point',
  'signal'],
 ['palawan'],
 ['seine', 'seine', 'seine', 'et', 'et', 'marne', 'marne'],
 ['west',
  'west',
  'West',
  'western United States',
  'country',
  'country',
  'nation',
  'land',
  'country'],
 ['bailiwick',
  'bailiwick',
  'bailiwick',
  'guernsey',
  'guernsey',
  'Guernsey',
  'island of Guernsey'],
 ['pleuronectidae',
  'pleuronectidae',
  'Pleuronectidae',
  'family Pleuronectidae'],
 ['income',
  'income',
  'income',
  'tax',
  'tax',
  'tax',
  'united',
  'united',
  'connect',
  'link',
  'link up',
  'join',
  'unite',
  'state',
  'state',
  'state'],
 ['series', 'series', 'series', 'gp3', 'gp3'],
 ['septimius', 'severus'],
 ['pharaoh', 'pharaoh', 'Pharaoh', 'Pharaoh of Egypt'],
 ['metropolitan',
  'metropolitan',
  'metropolitan',
  'borough',
  'borough',
  'borough',
  'doncaster',
  'doncaster'],
 ['history',
  'history',
  'history',
  'jew',
  'jew',
  'Jew',
  'Hebrew',
  'Israelite',
  'poland',
  'poland',
  'Poland',
  'Republic of Poland',
  'Polska'],
 ['erasure', 'erasure', 'erasure'],
 ['suez', 'suez', 'Suez', 'canal', 'canal', 'canal', 'canalize', 'canalise'],
 ['naval',
  'naval',
  'naval',
  'air',
  'air',
  'atmosphere',
  'air',
  'station',
  'station',
  'station',
  'lemoore',
  'lemoore'],
 ['lower',
  'lower',
  'lower berth',
  'lower',
  'saxony',
  'saxony',
  'Saxony',
  'Sachsen',
  'Saxe'],
 ['robert',
  'robert',
  'Robert',
  'Henry M. Robert',
  'Henry Martyn Robert',
  'stack',
  'stack',
  'stack'],
 ['boeing'],
 ['wexford', 'gaa'],
 ['miss',
  'miss',
  'girl',
  'miss',
  'missy',
  'young lady',
  'young woman',
  'fille',
  'universe',
  'universe',
  'universe',
  'existence',
  'creation',
  'world',
  'cosmos',
  'macrocosm'],
 ['sydney',
  'sydney',
  'Sydney',
  'central',
  'central',
  'central',
  'telephone exchange',
  'exchange',
  'business',
  'business',
  'business',
  'business sector',
  'district',
  'district',
  'district',
  'territory',
  'territorial dominion',
  'dominion'],
 ['peninsula', 'peninsula', 'peninsula', 'keweenaw', 'keweenaw'],
 ['music', 'music', 'music'],
 ['g',
  'g',
  'gram',
  'gramme',
  'gm',
  'g',
  'league',
  'league',
  'league',
  'nba',
  'nba'],
 ['makati'],
 ['genre', 'genre', 'genre', 'art', 'art', 'art', 'fine art'],
 ['racecourse',
  'racecourse',
  'racetrack',
  'racecourse',
  'raceway',
  'track',
  'aintree',
  'aintree'],
 ['colchester'],
 ['christian', 'christian', 'Christian', 'rock', 'rock', 'rock', 'stone'],
 ['clash',
  'clash',
  'clang',
  'clangor',
  'clangour',
  'clangoring',
  'clank',
  'clash',
  'crash'],
 ['schiller',
  'schiller',
  'Schiller',
  'Johann Christoph Friedrich von Schiller',
  'friedrich',
  'friedrich'],
 ['comedy',
  'comedy',
  'comedy',
  'drama',
  'drama',
  'play',
  'drama',
  'dramatic play'],
 ['tiberias'],
 ['basel', 'basel', 'Basel', 'Basle', 'Bale', 'fc', 'fc'],
 ['new',
  'new',
  'newfangled',
  'new',
  'york',
  'york',
  'York',
  'House of York',
  'knicks',
  'knicks'],
 ['perm', 'perm', 'Perm', 'Molotov', 'krai', 'krai'],
 ['dordogne'],
 ['dutch',
  'dutch',
  'Dutch',
  'Dutch people',
  'west',
  'west',
  'West',
  'western United States',
  'india',
  'india',
  'India',
  'Republic of India',
  'Bharat',
  'company',
  'company',
  'company'],
 ['titian', 'titian', 'Titian', 'Tiziano Vecellio'],
 ['victorian',
  'victorian',
  'Victorian',
  'burlesque',
  'burlesque',
  'burlesque'],
 ['tvb'],
 ['muridae', 'muridae', 'Muridae', 'family Muridae'],
 ['tvxq'],
 ['cope', 'cope', 'header', 'coping', 'cope', 'kenneth', 'kenneth'],
 ['london',
  'london',
  'London',
  'Greater London',
  'British capital',
  'capital of the United Kingdom',
  'borough',
  'borough',
  'borough',
  'islington',
  'islington'],
 ['top',
  'top',
  'peak',
  'crown',
  'crest',
  'top',
  'tip',
  'summit',
  'cow',
  'cow',
  'cow',
  'moo-cow',
  'production',
  'production',
  'production'],
 ['bradford',
  'bradford',
  'Bradford',
  'William Bradford',
  'bull',
  'bull',
  'bull'],
 ['mike',
  'mike',
  'microphone',
  'mike',
  'oldfield',
  'oldfield',
  'Oldfield',
  'Barney Oldfield',
  'Berna Eli Oldfield'],
 ['shooter', 'shooter', 'taw', 'shooter', 'game', 'game', 'game'],
 ['hull',
  'hull',
  'hull',
  'kingston',
  'kingston',
  'Kingston',
  'rover',
  'rover',
  'wanderer',
  'roamer',
  'rover',
  'bird of passage'],
 ['national',
  'national',
  'national',
  'science',
  'science',
  'science',
  'scientific discipline',
  'foundation',
  'foundation',
  'foundation'],
 ['grau'],
 ['dannii', 'minogue'],
 ['christopher',
  'christopher',
  'Christopher',
  'Saint Christopher',
  'St. Christopher',
  'nolan',
  'nolan'],
 ['moscow',
  'moscow',
  'Moscow',
  'capital of the Russian Federation',
  'Russian capital',
  'oblast',
  'oblast'],
 ['british',
  'british',
  'British',
  'British people',
  'Brits',
  'national',
  'national',
  'national',
  'party',
  'party',
  'party'],
 ['balochi',
  'balochi',
  'Balochi',
  'Baluchi',
  'language',
  'language',
  'language',
  'linguistic communication'],
 ['benjamin',
  'benjamin',
  'benzoin',
  'gum benzoin',
  'benjamin',
  'gum benjamin',
  'asa dulcis',
  'franklin',
  'franklin',
  'Franklin',
  'John Hope Franklin'],
 ['big',
  'big',
  'large',
  'big',
  'south',
  'south',
  'South',
  'conference',
  'conference',
  'conference'],
 ['cantabria'],
 ['chain', 'chain', 'chain', 'alice', 'alice'],
 ['michigan',
  'michigan',
  'Michigan',
  'Wolverine State',
  'Great Lakes State',
  'MI'],
 ['soundgarden'],
 ['bermondsey'],
 ['division',
  'division',
  'division',
  'football',
  'football',
  'football',
  'season',
  'season',
  'season',
  '2017',
  '2017',
  'ncaa',
  'ncaa',
  'fbs',
  'fbs'],
 ['northwestern',
  'northwestern',
  'northwestern',
  'northwesterly',
  'northwest',
  'united',
  'united',
  'connect',
  'link',
  'link up',
  'join',
  'unite',
  'state',
  'state',
  'state'],
 ['southeast',
  'southeast',
  'southeasterly',
  'southeast',
  'asia',
  'asia',
  'Asia'],
 ['social',
  'social',
  'sociable',
  'social',
  'mixer',
  'psychology',
  'psychology',
  'psychology',
  'psychological science'],
 ['john',
  'john',
  'toilet',
  'lavatory',
  'lav',
  'can',
  'john',
  'privy',
  'bathroom',
  'coltrane',
  'coltrane'],
 ['roll',
  'roll',
  'bankroll',
  'roll',
  'distinguished',
  'distinguished',
  'distinguish',
  'separate',
  'differentiate',
  'secern',
  'secernate',
  'severalize',
  'severalise',
  'tell',
  'tell apart',
  'philatelist',
  'philatelist',
  'philatelist',
  'stamp collector'],
 ['restoration',
  'restoration',
  'Restoration',
  'movement',
  'movement',
  'motion',
  'movement',
  'move',
  'motility'],
 ['danny', 'elfman'],
 ['language',
  'language',
  'language',
  'linguistic communication',
  'konkani',
  'konkani'],
 ['dungannon'],
 ['united',
  'united',
  'connect',
  'link',
  'link up',
  'join',
  'unite',
  'soccer',
  'soccer',
  'soccer',
  'association football',
  'league',
  'league',
  'league'],
 ['chapter',
  'chapter',
  'chapter',
  'verse',
  'verse',
  'verse',
  'versify',
  'poetize',
  'poetise',
  'bible',
  'bible',
  'Bible',
  'Christian Bible',
  'Book',
  'Good Book',
  'Holy Scripture',
  'Holy Writ',
  'Scripture',
  'Word of God',
  'Word'],
 ['isle',
  'isle',
  'isle',
  'islet',
  'man',
  'man',
  'man',
  'adult male',
  'tt',
  'tt',
  'terrestrial time',
  'TT',
  'terrestrial dynamical time',
  'TDT',
  'ephemeris time'],
 ['zurich', 'zurich', 'Zurich', 'eth', 'eth'],
 ['emirate', 'emirate', 'emirate', 'abu', 'abu', 'dhabi', 'dhabi'],
 ['delaware',
  'delaware',
  'Delaware',
  'Delaware River',
  'river',
  'river',
  'river'],
 ['black', 'black', 'black', 'sea', 'sea', 'sea'],
 ['antigua', 'antigua', 'Antigua'],
 ['primary',
  'primary',
  'basal',
  'primary',
  'school',
  'school',
  'school',
  'schooling'],
 ['berber',
  'berber',
  'Berber',
  'language',
  'language',
  'language',
  'linguistic communication'],
 ['loch', 'loch', 'loch', 'lomond', 'lomond'],
 ['african', 'african', 'African', 'union', 'union', 'union'],
 ['north',
  'north',
  'North',
  'american',
  'american',
  'American',
  'numbering',
  'numbering',
  'enumeration',
  'numbering',
  'plan',
  'plan',
  'plan',
  'project',
  'contrive',
  'design'],
 ['mountain', 'mountain', 'mountain', 'mount', 'ural', 'ural'],
 ['utah', 'utah', 'Utah', 'Beehive State', 'Mormon State', 'UT'],
 ['cup', 'cup', 'cup', 'cupful', 'algarve', 'algarve'],
 ['mixed',
  'mixed',
  'blend',
  'flux',
  'mix',
  'conflate',
  'commingle',
  'immix',
  'fuse',
  'coalesce',
  'meld',
  'combine',
  'merge',
  'martial',
  'martial',
  'Martial',
  'art',
  'art',
  'art',
  'fine art'],
 ['jaxa'],
 ['plateau', 'plateau', 'tableland', 'plateau', 'state', 'state', 'state'],
 ['albanian',
  'albanian',
  'Albanian',
  'national',
  'national',
  'national',
  'awakening',
  'awakening',
  'awakening',
  'wakening',
  'waking up'],
 ['unionidae', 'unionidae', 'Unionidae', 'family Unionidae'],
 ['mystery',
  'mystery',
  'mystery',
  'enigma',
  'secret',
  'closed book',
  'fiction',
  'fiction',
  'fiction'],
 ['metropolitan',
  'metropolitan',
  'metropolitan',
  'police',
  'police',
  'police',
  'police force',
  'constabulary',
  'law',
  'service',
  'service',
  'service'],
 ['bukovina'],
 ['wilbert', 'awdry'],
 ['american', 'american', 'American'],
 ['western',
  'western',
  'Western',
  'horse opera',
  'bulldog',
  'bulldog',
  'bulldog',
  'English bulldog'],
 ['christian',
  'christian',
  'Christian',
  'theology',
  'theology',
  'theology',
  'divinity'],
 ['patriarch', 'patriarch', 'patriarch'],
 ['skanderbeg'],
 ['korea',
  'korea',
  'Korea',
  'Korean Peninsula',
  'Dae-Han-Min-Gook',
  'Han-Gook',
  'japanese',
  'japanese',
  'Japanese',
  'Nipponese',
  'rule',
  'rule',
  'rule',
  'linguistic rule'],
 ['major',
  'major',
  'major',
  'league',
  'league',
  'league',
  'lacrosse',
  'lacrosse',
  'lacrosse'],
 ['perak'],
 ['graduate',
  'graduate',
  'alumnus',
  'alumna',
  'alum',
  'graduate',
  'grad',
  'school',
  'school',
  'school',
  'schooling'],
 ['master',
  'master',
  'maestro',
  'master',
  'fine',
  'fine',
  'ticket',
  'fine',
  'art',
  'art',
  'art',
  'fine art'],
 ['little',
  'little',
  'fiddling',
  'footling',
  'lilliputian',
  'little',
  'niggling',
  'piddling',
  'piffling',
  'petty',
  'picayune',
  'trivial',
  'league',
  'league',
  'league',
  'world',
  'world',
  'universe',
  'existence',
  'creation',
  'world',
  'cosmos',
  'macrocosm',
  'series',
  'series',
  'series'],
 ['tugboat', 'tugboat', 'tugboat', 'tug', 'towboat', 'tower'],
 ['united',
  'united',
  'connect',
  'link',
  'link up',
  'join',
  'unite',
  'state',
  'state',
  'state',
  'presidential',
  'presidential',
  'presidential',
  'election',
  'election',
  'election',
  '2016',
  '2016'],
 ['united',
  'united',
  'connect',
  'link',
  'link up',
  'join',
  'unite',
  'state',
  'state',
  'state',
  'national',
  'national',
  'national',
  'rugby',
  'rugby',
  'rugby',
  'rugby football',
  'rugger',
  'union',
  'union',
  'union',
  'unification',
  'team',
  'team',
  'team',
  'team up'],
 ['intercalated',
  'intercalated',
  'intercalate',
  'game',
  'game',
  'game',
  '1906',
  '1906'],
 ['province',
  'province',
  'state',
  'province',
  'bocas',
  'bocas',
  'del',
  'del',
  'toro',
  'toro'],
 ['four',
  'four',
  'four-spot',
  'four',
  'engine',
  'engine',
  'locomotive',
  'engine',
  'locomotive engine',
  'railway locomotive',
  'inline',
  'inline'],
 ['english',
  'english',
  'English',
  'English language',
  'feudal',
  'feudal',
  'feudal',
  'feudalistic',
  'barony',
  'barony',
  'barony'],
 ['royal',
  'royal',
  'royal',
  'order',
  'order',
  'order',
  'guelphic',
  'guelphic'],
 ['bodybuilding',
  'bodybuilding',
  'bodybuilding',
  'anaerobic exercise',
  'muscle building',
  'musclebuilding'],
 ['dusty',
  'dusty',
  'dusty',
  'dust-covered',
  'springfield',
  'springfield',
  'Springfield',
  'capital of Illinois'],
 ['caserta'],
 ['northrop',
  'northrop',
  'Northrop',
  'John Howard Northrop',
  'grumman',
  'grumman'],
 ['bourbon',
  'bourbon',
  'Bourbon',
  'restoration',
  'restoration',
  'Restoration'],
 ['sql'],
 ['south', 'south', 'South', 'cambridgeshire', 'cambridgeshire'],
 ['alappuzha'],
 ['united',
  'united',
  'connect',
  'link',
  'link up',
  'join',
  'unite',
  'state',
  'state',
  'state',
  'national',
  'national',
  'national',
  'guard',
  'guard',
  'guard'],
 ['korean',
  'korean',
  'Korean',
  'drama',
  'drama',
  'play',
  'drama',
  'dramatic play'],
 ['thiruvananthapuram'],
 ['collecting',
  'collecting',
  'collection',
  'collecting',
  'assembling',
  'aggregation'],
 ['uzbek', 'uzbek', 'Uzbek', 'Uzbeg', 'Uzbak', 'Usbek', 'Usbeg'],
 ['limited', 'limited', 'express', 'limited', 'vickers', 'vickers'],
 ['luis', 'miguel'],
 ['ottoman',
  'ottoman',
  'Ottoman',
  'Ottoman Turk',
  'Osmanli',
  'navy',
  'navy',
  'United States Navy',
  'US Navy',
  'USN',
  'Navy'],
 ['truman',
  'truman',
  'Truman',
  'Harry Truman',
  'Harry S Truman',
  'President Truman',
  'capote',
  'capote',
  'capote',
  'hooded coat'],
 ['arnold',
  'arnold',
  'Arnold',
  'Matthew Arnold',
  'schwarzenegger',
  'schwarzenegger'],
 ['taurus',
  'taurus',
  'Sanchez',
  'Ilich Sanchez',
  'Ilich Ramirez Sanchez',
  'Carlos',
  'Carlos the Jackal',
  'Salim',
  'Andres Martinez',
  'Taurus',
  'Glen Gebhard',
  'Hector Hevodidbon',
  'Michael Assat',
  'mountain',
  'mountain',
  'mountain',
  'mount'],
 ['easter',
  'easter',
  'Easter',
  'rising',
  'rising',
  'rise',
  'rising',
  'ascent',
  'ascension'],
 ['henry',
  'henry',
  'henry',
  'H',
  'david',
  'david',
  'David',

In [9]:
lemmatized_tokenized_queries

[['yanni'],
 ['k', 'pop'],
 ['venice', 'film', 'festival'],
 ['downtown', 'brooklyn'],
 ['pennsylvania', 'house', 'representative'],
 ['northern', 'premier', 'league'],
 ['first', 'national', 'picture'],
 ['poland'],
 ['cyperaceae'],
 ['trinidad', 'tobago'],
 ['normandy', 'landing'],
 ['perry', 'index'],
 ['arm', 'architecture'],
 ['mi5'],
 ['patriarch', 'antioch'],
 ['nashik', 'district'],
 ['semiotics'],
 ['santa', 'cruz', 'de', 'tenerife'],
 ['gastropoda'],
 ['zaragoza'],
 ['south', 'carolina'],
 ['augustine', 'hippo'],
 ['canton', 'geneva'],
 ['leo', 'tolstoy'],
 ['riemannian', 'manifold'],
 ['tuzla'],
 ['subaru'],
 ['tomsk'],
 ['united', 'state', 'department', 'agriculture'],
 ['north', 'borneo'],
 ['isaac', 'asimov'],
 ['hilbert', 'space'],
 ['chechen'],
 ['arunachal', 'pradesh'],
 ['central', 'otago'],
 ['ira', 'gershwin'],
 ['rock', 'roll'],
 ['fiba'],
 ['east', 'coast', 'united', 'state'],
 ['wikipedia'],
 ['pernambuco'],
 ['west', 'coast', 'eagle'],
 ['twin', 'peak'],
 ['dutch', 'language'],
 ['liberal', 'party', 'canada'],
 ['spratly', 'island'],
 ['kampala'],
 ['national', 'film', 'board', 'canada'],
 ['turkish', 'war', 'independence'],
 ['chania'],
 ['oakland', 'raider'],
 ['krishnagiri', 'district'],
 ['vr', 'group'],
 ['trade', 'name'],
 ['anglo', 'saxon'],
 ['bermuda'],
 ['paradox', 'development', 'studio'],
 ['usenet'],
 ['bbc', 'radio'],
 ['wallace', 'stevens'],
 ['spain'],
 ['franchising'],
 ['united', 'artist', 'record'],
 ['royal', 'corp', 'signal'],
 ['palawan'],
 ['seine', 'et', 'marne'],
 ['west', 'country'],
 ['bailiwick', 'guernsey'],
 ['pleuronectidae'],
 ['income', 'tax', 'united', 'state'],
 ['gp3', 'series'],
 ['septimius', 'severus'],
 ['pharaoh'],
 ['metropolitan', 'borough', 'doncaster'],
 ['history', 'jew', 'poland'],
 ['erasure'],
 ['suez', 'canal'],
 ['naval', 'air', 'station', 'lemoore'],
 ['lower', 'saxony'],
 ['robert', 'stack'],
 ['boeing'],
 ['wexford', 'gaa'],
 ['miss', 'universe'],
 ['sydney', 'central', 'business', 'district'],
 ['keweenaw', 'peninsula'],
 ['music'],
 ['nba', 'g', 'league'],
 ['makati'],
 ['genre', 'art'],
 ['aintree', 'racecourse'],
 ['colchester'],
 ['christian', 'rock'],
 ['clash'],
 ['friedrich', 'schiller'],
 ['comedy', 'drama'],
 ['tiberias'],
 ['fc', 'basel'],
 ['new', 'york', 'knicks'],
 ['perm', 'krai'],
 ['dordogne'],
 ['dutch', 'west', 'india', 'company'],
 ['titian'],
 ['victorian', 'burlesque'],
 ['tvb'],
 ['muridae'],
 ['tvxq'],
 ['kenneth', 'cope'],
 ['london', 'borough', 'islington'],
 ['top', 'cow', 'production'],
 ['bradford', 'bull'],
 ['mike', 'oldfield'],
 ['shooter', 'game'],
 ['hull', 'kingston', 'rover'],
 ['national', 'science', 'foundation'],
 ['grau'],
 ['dannii', 'minogue'],
 ['christopher', 'nolan'],
 ['moscow', 'oblast'],
 ['british', 'national', 'party'],
 ['balochi', 'language'],
 ['benjamin', 'franklin'],
 ['big', 'south', 'conference'],
 ['cantabria'],
 ['alice', 'chain'],
 ['michigan'],
 ['soundgarden'],
 ['bermondsey'],
 ['2017', 'ncaa', 'division', 'fbs', 'football', 'season'],
 ['northwestern', 'united', 'state'],
 ['southeast', 'asia'],
 ['social', 'psychology'],
 ['john', 'coltrane'],
 ['roll', 'distinguished', 'philatelist'],
 ['restoration', 'movement'],
 ['danny', 'elfman'],
 ['konkani', 'language'],
 ['dungannon'],
 ['united', 'soccer', 'league'],
 ['chapter', 'verse', 'bible'],
 ['isle', 'man', 'tt'],
 ['eth', 'zurich'],
 ['emirate', 'abu', 'dhabi'],
 ['delaware', 'river'],
 ['black', 'sea'],
 ['antigua'],
 ['primary', 'school'],
 ['berber', 'language'],
 ['loch', 'lomond'],
 ['african', 'union'],
 ['north', 'american', 'numbering', 'plan'],
 ['ural', 'mountain'],
 ['utah'],
 ['algarve', 'cup'],
 ['mixed', 'martial', 'art'],
 ['jaxa'],
 ['plateau', 'state'],
 ['albanian', 'national', 'awakening'],
 ['unionidae'],
 ['mystery', 'fiction'],
 ['metropolitan', 'police', 'service'],
 ['bukovina'],
 ['wilbert', 'awdry'],
 ['american'],
 ['western', 'bulldog'],
 ['christian', 'theology'],
 ['patriarch'],
 ['skanderbeg'],
 ['korea', 'japanese', 'rule'],
 ['major', 'league', 'lacrosse'],
 ['perak'],
 ['graduate', 'school'],
 ['master', 'fine', 'art'],
 ['little', 'league', 'world', 'series'],
 ['tugboat'],
 ['2016', 'united', 'state', 'presidential', 'election'],
 ['united', 'state', 'national', 'rugby', 'union', 'team'],
 ['1906', 'intercalated', 'game'],
 ['bocas', 'del', 'toro', 'province'],
 ['inline', 'four', 'engine'],
 ['english', 'feudal', 'barony'],
 ['royal', 'guelphic', 'order'],
 ['bodybuilding'],
 ['dusty', 'springfield'],
 ['caserta'],
 ['northrop', 'grumman'],
 ['bourbon', 'restoration'],
 ['sql'],
 ['south', 'cambridgeshire'],
 ['alappuzha'],
 ['united', 'state', 'national', 'guard'],
 ['korean', 'drama'],
 ['thiruvananthapuram'],
 ['collecting'],
 ['uzbek'],
 ['vickers', 'limited'],
 ['luis', 'miguel'],
 ['ottoman', 'navy'],
 ['truman', 'capote'],
 ['arnold', 'schwarzenegger'],
 ['taurus', 'mountain'],
 ['easter', 'rising'],
 ['henry', 'david', 'thoreau'],
 ['george', 'jones'],
 ['bbc', 'radio', '1'],
 ['craven'],
 ['architecture'],
 ['sega'],
 ['second', 'sea', 'lord'],
 ['stena', 'line'],
 ['wingecarribee', 'shire'],
 ['fraser', 'coast', 'region'],
 ['intellivision'],
 ['gridiron', 'football'],
 ['moreton', 'bay', 'region'],
 ['ultimate', 'play', 'game'],
 ['literature'],
 ['podgorica'],
 ['lugano'],
 ['smokey', 'robinson'],
 ['major', 'league', 'soccer'],
 ['london', 'borough', 'redbridge'],
 ['roman', 'britain'],
 ['budapest'],
 ['rugby', 'football'],
 ['archbishop', 'york'],
 ['edward', 'ii', 'england'],
 ['ajmer'],
 ['yamaguchi', 'prefecture'],
 ['jaipur'],
 ['indonesian', 'cuisine'],
 ['port', 'los', 'angeles'],
 ['british', 'academy'],
 ['united', 'methodist', 'church'],
 ['independent', 'music'],
 ['chiswick'],
 ['celebrity'],
 ['ivy', 'league'],
 ['na'],
 ['province', 'massachusetts', 'bay'],
 ['christmas', 'carol'],
 ['aix', 'en', 'provence'],
 ['black', 'hill'],
 ['willamette', 'valley'],
 ['master', 'wine'],
 ['carl', 'reiner'],
 ['podlaskie', 'voivodeship'],
 ['princess'],
 ['collins', 'crime', 'club'],
 ['romanian', 'naval', 'force'],
 ['poxviridae'],
 ['koper'],
 ['limerick', 'gaa'],
 ['ancona'],
 ['mauritius'],
 ['clark', 'university'],
 ['ohio'],
 ['ludwigsburg'],
 ['province', 'chile'],
 ['right', 'wing', 'politics'],
 ['horticulture'],
 ['richard', 'nixon'],
 ['indie', 'rock'],
 ['samsung'],
 ['virginia', 'general', 'assembly'],
 ['schutzstaffel'],
 ['cloud', 'computing'],
 ['upper', 'carniola'],
 ['crown', 'colony'],
 ['metropolitan', 'borough', 'solihull'],
 ['valladolid'],
 ['william', 'goldman'],
 ['socialist', 'unity', 'party', 'germany'],
 ['irem'],
 ['turkic', 'people'],
 ['coldplay'],
 ['prunus'],
 ['odin'],
 ['vh1'],
 ['twelfth', 'grade'],
 ['faversham'],
 ['city', 'townsville'],
 ['trinity', 'college', 'dublin'],
 ['tasmanian', 'house', 'assembly'],
 ['kgb'],
 ['idaho'],
 ['liao', 'dynasty'],
 ['gascon', 'language'],
 ['luxembourg', 'city'],
 ['saddam', 'hussein'],
 ['ovid'],
 ['venus'],
 ['srikakulam', 'district'],
 ['vest', 'agder'],
 ['comedy'],
 ['megadeth'],
 ['sioux'],
 ['baie', 'james'],
 ['frontier', 'martial', 'art', 'wrestling'],
 ['east', 'lothian'],
 ['indomalayan', 'realm'],
 ['albacete'],
 ['richard', 'fleischer'],
 ['cincinnati', 'red'],
 ['vyborg'],
 ['provincial', 'assembly', 'punjab'],
 ['hamburg'],
 ['ku', 'ring', 'gai', 'council'],
 ['hanoi'],
 ['northern', 'england'],
 ['nonpartisanism'],
 ['reserve', 'bank', 'india'],
 ['tony', 'hatch'],
 ['joan', 'arc'],
 ['chinese', 'american'],
 ['fox', 'broadcasting', 'company'],
 ['parramatta', 'eel'],
 ['duisburg'],
 ['oxford', 'university', 'press'],
 ['yukon'],
 ['tenant', 'purchase', 'scheme'],
 ['cthulhu', 'mythos'],
 ['cape', 'town'],
 ['phoenicia'],
 ['equestrianism'],
 ['taunton'],
 ['1947', 'ceylonese', 'parliamentary', 'election'],
 ['triathlon'],
 ['west', 'coast', 'main', 'line'],
 ['ghana'],
 ['manchester', 'metrolink'],
 ['darfur'],
 ['jim', 'crockett', 'promotion'],
 ['antoninus', 'pius'],
 ['isle', 'dog'],
 ['smith'],
 ['dewan', 'rakyat'],
 ['jennifer', 'rowe'],
 ['kaduna', 'state'],
 ['dahomey'],
 ['nakskov'],
 ['ciutat', 'vella'],
 ['ohio', 'river'],
 ['civil', 'engineering'],
 ['kaluga', 'oblast'],
 ['london', 'borough', 'croydon'],
 ['guillermo', 'del', 'toro'],
 ['germany'],
 ['french', 'polynesia'],
 ['chvrches'],
 ['mark', 'twain'],
 ['shaheed', 'bhagat', 'singh', 'nagar', 'district'],
 ['cyclades'],
 ['strabo'],
 ['milton', 'bradley', 'company'],
 ['occitan', 'language'],
 ['yenisei', 'river'],
 ['bangladesh'],
 ['lake', 'tahoe'],
 ['brandenburg'],
 ['jacob'],
 ['france', 'national', 'football', 'team'],
 ['veikkausliiga'],
 ['2015', 'canadian', 'federal', 'election'],
 ['kurdistan', 'region'],
 ['snk'],
 ['bbc', 'television'],
 ['united', 'state', 'department', 'defense'],
 ['prince', 'elector'],
 ['new', 'england'],
 ['rca'],
 ['qinghai'],
 ['chilean', 'war', 'independence'],
 ['daft', 'punk'],
 ['ghana', 'national', 'football', 'team'],
 ['chinese', 'buddhism'],
 ['florence'],
 ['samara', 'oblast'],
 ['yekaterinburg'],
 ['connecticut', 'river'],
 ['indonesia'],
 ['vancouver'],
 ['miami', 'marlin'],
 ['joseph', 'stalin'],
 ['travel', 'literature'],
 ['christian', 'democratic', 'appeal'],
 ['detroit', 'piston'],
 ['taranto'],
 ['port', 'washington', 'branch'],
 ['yellowknife'],
 ['sahrawi', 'arab', 'democratic', 'republic'],
 ['derry', 'gaa'],
 ['unionism', 'ireland'],
 ['soviet', 'armed', 'force'],
 ['los', 'angeles'],
 ['thomas', 'jefferson'],
 ['hal', 'roach'],
 ['cardiff', 'rfc'],
 ['government', 'kerala'],
 ['regent'],
 ['british', 'people'],
 ['american'],
 ['bell', 'system'],
 ['sabrina', 'carpenter'],
 ['danielle', 'steel'],
 ['lincolnshire'],
 ['printmaking'],
 ['vicenza'],
 ['eric', 'clapton'],
 ['dj', 'khaled'],
 ['county', 'donegal'],
 ['lockheed', 'corporation'],
 ['southern', 'rock'],
 ['george', 'gershwin'],
 ['salvation', 'army'],
 ['bell', 'lab'],
 ['list', 'north', 'carolina', 'state', 'park'],
 ['falklands', 'war'],
 ['gustav', 'mahler'],
 ['monster', 'movie'],
 ['cheap', 'trick'],
 ['chinese', 'taipei'],
 ['liechtenstein'],
 ['daily', 'mail'],
 ['solan', 'district'],
 ['goth'],
 ['british', 'empire'],
 ['scholastic', 'corporation'],
 ['ten', 'pin', 'bowling'],
 ['city', 'university', 'new', 'york'],
 ['vinnytsia', 'oblast'],
 ['centre', 'national', 'de', 'la', 'recherche', 'scientifique'],
 ['opeth'],
 ['neuwied'],
 ['tampere'],
 ['international', 'brigade'],
 ['north', 'london'],
 ['serbian', 'cyrillic', 'alphabet'],
 ['northeastern', 'ontario'],
 ['hackensack', 'river'],
 ['old', 'world', 'warbler'],
 ['danish', 'superliga'],
 ['niue'],
 ['puducherry'],
 ['namibia'],
 ['royal', 'rumble'],
 ['atlantic', 'league', 'professional', 'baseball'],
 ['bornholm'],
 ['alappuzha', 'district'],
 ['spongebob', 'squarepants'],
 ['royal', 'caribbean', 'international'],
 ['kim', 'jong', 'il'],
 ['keanu', 'reef'],
 ['argentina', 'national', 'football', 'team'],
 ['lloyd', 'bacon'],
 ['annette', 'andre'],
 ['british', 'film', 'institute'],
 ['second', 'polish', 'republic'],
 ['geology'],
 ['adventure', 'film'],
 ['jeddah'],
 ['amitabh', 'bachchan'],
 ['london', 'school', 'economics'],
 ['buryatia'],
 ['great', 'purge'],
 ['bandai', 'namco', 'entertainment'],
 ['trojan', 'war'],
 ['katy', 'perry'],
 ['vincent', 'van', 'gogh'],
 ['disneyland', 'paris'],
 ['islamism'],
 ['thor'],
 ['mersin'],
 ['clint', 'eastwood'],
 ['bulgarian', 'cup'],
 ['gauteng'],
 ['team17'],
 ['babur'],
 ['dili'],
 ['arabic', 'literature'],
 ['traditional', 'chinese', 'character'],
 ['knight'],
 ['vadodara'],
 ['javanese', 'language'],
 ['pope'],
 ['botany'],
 ['limehouse'],
 ['international', 'security', 'assistance', 'force'],
 ['barranquilla'],
 ['met', 'mother'],
 ['long', 'island'],
 ['infantry'],
 ['developing', 'country'],
 ['carmarthenshire'],
 ['province', 'sweden'],
 ['minnesota', 'wild'],
 ['roll', 'royce', 'limited'],
 ['county', 'fermanagh'],
 ['steve', 'ditko'],
 ['parthian', 'empire'],
 ['toyota', 'corolla'],
 ['great', 'depression'],
 ['postage', 'stamp'],
 ['napoleon', 'iii'],
 ['university', 'leicester'],
 ['master', 'universe'],
 ['albert', 'einstein'],
 ['patriotism'],
 ['international', 'boxing', 'organization'],
 ['massif', 'central'],
 ['perennial', 'plant'],
 ['fredric', 'march'],
 ['malagasy', 'language'],
 ['torah', 'reading'],
 ['union', 'navy'],
 ['nascar', 'xfinity', 'series'],
 ['tahiti'],
 ['lahore'],
 ['galois', 'group'],
 ['key', 'west'],
 ['john', 'b'],
 ['nagoya'],
 ['surabaya'],
 ['ecumenical', 'patriarch', 'constantinople'],
 ['guadeloupe'],
 ['welsh', 'government'],
 ['yugoslavia'],
 ['plain', 'indian'],
 ['australian', 'hip', 'hop'],
 ['peerage', 'scotland'],
 ['gambino', 'crime', 'family'],
 ['ice', 'hockey'],
 ['australian', 'defence', 'force'],
 ['korean', 'state', 'railway'],
 ['monash', 'university'],
 ['television', 'channel'],
 ['italian', 'renaissance'],
 ['hell'],
 ['fc', 'porto'],
 ['south', 'india'],
 ['government', 'ireland'],
 ['legislative', 'assembly', 'ontario'],
 ['region', 'southern', 'denmark'],
 ['zagreb'],
 ['coahuila'],
 ['assyrian', 'people'],
 ['percussion', 'instrument'],
 ['tuam'],
 ['private', 'university'],
 ['alicia', 'key'],
 ['fox', 'news'],
 ['aramaic'],
 ['quebec', 'major', 'junior', 'hockey', 'league'],
 ['osun', 'state'],
 ['pablo', 'picasso'],
 ['bangkok'],
 ['adriatic', 'sea'],
 ['niger', 'river'],
 ['local', 'government', 'area', 'western', 'australia'],
 ['lao'],
 ['carnatic', 'music'],
 ['new', 'mexico'],
 ['bangalore'],
 ['donald', 'duck'],
 ['minister', 'state'],
 ['royal', 'college', 'surgeon', 'ireland'],
 ['3000', 'metre', 'steeplechase'],
 ['lenape'],
 ['david', 'weber'],
 ['tagalog', 'language'],
 ['oklahoma', 'sooner', 'football'],
 ['university', 'toronto'],
 ['paris', 'foreign', 'mission', 'society'],
 ['directv'],
 ['hawthorn', 'football', 'club'],
 ['bromsgrove'],
 ['durham', 'university'],
 ['badulla'],
 ['posix'],
 ['altai', 'krai'],
 ['hmong', 'people'],
 ['motown'],
 ['freestyle', 'swimming'],
 ['kutaisi'],
 ['futurama'],
 ['thane'],
 ['order', 'st', 'michael', 'st', 'george'],
 ['royal', 'college', 'physician', 'edinburgh'],
 ['20th', 'century', 'fox'],
 ['finland'],
 ['tina', 'arena'],
 ['internet', 'forum'],
 ['muromachi', 'period'],
 ['county', 'dublin'],
 ['meath', 'gaa'],
 ['latvian', 'higher', 'league'],
 ['ecclesiastical', 'latin'],
 ['spiritualism'],
 ['akb48'],
 ['vice', 'president', 'united', 'state'],
 ['west', 'germanic', 'language'],
 ['tauranga'],
 ['1500', 'metre'],
 ['chukchi', 'sea'],
 ['video', 'game', 'publisher'],
 ['al', 'anbar', 'governorate'],
 ['grozny'],
 ['bryan', 'adam'],
 ['wwe', 'network'],
 ['aube'],
 ['stephen', 'hillenburg'],
 ['gascony'],
 ['rashtriya', 'swayamsevak', 'sangh'],
 ['abbasid', 'caliphate'],
 ['bbc', 'america'],
 ['reba', 'mcentire'],
 ['singapore'],
 ['keio', 'university'],
 ['antioquia', 'department'],
 ['koine', 'greek'],
 ['northern', 'cyprus'],
 ['travel', 'channel'],
 ['slade'],
 ['eastern', 'europe'],
 ['university', 'nottingham'],
 ['cinema', 'philippine'],
 ['cumbernauld'],
 ['congregation', 'christian', 'brother'],
 ['montreux'],
 ['davis', 'cup'],
 ['ulyanovsk', 'oblast'],
 ['persian', 'gulf'],
 ['planetary', 'habitability'],
 ['centre', 'right', 'politics'],
 ['order', 'ontario'],
 ['role', 'playing', 'video', 'game'],
 ['dutch', 'golden', 'age', 'painting'],
 ['herbaceous', 'plant'],
 ['ba', 'rhin'],
 ['physician'],
 ['gros', 'de', 'vaud', 'district'],
 ['usb'],
 ['tom', 'jerry'],
 ['mendoza', 'province'],
 ['exeter', 'chief'],
 ['cupressaceae'],
 ['book', 'judge'],
 ['english', 'study'],
 ['mysticism'],
 ['moravian', 'silesian', 'region'],
 ['volvo'],
 ['belarusian'],
 ['philippine', 'basketball', 'association'],
 ['sui', 'dynasty'],
 ['dalai', 'lama'],
 ['tigris'],
 ['rigveda'],
 ['political', 'radicalism'],
 ['apocalyptic', 'post', 'apocalyptic', 'fiction'],
 ['chinese', 'folk', 'religion'],
 ['trajan'],
 ['mark', 'millar'],
 ['romeo', 'juliet'],
 ['grand', 'cayman'],
 ['witney'],
 ['palmerston', 'north'],
 ['college', 'board'],
 ['sam', 'raimi'],
 ['berber'],
 ['def', 'jam', 'recording'],
 ['bahamas'],
 ['old', 'irish'],
 ['stockholm', 'municipality'],
 ['szeged'],
 ['london', 'borough', 'haringey'],
 ['ahvaz'],
 ['vilnius'],
 ['nanchang'],
 ['sarawak'],
 ['mainland', 'china'],
 ['telugu', 'language'],
 ['amazon', 'river'],
 ['san', 'francisco', 'bay'],
 ['john', 'baptist'],
 ['civil', 'political', 'right'],
 ['gaeltacht'],
 ['palatine', 'hungary'],
 ['malacca'],
 ['sahara'],
 ['rascal', 'flatts'],
 ['eastern', 'wu'],
 ['steven', 'spielberg'],
 ['university', 'texas', 'austin'],
 ['subroutine'],
 ['nelson', 'rockefeller'],
 ['hiroshima'],
 ['w'],
 ['canterbury', 'bankstown', 'bulldog'],
 ['luhansk', 'oblast'],
 ['gracillariidae'],
 ['mendip', 'hill'],
 ['derbyshire'],
 ['free', 'state', 'prussia'],
 ['olympique', 'de', 'marseille'],
 ['la', 'palma'],
 ['smolensk'],
 ['cuban', 'revolution'],
 ['fa', 'cup', 'final'],
 ['distinguished', 'service', 'order'],
 ['luc', 'besson'],
 ['mid', 'north'],
 ['sarah', 'jane', 'adventure'],
 ['island', 'record'],
 ['rice', 'university'],
 ['thirteen', 'colony'],
 ['treat', 'williams'],
 ['riverside', 'record'],
 ['greater', 'western', 'sydney'],
 ['babylon'],
 ['lleida'],
 ['department', 'honduras'],
 ['volhynia'],
 ['guinness'],
 ['new', 'york', 'harbor'],
 ['gothic', 'fiction'],
 ['world', 'hockey', 'association'],
 ['ganges'],
 ['ypres', 'salient'],
 ['episcopal', 'polity'],
 ['royal', 'navy'],
 ['korn'],
 ['united', 'state', 'dollar'],
 ['minnesota', 'twin'],
 ['prussian', 'navy'],
 ['l'],
 ['vangelis'],
 ['virginia', 'military', 'institute'],
 ['northern', 'ireland', 'executive'],
 ['deccan', 'plateau'],
 ['akira', 'toriyama'],
 ['action', 'adventure', 'game'],
 ['progressive', 'conservative', 'party', 'canada'],
 ['morobe', 'province'],
 ['queensland'],
 ['miyagi', 'prefecture'],
 ['senate', 'philippine'],
 ['federico', 'fellini'],
 ['australian', 'national', 'university'],
 ['rebellion'],
 ['biographical', 'film'],
 ['lublin', 'voivodeship'],
 ['louis', 'xiv', 'france'],
 ['united', 'state', 'declaration', 'independence'],
 ['bremen'],
 ['duke', 'aquitaine'],
 ['plymouth'],
 ['ian', 'mcewan'],
 ['stephen', 'king'],
 ['professional', 'dart', 'corporation'],
 ['international', 'wrestling', 'revolution', 'group'],
 ['carnian'],
 ['tver', 'oblast'],
 ['bhutan'],
 ['ringo', 'starr'],
 ['algonquian', 'language'],
 ['double', 'bass'],
 ['ellesmere', 'island'],
 ['albert', 'pyun'],
 ['faith'],
 ['new', 'york', 'metropolitan', 'area'],
 ['fc', 'dallas'],
 ['olympique', 'lyonnais'],
 ['edmonton'],
 ['braunschweig'],
 ['cieszyn', 'county'],
 ['bill', 'murray'],
 ['kingdom', 'romania'],
 ['armoured', 'warfare'],
 ['jagiellonian', 'university'],
 ['swiss', 'air', 'force'],
 ['hawick'],
 ['poitier'],
 ['polish', 'language'],
 ['middle', 'tennessee'],
 ['jewish', 'philosophy'],
 ['greek', 'resistance'],
 ['mississauga'],
 ['south', 'los', 'angeles'],
 ['river', 'state'],
 ['binghamton', 'university'],
 ['boston', 'red', 'sox'],
 ['leeds', 'rhino'],
 ['altai', 'mountain'],
 ['piedmont', 'triad'],
 ['nairobi'],
 ['east', 'dunbartonshire'],
 ['hampton', 'road'],
 ['hungarian', 'revolution', '1956'],
 ['social', 'liberalism'],
 ['england', 'cricket', 'team'],
 ['actinopterygii'],
 ['downtown', 'calgary'],
 ['greyhound', 'racing', 'united', 'kingdom'],
 ['puntland'],
 ['sierra', 'madre', 'occidental'],
 ['parliament', 'england'],
 ['streatham'],
 ['tampa', 'bay', 'viper'],
 ['tristan', 'da', 'cunha'],
 ['charles', 'england'],
 ['president', 'colombia'],
 ['riemannian', 'geometry'],
 ['australian', 'rule', 'football'],
 ['english', 'rugby', 'union', 'system'],
 ['twickenham'],
 ['felix', 'cat'],
 ['university', 'denver'],
 ['epiphyte'],
 ['wall', 'street', 'journal'],
 ['daraa'],
 ['lepidoptera'],
 ['lusitania'],
 ['eerste', 'divisie'],
 ['columbidae'],
 ['cenozoic'],
 ['hillary', 'clinton'],
 ['woody', 'woodpecker'],
 ['oakland', 'athletics'],
 ['lake', 'district', 'national', 'park'],
 ['dnipropetrovsk', 'oblast'],
 ['chemistry'],

In [10]:
from rank_bm25 import BM25Okapi
bm25 = BM25Okapi(lemmatized_tokenized_docs)

In [11]:
scores_of_all_queries = []

for query in lesked_queries:
    scores_of_all_queries.append(bm25.get_scores(query))

In [12]:
from collections import defaultdict
from helper import Scoredoc

doc_dict = defaultdict(str)

for i, doc in enumerate(dataset.docs_iter()):
    doc_dict[i] = doc.doc_id

doc_dict = dict(doc_dict)

qrels_dict = defaultdict(list)

for qrel in dataset.qrels_iter():
    qrels_dict[qrel.query_id].append(qrel.doc_id)

qrels_dict = dict(qrels_dict)

score_doc_dict = defaultdict(list)

for scoreddoc in dataset.scoreddocs_iter():
    doc_id = scoreddoc.doc_id
    score = scoreddoc.score

    scoreddoc_object = Scoredoc(doc_id, score)

    score_doc_dict[scoreddoc.query_id].append(scoreddoc_object)

score_doc_dict = dict(score_doc_dict)

print("Necessary dicts created!")

Necessary dicts created!

In [13]:
query_ids = [query.query_id for query in dataset.queries_iter()]
query_ids

['123839',
 '188629',
 '13898',
 '316959',
 '515031',
 '123783',
 '4332',
 '9591',
 '114982',
 '563603',
 '104206',
 '1580851',
 '23678',
 '37480',
 '109454',
 '544250',
 '12519',
 '115015',
 '84287',
 '24998',
 '11925',
 '643',
 '113075',
 '1250387',
 '72012',
 '167865',
 '1425120',
 '24883',
 '27200',
 '136856',
 '6031',
 '1313191',
 '187115',
 '84110',
 '208234',
 '6431',
 '10799',
 '1417144',
 '32512',
 '677637',
 '97937',
 '113765',
 '12900',
 '1294909',
 '73745',
 '11692',
 '22173',
 '76662',
 '164301',
 '23344',
 '9367',
 '592217',
 '98546',
 '98175',
 '15189',
 '1256',
 '1815937',
 '1249076',
 '80274',
 '38489',
 '11311',
 '4754',
 '257711',
 '141668',
 '100895',
 '32945',
 '112321',
 '133725',
 '424464',
 '523456',
 '1327515',
 '12101',
 '9739',
 '189869',
 '143444',
 '78940',
 '12527',
 '327199',
 '7707',
 '97455',
 '1262433',
 '488875',
 '74026',
 '358108',
 '95179',
 '7862',
 '151797',
 '92980',
 '100876',
 '238228',
 '107755',
 '32539',
 '12953',
 '24843',
 '119528',
 '30765',
 '134772',
 '27711',
 '361260',
 '17874',
 '3524',
 '75902',
 '809894',
 '126362',
 '288208',
 '406254',
 '240663',
 '34848',
 '195113',
 '264822',
 '8387',
 '186363',
 '165761',
 '76875',
 '605155',
 '17836',
 '83566',
 '132697',
 '1563',
 '23924',
 '1433',
 '29737',
 '26758',
 '19717',
 '7870',
 '16093',
 '34844',
 '2234455',
 '382531',
 '12252',
 '11446',
 '21027',
 '1370698',
 '113657',
 '3348',
 '217425',
 '197576',
 '129397',
 '257126',
 '67592',
 '93136',
 '892237',
 '20605',
 '1219',
 '389032',
 '10656',
 '1778',
 '108160',
 '964897',
 '94266',
 '13744',
 '13539',
 '407598',
 '97620',
 '203795',
 '356090',
 '112731',
 '714608',
 '88181',
 '87960',
 '96791',
 '172084',
 '1836051',
 '14393',
 '1559299',
 '82801',
 '969771',
 '125685',
 '101336',
 '78856',
 '126985',
 '231130',
 '197161',
 '94693',
 '1339737',
 '273381',
 '73398',
 '179677',
 '90354',
 '1608685',
 '446634',
 '1595',
 '73102',
 '494392',
 '94832',
 '24349',
 '12374',
 '151391',
 '584158',
 '15282',
 '434927',
 '21969',
 '15987',
 '13776',
 '768304',
 '132575',
 '833105',
 '76345',
 '537',
 '181536',
 '4215',
 '17227',
 '97781',
 '1589',
 '119663',
 '1336894',
 '1568489',
 '133700',
 '147768',
 '674995',
 '1047896',
 '6368',
 '172053',
 '1045273',
 '80687',
 '1263864',
 '81739',
 '113925',
 '73285',
 '27399',
 '35101',
 '5570',
 '14758',
 '10792',
 '726995',
 '17814',
 '908',
 '85435',
 '79941',
 '140552',
 '145807',
 '107616',
 '13801',
 '357261',
 '34865',
 '2259',
 '6213',
 '72576',
 '163527',
 '75654',
 '29687',
 '1283640',
 '1703622',
 '324633',
 '37756',
 '1237543',
 '342167',
 '1058358',
 '248154',
 '330931',
 '163736',
 '488869',
 '20603',
 '8055',
 '109832',
 '9332',
 '204974',
 '339255',
 '22113',
 '94641',
 '10825',
 '71636',
 '2078947',
 '146007',
 '11481',
 '1282373',
 '605568',
 '276580',
 '190225',
 '26652',
 '14325',
 '23815',
 '119102',
 '17755',
 '29896',
 '26093',
 '1272415',
 '94442',
 '260160',
 '152382',
 '883324',
 '71191',
 '178216',
 '1408773',
 '6047',
 '1410732',
 '37218',
 '22295',
 '12601',
 '15200',
 '14027',
 '545390',
 '81411',
 '1324050',
 '8669',
 '21961',
 '612261',
 '389274',
 '39839',
 '90512',
 '185712',
 '302505',
 '2623',
 '1343759',
 '725960',
 '5554',
 '180826',
 '22170',
 '203549',
 '270009',
 '110384',
 '296861',
 '6835',
 '19342',
 '18363',
 '226344',
 '37955',
 '19145',
 '14445',
 '605066',
 '2228',
 '2613',
 '1742574',
 '28296',
 '100963',
 '561358',
 '13460',
 '85285',
 '4925',
 '104339',
 '183397',
 '156457',
 '284',
 '34937',
 '76048',
 '164182',
 '411597',
 '422208',
 '3522',
 '73430',
 '113428',
 '9399',
 '2243',
 '157351',
 '2842',
 '377416',
 '4855',
 '4397',
 '1846628',
 '75969',
 '635597',
 '2581',
 '20437',
 '76039',
 '9356',
 '22213',
 '1250',
 '70969',
 '1349',
 '6644',
 '103434',
 '384474',
 '1669212',
 '596568',
 '98507',
 '128283',
 '815972',
 '5816',
 '1344825',
 '11029',
 '82288',
 '639167',
 '80536',
 '254180',
 '97274',
 '4722',
 '159099',
 '25706',
 '104011',
 '6033',
 '14011',
 '4616',
 '6482',
 '310032',
 '25193',
 '27720',
 '21972',
 '633954',
 '37908',
 '1870966',
 '487985',
 '105462',
 '510206',
 '7560',
 '12705',
 '117619',
 '305484',
 '1090430',
 '1777480',
 '1268117',
 '1289085',
 '1338779',
 '1817436',
 '24242',
 '20898',
 '16880',
 '37945',
 '4085',
 '2130523',
 '18091',
 '19675',
 '78817',
 '5400',
 '32411',
 '1322',
 '188952',
 '4720',
 '25242',
 '763957',
 '84315',
 '107129',
 '7407',
 '83325',
 '526775',
 '5204',
 '1787',
 '112402',
 '92302',
 '2986',
 '161918',
 '71995',
 '18192',
 '85636',
 '26444',
 '6390',
 '134543',
 '923020',
 '834741',
 '184241',
 '88748',
 '391276',
 '8899',
 '26219',
 '8938',
 '166642',
 '24861',
 '1352',
 '16006',
 '473460',
 '210583',
 '75859',
 '6879',
 '152885',
 '238499',
 '473275',
 '196310',
 '5896',
 '5002',
 '226743',
 '110572',
 '543',
 '26103',
 '208058',
 '68416',
 '895072',
 '12773',
 '1182701',
 '13957',
 '28752',
 '6227',
 '119284',
 '273555',
 '17203',
 '609350',
 '117495',
 '1641154',
 '1705',
 '19435',
 '154661',
 '108269',
 '7026',
 '165900',
 '131685',
 '9643',
 '1515',
 '34957',
 '88458',
 '152413',
 '479595',
 '7647',
 '6264',
 '29411',
 '75908',
 '71994',
 '27795',
 '704769',
 '2274',
 '12626',
 '639949',
 '207327',
 '1274160',
 '10688',
 '24454',
 '128712',
 '181363',
 '80',
 '10413',
 '120973',
 '145081',
 '206583',
 '24782',
 '1365055',
 '317887',
 '740767',
 '73024',
 '25238',
 '56872',
 '5219',
 '42749',
 '1444121',
 '24145',
 '93598',
 '24066',
 '5065',
 '123063',
 '14451',
 '301383',
 '197016',
 '141405',
 '159773',
 '6138',
 '26051',
 '1712787',
 '73768',
 '12699',
 '121064',
 '681120',
 '81877',
 '197769',
 '173023',
 '194810',
 '370139',
 '21892',
 '77940',
 '108305',
 '10456',
 '243438',
 '352646',
 '23335',
 '4559',
 '762',
 '95338',
 '422214',
 '10221',
 '22149',
 '1403468',
 '9022',
 '70754',
 '7353',
 '79109',
 '9106',
 '2032420',
 '1270810',
 '102991',
 '366863',
 '750376',
 '98133',
 '1194068',
 '13415',
 '764844',
 '849899',
 '448622',
 '927392',
 '1063349',
 '128187',
 '1614640',
 '477200',
 '9748',
 '157369',
 '22800',
 '80219',
 '1403378',
 '146323',
 '97591',
 '80765',
 '125608',
 '351608',
 '81103',
 '4334',
 '21439',
 '113621',
 '90496',
 '2547',
 '488858',
 '217759',
 '189034',
 '90382',
 '814731',
 '14032',
 '75643',
 '1662573',
 '479233',
 '187769',
 '38035',
 '155722',
 '70941',
 '88077',
 '1683175',
 '30883',
 '289837',
 '28823',
 '34394',
 '19625',
 '110332',
 '92668',
 '11644',
 '133621',
 '86063',
 '1731034',
 '109201',
 '236830',
 '86499',
 '15015',
 '1467096',
 '518649',
 '1529682',
 '389454',
 '20213',
 '97540',
 '159101',
 '10524',
 '466077',
 '374708',
 '135038',
 '129387',
 '593570',
 '99196',
 '32938',
 '9755',
 '1421273',
 '13706',
 '226734',
 '100123',
 '1640988',
 '133233',
 '1608',
 '1264172',
 '1594725',
 '157511',
 '13850',
 '15277',
 '131074',
 '17237',
 '3249',
 '13326',
 '1814473',
 '1156870',
 '25280',
 '323708',
 '13016',
 '222183',
 '10968',
 '109940',
 '129732',
 '118690',
 '179517',
 '12198',
 '19019',
 '434541',
 '1248',
 '319553',
 '252889',
 '138439',
 '35022',
 '182032',
 '13954',
 '136151',
 '12030',
 '21583',
 '15741',
 '489',
 '11435',
 '6649',
 '14868',
 '37861',
 '248820',
 '1727920',
 '121664',
 '377463',
 '110662',
 '11420',
 '13685',
 '1685919',
 '1274158',
 '23083',
 '14139',
 '166211',
 '161907',
 '721863',
 '110381',
 '27264',
 '672596',
 '161341',
 '114943',
 '37957',
 '108695',
 '479110',
 '129109',
 '16266',
 '399420',
 '759288',
 '34119',
 '10963',
 '14608',
 '283712',
 '266655',
 '203968',
 '1313526',
 '7836',
 '119662',
 '140457',
 '1276229',
 '110281',
 '5195',
 '100816',
 '5103',
 '429845',
 '4088',
 '11072',
 '17962',
 '1254149',
 '8394',
 '305914',
 '665122',
 '13888',
 '126682',
 '133726',
 '154029',
 '1116',
 '172058',
 '55300',
 '374325',
 '23079',
 '2120001',
 '114890',
 '4831',
 '111289',
 '165585',
 '214810',
 '126571',
 '7755',
 '13630',
 '918270',
 '83187',
 '9865',
 '122086',
 '11428',
 '314278',
 '1062661',
 '503034',
 '155036',
 '446428',
 '10976',
 '20434',
 '3544',
 '25445',
 '717881',
 '71381',
 '117555',
 '682338',
 '245828',
 '35568',
 '20021',
 '606000',
 '38408',
 '114257',
 '332492',
 '15319',
 '229404',
 '5781',
 '20183',
 '9603',
 '192096',
 '79820',
 '411516',
 '77789',
 '1313521',
 '388950',
 '109985',
 '1585',
 '264823',
 '22226',
 '164723',
 '9041',
 '71649',
 '88210',
 '128218',
 '212288',
 '211013',
 '79',
 '438884',
 '1099352',
 '99045',
 '274498',
 '134029',
 '35023',
 '2402726',
 '13373',
 '2938',
 '103786',
 '88775',
 '809',
 '1032451',
 '35036',
 '89567',
 '170548',
 '22672',
 '82044',
 '123639',
 '20906',
 '7769',
 '385089',
 '24704',
 '2266',
 '677582',
 '90428',
 '9454',
 '211320',
 '161909',
 '1964',
 '115785',
 '409207',
 '232564',
 '9137',
 '9492',
 '497039',
 '78081',
 '2070217',
 '77289',
 '7611',
 '235972',
 '19574',
 '70946',
 '956',
 '179671',
 '11448',
 '805510',
 '36957',
 '228293',
 '23327',
 '19017',
 '344485',
 '1558158',
 '76587',
 '26910',
 '1148665',
 '1932345',
 '555050',
 '121447',
 '73560',
 '151629',
 '23266',
 '4647',
 '101622',
 '112935',
 '27673',
 '18788',
 '32955',
 '242902',
 '90776',
 '105401',
 '843489',
 '18207',
 '36683',
 '15712',
 '14076',
 '9681',
 '219237',
 '1031987',
 '6502',
 '106031',
 '225142',
 '15420',
 '84194',
 '133570',
 '6815',
 '1357000',
 '205081',
 '15850',
 '197853',
 '14293',
 '457924',
 '128345',
 '1407356',
 '103335',
 '23918',
 '269840',
 '161933',
 '20681',
 '90437',
 '114728',
 '129948',
 '126860',
 '9765',
 '2113',
 '748790',
 '17645',
 '120677',
 '108913',
 '88958',
 '15351',
 '396742',
 '182986',
 '10946',
 '35538',
 '14314',
 '479034',
 '22120',
 '488649',
 '7022',
 '133309',
 '37830',
 '102670',
 '233552',
 '92119',
 '79532',
 '146760',
 '15425',
 '8877',
 '448',
 '1117181',
 '132661',
 '2473',
 '164285',
 '11145',
 '1407349',
 '9379',
 '1909580',
 '111964',
 '10329',
 '18137',
 '13676',
 '26442',
 '6326',
 '75046',
 '746557',
 '11138',
 '15463',
 '22402',
 '23936',
 '32442',
 '7607',
 '103543',
 '1900776',
 '1973651',
 '7276',
 '1387',
 '5590',
 '9780',
 '8882',
 '81156',
 '189807',
 '87882',
 '17047',
 '864775',
 '167358',
 '97923',
 '25611',
 '1407055',
 '213595',
 '2175',
 '17512',
 '21907',
 '781',
 '1584920',
 '187188',
 '358658',
 '189862',
 '8610',
 '239821',
 '97945',
 '119644',
 '337441',
 '80187',
 '15355',
 '1310225',
 '254991',
 '91502',
 '1205882',
 '88824',
 '120183',
 '106926',
 '4383',
 '272146',
 '127768',
 '1313596',
 '1522224',
 '25771',
 '23005',
 '5326',
 ...]

In [14]:
scores_of_all_queries

[array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 7.71542974, 0.        , ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([ 0.        ,  0.        , 34.63292927, ...,  0.        ,
         0.        ,  0.        ], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 3.90094591, 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([14.65602297,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 3.74912202,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        8.19939645], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 3.50826776, ..., 0.        , 3.85614806,
        3.84164519], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 4.24064848,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 3.50826776, ..., 0.        , 3.85614806,
        3.84164519], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        8.77160353], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([6.11360788, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        8.19939645], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 6.11017902, 0.        , ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 8.42623208, 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 3.50826776, ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0.       , 9.9415872, 0.       , ..., 0.       , 0.       ,
        0.       ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 3.60150495,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 3.50826776, ..., 0.        , 3.85614806,
        3.84164519], shape=(369721,)),
 array([7.27088024, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([9.54829028, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([1.70185172, 3.91102417, 0.        , ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        8.19939645], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([ 0.        ,  0.        , 16.39561238, ...,  9.80851874,
         0.        ,  0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 8.39217622, 0.        , ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 9.18842089, ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0.        , 0.        , 3.25994644, ..., 0.        , 3.43224242,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        6.89422954], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 6.20727856, 0.        , ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 9.10604227, 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        8.77160353], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([ 0.        ,  0.        , 15.65866959, ...,  0.        ,
         0.        ,  0.        ], shape=(369721,)),
 array([0.        , 0.        , 3.50826776, ..., 0.        , 3.85614806,
        3.84164519], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        , 14.15057712], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 5.27199766, ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([ 0.        ,  0.        , 19.90388015, ...,  0.        ,
         0.        ,  0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([ 0.        ,  0.        ,  0.        , ...,  0.        ,
        13.82574574,  0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        4.75145879], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 4.24064848,
        0.        ], shape=(369721,)),
 array([ 0.        ,  0.        ,  0.        , ...,  0.        ,
        10.87287224,  0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([ 0.        ,  0.        , 21.49308558, ...,  0.        ,
         0.        ,  0.        ], shape=(369721,)),
 array([0.        , 8.39217622, 0.        , ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 3.85614806,
        3.84164519], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([ 0.       , 15.0649568,  0.       , ...,  0.       ,  0.       ,
         0.       ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([ 0.        ,  0.        , 16.39561238, ...,  0.        ,
         0.        ,  0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        4.75145879], shape=(369721,)),
 array([0.        , 8.39217622, 0.        , ..., 0.        , 0.        ,
        9.78141058], shape=(369721,)),
 array([12.37643539,  0.        , 16.39561238, ...,  0.        ,
         0.        ,  0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([ 0.        ,  0.        , 11.68663828, ...,  0.        ,
         3.85614806, 13.65004123], shape=(369721,)),
 array([0.        , 0.        , 3.50826776, ..., 0.        , 3.85614806,
        3.84164519], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 1.28538269,
        1.2805484 ], shape=(369721,)),
 array([41.40036841,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([8.18905714, 9.9415872 , 0.        , ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 3.50826776, ..., 0.        , 3.85614806,
        3.84164519], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 7.46785289, 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([ 0.        ,  0.        ,  0.        , ...,  0.        ,
        10.87287224,  0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 6.37569816,
        0.        ], shape=(369721,)),
 array([7.80888959, 1.12579129, 4.75397984, ..., 2.54749954, 0.74277133,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 5.14137622, ..., 5.33258459, 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([ 0.        ,  0.        , 16.39561238, ...,  0.        ,
         0.        ,  0.        ], shape=(369721,)),
 array([0.        , 6.20727856, 0.        , ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([9.21890502, 0.        , 0.90186672, ..., 6.532786  , 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 3.50826776, ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([ 0.        ,  0.        , 16.39561238, ...,  0.        ,
         0.        ,  0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 1.28538269,
        1.2805484 ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([ 0.       ,  0.       ,  0.       , ...,  0.       , 14.6265889,
         0.       ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        9.78141058], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([ 0.        , 12.16218905,  7.62151851, ...,  0.        ,
         0.        ,  0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 5.60302354, 0.        , ..., 0.        , 0.        ,
        0.        ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 1.28538269,
        1.2805484 ], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        , 17.07913876], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.      , 0.      , 0.      , ..., 0.      , 3.947767, 0.      ],
       shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        8.77160353], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0., 0., 0., ..., 0., 0., 0.], shape=(369721,)),
 array([0.        , 0.        , 0.        , ..., 0.        , 5.35201503,
        5.33188625], shape=(369721,)),
 array([2.04973538, 7.18454504, 0.        , ..., 2.05735837, 0.        ,

In [15]:
from collections import defaultdict

query_id_vs_text = defaultdict(str)

for query in dataset.queries_iter():
    query_id_vs_text[query.query_id] = query.text

In [16]:
import gc
del dataset
del tokenized
del lematizer
del bm25
gc.collect()

0

In [17]:
del lemmatized_tokenized_docs
del lemmatized_tokenized_queries
del lemmatized_words
del query_tokenized
gc.collect()

0

In [18]:
import numpy as np
query_id_and_its_doc_for_10 = defaultdict(list)

for i in range(len(query_ids)):
    found_doc_list = []
    similarity = scores_of_all_queries[i]

    index_of_found_docs = np.where(similarity > 0)[0]

    for index in list(index_of_found_docs):
        found_doc_list.append((similarity[index], doc_dict[index]))

    if len(found_doc_list) <= 10:
        for mytuple in found_doc_list:
            query_id_and_its_doc_for_10[query_ids[i]].append(mytuple[1])
    else:
        for mytuple in sorted(found_doc_list, reverse=True):
            query_id_and_its_doc_for_10[query_ids[i]].append(mytuple[1])

            if len(query_id_and_its_doc_for_10[query_ids[i]]) == 10:
                break

In [19]:
query_id_and_its_doc_for_10

defaultdict(list,
            {'123839': ['806300',
              '123839',
              '806326',
              '836567',
              '806075',
              '1793430',
              '806263',
              '799188',
              '1727316',
              '1901730'],
             '188629': ['188629',
              '2191096',
              '2185399',
              '2304431',
              '1046396',
              '1990307',
              '2296288',
              '2290269',
              '533438',
              '62956'],
             '13898': ['13898',
              '2336616',
              '1921403',
              '1874948',
              '2213954',
              '2108627',
              '2248373',
              '525283',
              '2216860',
              '1453647'],
             '316959': ['316959',
              '348869',
              '1836641',
              '2156815',
              '1326263',
              '930698',
              '395421',
              '918373',
              '2215542',
              '1525222'],
             '515031': ['887826',
              '832086',
              '1842084',
              '1176215',
              '515031',
              '1569953',
              '836749',
              '1376470',
              '1283126',
              '1125994'],
             '123783': ['1210005',
              '1209576',
              '1209561',
              '2200269',
              '1630942',
              '1675282',
              '123783',
              '1214652',
              '579503',
              '2260318'],
             '4332': ['4332',
              '1991105',
              '1516841',
              '989116',
              '2251834',
              '1815319',
              '816040',
              '159520',
              '1863594',
              '1090555'],
             '9591': ['908435',
              '138626',
              '2416624',
              '390102',
              '1898638',
              '2250838',
              '143444',
              '1966629',
              '1483036',
              '1759147'],
             '114982': ['1341103',
              '2444081',
              '1191721',
              '917379',
              '2305216',
              '2305139'],
             '563603': ['390174',
              '2207107',
              '373237',
              '12846',
              '349302',
              '563603',
              '394294',
              '270469',
              '1233547',
              '219324'],
             '104206': ['104018',
              '2096056',
              '1673999',
              '1281151',
              '1858334',
              '200511',
              '149391',
              '985149',
              '983967',
              '418789'],
             '1580851': ['1549040',
              '1528190',
              '1126483',
              '1298253',
              '1255868',
              '461900',
              '206012',
              '167480',
              '758452',
              '307243'],
             '23678': ['23678',
              '1708807',
              '1537291',
              '1815535',
              '349822',
              '2200763',
              '1771004',
              '608269',
              '342272',
              '1691970'],
             '37480': ['246157',
              '77763',
              '1017336',
              '154685',
              '702790',
              '1589436',
              '845773',
              '1027733',
              '1571906',
              '305953'],
             '109454': ['109454',
              '1450070',
              '2045342',
              '2100641',
              '2069260',
              '1280868',
              '1648909',
              '82801',
              '702222',
              '1746976'],
             '544250': ['544250',
              '2095411',
              '682657',
              '630265',
              '1322312',
              '1937433',
              '2347517',
              '466841',
              '730726',
              '1458026'],
             '12519': ['1374322',
              '1091625',
              '869618',
              '1005711',
              '1739665',
              '12519',
              '4538',
              '175050',
              '82510',
              '2264749'],
             '115015': ['2202113',
              '1351327',
              '115015',
              '1978384',
              '2133651',
              '458160',
              '1591706',
              '2315210',
              '2215175',
              '1290856'],
             '84287': ['189580',
              '1095591',
              '1422745',
              '1571607',
              '1427890',
              '891543',
              '1907688',
              '84287',
              '1308897',
              '2332777'],
             '24998': ['1409082',
              '2149920',
              '1394401',
              '1941659',
              '2339264',
              '1323056',
              '917063',
              '59107',
              '1553086',
              '2407468'],
             '11925': ['580492',
              '1148523',
              '2108567',
              '975838',
              '232799',
              '2207088',
              '555629',
              '1355039',
              '1687991',
              '1595836'],
             '643': ['1115256',
              '643',
              '1769441',
              '88810',
              '33435',
              '2246138',
              '1495790',
              '1892260',
              '1786083',
              '143150'],
             '113075': ['113075',
              '100596',
              '21628',
              '1217819',
              '1733437',
              '572485',
              '344421',
              '1704209',
              '1043682',
              '2334418'],
             '1250387': ['1727869',
              '2195293',
              '297902',
              '1683108',
              '599253',
              '1207201',
              '1250387',
              '2217046',
              '1589325',
              '1133175'],
             '72012': ['72012',
              '111443',
              '111938',
              '103174',
              '2371473',
              '111442',
              '191745',
              '1806360',
              '863599',
              '1876814'],
             '167865': ['167865',
              '385342',
              '1964134',
              '221442',
              '1846426',
              '2229172',
              '299025',
              '1303512',
              '737868',
              '1820245'],
             '1425120': ['2316655',
              '1083694',
              '836205',
              '1737940',
              '1425120',
              '2198169',
              '12523',
              '546380',
              '2348752',
              '2147182'],
             '24883': ['24883',
              '1394026',
              '2172776',
              '2393527',
              '1877437',
              '1734607',
              '2355895',
              '647047',
              '2178291',
              '1603081'],
             '27200': ['1352641',
              '764959',
              '1834661',
              '1493043',
              '923643',
              '1833536',
              '2389598',
              '148043',
              '2314961',
              '1750849'],
             '136856': ['136856',
              '1445582',
              '2272554',
              '2037574',
              '817838',
              '2312312',
              '2059311',
              '506684',
              '2444515',
              '357239'],
             '6031': ['123675',
              '117413',
              '975229',
              '23531',
              '1466349',
              '1298646',
              '306781',
              '1620199',
              '623176',
              '101000'],
             '1313191': ['1313191',
              '94675',
              '2133060',
              '216370',
              '1641900',
              '2288854',
              '443142',
              '436036',
              '2158753',
              '1198513'],
             '187115': ['187115',
              '1464470',
              '975998',
              '1012100',
              '964282',
              '2449992',
              '70941',
              '2246466',
              '1301843',
              '2442546'],
             '84110': ['1924159',
              '1670119',
              '1395090',
              '1987297',
              '1936088',
              '1935764',
              '2087053',
              '1052069',
              '1275995',
              '306509'],
             '208234': ['208234',
              '263739',
              '1685838',
              '1629265',
              '795404',
              '1697013',
              '1665946',
              '1278779',
              '871878',
              '2375071'],
             '6431': ['6431',
              '5400',
              '32256',
              '713517',
              '273681',
              '556999',
              '603672',
              '336647',
              '510840',
              '872358'],
             '10799': ['10799',
              '313344',
              '325859',
              '242372',
              '1439685',
              '1294553',
              '1653609',
              '164172',
              '1415399',
              '684799'],
             '1417144': ['2168362',
              '1593467',
              '1599859',
              '1122564',
              '1077838',
              '2077423',
              '1008029',
              '424500',
              '491879',
              '1861636'],
             '32512': ['827758',
              '2052704',
              '1454938',
              '1975061',
              '1135484',
              '168470',
              '4128',
              '758040',
              '2143778',
              '1990265'],
             '677637': ['1797233',
              '1364109',
              '1214837',
              '311557',
              '122359',
              '322640',
              '424385',
              '1102365',
              '1577989',
              '677637'],
             '97937': ['1096276',
              '1604490',
              '902154',
              '1383368',
              '2130224',
              '1885628',
              '2391516',
              '1206431',
              '2226421',
              '2194096'],
             '113765': ['624238',
              '557100',
              '445999',
              '1132759',
              '1807222',
              '1276605',
              '1737172',
              '707880',
              '155254',
              '1697156'],
             '12900': ['925414',
              '379149',
              '171087',
              '2315670',
              '1150042',
              '889438',
              '984273',
              '405319',
              '326390',
              '740408'],
             '1294909': ['127179',
              '1437752',
              '2413308',
              '140477',
              '1076256',
              '160522',
              '75643',
              '129833',
              '1395726',
              '1346200'],
             '73745': ['144080',
              '55300',
              '179605',
              '167000',
              '941681',
              '146797',
              '230974',
              '1160423',
              '505451',
              '1714964'],
             '11692': ['11692',
              '1869155',
              '2158113',
              '1789375',
              '938197',
              '1664266',
              '186017',
              '212300',
              '1471707',
              '378055'],
             '22173': ['22173',
              '1996894',
              '2451809',
              '2333975',
              '1652701',
              '1481423',
              '1405463',
              '1081052',
              '2296579',
              '161142'],
             '76662': ['1508270',
              '1887855',
              '765779',
              '1503801',
              '848651',
              '2215345',
              '2422497',
              '1676360',
              '2261937',
              '1335769'],
             '164301': ['2352467',
              '674438',
              '614691',
              '414892',
              '163054',
              '1703770',
              '1198762',
              '139800',
              '169941',
              '1791930'],
             '23344': ['23344',
              '2176190',
              '2063227',
              '1911804',
              '2448301',
              '1865562',
              '2093481',
              '1192138',
              '2002375',
              '420936'],
             '9367': ['1080010',
              '1942436',
              '2377011',
              '1014015',
              '613453',
              '833316',
              '1920332',
              '1920437',
              '2317161',
              '1996632'],
             '592217': ['592217',
              '728912',
              '1932439',
              '2371077',
              '350482',
              '419529',
              '901650',
              '722653',
              '2456544',
              '323950'],
             '98546': ['98546',
              '1651627',
              '630445',
              '2165734',
              '1876890',
              '1746039',
              '2096022',
              '888182',
              '2016946',
              '869968'],
             '98175': ['1863235',
              '98175',
              '979418',
              '1634510',
              '1514310',
              '1824993',
              '105110',
              '1476590',
              '1562537',
              '2132896'],
             '15189': ['124228',
              '15189',
              '1942441',
              '2402251',
              '557967',
              '1638193',
              '1423601',
              '1903962',
              '465902',
              '84799'],
             '1256': ['876761',
              '113333',
              '1235263',
              '538932',
              '271822',
              '2440176',
              '1256',
              '2157777',
              '2314072',
              '2311645'],
             '1815937': ['1815937',
              '243805',
              '2289785',
              '2086664',
              '565326',
              '204845',
              '10342',
              '1275085',
              '850359',
              '247379'],
             '1249076': ['776649',
              '148739',
              '1249076',
              '582125',
              '271184',
              '1218390',
              '597808',
              '1404931',
              '117077',
              '577424'],
             '80274': ['849206',
              '150130',
              '340664',
              '80274',
              '176310',
              '304719',
              '716455',
              '1873712',
              '283567',
              '176330'],
             '38489': ['461229',
              '1130473',
              '282393',
              '2390162',
              '1845290',
              '585857',
              '2441739',
              '1222036',
              '992021',
              '2310760'],
             '11311': ['1971400',
              '2445017',
              '2335274',
              '1513312',
              '11811',
              '2445229',
              '2299615',
              '1485803',
              '77619',
              '2195076'],
             '4754': ['4754',
              '1096243',
              '236496',
              '553733',
              '1194767',
              '2149205',
              '2015409',
              '547188',
              '2356140',
              '1656412'],
             '257711': ['357261',
              '257711',
              '1484995',
              '1936587',
              '1628781',
              '1162525',
              '1347610',
              '825222',
              '300746',
              '1907372'],
             '141668': ['1238621',
              '1722747',
              '395221',
              '165351',
              '1914607',
              '1958630',
              '1640075',
              '954750',
              '1062897',
              '753613'],
             '100895': ['100895',
              '1673670',
              '2077781',
              '1137894',
              '2357750',
              '551090',
              '232851',
              '414800',
              '1511933',
              '558572'],
             '32945': ['32945',
              '2282975',
              '30883',
              '661736',
              '781080',
              '1304274',
              '2026880',
              '2031608',
              '2096142',
              '583542'],
             '112321': ['8105',
              '112321',
              '1852415',
              '1250',
              '794500',
              '7407',
              '2112478',
              '58462',
              '2187',
              '1868888'],
             '133725': ['133725',
              '6502',
              '73573',
              '2123315',
              '1959279',
              '415845',
              '449439',
              '2056826',
              '753034',
              '9140'],
             '424464': ['1487470', '18386', '424464', '663519'],
             '523456': ['1111392',
              '523456',
              '524668',
              '1124756',
              '1077052',
              '341506',
              '114881',
              '2404771',
              '1970831',
              '1097635'],
             '1327515': ['2288752',
              '1327515',
              '2156783',
              '1926176',
              '952689',
              '2194210',
              '1537119',
              '1505058',
              '1412780',
              '2384755'],
             '12101': ['859022',
              '2140400',
              '1602439',
              '1815846',
              '1836521',
              '138606',
              '350923',
              '1939375',
              '1436095',
              '1939353'],
             '9739': ['274722',
              '1096838',
              '1024639',
              '1375473',
              '370163',
              '9739',
              '1949261',
              '1912766',
              '706941',
              '473870'],
             '189869': ['367496',
              '128794',
              '134672',
              '1324666',
              '142177',
              '298520',
              '1142186',
              '132340',
              '2127341',
              '189807'],
             '143444': ['390102',
              '143444',
              '1363154',
              '1719779',
              '760591',
              '1595491',
              '717282',
              '1421267',
              '31332',
              '619180'],
             '78940': ['400988',
              '1225575',
              '2187325',
              '400966',
              '663857',
              '663465',
              '78940',
              '1519096',
              '129940',
              '273488'],
             '12527': ['2428193',
              '12527',
              '1557331',
              '1263830',
              '1555649',
              '756172',
              '2421049',
              '85080',
              '462386',
              '23963'],
             '327199': ['2431271',
              '1121851',
              '163489',
              '2201943',
              '327199',
              '446190',
              '824648',
              '1799204',
              '1475136',
              '763445'],
             '7707': ['7707',
              '607670',
              '662426',
              '2431336',
              '1450844',
              '2307061',
              '86731',
              '2080398',
              '1330041',
              '2024588'],
             '97455': ['193928',
              '355309',
              '390447',
              '612425',

In [21]:
import ir_datasets

dataset = ir_datasets.load("wikir/en1k/training")
doc_id_vs_text = defaultdict(str)

for doc in dataset.docs_iter():
    doc_id_vs_text[doc.doc_id] = doc.text

In [22]:
query_doc_pairs = defaultdict(list)

for query_id in query_ids:
    for doc_id in query_id_and_its_doc_for_10[query_id]:
        query_doc_pairs[query_id].append((query_id_vs_text[query_id], doc_id_vs_text[doc_id]))

In [23]:
query_doc_pairs["123839"]

[('yanni',
  'it is a compilation of tracks from his five previous studio albums released between 1980 and 1989 plus three new compositions yanni was encouraged to release the album by his then partner actress linda evans reflections of passion became yanni s fastest selling and most successful album of his career upon release it reached no 1 on the billboard top new age albums chart and no 29 on the billboard 200 yanni supported the album with a nationwide concert tour in 1990 that featured his band and an orchestra in 1995 it was certified double platinum for selling 2 million copies in the us in august 1989 yanni released his fifth studio album niki nana the album marked his stylistic development from solo keyboard music towards rock with the addition of additional vocalists musicians and choir around the same time of its release yanni s newfound relationship with american actress linda evans who had become a fan of his music received press attention not long into their relationship evans pitched an idea she had for an album from yanni which was long in duration reflected a single mood throughout and something that she could play at dinner parties she mentioned'),
 ('yanni',
  'although this genre of music was not well suited for commercial pop radio and music television yanni received international recognition by producing concerts at historic monuments and by producing videos that were broadcast on public television his breakthrough concert live at the acropolis yielded the second best selling music concert video of all time additional historic sites for yanni s concerts have included india s taj mahal china s forbidden city the united arab emirates burj khalifa russia s kremlin puerto rico s el morro castle lebanon s ancient city of byblos tunisia s roman theatre of carthage india s laxmi vilas palace the egyptian pyramids and great sphinx of giza and the amman citadel at least sixteen of yanni s albums have peaked at no 1 in billboard s top new age album category and two albums dare to dream and in my time received grammy award nominations yanni has performed in more than 30 countries on five continents and through late 2015 yanni had performed live in concert before more than 5 million people and had accumulated more than 40 platinum and gold albums globally with sales totaling over 25 million copies a longtime fundraiser for public television'),
 ('yanni',
  'the album peaked at no 1 on billboard s top new age album chart and at no 21 on the billboard 200 chart in the same year the corresponding concert tour in 1998 was the tribute world tour 1998 tribute pays musical homage to india on several songs greek born composer and keyboardist yanni describes the album as a tribute to the builders of the taj and the forbidden city as well as to the people of india and china yanni s ethereal keyboard work is backed by orchestra vocalists a choir and various world instruments including didgeridoo duduk charango and bamboo saxophone yanni hired armen anassian as conductor on faith as he had never watched him conduct an orchestra that s how yanni does many things anassian said in a 1998 interview with the toledo blade anassian concedes that he had some doubts about the artist s plans to perform at india s taj mahal and china s forbidden city for tribute to be honest a few years ago when he was talking about it the idea was so amazing i myself was very skeptical understandably so but the truth is it happened we did it anassian said the'),
 ('yanni',
  'adams was born in joliet illinois band members of regional rock band chameleon included adams on drums vocals and percussion yanni on keyboards and synthesizers dugan mcneill on lead vocals and bass guitars johnny donaldson on all guitars and mark anthony on lead vocals and keyboards their albums included chameleon techno color hologram sky and balance the group was noted for adams revolving gyroscope drum kit who played his rapidly spinning drums before m tley cr e s tommy lee s similar arrangement in 1987 yanni was putting together his first touring band to promote his album out of silence as well as selections from keys to imagination this early band included yanni john tesh and joyce imbesi on keyboards and adams on drums adams is widely recognized for his drum solo on the live at the acropolis concert film he is also featured in the live at royal albert hall released in 1995 when yanni staged his tribute concerts in 1996 1997 adams did not join him as he had to stay back in the united states to deal with issues on his son s autism and help raise him joel taylor became the substitute drummer for the said'),
 ('yanni',
  'it was recorded at the herodes atticus theatre in athens greece during his 1993 tour in support of his eighth studio album in my time 1993 the concert took a year and a half to organise and cost yanni 2 million of his own money to fund he performs with his six piece band and the royal philharmonic orchestra conducted by shahrdad rohani the album was mixed and produced by yanni in his studio and was made into a television special which aired in the united states on public broadcasting service pbs live at the acropolis received a mostly positive reception from music critics it was an instant commercial success reaching number one on the billboard new age albums chart and number 5 on the billboard 200 it remains yanni s highest selling release with 4 million albums and 600 000 home videos sold in the united states and an estimated 7 million copies sold worldwide in 1994 the video received a primetime emmy award nomination for outstanding individual achievement in lighting direction electronic for a drama series variety series miniseries or a special a remastered edition with bonus material to commemorate the album s 25th anniversary was released in'),
 ('yanni',
  'the two concerts were performed outdoors on the grounds of el morro castle in san juan puerto rico in december 2011 the cd peaked at 1 on billboard s new age album list in both 2012 and 2013 live at el morro puerto rico was recorded and filmed during two sold out concerts performed outdoors on december 16 and 17 2011 on the grounds of the castillo san felipe del morro el morro a unesco world heritage site in the old san juan yanni had reportedly planned for twenty years to perform at the historic site yanni explained that two concerts were planned for friday and saturday night with the ensuing sunday being a contingent rain day it reportedly rained for 25 days in a row preceding the first night s concert on friday and the first concert itself was interrupted and eventually cut short three quarters of the way through by rain and wind causing danger for the outdoor performance the evening of the second show saturday the weather was better and the show was completed as planned yanni said that 35 cameras and three live camera operators were able to capture the show departing the island on sunday'),
 ('yanni',
  'its corresponding concert tour was the 1987 concert series the liner notes dedicate the album to his homeland in kalamata greece respectively dedicated to the town of kalamata greece which stood strong and waited for me one last time the album was reissued in 2009 by valley entertainment in a review by william ruhlmann of allmusic yanni s second album like his first keys to imagination was recorded entirety on synthesizers at his home studio the composer performer makes extensive use of the orchestral possibilities of electronics creating big themes to play across elaborate echoing rhythm tracks unlike much adult alternative music it s constantly stimulating foreground music with an extremely modern sound 1987 selections from keys to imagination and out of silence it was during this year that yanni was putting together his first touring band to promote his album out of silence as well as selections from keys to imagination although i d written as always with an orchestra in mind i couldn t afford one so i reproduced that sound in my studio with my synthesizers but because i wanted to play everything live onstage and not against tape i needed three keyboard players and a drummer'),
 ('yanni',
  'singles from the album included rabba released in 2003 and sajan released in 2004 the tunes on sampooran were written incorporating traditional material from the eastern classical tradition and adapting these with music which was based on the jazz rock fusion explosion of the seventies it possesses arguably the finest musical arrangements that have ever been experienced in the country and the compositions really light up the album the album starts with the lukewarm sajan whose lyrics have been taken from a kaafi written by shah hussain a moderate mix of acoustic guitars and percussion and some sweet flute playing renders this a really good opening track waris shah is next with its yanni isque musical intonations and lyrics inspired from texts by amrita preetam the album seems to be getting into a groove as the vocals start getting tuned up and the music gets more and more passionate a classically inspired flute arrangement mixed with soft bass drums and javed bashir does total justice with the lyrics the song has probably lingered on a bit and some pieces seem a bit lengthy but overall it is the vocals that stand out on waris shah more than anything else rabba'),
 ('yanni',
  'contrary to some sources this film was never released under the title vampire playgirls count dracula s great love opens outside a creepy old sanitorium in the carpathian mountains as two delivery men arrive with a large heavy man shaped crate the owner doctor wendell marlow paul naschy has just purchased the sanitorium but has not yet moved in realizing that these rich castle owning types have money and jewels just lying around they decide to wander about and see if there is anything they can steal one is struck in the head with an axe and the other gets his throat ripped out by a man in a black cape with velvet lining the opening scene is repeated over and over again as the opening credits roll meanwhile a stagecoach loaded with four young women karen haydee politoff senta rosanna yanni marlene ingrid garbo and elke mirta miller and imre polvi vic winner a strapping young male who is really nothing more than an extended cameo loses a carriage wheel in the infamous borgo pass when the stagecoach driver is killed in a freak accident the five passengers seek shelter from an oncoming storm in the nearby sanitorium where'),
 ('yanni',
  'at age 16 lavie toured canada as a backup singer with the french canadian hip hop group dubmatique after which she recorded her own demo cd lavie s demo cd reached the same producer who had co written mariah carey s first album and lavie accepted his invitation to move to california to work with him in 2006 lavie s vocals were included on the soundtracks of the motion pictures stick it and the guardian in 2007 lavie became one of the earliest to use the internet to reach fans and arouse interest of record labels by october her music video angel was featured on youtube s front page and became a finalist in the 2007 youtube awards music category lavie was listed as singer songwriter in her first album everything or nothing which was released under an independent record label in february 2010 lavie produced and performed in the charity collaboration video we are the world 25 for haiti youtube edition for relief of victims of the 2010 haiti earthquake journalist diane sawyer named the video s contributors abc news persons of the week since 2010 lavie has been a vocalist of contemporary instrumentalist yanni on his tours contributing')]

In [24]:
len(query_doc_pairs.keys())

1442

In [25]:
from sentence_transformers import CrossEncoder
model = CrossEncoder('cross-encoder/ms-marco-MiniLM-L6-v2')

/run/media/tahas44/Yeni Birim/Technarts/Intern/NLP/InformationRetrieval/.venv/lib64/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 105/105 [00:00<00:00, 2560.42it/s]

In [26]:
dict_keys_set = set(query_doc_pairs.keys())

In [27]:
query_score_dict = defaultdict(list)

for query_id in query_ids:
    if query_id in dict_keys_set:
        query_score_dict[query_id] = list(model.predict(query_doc_pairs[query_id]))

In [28]:
query_score_dict["123839"]

[np.float32(6.4627924),
 np.float32(6.419842),
 np.float32(4.9677753),
 np.float32(3.0357656),
 np.float32(5.5189133),
 np.float32(2.3268332),
 np.float32(4.384878),
 np.float32(0.7513137),
 np.float32(-3.6361036),
 np.float32(-4.7235107)]

In [29]:
del query_doc_pairs 
gc.collect()

271

In [30]:
most_related_10_dict = defaultdict(list)
most_related_10_dict_with_scores = defaultdict(list)

for query_id in query_ids:
    if query_id in dict_keys_set:
        related_10 = []

        for i, score in enumerate(query_score_dict[query_id]):
            related_10.append((score, i))

        for mytuple in sorted(related_10, reverse=True):
            most_related_10_dict[query_id].append(query_id_and_its_doc_for_10[query_id][mytuple[1]])
            most_related_10_dict_with_scores[query_id].append((query_id_and_its_doc_for_10[query_id][mytuple[1]], mytuple[0]))

            if len(most_related_10_dict[query_id]) == 10:
                break

In [31]:
def recall(found_docs: list, test_list: list) -> float:
    counter = 0
    test_set = set(test_list)

    for doc_id in found_docs:
        if doc_id in test_set:
            counter += 1

    return (counter / len(test_list)) * 100

def precision(found_docs: list, test_list: list) -> float:
    counter = 0
    test_set = set(test_list)

    for doc_id in found_docs:
        if doc_id in test_set:
            counter += 1

    return (counter / len(found_docs)) * 100

def precision_AP(found_docs: list, test_list: list) -> float:
    counter = 0

    test_set = set(test_list)

    for doc in found_docs:
        if doc in test_set:
            counter += 1

    return counter / len(found_docs)


def AP(found_docs: list, test_list: list) -> float:
    total = 0

    for i in range(1, 10 + 1):
        if i < len(found_docs):
            precision_k = precision_AP(found_docs[:i], test_list)
            total += precision_k * (found_docs[i - 1] in set(test_list))

    return total / len(test_list)

In [32]:
recall_10_list, precision_10_list, AP_10_list = [], [], []

for query_id in query_ids:
    if query_id in dict_keys_set:
        recall_10_value = recall(most_related_10_dict[query_id], qrels_dict[query_id])
        precision_10_value = precision(most_related_10_dict[query_id], qrels_dict[query_id])
        AP_10_value = AP(most_related_10_dict[query_id], qrels_dict[query_id])

        recall_10_list.append(recall_10_value)
        precision_10_list.append(precision_10_value)
        AP_10_list.append(AP_10_value)
    else:
        recall_10_list.append(0)
        precision_10_list.append(0)
        AP_10_list.append(0)

In [33]:
len(recall_10_list)

1444

In [34]:
import pandas as pd

df_10 = pd.DataFrame({
    "Query_ID": query_ids,
    "recall_10": recall_10_list,
    "precision_10": precision_10_list,
    "AP_10": AP_10_list
})

df_10

     Query_ID   recall_10  precision_10     AP_10
0      123839  100.000000          60.0  0.915079
1      188629   33.333333          20.0  0.333333
2       13898   33.333333          20.0  0.333333
3      316959   22.222222          20.0  0.222222
4      515031   14.285714          20.0  0.100000
...       ...         ...           ...       ...
1439   896124   12.500000          10.0  0.062500
1440    12319    4.545455          10.0  0.045455
1441     4421    0.000000           0.0  0.000000
1442   296526    0.000000           0.0  0.000000
1443   341793   14.285714          10.0  0.142857

[1444 rows x 4 columns]

In [35]:
from sklearn.metrics import ndcg_score

doc_id_score_dict = defaultdict(float)
ndcg_10_list = []

for idx in range(len(df_10)):
    query_id = df_10.loc[idx, "Query_ID"]
    if query_id in dict_keys_set:
        scoredoc_object_list = score_doc_dict[query_id]

        for scoreddoc_object in scoredoc_object_list:
            doc_id_score_dict[scoreddoc_object.doc_id] = scoreddoc_object.score

        model_score_tuple_list = most_related_10_dict_with_scores[query_id]

        y_score, y_true = [], []

        for mytuple in model_score_tuple_list:
            doc_id = mytuple[0]
            score = mytuple[1]

            y_score.append(score)
            y_true.append(doc_id_score_dict[doc_id])

        if len(y_score) == 0:
            ndcg_10_list.append(0.0)
            continue

        if len(y_score) == 1:
            y_true.append(0.0)
            y_score.append(0.0)

        if len(y_true) == len(y_score):
            ndcg_10_list.append(ndcg_score(np.asarray([y_true]), np.asarray([y_score]), k=10))
        else:
            print("There is a problem with query", query_id)
    else:
        ndcg_10_list.append(0)

In [36]:
len(ndcg_10_list)

1444

In [37]:
df_10["NDCG_10"] = ndcg_10_list
df_10

     Query_ID   recall_10  precision_10     AP_10   NDCG_10
0      123839  100.000000          60.0  0.915079  0.995386
1      188629   33.333333          20.0  0.333333  0.998342
2       13898   33.333333          20.0  0.333333  0.000000
3      316959   22.222222          20.0  0.222222  0.991666
4      515031   14.285714          20.0  0.100000  0.760507
...       ...         ...           ...       ...       ...
1439   896124   12.500000          10.0  0.062500  0.990022
1440    12319    4.545455          10.0  0.045455  0.775022
1441     4421    0.000000           0.0  0.000000  0.990301
1442   296526    0.000000           0.0  0.000000  0.693317
1443   341793   14.285714          10.0  0.142857  0.733019

[1444 rows x 5 columns]

In [38]:
df_10["f_score_10"] = 2 * df_10["recall_10"] * df_10["precision_10"] / (df_10["recall_10"] + df_10["precision_10"])
df_10

     Query_ID   recall_10  precision_10     AP_10   NDCG_10  f_score_10
0      123839  100.000000          60.0  0.915079  0.995386   75.000000
1      188629   33.333333          20.0  0.333333  0.998342   25.000000
2       13898   33.333333          20.0  0.333333  0.000000   25.000000
3      316959   22.222222          20.0  0.222222  0.991666   21.052632
4      515031   14.285714          20.0  0.100000  0.760507   16.666667
...       ...         ...           ...       ...       ...         ...
1439   896124   12.500000          10.0  0.062500  0.990022   11.111111
1440    12319    4.545455          10.0  0.045455  0.775022    6.250000
1441     4421    0.000000           0.0  0.000000  0.990301         NaN
1442   296526    0.000000           0.0  0.000000  0.693317         NaN
1443   341793   14.285714          10.0  0.142857  0.733019   11.764706

[1444 rows x 6 columns]

In [40]:
df_10["f_score_10"] = df_10["f_score_10"].fillna(0)

In [41]:
df_10

     Query_ID   recall_10  precision_10     AP_10   NDCG_10  f_score_10
0      123839  100.000000          60.0  0.915079  0.995386   75.000000
1      188629   33.333333          20.0  0.333333  0.998342   25.000000
2       13898   33.333333          20.0  0.333333  0.000000   25.000000
3      316959   22.222222          20.0  0.222222  0.991666   21.052632
4      515031   14.285714          20.0  0.100000  0.760507   16.666667
...       ...         ...           ...       ...       ...         ...
1439   896124   12.500000          10.0  0.062500  0.990022   11.111111
1440    12319    4.545455          10.0  0.045455  0.775022    6.250000
1441     4421    0.000000           0.0  0.000000  0.990301    0.000000
1442   296526    0.000000           0.0  0.000000  0.693317    0.000000
1443   341793   14.285714          10.0  0.142857  0.733019   11.764706

[1444 rows x 6 columns]

In [42]:
query_doc_pairs = defaultdict(list)

for query_id in query_ids:
    for doc_id in query_id_and_its_doc_for_10[query_id]:
        query_doc_pairs[query_id].append((query_id_vs_text[query_id], doc_id_vs_text[doc_id]))

In [43]:
most_related_5_dict = defaultdict(list)
most_related_5_dict_with_scores = defaultdict(list)

for query_id in query_ids:
    if query_id in dict_keys_set:
        related_10 = []

        for i, score in enumerate(query_score_dict[query_id]):
            related_10.append((score, i))

        for mytuple in sorted(related_10, reverse=True):
            most_related_5_dict[query_id].append(query_id_and_its_doc_for_10[query_id][mytuple[1]])
            most_related_5_dict_with_scores[query_id].append((query_id_and_its_doc_for_10[query_id][mytuple[1]], mytuple[0]))

            if len(most_related_5_dict[query_id]) == 5:
                break

In [44]:
recall_5_list, precision_5_list, AP_5_list = [], [], []

for query_id in query_ids:
    if query_id in dict_keys_set:
        recall_5_value = recall(most_related_5_dict[query_id], qrels_dict[query_id])
        precision_5_value = precision(most_related_5_dict[query_id], qrels_dict[query_id])
        AP_5_value = AP(most_related_5_dict[query_id], qrels_dict[query_id])

        recall_5_list.append(recall_5_value)
        precision_5_list.append(precision_5_value)
        AP_5_list.append(AP_5_value)
    else:
        recall_5_list.append(0)
        precision_5_list.append(0)
        AP_5_list.append(0)

In [45]:
df_10

     Query_ID   recall_10  precision_10     AP_10   NDCG_10  f_score_10
0      123839  100.000000          60.0  0.915079  0.995386   75.000000
1      188629   33.333333          20.0  0.333333  0.998342   25.000000
2       13898   33.333333          20.0  0.333333  0.000000   25.000000
3      316959   22.222222          20.0  0.222222  0.991666   21.052632
4      515031   14.285714          20.0  0.100000  0.760507   16.666667
...       ...         ...           ...       ...       ...         ...
1439   896124   12.500000          10.0  0.062500  0.990022   11.111111
1440    12319    4.545455          10.0  0.045455  0.775022    6.250000
1441     4421    0.000000           0.0  0.000000  0.990301    0.000000
1442   296526    0.000000           0.0  0.000000  0.693317    0.000000
1443   341793   14.285714          10.0  0.142857  0.733019   11.764706

[1444 rows x 6 columns]

In [46]:
df_10["recall_5"] = recall_5_list
df_10["precision_5"] = precision_5_list
df_10["AP_5"] = AP_5_list

In [47]:
df_10

,Query_ID,recall_10,precision_10,AP_10,NDCG_10,f_score_10,recall_5,precision_5,AP_5
0,123839,100.000000,60.0,0.915079,0.995386,75.000000,66.666667,80.0,0.500000
1,188629,33.333333,20.0,0.333333,0.998342,25.000000,33.333333,40.0,0.333333
2,13898,33.333333,20.0,0.333333,0.000000,25.000000,33.333333,40.0,0.333333
3,316959,22.222222,20.0,0.222222,0.991666,21.052632,22.222222,40.0,0.222222
4,515031,14.285714,20.0,0.100000,0.760507,16.666667,14.285714,40.0,0.071429
...,...,...,...,...,...,...,...,...,...
1439,896124,12.500000,10.0,0.062500,0.990022,11.111111,12.500000,20.0,0.062500
1440,12319,4.545455,10.0,0.045455,0.775022,6.250000,4.545455,20.0,0.045455
1441,4421,0.000000,0.0,0.000000,0.990301,0.000000,0.000000,0.0,0.000000
1442,296526,0.000000,0.0,0.000000,0.693317,0.000000,0.000000,0.0,0.000000
1443,341793,14.285714,10.0,0.142857,0.733019,11.764706,14.285714,20.0,0.142857

In [48]:
df_10["f_score_5"] = 2 * df_10["recall_5"] * df_10["precision_5"] / (df_10["recall_5"] + df_10["precision_5"])

In [49]:
df_10

,Query_ID,recall_10,precision_10,AP_10,NDCG_10,f_score_10,recall_5,precision_5,AP_5,f_score_5
0,123839,100.000000,60.0,0.915079,0.995386,75.000000,66.666667,80.0,0.500000,72.727273
1,188629,33.333333,20.0,0.333333,0.998342,25.000000,33.333333,40.0,0.333333,36.363636
2,13898,33.333333,20.0,0.333333,0.000000,25.000000,33.333333,40.0,0.333333,36.363636
3,316959,22.222222,20.0,0.222222,0.991666,21.052632,22.222222,40.0,0.222222,28.571429
4,515031,14.285714,20.0,0.100000,0.760507,16.666667,14.285714,40.0,0.071429,21.052632
...,...,...,...,...,...,...,...,...,...,...
1439,896124,12.500000,10.0,0.062500,0.990022,11.111111,12.500000,20.0,0.062500,15.384615
1440,12319,4.545455,10.0,0.045455,0.775022,6.250000,4.545455,20.0,0.045455,7.407407
1441,4421,0.000000,0.0,0.000000,0.990301,0.000000,0.000000,0.0,0.000000,NaN
1442,296526,0.000000,0.0,0.000000,0.693317,0.000000,0.000000,0.0,0.000000,NaN
1443,341793,14.285714,10.0,0.142857,0.733019,11.764706,14.285714,20.0,0.142857,16.666667

In [51]:
from sklearn.metrics import ndcg_score

doc_id_score_dict = defaultdict(float)
ndcg_5_list = []

for idx in range(len(df_10)):
    query_id = df_10.loc[idx, "Query_ID"]
    if query_id in dict_keys_set:
        scoredoc_object_list = score_doc_dict[query_id]

        for scoreddoc_object in scoredoc_object_list:
            doc_id_score_dict[scoreddoc_object.doc_id] = scoreddoc_object.score

        model_score_tuple_list = most_related_5_dict_with_scores[query_id]

        y_score, y_true = [], []

        for mytuple in model_score_tuple_list:
            doc_id = mytuple[0]
            score = mytuple[1]

            y_score.append(score)
            y_true.append(doc_id_score_dict[doc_id])

        if len(y_score) == 0:
            ndcg_5_list.append(0.0)
            continue

        if len(y_score) == 1:
            y_true.append(0.0)
            y_score.append(0.0)

        if len(y_true) == len(y_score):
            ndcg_5_list.append(ndcg_score(np.asarray([y_true]), np.asarray([y_score]), k=5))
        else:
            print("There is a problem with query", query_id)
    else:
        ndcg_5_list.append(0)

In [52]:
df_10["NDCG_5"] = ndcg_5_list

In [53]:
df_10

,Query_ID,recall_10,precision_10,AP_10,NDCG_10,f_score_10,recall_5,precision_5,AP_5,f_score_5,NDCG_5
0,123839,100.000000,60.0,0.915079,0.995386,75.000000,66.666667,80.0,0.500000,72.727273,0.998041
1,188629,33.333333,20.0,0.333333,0.998342,25.000000,33.333333,40.0,0.333333,36.363636,0.997851
2,13898,33.333333,20.0,0.333333,0.000000,25.000000,33.333333,40.0,0.333333,36.363636,0.000000
3,316959,22.222222,20.0,0.222222,0.991666,21.052632,22.222222,40.0,0.222222,28.571429,0.989511
4,515031,14.285714,20.0,0.100000,0.760507,16.666667,14.285714,40.0,0.071429,21.052632,0.754046
...,...,...,...,...,...,...,...,...,...,...,...
1439,896124,12.500000,10.0,0.062500,0.990022,11.111111,12.500000,20.0,0.062500,15.384615,0.989962
1440,12319,4.545455,10.0,0.045455,0.775022,6.250000,4.545455,20.0,0.045455,7.407407,0.840926
1441,4421,0.000000,0.0,0.000000,0.990301,0.000000,0.000000,0.0,0.000000,NaN,0.986912
1442,296526,0.000000,0.0,0.000000,0.693317,0.000000,0.000000,0.0,0.000000,NaN,0.674780
1443,341793,14.285714,10.0,0.142857,0.733019,11.764706,14.285714,20.0,0.142857,16.666667,1.000000

In [54]:
mydict = {
    "Method": "BM25 - Lemmatization Cross Encoder With Query Expansion",
    "recall_5_mean": df_10["recall_5"].mean(),
    "recall_5_std": df_10["recall_5"].std(),
    "recall_5_max": df_10["recall_5"].max(),
    "recall_5_min": df_10["recall_5"].min(),
    "recall_10_mean": df_10["recall_10"].mean(),
    "recall_10_std": df_10["recall_10"].std(),
    "recall_10_max": df_10["recall_10"].max(),
    "recall_10_min": df_10["recall_10"].min(),
    "precision_5_mean": df_10["precision_5"].mean(),
    "precision_5_std": df_10["precision_5"].std(),
    "precision_5_max": df_10["precision_5"].max(),
    "precision_5_min": df_10["precision_5"].min(),
    "precision_10_mean": df_10["precision_10"].mean(),
    "precision_10_std": df_10["precision_10"].std(),
    "precision_10_max": df_10["precision_10"].max(),
    "precision_10_min": df_10["precision_10"].min(),
    "f_score_5_mean": df_10["f_score_5"].mean(),
    "f_score_5_std": df_10["f_score_5"].std(),
    "f_score_5_max": df_10["f_score_5"].max(),
    "f_score_5_min": df_10["f_score_5"].min(),
    "f_score_10_mean": df_10["f_score_10"].mean(),
    "f_score_10_std": df_10["f_score_10"].std(),
    "f_score_10_max": df_10["f_score_10"].max(),
    "f_score_10_min": df_10["f_score_10"].min(),
    "MAP_5": df_10["AP_5"].mean(),
    "MAP_10": df_10["AP_10"].mean(),
    "NDCG_5_mean": df_10["NDCG_5"].mean(),
    "NDCG_5_std": df_10["NDCG_5"].std(),
    "NDCG_5_max": df_10["NDCG_5"].max(),
    "NDCG_5_min": df_10["NDCG_5"].min(),
    "NDCG_10_mean": df_10["NDCG_10"].mean(),
    "NDCG_10_std": df_10["NDCG_10"].std(),
    "NDCG_10_max": df_10["NDCG_10"].max(),
    "NDCG_10_min": df_10["NDCG_10"].min()
}

In [55]:
df_parquet = pd.DataFrame(mydict, index=[0])
df_parquet

,Method,recall_5_mean,recall_5_std,recall_5_max,recall_5_min,recall_10_mean,recall_10_std,recall_10_max,recall_10_min,precision_5_mean,...,MAP_5,MAP_10,NDCG_5_mean,NDCG_5_std,NDCG_5_max,NDCG_5_min,NDCG_10_mean,NDCG_10_std,NDCG_10_max,NDCG_10_min
0,BM25 - Lemmatization Cross Encoder With Query ...,15.642264,14.4619,83.333333,0.0,20.540319,19.448146,100.0,0.0,32.523084,...,0.121822,0.152152,0.804181,0.326229,1.0,0.0,0.81125,0.289479,1.0,0.0

In [56]:
df_parquet.to_parquet("BM25LemmatizationCrossEncoderWithQueryExpansion.parquet")