In [1]:
import ir_datasets
from nltk.stem import WordNetLemmatizer
import nltk
from helper import create_tokenized_word_list

dataset = ir_datasets.load("wikir/en1k/training")
tokenized = create_tokenized_word_list(dataset)

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/tahas44/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [2]:
nltk.download("punkt_tab")
nltk.download("wordnet")

[nltk_data] Downloading package punkt_tab to
[nltk_data]     /home/tahas44/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package wordnet to /home/tahas44/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [3]:
lemmatized_tokenized_docs = []
lematizer = WordNetLemmatizer()

for query_list in tokenized:
    lemmatized_words = [lematizer.lemmatize(word) for word in query_list]
    lemmatized_tokenized_docs.append(lemmatized_words)

print("Docs lemmatized")

Docs lemmatized

In [4]:
from helper import create_tokenized_word_list_for_query
query_tokenized = create_tokenized_word_list_for_query(dataset)
print("Queries tokenized!")

Queries tokenized!

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/tahas44/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [5]:
lemmatized_tokenized_queries = []

for query_list in query_tokenized:
    lemmatized_words = [lematizer.lemmatize(words) for words in query_list]
    lemmatized_tokenized_queries.append(lemmatized_words)

print("Queries lemmatized")

Queries lemmatized

In [6]:
from rank_bm25 import BM25Okapi
bm25 = BM25Okapi(lemmatized_tokenized_docs)

In [7]:
scores_of_all_queries = []

for query in lemmatized_tokenized_queries:
    scores_of_all_queries.append(bm25.get_scores(query))

In [8]:
from collections import defaultdict
from helper import Scoredoc

doc_dict = defaultdict(str)

for i, doc in enumerate(dataset.docs_iter()):
    doc_dict[i] = doc.doc_id

doc_dict = dict(doc_dict)

qrels_dict = defaultdict(list)

for qrel in dataset.qrels_iter():
    qrels_dict[qrel.query_id].append(qrel.doc_id)

qrels_dict = dict(qrels_dict)

score_doc_dict = defaultdict(list)

for scoreddoc in dataset.scoreddocs_iter():
    doc_id = scoreddoc.doc_id
    score = scoreddoc.score

    scoreddoc_object = Scoredoc(doc_id, score)

    score_doc_dict[scoreddoc.query_id].append(scoreddoc_object)

score_doc_dict = dict(score_doc_dict)

print("Necessary dicts created!")

Necessary dicts created!

In [ ]:
query_ids = [query.query_id for query in dataset.queries_iter()]
query_ids

['123839',
 '188629',
 '13898',
 '316959',
 '515031',
 '123783',
 '4332',
 '9591',
 '114982',
 '563603',
 '104206',
 '1580851',
 '23678',
 '37480',
 '109454',
 '544250',
 '12519',
 '115015',
 '84287',
 '24998',
 '11925',
 '643',
 '113075',
 '1250387',
 '72012',
 '167865',
 '1425120',
 '24883',
 '27200',
 '136856',
 '6031',
 '1313191',
 '187115',
 '84110',
 '208234',
 '6431',
 '10799',
 '1417144',
 '32512',
 '677637',
 '97937',
 '113765',
 '12900',
 '1294909',
 '73745',
 '11692',
 '22173',
 '76662',
 '164301',
 '23344',
 '9367',
 '592217',
 '98546',
 '98175',
 '15189',
 '1256',
 '1815937',
 '1249076',
 '80274',
 '38489',
 '11311',
 '4754',
 '257711',
 '141668',
 '100895',
 '32945',
 '112321',
 '133725',
 '424464',
 '523456',
 '1327515',
 '12101',
 '9739',
 '189869',
 '143444',
 '78940',
 '12527',
 '327199',
 '7707',
 '97455',
 '1262433',
 '488875',
 '74026',
 '358108',
 '95179',
 '7862',
 '151797',
 '92980',
 '100876',
 '238228',
 '107755',
 '32539',
 '12953',
 '24843',
 '119528',
 '30765',
 '134772',
 '27711',
 '361260',
 '17874',
 '3524',
 '75902',
 '809894',
 '126362',
 '288208',
 '406254',
 '240663',
 '34848',
 '195113',
 '264822',
 '8387',
 '186363',
 '165761',
 '76875',
 '605155',
 '17836',
 '83566',
 '132697',
 '1563',
 '23924',
 '1433',
 '29737',
 '26758',
 '19717',
 '7870',
 '16093',
 '34844',
 '2234455',
 '382531',
 '12252',
 '11446',
 '21027',
 '1370698',
 '113657',
 '3348',
 '217425',
 '197576',
 '129397',
 '257126',
 '67592',
 '93136',
 '892237',
 '20605',
 '1219',
 '389032',
 '10656',
 '1778',
 '108160',
 '964897',
 '94266',
 '13744',
 '13539',
 '407598',
 '97620',
 '203795',
 '356090',
 '112731',
 '714608',
 '88181',
 '87960',
 '96791',
 '172084',
 '1836051',
 '14393',
 '1559299',
 '82801',
 '969771',
 '125685',
 '101336',
 '78856',
 '126985',
 '231130',
 '197161',
 '94693',
 '1339737',
 '273381',
 '73398',
 '179677',
 '90354',
 '1608685',
 '446634',
 '1595',
 '73102',
 '494392',
 '94832',
 '24349',
 '12374',
 '151391',
 '584158',
 '15282',
 '434927',
 '21969',
 '15987',
 '13776',
 '768304',
 '132575',
 '833105',
 '76345',
 '537',
 '181536',
 '4215',
 '17227',
 '97781',
 '1589',
 '119663',
 '1336894',
 '1568489',
 '133700',
 '147768',
 '674995',
 '1047896',
 '6368',
 '172053',
 '1045273',
 '80687',
 '1263864',
 '81739',
 '113925',
 '73285',
 '27399',
 '35101',
 '5570',
 '14758',
 '10792',
 '726995',
 '17814',
 '908',
 '85435',
 '79941',
 '140552',
 '145807',
 '107616',
 '13801',
 '357261',
 '34865',
 '2259',
 '6213',
 '72576',
 '163527',
 '75654',
 '29687',
 '1283640',
 '1703622',
 '324633',
 '37756',
 '1237543',
 '342167',
 '1058358',
 '248154',
 '330931',
 '163736',
 '488869',
 '20603',
 '8055',
 '109832',
 '9332',
 '204974',
 '339255',
 '22113',
 '94641',
 '10825',
 '71636',
 '2078947',
 '146007',
 '11481',
 '1282373',
 '605568',
 '276580',
 '190225',
 '26652',
 '14325',
 '23815',
 '119102',
 '17755',
 '29896',
 '26093',
 '1272415',
 '94442',
 '260160',
 '152382',
 '883324',
 '71191',
 '178216',
 '1408773',
 '6047',
 '1410732',
 '37218',
 '22295',
 '12601',
 '15200',
 '14027',
 '545390',
 '81411',
 '1324050',
 '8669',
 '21961',
 '612261',
 '389274',
 '39839',
 '90512',
 '185712',
 '302505',
 '2623',
 '1343759',
 '725960',
 '5554',
 '180826',
 '22170',
 '203549',
 '270009',
 '110384',
 '296861',
 '6835',
 '19342',
 '18363',
 '226344',
 '37955',
 '19145',
 '14445',
 '605066',
 '2228',
 '2613',
 '1742574',
 '28296',
 '100963',
 '561358',
 '13460',
 '85285',
 '4925',
 '104339',
 '183397',
 '156457',
 '284',
 '34937',
 '76048',
 '164182',
 '411597',
 '422208',
 '3522',
 '73430',
 '113428',
 '9399',
 '2243',
 '157351',
 '2842',
 '377416',
 '4855',
 '4397',
 '1846628',
 '75969',
 '635597',
 '2581',
 '20437',
 '76039',
 '9356',
 '22213',
 '1250',
 '70969',
 '1349',
 '6644',
 '103434',
 '384474',
 '1669212',
 '596568',
 '98507',
 '128283',
 '815972',
 '5816',
 '1344825',
 '11029',
 '82288',
 '639167',
 '80536',
 '254180',
 '97274',
 '4722',
 '159099',
 '25706',
 '104011',
 '6033',
 '14011',
 '4616',
 '6482',
 '310032',
 '25193',
 '27720',
 '21972',
 '633954',
 '37908',
 '1870966',
 '487985',
 '105462',
 '510206',
 '7560',
 '12705',
 '117619',
 '305484',
 '1090430',
 '1777480',
 '1268117',
 '1289085',
 '1338779',
 '1817436',
 '24242',
 '20898',
 '16880',
 '37945',
 '4085',
 '2130523',
 '18091',
 '19675',
 '78817',
 '5400',
 '32411',
 '1322',
 '188952',
 '4720',
 '25242',
 '763957',
 '84315',
 '107129',
 '7407',
 '83325',
 '526775',
 '5204',
 '1787',
 '112402',
 '92302',
 '2986',
 '161918',
 '71995',
 '18192',
 '85636',
 '26444',
 '6390',
 '134543',
 '923020',
 '834741',
 '184241',
 '88748',
 '391276',
 '8899',
 '26219',
 '8938',
 '166642',
 '24861',
 '1352',
 '16006',
 '473460',
 '210583',
 '75859',
 '6879',
 '152885',
 '238499',
 '473275',
 '196310',
 '5896',
 '5002',
 '226743',
 '110572',
 '543',
 '26103',
 '208058',
 '68416',
 '895072',
 '12773',
 '1182701',
 '13957',
 '28752',
 '6227',
 '119284',
 '273555',
 '17203',
 '609350',
 '117495',
 '1641154',
 '1705',
 '19435',
 '154661',
 '108269',
 '7026',
 '165900',
 '131685',
 '9643',
 '1515',
 '34957',
 '88458',
 '152413',
 '479595',
 '7647',
 '6264',
 '29411',
 '75908',
 '71994',
 '27795',
 '704769',
 '2274',
 '12626',
 '639949',
 '207327',
 '1274160',
 '10688',
 '24454',
 '128712',
 '181363',
 '80',
 '10413',
 '120973',
 '145081',
 '206583',
 '24782',
 '1365055',
 '317887',
 '740767',
 '73024',
 '25238',
 '56872',
 '5219',
 '42749',
 '1444121',
 '24145',
 '93598',
 '24066',
 '5065',
 '123063',
 '14451',
 '301383',
 '197016',
 '141405',
 '159773',
 '6138',
 '26051',
 '1712787',
 '73768',
 '12699',
 '121064',
 '681120',
 '81877',
 '197769',
 '173023',
 '194810',
 '370139',
 '21892',
 '77940',
 '108305',
 '10456',
 '243438',
 '352646',
 '23335',
 '4559',
 '762',
 '95338',
 '422214',
 '10221',
 '22149',
 '1403468',
 '9022',
 '70754',
 '7353',
 '79109',
 '9106',
 '2032420',
 '1270810',
 '102991',
 '366863',
 '750376',
 '98133',
 '1194068',
 '13415',
 '764844',
 '849899',
 '448622',
 '927392',
 '1063349',
 '128187',
 '1614640',
 '477200',
 '9748',
 '157369',
 '22800',
 '80219',
 '1403378',
 '146323',
 '97591',
 '80765',
 '125608',
 '351608',
 '81103',
 '4334',
 '21439',
 '113621',
 '90496',
 '2547',
 '488858',
 '217759',
 '189034',
 '90382',
 '814731',
 '14032',
 '75643',
 '1662573',
 '479233',
 '187769',
 '38035',
 '155722',
 '70941',
 '88077',
 '1683175',
 '30883',
 '289837',
 '28823',
 '34394',
 '19625',
 '110332',
 '92668',
 '11644',
 '133621',
 '86063',
 '1731034',
 '109201',
 '236830',
 '86499',
 '15015',
 '1467096',
 '518649',
 '1529682',
 '389454',
 '20213',
 '97540',
 '159101',
 '10524',
 '466077',
 '374708',
 '135038',
 '129387',
 '593570',
 '99196',
 '32938',
 '9755',
 '1421273',
 '13706',
 '226734',
 '100123',
 '1640988',
 '133233',
 '1608',
 '1264172',
 '1594725',
 '157511',
 '13850',
 '15277',
 '131074',
 '17237',
 '3249',
 '13326',
 '1814473',
 '1156870',
 '25280',
 '323708',
 '13016',
 '222183',
 '10968',
 '109940',
 '129732',
 '118690',
 '179517',
 '12198',
 '19019',
 '434541',
 '1248',
 '319553',
 '252889',
 '138439',
 '35022',
 '182032',
 '13954',
 '136151',
 '12030',
 '21583',
 '15741',
 '489',
 '11435',
 '6649',
 '14868',
 '37861',
 '248820',
 '1727920',
 '121664',
 '377463',
 '110662',
 '11420',
 '13685',
 '1685919',
 '1274158',
 '23083',
 '14139',
 '166211',
 '161907',
 '721863',
 '110381',
 '27264',
 '672596',
 '161341',
 '114943',
 '37957',
 '108695',
 '479110',
 '129109',
 '16266',
 '399420',
 '759288',
 '34119',
 '10963',
 '14608',
 '283712',
 '266655',
 '203968',
 '1313526',
 '7836',
 '119662',
 '140457',
 '1276229',
 '110281',
 '5195',
 '100816',
 '5103',
 '429845',
 '4088',
 '11072',
 '17962',
 '1254149',
 '8394',
 '305914',
 '665122',
 '13888',
 '126682',
 '133726',
 '154029',
 '1116',
 '172058',
 '55300',
 '374325',
 '23079',
 '2120001',
 '114890',
 '4831',
 '111289',
 '165585',
 '214810',
 '126571',
 '7755',
 '13630',
 '918270',
 '83187',
 '9865',
 '122086',
 '11428',
 '314278',
 '1062661',
 '503034',
 '155036',
 '446428',
 '10976',
 '20434',
 '3544',
 '25445',
 '717881',
 '71381',
 '117555',
 '682338',
 '245828',
 '35568',
 '20021',
 '606000',
 '38408',
 '114257',
 '332492',
 '15319',
 '229404',
 '5781',
 '20183',
 '9603',
 '192096',
 '79820',
 '411516',
 '77789',
 '1313521',
 '388950',
 '109985',
 '1585',
 '264823',
 '22226',
 '164723',
 '9041',
 '71649',
 '88210',
 '128218',
 '212288',
 '211013',
 '79',
 '438884',
 '1099352',
 '99045',
 '274498',
 '134029',
 '35023',
 '2402726',
 '13373',
 '2938',
 '103786',
 '88775',
 '809',
 '1032451',
 '35036',
 '89567',
 '170548',
 '22672',
 '82044',
 '123639',
 '20906',
 '7769',
 '385089',
 '24704',
 '2266',
 '677582',
 '90428',
 '9454',
 '211320',
 '161909',
 '1964',
 '115785',
 '409207',
 '232564',
 '9137',
 '9492',
 '497039',
 '78081',
 '2070217',
 '77289',
 '7611',
 '235972',
 '19574',
 '70946',
 '956',
 '179671',
 '11448',
 '805510',
 '36957',
 '228293',
 '23327',
 '19017',
 '344485',
 '1558158',
 '76587',
 '26910',
 '1148665',
 '1932345',
 '555050',
 '121447',
 '73560',
 '151629',
 '23266',
 '4647',
 '101622',
 '112935',
 '27673',
 '18788',
 '32955',
 '242902',
 '90776',
 '105401',
 '843489',
 '18207',
 '36683',
 '15712',
 '14076',
 '9681',
 '219237',
 '1031987',
 '6502',
 '106031',
 '225142',
 '15420',
 '84194',
 '133570',
 '6815',
 '1357000',
 '205081',
 '15850',
 '197853',
 '14293',
 '457924',
 '128345',
 '1407356',
 '103335',
 '23918',
 '269840',
 '161933',
 '20681',
 '90437',
 '114728',
 '129948',
 '126860',
 '9765',
 '2113',
 '748790',
 '17645',
 '120677',
 '108913',
 '88958',
 '15351',
 '396742',
 '182986',
 '10946',
 '35538',
 '14314',
 '479034',
 '22120',
 '488649',
 '7022',
 '133309',
 '37830',
 '102670',
 '233552',
 '92119',
 '79532',
 '146760',
 '15425',
 '8877',
 '448',
 '1117181',
 '132661',
 '2473',
 '164285',
 '11145',
 '1407349',
 '9379',
 '1909580',
 '111964',
 '10329',
 '18137',
 '13676',
 '26442',
 '6326',
 '75046',
 '746557',
 '11138',
 '15463',
 '22402',
 '23936',
 '32442',
 '7607',
 '103543',
 '1900776',
 '1973651',
 '7276',
 '1387',
 '5590',
 '9780',
 '8882',
 '81156',
 '189807',
 '87882',
 '17047',
 '864775',
 '167358',
 '97923',
 '25611',
 '1407055',
 '213595',
 '2175',
 '17512',
 '21907',
 '781',
 '1584920',
 '187188',
 '358658',
 '189862',
 '8610',
 '239821',
 '97945',
 '119644',
 '337441',
 '80187',
 '15355',
 '1310225',
 '254991',
 '91502',
 '1205882',
 '88824',
 '120183',
 '106926',
 '4383',
 '272146',
 '127768',
 '1313596',
 '1522224',
 '25771',
 '23005',
 '5326',
 ...]

In [10]:
from collections import defaultdict

query_id_vs_text = defaultdict(str)

for query in dataset.queries_iter():
    query_id_vs_text[query.query_id] = query.text

In [ ]:
import numpy as np
query_id_and_its_doc = defaultdict(list)

for i in range(len(query_ids)):
    found_doc_list = []
    similarity = scores_of_all_queries[i]

    index_of_found_docs = np.where(similarity > 0)[0]

    for index in list(index_of_found_docs):
        found_doc_list.append((similarity[index], doc_dict[index]))

    if len(found_doc_list) <= 10:
        for mytuple in sorted(found_doc_list, reverse=True):
            query_id_and_its_doc[query_ids[i]].append(mytuple[1])
    else:
        for mytuple in sorted(found_doc_list, reverse=True):
            query_id_and_its_doc[query_ids[i]].append(mytuple[1])

            if len(query_id_and_its_doc[query_ids[i]]) == 10:
                break

In [12]:
import gc
del tokenized
del lematizer
del query_tokenized
gc.collect()

0

In [13]:
del dataset
del lemmatized_words
gc.collect()

0

In [14]:
import ir_datasets
dataset = ir_datasets.load("wikir/en1k/training")

doc_id_vs_text = defaultdict(str)

for doc in dataset.docs_iter():
    doc_id_vs_text[doc.doc_id] = doc.text

In [15]:
del dataset
gc.collect()

0

In [16]:
query_doc_pairs = defaultdict(list)

for query_id in query_ids:
    for doc_id in query_id_and_its_doc[query_id]:
        query_doc_pairs[query_id].append((query_id_vs_text[query_id], doc_id_vs_text[doc_id]))

In [17]:
from sentence_transformers import CrossEncoder
model = CrossEncoder('cross-encoder/ms-marco-MiniLM-L6-v2')

/run/media/tahas44/Yeni Birim/Technarts/Intern/NLP/InformationRetrieval/.venv/lib64/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 105/105 [00:00<00:00, 2522.95it/s]

In [18]:
dict_keys_set = set(query_doc_pairs.keys())

In [19]:
query_score_dict = defaultdict(list)

for query_id in query_ids:
    if query_id in dict_keys_set:
        query_score_dict[query_id] = list(model.predict(query_doc_pairs[query_id]))

In [20]:
query_score_dict["123839"]

[np.float32(6.4627924),
 np.float32(6.419842),
 np.float32(4.9677753),
 np.float32(3.0357656),
 np.float32(5.5189133),
 np.float32(2.3268332),
 np.float32(4.384878),
 np.float32(0.7513137),
 np.float32(-3.6361036),
 np.float32(-4.7235107)]

In [21]:
del query_doc_pairs
gc.collect()

133

In [22]:
most_related_3_dict = defaultdict(list)
most_related_3_dict_with_scores = defaultdict(list)

for query_id in query_ids:
    if query_id in dict_keys_set:
        related_10 = []

        for i, score in enumerate(query_score_dict[query_id]):
            related_10.append((score, i))

        for mytuple in sorted(related_10, reverse=True):
            most_related_3_dict[query_id].append(query_id_and_its_doc[query_id][mytuple[1]])
            most_related_3_dict_with_scores[query_id].append((query_id_and_its_doc[query_id][mytuple[1]], mytuple[0]))

            if len(most_related_3_dict[query_id]) == 3:
                break

In [23]:
most_related_3_dict

defaultdict(list,
            {'123839': ['806300', '123839', '806075'],
             '188629': ['188629', '2185399', '1990307'],
             '13898': ['13898', '2213954', '1698181'],
             '316959': ['316959', '1326263', '930698'],
             '515031': ['515031', '888195', '832086'],
             '123783': ['1210005', '1209576', '123783'],
             '4332': ['4332', '1442076', '989116'],
             '9591': ['143444', '1898638', '2416624'],
             '114982': ['2305139', '2305216', '1341103'],
             '563603': ['12846', '563603', '349302'],
             '104206': ['1281151', '1972988', '104018'],
             '1580851': ['1549040', '2218736', '2187550'],
             '23678': ['23678', '936323', '342272'],
             '37480': ['77763', '305953', '1027733'],
             '109454': ['109454', '2069260', '2100641'],
             '544250': ['544250', '2095411', '630265'],
             '12519': ['1091625', '1739665', '1005711'],
             '115015': ['115015', '1351327', '2202113'],
             '84287': ['84287', '891543', '1422745'],
             '24998': ['2149920', '2339264', '1394401'],
             '11925': ['1148523', '580492', '2108567'],
             '643': ['1115256', '643', '2246138'],
             '113075': ['113075', '572485', '1733437'],
             '1250387': ['1250387', '2217046', '297902'],
             '72012': ['111938', '111443', '72012'],
             '167865': ['167865', '385342', '1964134'],
             '1425120': ['2316655', '1425120', '1083694'],
             '24883': ['24883', '647047', '2393527'],
             '27200': ['2389598', '292569', '1493043'],
             '136856': ['136856', '2272554', '2037574'],
             '6031': ['123675', '975229', '23531'],
             '1313191': ['1313191', '94675', '2158753'],
             '187115': ['187115', '964282', '70941'],
             '84110': ['1987297', '1052069', '1924159'],
             '208234': ['208234', '263739', '1685838'],
             '6431': ['6431', '5400', '510840'],
             '10799': ['10799', '1439685', '242372'],
             '1417144': ['1077838', '1122564', '2168362'],
             '32512': ['28484', '1975061', '4128'],
             '677637': ['122359', '1797233', '677637'],
             '97937': ['2130224', '1604490', '1885628'],
             '113765': ['1807222', '707880', '557100'],
             '12900': ['1150042', '2315670', '326390'],
             '1294909': ['140477', '1437752', '75643'],
             '73745': ['144080', '73745', '55300'],
             '11692': ['11692', '1789375', '2158113'],
             '22173': ['1405463', '1996894', '22173'],
             '76662': ['2261937', '1503801', '1508270'],
             '164301': ['163054', '2352467', '139800'],
             '23344': ['23344', '1911804', '2176190'],
             '9367': ['1080010', '1942436', '1014015'],
             '592217': ['592217', '350482', '1932439'],
             '98546': ['2165734', '98546', '1876890'],
             '98175': ['98175', '1514310', '105110'],
             '15189': ['15189', '2402251', '124228'],
             '1256': ['1256', '113333', '538932'],
             '1815937': ['1815937', '1275085', '204845'],
             '1249076': ['1249076', '271184', '117077'],
             '80274': ['80274', '176310', '150130'],
             '38489': ['461229', '2441739', '282393'],
             '11311': ['77619', '11811', '2445017'],
             '4754': ['4754', '2149205', '1096243'],
             '257711': ['825222', '257711', '408205'],
             '141668': ['1238621', '2148663', '1722747'],
             '100895': ['100895', '1673670', '2077781'],
             '32945': ['32945', '2282975', '1445894'],
             '112321': ['112321', '956494', '107590'],
             '133725': ['133725', '6502', '2123315'],
             '424464': ['18386', '424464', '663519'],
             '523456': ['523456', '414850', '1097635'],
             '1327515': ['2288752', '1327515', '1926176'],
             '12101': ['1602439', '2140400', '1939353'],
             '9739': ['9739', '370163', '473870'],
             '189869': ['367496', '142177', '128794'],
             '143444': ['143444', '1363154', '390102'],
             '78940': ['129940', '400988', '400966'],
             '12527': ['12527', '756172', '1555649'],
             '327199': ['327199', '1121851', '824648'],
             '7707': ['7707', '2080398', '1330041'],
             '97455': ['931552', '97455', '841488'],
             '1262433': ['1262433', '138787', '2096993'],
             '488875': ['488875', '1468866', '924773'],
             '74026': ['74026', '1212400', '1917430'],
             '358108': ['2399039', '203958', '77900'],
             '95179': ['215045', '95179', '833428'],
             '7862': ['31959', '104958', '1213179'],
             '151797': ['151797', '1026962', '308871'],
             '92980': ['92980', '1332097', '2449764'],
             '100876': ['100876', '2091746', '222669'],
             '238228': ['238228', '1379427', '1663108'],
             '107755': ['107755', '44834', '736844'],
             '32539': ['1435368', '32539', '2149417'],
             '12953': ['453850', '198529', '2331536'],
             '24843': ['1585346', '24843', '1642342'],
             '119528': ['119528', '435219', '362056'],
             '30765': ['30765', '1663392', '403630'],
             '134772': ['1747453', '2402212', '1715223'],
             '27711': ['1970676', '27711', '1159074'],
             '361260': ['361260', '1167923', '1139701'],
             '17874': ['987714', '1559204', '17874'],
             '3524': ['1078977', '2406059', '312864'],
             '75902': ['1707214', '1701864', '1294898'],
             '809894': ['809894', '981873', '1929305'],
             '126362': ['126362', '1788275', '847633'],
             '288208': ['2038287', '1028489'],
             '406254': ['406254', '2085523', '1826790'],
             '240663': ['240663', '142967', '1757413'],
             '34848': ['34848', '764750', '35883'],
             '195113': ['195113', '512045', '1278027'],
             '264822': ['264822', '971142', '1546929'],
             '8387': ['961577', '1929813', '228678'],
             '186363': ['186363', '1477370', '307321'],
             '165761': ['165761', '1708821', '2418542'],
             '76875': ['525565', '76875', '1713010'],
             '605155': ['605155', '278103', '1945317'],
             '17836': ['2312089', '681981', '1770705'],
             '83566': ['405127', '1394872', '1592245'],
             '132697': ['132697', '676336', '157351'],
             '1563': ['1618763', '370062', '235562'],
             '23924': ['164214', '1123817', '23924'],
             '1433': ['759076', '1034593', '457952'],
             '29737': ['2013840', '2108118', '29725'],
             '26758': ['26758', '2076571', '783497'],
             '19717': ['19717', '197786', '897561'],
             '7870': ['1485191', '679711', '651143'],
             '16093': ['16093', '88824', '473674'],
             '34844': ['34844', '250649', '2217226'],
             '2234455': ['2234455', '2141640', '1185954'],
             '382531': ['382531', '804041', '1354075'],
             '12252': ['12252', '1352426', '1355090'],
             '11446': ['2235819', '2036847', '2172471'],
             '21027': ['21027', '2360154', '179968'],
             '1370698': ['1980203', '1698174', '1370698'],
             '113657': ['107744', '314346', '677226'],
             '3348': ['1799474', '1044923', '2454319'],
             '217425': ['217425', '1252303', '2087267'],
             '197576': ['197576', '2167463', '583354'],
             '129397': ['129395', '129397', '1876925'],
             '257126': ['257126', '2278890', '1421735'],
             '67592': ['67592', '1222054', '1652321'],
             '93136': ['1763306', '2249779', '2080743'],
             '892237': ['892237', '13602', '1890005'],
             '20605': ['20605', '196435', '2369296'],
             '1219': ['1219', '279916', '1960738'],
             '389032': ['12272', '414013', '640557'],
             '10656': ['2424571', '1275607', '1292547'],
             '1778': ['1778', '1724183', '19019'],
             '108160': ['108160', '1099114', '591392'],
             '964897': ['964897', '1684564', '479549'],
             '94266': ['94266', '649096', '342200'],
             '13744': ['13744', '2190600', '2140823'],
             '13539': ['277538', '1465507', '630127'],
             '407598': ['1971358', '1985313', '407598'],
             '97620': ['1423868', '1774656', '1096878'],
             '203795': ['203795', '2134753', '2381133'],
             '356090': ['356090', '528928', '1535978'],
             '112731': ['1342092', '2147684', '1965175'],
             '714608': ['714608', '1281195', '156180'],
             '88181': ['88181', '656218', '588468'],
             '87960': ['458741', '556337', '587228'],
             '96791': ['96791', '1114237', '181114'],
             '172084': ['283954', '700833', '172084'],
             '1836051': ['1522614', '19342', '93722'],
             '14393': ['580610', '1141467', '699848'],
             '1559299': ['1559299', '1534860', '1889526'],
             '82801': ['82801', '109458', '1633082'],
             '969771': ['1534783', '1529604', '370103'],
             '125685': ['125685', '732193', '1571770'],
             '101336': ['992327', '2442722', '723364'],
             '78856': ['78856', '1374910', '983910'],
             '126985': ['126985', '1035524', '2196806'],
             '231130': ['2177956', '2137040', '2052103'],
             '197161': ['197161', '754196', '1636113'],
             '94693': ['94693', '951006', '1225202'],
             '1339737': ['2151851', '2203733', '1124204'],
             '273381': ['2306578', '1144915', '743550'],
             '73398': ['774600', '813538', '838534'],
             '179677': ['179677', '346430', '809096'],
             '90354': ['90354', '89589', '812990'],
             '1608685': ['856217', '2156109', '1561291'],
             '446634': ['1318941', '2438685', '510967'],
             '1595': ['888134', '1960118', '1499759'],
             '73102': ['840361', '884888', '2297408'],
             '494392': ['494392', '313393', '1986461'],
             '94832': ['94832', '94799', '595508'],
             '24349': ['133149', '24349', '2040373'],
             '12374': ['12374', '639852', '11139'],
             '151391': ['151391', '2344487', '1072063'],
             '584158': ['584158', '16006', '1699242'],
             '15282': ['643115', '15282', '116506'],
             '434927': ['1815312', '434927', '1116176'],
             '21969': ['21969', '1342497', '1569117'],
             '15987': ['1889773', '158483', '491822'],
             '13776': ['140100', '935549', '1448247'],
             '768304': ['178907', '806092', '2415064'],
             '132575': ['132575', '1235422', '1013072'],
             '833105': ['1418862', '1476051', '2404494'],
             '76345': ['969818', '205113', '888259'],
             '537': ['537', '842143', '556979'],
             '181536': ['181536', '362030', '2438006'],
             '4215': ['1363945', '244269', '72988'],
             '17227': ['1222837', '2376958', '168722'],
             '97781': ['2171414', '1551645', '1370210'],
             '1589': ['1589', '80274', '304719'],
             '119663': ['119663', '385340', '1435726'],
             '1336894': ['506495', '1856164', '1843535'],
             '1568489': ['1568489', '367482', '1061347'],
             '133700': ['133700', '1433013', '1247892'],
             '147768': ['147768', '1221847', '1419755'],
             '674995': ['674995', '2377822', '180934'],
             '1047896': ['1047896', '780983', '1613615'],
             '6368': ['6368', '465821', '687049'],
             '172053': ['1001864', '1456217', '172053'],
             '1045273': ['1045273', '690024', '87860'],
             '80687': ['207264', '80687', '2314600'],
             '1263864': ['20711', '1898350', '493275'],
             '81739': ['81739', '396970', '1491329'],
             '113925': ['1182338', '1042610', '113925'],
             '73285': ['73285', '1586232', '1178786'],
             '27399': ['1171402', '1391135', '1085631'],
             '35101': ['35101', '566928', '100840'],
             '5570': ['934088', '15955', '5570'],
             '14758': ['14758', '367980', '512502'],
             '10792': ['10792', '1473373', '308356'],
             '726995': ['726995', '77104', '538799'],
             '17814': ['1176814', '142213', '1729746'],
             '908': ['908', '1143167', '2443105'],
             '85435': ['2017706', '85435', '301309'],
             '79941': ['79941', '1705119', '2320491'],
             '140552': ['140552', '1903014', '727372'],
             '145807': ['145807', '89595', '147835'],
             '107616': ['107616', '497277', '910719'],
             '13801': ['13801', '113055', '1978463'],
             '357261': ['357261', '1017124', '1319850'],
             '34865': ['481179', '34865', '580016'],
             '2259': ['1427998', '753861', '656403'],
             '6213': ['6213', '1387836', '2024782'],
             '72576': ['1231040', '2320928', '512547'],
             '163527': ['2055561', '163527', '1467740'],
             '75654': ['75654', '98297', '1820818'],
             '29687': ['29687', '895773', '1950969'],
             '1283640': ['1476134', '1283640', '2013098'],
             '1703622': ['1703622', '772007', '1391703'],
             '324633': ['324633', '1250916', '1366701'],
             '37756': ['37756', '1366728', '995537'],
             '1237543': ['1138593', '136819', '126571'],
             '342167': ['81830', '111259', '755016'],
             '1058358': ['1058358', '1023064', '2131984'],
             '248154': ['248154', '2189403', '2190309'],
             '330931': ['93973', '2143116', '330931'],
             '163736': ['163736', '1303180', '1890776'],
             '488869': ['1178803', '2033887', '924773'],
             '20603': ['20603', '283895', '897906'],
             '8055': ['8055', '151703', '1866298'],
             '109832': ['598292', '865817', '2389970'],
             '9332': ['1990636', '755333', '701067'],
             '204974': ['204974', '2217571', '1021589'],
             '339255': ['940664', '339255', '166930'],
             '22113': ['22113', '313872', '1045465'],
             '94641': ['94641', '889466', '1469606'],
             '10825': ['1465528', '508584', '609927'],
             '71636': ['71636', '357261', '248592'],
             '2078947': ['2078947', '2404930', '1180183'],
             '146007': ['146007', '2264930', '285611'],
             '11481': ['173680', '145234', '468693'],
             '1282373': ['2000692', '1282373', '1733564'],
             '605568': ['605568', '1531052', '903574'],
             '276580': ['276580', '1420529', '1090231'],
             '190225': ['190225', '670190', '206896'],
             '26652': ['399595', '26652', '582057'],
             '14325': ['2264610', '1965178', '959117'],
             '23815': ['111795', '878233', '9764'],
             '119102': ['119102', '512808', '320954'],
             '17755': ['17755', '2286034', '1129554'],
             '29896': ['1827172', '2152013', '29896'],
             '26093': ['212', '26093', '1960225'],
             '1272415': ['1272415', '103483', '368314'],
             '94442': ['820377', '94442', '259278'],
             '260160': ['260160', '831710', '1326226'],
             '152382': ['152382', '1144288', '1085161'],
             '883324': ['883324', '924389', '270663'],
             '71191': ['71191', '546791', '1994238'],
             '178216': ['1947428', '1722932', '178995'],
             '1408773': ['2299537', '135900', '336814'],
             '6047': ['1604753', '1015150', '2150075'],
             '1410732': ['1410732', '426928', '355299'],
             '37218': ['37218', '28823', '9356'],
             '22295': ['22295', '87884', '7420'],
             '12601': ['1157406', '1248957', '374883'],
             '15200': ['2395461', '15200', '463937'],
             '14027': ['14027', '864128', '878423'],
             '545390': ['951555', '2412623', '936620'],
             '81411': ['81411', '1818443', '1717359'],
             '1324050': ['2360725', '1767051', '834133'],
             '8669': ['8669', '757549', '1555824'],
             '21961': ['253625', '555865', '1774402'],
             '612261': ['612261', '629794', '188621'],
             '389274': ['448913', '875416', '426345'],
             '39839': ['39839', '359154', '943847'],
             '90512': ['90512', '2053492', '2280669'],
             '185712': ['29843', '2165286', '185712'],
             '302505': ['302505', '996027', '1761175'],
             '2623': ['981008', '564954', '1369432'],
             '1343759': ['1343759', '1908559', '1259366'],
             '725960': ['2328179', '1141898', '2328206'],
             '5554': ['1813374', '1366795', '779779'],
             '180826': ['180826', '180911', '604135'],
             '22170': ['1557154', '2275652', '2172104'],
             '203549': ['203549', '1277007', '1196226'],
             '110384': ['1990060', '1715309', '139783'],
             '296861': ['274012', '2190793', '1448193'],
             '6835': ['1561926', '734482', '1059708'],
             '19342': ['19342', '1989270', '452282'],
             '18363': ['401463', '2080162', '18363'],
             '226344': ['1887169', '1531831', '1804944'],
             '37955': ['336539', '556570', '1482801'],
             '19145': ['19145', '624364', '936397'],
             '14445': ['14445', '387702', '703831'],
             '605066': ['605066', '1652640', '258678'],
             '2228': ['2228', '25019', '2217844'],
             '2613': ['2613', '2196563', '795120'],
             '1742574': ['1496601', '448696', '276657'],
             '28296': ['935028', '391441', '1731782'],
             '100963': ['100963', '1704129', '352229'],
             '561358': ['2415964', '561358', '2305586'],
             '13460': ['1443173', '1772373', '1839455'],
             '85285': ['711123', '335898', '1038151'],
             '4925': ['4928', '2349211', '1282390'],
             '104339': ['104339', '512427', '1305612'],
             '183397': ['183397', '752680', '1085027'],
             '156457': ['156457', '971060', '2406253'],
             '284': ['284', '932655', '171976'],
             '34937': ['34937', '293705', '1060010'],
             '76048': ['2121338', '1000256', '667399'],
             '164182': ['164182', '57935', '755531'],
             '411597': ['2369181', '2237418', '901454'],
             '422208': ['1597509', '1539656', '1032457'],
             '3522': ['3522', '262471', '1317353'],
             '73430': ['73430', '2037790', '1654136'],
             '113428': ['113428', '524941', '2393329'],
             '9399': ['9399', '124191', '2260906'],
             '2243': ['2243', '1106758', '2003205'],
             '157351': ['157351', '1700165', '132697'],
             '2842': ['2842', '1183507', '1044261'],
             '377416': ['2230490', '921897', '1081625'],
             '4855': ['1089776', '1623544', '828198'],
             '4397': ['4397', '25238', '1166122'],
             '1846628': ['1846628', '1923701', '2337382'],
             '75969': ['1978945', '826929', '134613'],
             '635597': ['635597', '2229440', '2232303'],
             '2581': ['2184003', '2159251', '192204'],
             '20437': ['20437', '757474', '504454'],
             '76039': ['76039', '2204961', '8681'],
             '9356': ['9356', '993310', '37218'],
             '22213': ['22213', '1183898', '22621'],
             '1250': ['2370725', '102389', '730278'],
             '70969': ['70969', '1601286', '493087'],
             '1349': ['1349', '682999', '77431'],
             '6644': ['371739', '140610', '892870'],
             '103434': ['1487186', '995289', '2311622'],
             '384474': ['384474', '403281', '1887220'],
             '1669212': ['2170507', '2128764', '363241'],

In [24]:
lemmatized_docs = []

for lemma_token_doc in lemmatized_tokenized_docs:
    lemmatized_docs.append(" ".join(lemma_token_doc))

lemmatized_docs

['used landing craft world war ii used today private boat training facility 6 71 inline six cylinder diesel engine 71 refers displacement cubic inch cylinder firing order engine 1 5 3 6 2 4 engine compression ratio 18 7 1 4 250 inch bore 5 00 inch stroke engine weighs 54 inch long 29 inch wide 41 inch tall 2 100 revolution per minute engine capable producing 230 horse power 172 kilowatt v type version 71 series developed 1957 6 71 two stroke engine engine naturally aspirate air provided via root type blower however 6 71t model turbocharger supercharger utilized fuel provided unit injector one per cylinder amount fuel injected engine controlled engine governor engine cooling via liquid water jacket boat cool external water pumped engine',
 'rejecting offer cambridge university moved london 1954 working mayfair advertising agency moonlighting hat check girl night club le club contemporain working royal college art met painter frank bowling still student married 1960 one son kitchen one woman interviewed nell dunn talking woman 1965 divorcing bowling late sixty kitchen went live later marry writer dulan barber continuing write novel also began writing non fiction biography patrick geddes gerard manley hopkins later life bought house barnwell northamptonshire became subject book name died 23 november 2005 novelist bessie head close friend pair corresponded 1969 head death 1986 range subject including head novel question power',
 'mat zan coached kuala lumpur fa 1999 malaysia fa cup 1999 charity cup 2000 2001 mat zan move head coach terengganu fa 2001 malaysia cup 2001 malaysia charity cup second place malaysia league plus f c 2008 took 2nd place premier league automatically promoted malaysia super league 2012 comeback terengganu fa go fa cup semi final round two afc cup 2015 mat zan move melaka united 2015 malaysia fam league 2016 malaysia premier league contract renewed melaka end 2016 appointed new head coach airasia allstars fc renamed petaling jaya ranger f c 2017 season signed 1 year contract negeri sembilan form 2019 season mat zan also coached club side malaysia u 21 squad harimau muda b plate winner singapore starhub league cup thanj nien newspaper cup vietnam 3rd place hassanal bolkiah cup brunei 3rd place',
 'barcode machine readable optical label contains information item attached practice qr code often contain data locator identifier tracker point website application qr code us four standardized encoding mode numeric alphanumeric byte binary kanji store data efficiently extension may also used quick response system became popular outside automotive industry due fast readability greater storage capacity compared standard upc barcodes application include product tracking item identification time tracking document management general marketing qr code consists black square arranged square grid white background read imaging device camera processed using reed solomon error correction image appropriately interpreted required data extracted pattern present horizontal vertical component image qr code system invented 1994 japanese company denso wave purpose track vehicle manufacturing designed allow high speed component scanning qr code used much',
 'since subordination monarchy parliament increasingly democratic method parliamentary government question whether parliament hold supreme ability legislate whether traditional view put forward v dicey parliament power make law except law bound successor reconsidered constitutional theorist including sir william wade trevor allan light european community act 1972 provision relating europe position human right act 1998 attempt make legislation entrenched issue remain contested parliamentary sovereignty description extent parliament united kingdom absolute unlimited power framed term extent authority parliament hold whether sort law pas country written constitution often bind parliament act certain way written constitution united kingdom united kingdom parliament central institution state term',
 'tournament brought together club champion many domestic beach soccer league across europe almost vein uefa champion league twenty team confirmed participation inaugural tournament first beach soccer winner cup held sand san benedetto del tronto rive delle palme located ascoli italy 15 19 may 2013 cup involving champion different official national league across old continent 18 different country represented tournament first stage eighteen champion officially sanctioned beach soccer national championship plus host italian runner got distributed five group yet offering interesting battle powerful team compete head group side topping group granted ticket quarterfinal stage accompanied three best second ranked team stadium used called umpi smart beach arena new state art facility intended maximize technology environmental consciousness directive create stadium offer 360 degree amusement possibility citizen',
 'january 1948 ballen acquired interest goode became sole owner moved company philadelphia pennsylvania label based rest existence 1956 label specialized rhythm blue ivin ballen died miami beach florida february 1978 gotham notable contribution american music release recording acoustic bluesman dan pickett originally recorded 1949 another artist recorded gotham included doug quattlebaum song lizzie lou one last release label doris browne singer around 1949 1950 period performed weekly show broadcast wpen philadelphia hour long show called parisian tailor kiddie hour 1953 label appeared keen push browne profile single please believe bw oh baby backed doc bagby recording also backed single end time bw love gotham g 296 another recording game love bw cherie',
 'particularly notable association several canada leading blue singer including richard hock walsh tony flaim chuck jackson also associated downchild blue band band named cameo lounge toronto hotel isabella 1970s 1980s cameo lounge featured primarily local blue artist 1978 regular house band initially led richard hock walsh one several period walsh either fired quit lead singer downchild blue band walsh soon joined former crowbar keyboard player rabbit ray harrison along guitarist john bride became core group three decade history initial band member included billy bryan later parachute club drum omar tunnock later funk blue band fathead bass hock walsh soon left band return downchild briefly replaced fraser finlayson band cueball prior band finding replacement tony flaim hock walsh replaced downchild billy bryan replaced',
 'also known wamba wamba wemba wemba bear strong similarity woiwurrung moravian missionary came started learn language wembawemba territory archibald macarthur camppbell gannawarra station quickly noted native perceiving understood slipped using another language willing allow cultural conquest enable whitemen learn matter wished keep secret outsider european settlement nineteenth century wemba wemba occupied area around loddon river reaching northward kerang victoria swan hill including area avoca river southward towards quambatook northeasterly direction territory ran new south wale victorian border boorrorban moulamein extended vicinity barham lake boga boora victoria also fell within domain overall extension territory calculated norman tindale roughly wembawemba registered consisting five horde stone list horde residing around towaninny meelool station name indicating thought quarrelsome lake boga gonn murray river called dietjenbaluk always',
 'moved south england cannock staffordshire formed balaam angel initially band self released series ep album entitled sun family via chapter 22 label played tour date opening cult caught attention virgin record signed released debut album greatest story ever told peaked 67 uk album chart august 1986 toured united state mission kiss label mate iggy pop second guitarist first non sibling ian mckean twenty flight rocker added band 1988 band began move away gothic rock music style sound common hard rock new found style recorded album live free die soon followed similar style recorded day madness leaving virgin record song show something special appeared soundtrack film plane train automobile presence largely ignored time 1993 album prime',
 'farming forestry remain central rural economy rural development also focus revitalising rural area way furthermore issue climate change renewable energy biodiversity water management becoming increasingly important aspect eu rural development policy 200 billion funding available support implementation 94 rdps across eu programming period 2007 2013 almost half money provided eafrd overseen european commission directorate general agriculture rural development eafrd budget rdps used achieve variety rural development goal including improving competitiveness farm forest agri food business helping protect natural environment supporting rural economy assisting quality life rural area',
 'died working project great storm 1703 born saffron walden essex baptised 31 march 1644 father henry became land steward earl suffolk owner audley end house 1652 young henry also worked audley end first porter secretary 1666 audley end house bought charles ii use base attending newmarket race became effectively royal palace winstanley developed interest engraving grand tour europe 1669 1674 impressed continental architecture engraving portrayed return believed studied engraving wenceslas hollar employed audley end house assistant clerk work 1676 embarked detailed set architectural engraving audley end house took ten year complete survive important early record english manor house architecture also designed set playing card became popular sold well appointed clerk',
 'grade listed building written history denton go back least 1253 owner one athelstan confused king name made estate see york already owned manorial right nearby otley subinfeuded sub let early date vavasours 1284 maugerus le vavasur held town fourth part knight fee archbishop york continued lord paramount 1379 according poll tax return one adam wayte appears farming manor time denton ordinary reputation clothes making drapery good estate passed ownership thwaites family elizabeth daughter henry thwaites married john vavasour weston died 1482 record show thwaites family resident denton village earlier time marriage 1515 estate passed fairfax family time thomas fairfax 1st lord fairfax cameron denton hall repute housing one best library',
 'elected house representative nigeria 2007 represent ebonyi ohaukwu federal constituency elected platform people democratic party pdp hon elizabeth ogbaga member following committee december 2009 hon elizabeth ogbaga expressed dissatisfaction called low level implementation project contained 2009 budget sponsored numerous bill motion often decried low participation woman politics stating affected democracy hon elizabeth ogbaga attracted various project oxygen plant mammogram machine federal medical centre abakaliki free antenatal care service pregnant mother ebonyi ohaukwu federal constituency construction several 3 classroom block hand pump boreholes onuenyim ishieke ndiofia nkaleke igweledoha ogbala parish effenyim ongoing oterufie nkaleke ndiechi ndiugo isophumini mbeke isophumini st michael parish mbeke ishieke nwonuewo effium ohaukwu ogen ohaukwu umugadu community secondary school also constructed national health care centre izenyi agbaja izzi lga ohagelode ongoing trained 50 youth ict well providing computer accessory hon elizabeth ogbaga constructed bridge across ebonyi river',
 'held annually since 2007 southern bank lake balaton hungary feature live act dj around world established artist new name event co created organizer sziget festival festival get famous popular year ticket usually sold go sale official ticket vendor event set new attendance record yearly first balaton sound festival held 12 july 15 july 2007 fact event held shore largest lake central europe mid summer twenty hour music schedule line gained significant public interest festival located west part zam rdi crossing panor z ldfa utca street inside festival area variable stage lounge tent established performance sponsor festival create luxurious chill facility hammock bean bag easy chair visitor balaton sound stay special campsite several pub cocktail bar restaurant equipped accoutrement absent hungary summer music',
 'co founded phillips collection husband duncan phillips born marjorie acker bourbon indiana sister six sibling parent charles ernest acker alice beal raised ossining new york phillips started drawing child uncle reynolds beal gifford beal men noticed phillips artistic ability suggested pursue art career path began attending art student league 1915 graduated 1918 studied boardman robinson marjorie phillips unmistakable style born painter duncan phillips phillips quoted stating want paint depressing picture painted primarily landscape still life work despite living socialite lifestyle alongside husband phillips made effort paint every morning washington c studio attended art exhibition duncan phillips century association january 1921 met duncan two married october year duncan art collector couple expanded collecting phillips moved washington c duncan dupont circle mansion duncan mother',
 '21 november 1811 21 may 1883 german born british botanist zoologist preiss born herzberg harz obtained doctorate probably hamburg emigrated western australia arrived swan river colony board britmart 4 december 1838 remaining january 1842 time became british subject time western australia preiss collected 200 000 plant specimen containing 3 000 4 000 specie collection together james drummond formed basis early study western australian flora 1842 left western australia london broke sold plant collection recoup cost various botanist published specie based specimen later collated johann lehmann form multi volume plantae preissianae sive enumeratio plantarum quas australasia occidentali et meridionale occidentali annis 1838 41 collegit l published hamburg 1844 1848 specimen collected preiss limited plant included bird reptile insect mollusc mollusc described karl theodor menke published hanover 1843 titled molluscorum',
 'emigrated france family 1956 due rise antisemitism egypt studied cole normale sup rieure de saint cloud sorbonne institut etude politiques de paris rousso notable work includes seminal book vichy france entitled vichy syndrome 1987 coined phrase commonly used describe era pas qui ne passe pa past pas expression possibly inspired ernst nolte june 6 1986 article entitled die vergangenheit die nicht vergehen past want pas away rousso currently serf director research french national centre scientific research cnrs involved since 1981 february 22 2017 rousso detained u custom border protection cbp agent 10 hour arrival george bush intercontinental airport houston nearly deported come give talk texas university detained entering country tourist visa paid stipend talk custom border protection agent',
 'headquarters london united kingdom stopped crowd funding service 2014 doctoral student oxford university vincent developed keen interest work muhammad yunus pioneer microfinance vincent saw peer peer microfinance brilliant alternative traditional method funding innovative idea 2009 financial crisis subsequent cut subsidy hit uk art scene highlighted need alternative community led way raising fund artist innovator prompting vincent launch sponsume site us power social network wisdom crowd help fund variety project ranging film documentary music theatre photography fashion technology scientific research green social enterprise 2012 sponsume helped crowd fund 1000 campaign project owner choose timeframe deadline target funding goal create non monetary reward generally linked project site levy 4 fee successful campaign collect 9 campaign failed reach target amount',
 'composed traditional tribe loteae sesbanieae robinieae large important clade distributed mostly temperate area specie clade share unique determinate root nodule structure clade predicted diverged legume lineage 48 3 1 0 million year ago eocene two tribe loteae robinieae traditionally included clade robinioids lavin schrire later included sesbanieae clade robinioids tribe robinieae primarily tropical arid temperate area containing mostly tree shrub new world tribe loteae herbaceous small shrubby legume closely related old world tribe galegeae loteae originally smaller group legume later 1994 polhill merged loteae tribe coronilleae greatly expanded loteae sesbanieae tribe single genus sesbania originally placed tribe robinieae loteae robinieae traditionally grouped clade robinioids two major group primarily found europe north america south america sesbanieae group included 2005 monophyly monophyly tribe loteae molecular data shown support monophyly exception new world lotus monophyly old',
 'south american conglomerate created owned germ n efromovich entrepreneur holding multiple citizenship brazil colombia poland group headquartered rio de janeiro brazil operates several airline south america among avianca holding 66 66 stake active exploration oil natural gas throughout region additionally operates hydroelectric power plant participates construction telecommunication infrastructure shipbuilding technical inspection radiochemistry radiopharmaceutical agriculture hospitality synergy group integrated airline company taca avianca holding company avianca holding synergy group owns 66 66 newly created subsidiary company kingsland holding el salvador owns 33 33 avianca taca synergy aerospace corp sub division synergy group headquartered bogota colombia major shareholder avianca holding company control eight airline four country avianca tampa cargo colombia avianca brazil variglog synerjet brazil vip aerogal ecuador grupo taca el salvador november 2012 synergy aerospace corp established synergy aerospace europe synergy aerospace established joint venture march 2011',
 'army regimental system headquarters stow ohio currently consists 1st battalion 145th armored regiment 900 soldier combined arm battalion ohio army national guard located throughout northeast ohio command control purpose within ohio army national guard 1st battaltion 145th armored regiment subordinate battalion 174th air defense artillery brigade 2013 battalion entered alignment training relationship 1st armored brigade combat team 34th infantry division may 2016 battalion donned shoulder sleeve insignia 34th infantry division anticipation formal alignment 1st armored brigade combat team september 2016 combined arm battalion 1st battalion 145th armored regiment able deploy two mechanized infantry company two armor company support company headquarters company battalion headquarters order accomplish federal state community mission headquarters company hhc four line company organic battalion combined arm battalion traditionally receive support company organic brigade support battalion bsb since battalion organic armored brigade combat team abct 737th support company',
 'unexpected object case morphology deemed exceptional term ecm coined government binding grammar framework although phenomenon closely related accusativus cum infinitivo construction latin ecm construction also studied within context raising verb license ecm known raising object verb many language lack ecm predicate even english number ecm verb small structural analysis ecm construction varies part according whether one pursues relatively flat structure layered one ecm construction licensed relatively small number verb english e g believe judge prove want let etc string bold ecm construction pronoun marked object case morphology function semantically subject infinitival verb right e acquire theta role verb right many ecm verb allow meaning expressed full object clause finite clause e g since meaning across clause remains consistent one tendency view ecm material e',

In [25]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf_idf_vect = TfidfVectorizer()
tf_idf_matrix = tf_idf_vect.fit_transform(lemmatized_docs)
print("TF-IDF matrix ready!")

TF-IDF matrix ready!

In [26]:
type(tf_idf_vect)

sklearn.feature_extraction.text.TfidfVectorizer

In [27]:
tf_idf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 32486544 stored elements and shape (369721, 772603)>

In [28]:
type(tf_idf_matrix)

scipy.sparse._csr.csr_matrix

In [29]:
tf_idf_vect.get_feature_names_out()

array(['00', '000', '0000', ..., 'zzt', 'zzx', 'zzz'],
      shape=(772603,), dtype=object)

In [30]:
import numpy as np
import scipy
import sklearn.feature_extraction.text

def get_top_word(tf_idf_matrix: scipy.sparse._csr.csr_matrix, 
                 tf_idf_vect: sklearn.feature_extraction.text.TfidfVectorizer,
                 doc_index: int):

    row = tf_idf_matrix[doc_index]

    if row.nnz == 0:
        return None

    max_index = np.argmax(row.data)
    top_feature_index = row.indices[max_index]
    feature_names = tf_idf_vect.get_feature_names_out()
    top_term = feature_names[top_feature_index]

    return top_term

In [31]:
for key, value in doc_dict.items():
    print(key, value)
    break

0 1781133

In [32]:
doc_id_vs_index = defaultdict(int)

for key, value in doc_dict.items():
    doc_id_vs_index[value] = key

doc_id_vs_index = dict(doc_id_vs_index)

In [33]:
doc_id_vs_index

{'1781133': 0,
 '2426736': 1,
 '2224122': 2,
 '219642': 3,
 '1728654': 4,
 '1889917': 5,
 '1518473': 6,
 '1459418': 7,
 '1102956': 8,
 '931408': 9,
 '1043905': 10,
 '488327': 11,
 '1069841': 12,
 '1601336': 13,
 '1415191': 14,
 '1531137': 15,
 '912052': 16,
 '935016': 17,
 '1671729': 18,
 '1946935': 19,
 '752649': 20,
 '1634473': 21,
 '867034': 22,
 '1064413': 23,
 '1612321': 24,
 '2222141': 25,
 '1784663': 26,
 '2285161': 27,
 '1445565': 28,
 '1469713': 29,
 '1466972': 30,
 '963723': 31,
 '897432': 32,
 '1218994': 33,
 '839556': 34,
 '2170795': 35,
 '1024270': 36,
 '1336432': 37,
 '2087053': 38,
 '421312': 39,
 '547088': 40,
 '636479': 41,
 '2166683': 42,
 '833090': 43,
 '2363592': 44,
 '2289234': 45,
 '1370298': 46,
 '1481866': 47,
 '1763284': 48,
 '1876607': 49,
 '729433': 50,
 '352078': 51,
 '2354924': 52,
 '2416742': 53,
 '1283366': 54,
 '1602376': 55,
 '1301443': 56,
 '1962423': 57,
 '2436983': 58,
 '79923': 59,
 '490168': 60,
 '502902': 61,
 '1738343': 62,
 '52687': 63,
 '503290': 64,
 '443815': 65,
 '2259227': 66,
 '1375558': 67,
 '488452': 68,
 '341885': 69,
 '2329563': 70,
 '328166': 71,
 '2305145': 72,
 '2243061': 73,
 '705605': 74,
 '1548811': 75,
 '1316555': 76,
 '1924943': 77,
 '350851': 78,
 '526876': 79,
 '759572': 80,
 '747365': 81,
 '1416073': 82,
 '2161217': 83,
 '1760290': 84,
 '1915270': 85,
 '1051703': 86,
 '1052256': 87,
 '51110': 88,
 '890294': 89,
 '1500765': 90,
 '1020455': 91,
 '495371': 92,
 '452464': 93,
 '1222862': 94,
 '1008941': 95,
 '1313953': 96,
 '414617': 97,
 '578027': 98,
 '1834363': 99,
 '247020': 100,
 '42650': 101,
 '404210': 102,
 '670777': 103,
 '1922332': 104,
 '1682663': 105,
 '827043': 106,
 '2124360': 107,
 '608864': 108,
 '867166': 109,
 '1146005': 110,
 '1716457': 111,
 '1580743': 112,
 '22915': 113,
 '581042': 114,
 '396072': 115,
 '1019762': 116,
 '275841': 117,
 '718113': 118,
 '1790396': 119,
 '2384572': 120,
 '2431285': 121,
 '73954': 122,
 '1749729': 123,
 '114691': 124,
 '1104339': 125,
 '268946': 126,
 '153113': 127,
 '134078': 128,
 '464565': 129,
 '2360440': 130,
 '495715': 131,
 '911987': 132,
 '2268633': 133,
 '450461': 134,
 '316757': 135,
 '849228': 136,
 '2194712': 137,
 '1703458': 138,
 '1939650': 139,
 '445183': 140,
 '401713': 141,
 '1149390': 142,
 '1377678': 143,
 '905625': 144,
 '1779127': 145,
 '1206213': 146,
 '593339': 147,
 '1664601': 148,
 '2045297': 149,
 '1953838': 150,
 '2090914': 151,
 '691051': 152,
 '284438': 153,
 '654194': 154,
 '1265726': 155,
 '1375028': 156,
 '378122': 157,
 '2162101': 158,
 '977792': 159,
 '1834965': 160,
 '263667': 161,
 '46367': 162,
 '91316': 163,
 '1265402': 164,
 '2260142': 165,
 '1215949': 166,
 '623528': 167,
 '771594': 168,
 '2244237': 169,
 '1807346': 170,
 '1321756': 171,
 '1176208': 172,
 '1637068': 173,
 '662640': 174,
 '2053593': 175,
 '89775': 176,
 '872240': 177,
 '1037188': 178,
 '1350565': 179,
 '1891236': 180,
 '2151546': 181,
 '491822': 182,
 '1604560': 183,
 '856805': 184,
 '2332243': 185,
 '985747': 186,
 '1916645': 187,
 '803876': 188,
 '2061324': 189,
 '1181449': 190,
 '1870723': 191,
 '901697': 192,
 '1139510': 193,
 '922548': 194,
 '2126952': 195,
 '171163': 196,
 '1397238': 197,
 '2200542': 198,
 '46623': 199,
 '2302994': 200,
 '908830': 201,
 '1108217': 202,
 '1762061': 203,
 '778753': 204,
 '546558': 205,
 '243476': 206,
 '967012': 207,
 '1993152': 208,
 '1391104': 209,
 '1271541': 210,
 '1581840': 211,
 '1436736': 212,
 '816566': 213,
 '1952483': 214,
 '1398534': 215,
 '1827655': 216,
 '799015': 217,
 '525690': 218,
 '267100': 219,
 '1244147': 220,
 '2431816': 221,
 '434489': 222,
 '2195412': 223,
 '1297422': 224,
 '433384': 225,
 '1900623': 226,
 '848515': 227,
 '1109677': 228,
 '2287975': 229,
 '1494638': 230,
 '408808': 231,
 '1463765': 232,
 '1178270': 233,
 '1099386': 234,
 '2273701': 235,
 '1212855': 236,
 '191802': 237,
 '779232': 238,
 '1956103': 239,
 '1907561': 240,
 '1050909': 241,
 '1092146': 242,
 '1976572': 243,
 '1248392': 244,
 '616195': 245,
 '2000404': 246,
 '2423357': 247,
 '659650': 248,
 '1547506': 249,
 '1529752': 250,
 '2005282': 251,
 '244754': 252,
 '185103': 253,
 '975603': 254,
 '1872273': 255,
 '1414512': 256,
 '2253053': 257,
 '542284': 258,
 '1516646': 259,
 '505354': 260,
 '1200601': 261,
 '400449': 262,
 '1945483': 263,
 '817499': 264,
 '2383527': 265,
 '695229': 266,
 '786119': 267,
 '506869': 268,
 '1223626': 269,
 '244051': 270,
 '1650199': 271,
 '1066802': 272,
 '720765': 273,
 '1699108': 274,
 '799610': 275,
 '1614679': 276,
 '292346': 277,
 '2228498': 278,
 '706641': 279,
 '163689': 280,
 '275855': 281,
 '2013685': 282,
 '1303464': 283,
 '1655861': 284,
 '1192671': 285,
 '1491150': 286,
 '1200714': 287,
 '1837262': 288,
 '1176211': 289,
 '1049101': 290,
 '353368': 291,
 '205080': 292,
 '1945843': 293,
 '2116027': 294,
 '2354390': 295,
 '1219364': 296,
 '1438170': 297,
 '648610': 298,
 '1473407': 299,
 '99657': 300,
 '1709368': 301,
 '1725791': 302,
 '1080344': 303,
 '934301': 304,
 '46682': 305,
 '91666': 306,
 '1345430': 307,
 '419878': 308,
 '1485719': 309,
 '1873128': 310,
 '757275': 311,
 '1403894': 312,
 '1673417': 313,
 '584763': 314,
 '1723712': 315,
 '2069560': 316,
 '1044169': 317,
 '555596': 318,
 '1856044': 319,
 '623221': 320,
 '1995291': 321,
 '366576': 322,
 '163766': 323,
 '558726': 324,
 '1073420': 325,
 '2450395': 326,
 '1051928': 327,
 '2312649': 328,
 '1446100': 329,
 '1391289': 330,
 '1101117': 331,
 '2408947': 332,
 '2081828': 333,
 '171510': 334,
 '2077207': 335,
 '1480579': 336,
 '152050': 337,
 '654923': 338,
 '932418': 339,
 '884779': 340,
 '2274110': 341,
 '158459': 342,
 '347765': 343,
 '1777683': 344,
 '648665': 345,
 '623412': 346,
 '68156': 347,
 '766917': 348,
 '2107567': 349,
 '1175233': 350,
 '559683': 351,
 '1860418': 352,
 '1795667': 353,
 '1641718': 354,
 '574117': 355,
 '1620310': 356,
 '588350': 357,
 '427966': 358,
 '972640': 359,
 '1292812': 360,
 '1356702': 361,
 '1445684': 362,
 '1803479': 363,
 '1870842': 364,
 '552668': 365,
 '650568': 366,
 '984901': 367,
 '1529682': 368,
 '474981': 369,
 '1956869': 370,
 '1183594': 371,
 '1466062': 372,
 '1882592': 373,
 '476247': 374,
 '1807325': 375,
 '800099': 376,
 '1726336': 377,
 '1440063': 378,
 '1495226': 379,
 '2115864': 380,
 '1458026': 381,
 '1082122': 382,
 '390760': 383,
 '1851753': 384,
 '2279163': 385,
 '343570': 386,
 '1254450': 387,
 '1055404': 388,
 '2220055': 389,
 '1797122': 390,
 '14788': 391,
 '1810127': 392,
 '1579833': 393,
 '1370153': 394,
 '1841256': 395,
 '1494651': 396,
 '2323590': 397,
 '2066901': 398,
 '1604353': 399,
 '2139078': 400,
 '1737480': 401,
 '1236792': 402,
 '1875980': 403,
 '2407778': 404,
 '1786772': 405,
 '1267642': 406,
 '1067024': 407,
 '2037941': 408,
 '345640': 409,
 '833080': 410,
 '485187': 411,
 '349322': 412,
 '534282': 413,
 '388444': 414,
 '17745': 415,
 '1969335': 416,
 '1537515': 417,
 '1436720': 418,
 '1862274': 419,
 '1488513': 420,
 '1422369': 421,
 '2435239': 422,
 '1287083': 423,
 '2189972': 424,
 '702421': 425,
 '1742534': 426,
 '6320': 427,
 '1616636': 428,
 '299284': 429,
 '732296': 430,
 '1985759': 431,
 '1702879': 432,
 '362047': 433,
 '376188': 434,
 '1495839': 435,
 '63546': 436,
 '1752379': 437,
 '1136718': 438,
 '450285': 439,
 '1356906': 440,
 '354903': 441,
 '1316363': 442,
 '1826749': 443,
 '2123091': 444,
 '48847': 445,
 '1102397': 446,
 '1013641': 447,
 '1576938': 448,
 '130525': 449,
 '911160': 450,
 '525908': 451,
 '767129': 452,
 '2396957': 453,
 '639344': 454,
 '1267370': 455,
 '2346755': 456,
 '1021068': 457,
 '619144': 458,
 '301736': 459,
 '216249': 460,
 '2114779': 461,
 '59666': 462,
 '1974356': 463,
 '2216600': 464,
 '489896': 465,
 '46973': 466,
 '1687126': 467,
 '668492': 468,
 '2118536': 469,
 '873714': 470,
 '315108': 471,
 '213039': 472,
 '1233285': 473,
 '831616': 474,
 '156093': 475,
 '1843132': 476,
 '827610': 477,
 '1406414': 478,
 '1404779': 479,
 '1199316': 480,
 '1363803': 481,
 '1626543': 482,
 '1896258': 483,
 '1375114': 484,
 '1648022': 485,
 '2305969': 486,
 '1621203': 487,
 '419572': 488,
 '1942794': 489,
 '2179059': 490,
 '1473371': 491,
 '1861654': 492,
 '2097080': 493,
 '961043': 494,
 '2340793': 495,
 '1296527': 496,
 '1676613': 497,
 '1731527': 498,
 '1631593': 499,
 '1939015': 500,
 '2293112': 501,
 '416818': 502,
 '645193': 503,
 '1394832': 504,
 '184790': 505,
 '1723971': 506,
 '11904': 507,
 '2124902': 508,
 '1195960': 509,
 '625837': 510,
 '1085126': 511,
 '2341992': 512,
 '1757853': 513,
 '1788677': 514,
 '1317778': 515,
 '51808': 516,
 '1038364': 517,
 '2423882': 518,
 '619314': 519,
 '764545': 520,
 '1690412': 521,
 '358455': 522,
 '1440482': 523,
 '1311247': 524,
 '621376': 525,
 '1876473': 526,
 '649143': 527,
 '1073137': 528,
 '2218039': 529,
 '1369906': 530,
 '914474': 531,
 '445831': 532,
 '1535993': 533,
 '1476328': 534,
 '2056359': 535,
 '1561': 536,
 '319078': 537,
 '139624': 538,
 '1717853': 539,
 '278413': 540,
 '2266376': 541,
 '130843': 542,
 '1642797': 543,
 '689598': 544,
 '1819802': 545,
 '2297570': 546,
 '1706190': 547,
 '1748911': 548,
 '471380': 549,
 '760624': 550,
 '1350053': 551,
 '1996237': 552,
 '2188281': 553,
 '1152117': 554,
 '196795': 555,
 '177478': 556,
 '420550': 557,
 '680594': 558,
 '1787392': 559,
 '1082432': 560,
 '1447927': 561,
 '2034876': 562,
 '1058159': 563,
 '1790879': 564,
 '547773': 565,
 '336620': 566,
 '1324779': 567,
 '522837': 568,
 '760244': 569,
 '1187825': 570,
 '1593535': 571,
 '418064': 572,
 '2161778': 573,
 '1770607': 574,
 '2296376': 575,
 '74455': 576,
 '481449': 577,
 '902151': 578,
 '1872235': 579,
 '1479225': 580,
 '232588': 581,
 '1762263': 582,
 '1578496': 583,
 '1272164': 584,
 '466611': 585,
 '1476120': 586,
 '2406781': 587,
 '557176': 588,
 '602881': 589,
 '1684794': 590,
 '572594': 591,
 '1369147': 592,
 '228276': 593,
 '490008': 594,
 '2445392': 595,
 '609296': 596,
 '2015504': 597,
 '1092073': 598,
 '1929302': 599,
 '2232136': 600,
 '2153506': 601,
 '189869': 602,
 '1997231': 603,
 '769369': 604,
 '1453209': 605,
 '1382040': 606,
 '1440872': 607,
 '1172918': 608,
 '1274248': 609,
 '587440': 610,
 '2315585': 611,
 '56032': 612,
 '2265557': 613,
 '640174': 614,
 '742105': 615,
 '198861': 616,
 '1846895': 617,
 '1831487': 618,
 '363709': 619,
 '1853099': 620,
 '1300577': 621,
 '1479629': 622,
 '1227950': 623,
 '204351': 624,
 '408665': 625,
 '371535': 626,
 '936815': 627,
 '1245563': 628,
 '2228749': 629,
 '1578090': 630,
 '1633341': 631,
 '833753': 632,
 '2365374': 633,
 '1444531': 634,
 '1957958': 635,
 '130292': 636,
 '2117506': 637,
 '1134389': 638,
 '1643482': 639,
 '1344207': 640,
 '286435': 641,
 '1291504': 642,
 '796098': 643,
 '1031914': 644,
 '1994268': 645,
 '1649013': 646,
 '1581957': 647,
 '187930': 648,
 '1001551': 649,
 '1831109': 650,
 '1768943': 651,
 '903194': 652,
 '1699617': 653,
 '439607': 654,
 '879740': 655,
 '2339742': 656,
 '1640380': 657,
 '907976': 658,
 '1134597': 659,
 '1743367': 660,
 '1948774': 661,
 '2268635': 662,
 '739777': 663,
 '2332797': 664,
 '2172875': 665,
 '2162452': 666,
 '2272841': 667,
 '1219336': 668,
 '930688': 669,
 '1082950': 670,
 '1281750': 671,
 '1651054': 672,
 '2246520': 673,
 '238859': 674,
 '1955775': 675,
 '2206862': 676,
 '2198819': 677,
 '299009': 678,
 '12699': 679,
 '80289': 680,
 '1756314': 681,
 '1666885': 682,
 '521269': 683,
 '1586850': 684,
 '2309594': 685,
 '16130': 686,
 '732539': 687,
 '1278079': 688,
 '1240802': 689,
 '735389': 690,
 '2285691': 691,
 '1436117': 692,
 '1141961': 693,
 '1227396': 694,
 '284213': 695,
 '838659': 696,
 '1085595': 697,
 '1222277': 698,
 '1261009': 699,
 '761095': 700,
 '2374850': 701,
 '1924303': 702,
 '94174': 703,
 '587031': 704,
 '2343378': 705,
 '1360854': 706,
 '1651218': 707,
 '150455': 708,
 '1675537': 709,
 '486042': 710,
 '1687393': 711,
 '2111603': 712,
 '1866031': 713,
 '92993': 714,
 '808499': 715,
 '630308': 716,
 '279165': 717,
 '38860': 718,
 '1051260': 719,
 '117925': 720,
 '1405501': 721,
 '1636589': 722,
 '1428707': 723,
 '590139': 724,
 '1951207': 725,
 '376531': 726,
 '2195727': 727,
 '916079': 728,
 '1852911': 729,
 '660914': 730,
 '301977': 731,
 '146612': 732,
 '38481': 733,
 '111997': 734,
 '1438246': 735,
 '1541865': 736,
 '2262357': 737,
 '732893': 738,
 '721263': 739,
 '66628': 740,
 '1136220': 741,
 '507466': 742,
 '223970': 743,
 '983584': 744,
 '1314723': 745,
 '548960': 746,
 '142185': 747,
 '154120': 748,
 '1132551': 749,
 '414725': 750,
 '2256244': 751,
 '948107': 752,
 '2012196': 753,
 '1446924': 754,
 '893863': 755,
 '21209': 756,
 '1436432': 757,
 '2373688': 758,
 '171515': 759,
 '1097033': 760,
 '438752': 761,
 '1928336': 762,
 '1865684': 763,
 '2287888': 764,
 '2446304': 765,
 '2056171': 766,
 '2371390': 767,
 '609990': 768,
 '1516592': 769,
 '1970590': 770,
 '2178443': 771,
 '635893': 772,
 '468029': 773,
 '52949': 774,
 '383321': 775,
 '1342771': 776,
 '1919812': 777,
 '1485194': 778,
 '2146945': 779,
 '784366': 780,
 '385494': 781,
 '1767191': 782,
 '632660': 783,
 '2104824': 784,
 '47063': 785,
 '1889894': 786,
 '1024600': 787,
 '1148670': 788,
 '592419': 789,
 '1773765': 790,
 '1873586': 791,
 '2359398': 792,
 '1905931': 793,
 '1815085': 794,
 '1656129': 795,
 '335995': 796,
 '1965384': 797,
 '1762869': 798,
 '1251703': 799,
 '969401': 800,
 '2033506': 801,
 '354200': 802,
 '1266900': 803,
 '1113459': 804,
 '380953': 805,
 '2229904': 806,
 '2018592': 807,
 '826394': 808,
 '2132423': 809,
 '1680926': 810,
 '1872997': 811,
 '2418607': 812,
 '1041047': 813,
 '1449595': 814,
 '1736239': 815,
 '1031682': 816,
 '1329831': 817,
 '1095995': 818,
 '2367619': 819,
 '993318': 820,
 '2194219': 821,
 '2229948': 822,
 '287440': 823,
 '1155498': 824,
 '537397': 825,
 '1950155': 826,
 '938318': 827,
 '1025705': 828,
 '1641586': 829,
 '2424136': 830,
 '286304': 831,
 '545582': 832,
 '1533985': 833,
 '12232': 834,
 '1762934': 835,
 '1124533': 836,
 '2229616': 837,
 '1909556': 838,
 '1527768': 839,
 '359481': 840,
 '604517': 841,
 '309360': 842,
 '614037': 843,
 '1647274': 844,
 '2156713': 845,
 '1643649': 846,
 '1820555': 847,
 '1098380': 848,
 '1512557': 849,
 '242173': 850,
 '271517': 851,
 '1028446': 852,
 '2051504': 853,
 '2266051': 854,
 '2291029': 855,
 '652227': 856,
 '804473': 857,
 '1483902': 858,
 '400538': 859,
 '1887435': 860,
 '2237341': 861,
 '566998': 862,
 '488489': 863,
 '1924166': 864,
 '2112900': 865,
 '1101595': 866,
 '2020287': 867,
 '462531': 868,
 '629117': 869,
 '885073': 870,
 '191368': 871,
 '1812443': 872,
 '1756375': 873,
 '735779': 874,
 '1062964': 875,
 '533989': 876,
 '1165107': 877,
 '686158': 878,
 '405385': 879,
 '2126114': 880,
 '629453': 881,
 '846051': 882,
 '499850': 883,
 '1784961': 884,
 '2427578': 885,
 '1681668': 886,
 '982671': 887,
 '920311': 888,
 '660323': 889,
 '2129233': 890,
 '2071199': 891,
 '962689': 892,
 '1573765': 893,
 '2359686': 894,
 '1466305': 895,
 '1971570': 896,
 '1920078': 897,
 '1108997': 898,
 '188681': 899,
 '1576641': 900,
 '2086790': 901,
 '1533076': 902,
 '2239180': 903,
 '2218321': 904,
 '274722': 905,
 '178885': 906,
 '2455917': 907,
 '951927': 908,
 '1133459': 909,
 '941904': 910,
 '384165': 911,
 '2403371': 912,
 '1966183': 913,
 '1316007': 914,
 '195274': 915,
 '1601355': 916,
 '430553': 917,
 '1126316': 918,
 '582858': 919,
 '1462125': 920,
 '2365679': 921,
 '193074': 922,
 '153103': 923,
 '986476': 924,
 '745513': 925,
 '404080': 926,
 '1384312': 927,
 '480911': 928,
 '1307019': 929,
 '1531457': 930,
 '869671': 931,
 '49322': 932,
 '2288218': 933,
 '1387161': 934,
 '2069937': 935,
 '1857115': 936,
 '1922545': 937,
 '849558': 938,
 '2086065': 939,
 '2331954': 940,
 '533423': 941,
 '424509': 942,
 '1631900': 943,
 '446545': 944,
 '2202373': 945,
 '493674': 946,
 '2064636': 947,
 '259203': 948,
 '998120': 949,
 '1180634': 950,
 '2233350': 951,
 '360535': 952,
 '55162': 953,
 '1078539': 954,
 '1301705': 955,
 '1881708': 956,
 '1742484': 957,
 '1361665': 958,
 '50844': 959,
 '1865783': 960,
 '2084891': 961,
 '1401872': 962,
 '2120927': 963,
 '1736528': 964,
 '1365969': 965,
 '1107669': 966,
 '1450156': 967,
 '833029': 968,
 '359352': 969,
 '1593533': 970,
 '2369938': 971,
 '1054325': 972,
 '301441': 973,
 '206354': 974,
 '1739835': 975,
 '1151438': 976,
 '992200': 977,
 '1641803': 978,
 '955358': 979,
 '376471': 980,
 '2440088': 981,
 '465571': 982,
 '1023220': 983,
 '767350': 984,
 '1504828': 985,
 '426776': 986,
 '1328473': 987,
 '131842': 988,
 '1114130': 989,
 '889313': 990,
 '2309833': 991,
 '621430': 992,
 '320332': 993,
 '2326300': 994,
 '2245701': 995,
 '1325860': 996,
 '2370375': 997,
 '239812': 998,
 '1570369': 999,
 ...}

In [34]:
doc_id_vs_index["806300"]

170443

In [35]:
get_top_word(tf_idf_matrix, tf_idf_vect, 170443)

'yanni'

In [36]:
doc_id_vs_text["806300"]

'it is a compilation of tracks from his five previous studio albums released between 1980 and 1989 plus three new compositions yanni was encouraged to release the album by his then partner actress linda evans reflections of passion became yanni s fastest selling and most successful album of his career upon release it reached no 1 on the billboard top new age albums chart and no 29 on the billboard 200 yanni supported the album with a nationwide concert tour in 1990 that featured his band and an orchestra in 1995 it was certified double platinum for selling 2 million copies in the us in august 1989 yanni released his fifth studio album niki nana the album marked his stylistic development from solo keyboard music towards rock with the addition of additional vocalists musicians and choir around the same time of its release yanni s newfound relationship with american actress linda evans who had become a fan of his music received press attention not long into their relationship evans pitched an idea she had for an album from yanni which was long in duration reflected a single mood throughout and something that she could play at dinner parties she mentioned'

In [37]:
counter = 0

for word in doc_id_vs_text["806300"].split():
    if word == "yanni":
        counter += 1

counter

6

In [38]:
lemmatized_tokenized_queries

[['yanni'],
 ['k', 'pop'],
 ['venice', 'film', 'festival'],
 ['downtown', 'brooklyn'],
 ['pennsylvania', 'house', 'representative'],
 ['northern', 'premier', 'league'],
 ['first', 'national', 'picture'],
 ['poland'],
 ['cyperaceae'],
 ['trinidad', 'tobago'],
 ['normandy', 'landing'],
 ['perry', 'index'],
 ['arm', 'architecture'],
 ['mi5'],
 ['patriarch', 'antioch'],
 ['nashik', 'district'],
 ['semiotics'],
 ['santa', 'cruz', 'de', 'tenerife'],
 ['gastropoda'],
 ['zaragoza'],
 ['south', 'carolina'],
 ['augustine', 'hippo'],
 ['canton', 'geneva'],
 ['leo', 'tolstoy'],
 ['riemannian', 'manifold'],
 ['tuzla'],
 ['subaru'],
 ['tomsk'],
 ['united', 'state', 'department', 'agriculture'],
 ['north', 'borneo'],
 ['isaac', 'asimov'],
 ['hilbert', 'space'],
 ['chechen'],
 ['arunachal', 'pradesh'],
 ['central', 'otago'],
 ['ira', 'gershwin'],
 ['rock', 'roll'],
 ['fiba'],
 ['east', 'coast', 'united', 'state'],
 ['wikipedia'],
 ['pernambuco'],
 ['west', 'coast', 'eagle'],
 ['twin', 'peak'],
 ['dutch', 'language'],
 ['liberal', 'party', 'canada'],
 ['spratly', 'island'],
 ['kampala'],
 ['national', 'film', 'board', 'canada'],
 ['turkish', 'war', 'independence'],
 ['chania'],
 ['oakland', 'raider'],
 ['krishnagiri', 'district'],
 ['vr', 'group'],
 ['trade', 'name'],
 ['anglo', 'saxon'],
 ['bermuda'],
 ['paradox', 'development', 'studio'],
 ['usenet'],
 ['bbc', 'radio'],
 ['wallace', 'stevens'],
 ['spain'],
 ['franchising'],
 ['united', 'artist', 'record'],
 ['royal', 'corp', 'signal'],
 ['palawan'],
 ['seine', 'et', 'marne'],
 ['west', 'country'],
 ['bailiwick', 'guernsey'],
 ['pleuronectidae'],
 ['income', 'tax', 'united', 'state'],
 ['gp3', 'series'],
 ['septimius', 'severus'],
 ['pharaoh'],
 ['metropolitan', 'borough', 'doncaster'],
 ['history', 'jew', 'poland'],
 ['erasure'],
 ['suez', 'canal'],
 ['naval', 'air', 'station', 'lemoore'],
 ['lower', 'saxony'],
 ['robert', 'stack'],
 ['boeing'],
 ['wexford', 'gaa'],
 ['miss', 'universe'],
 ['sydney', 'central', 'business', 'district'],
 ['keweenaw', 'peninsula'],
 ['music'],
 ['nba', 'g', 'league'],
 ['makati'],
 ['genre', 'art'],
 ['aintree', 'racecourse'],
 ['colchester'],
 ['christian', 'rock'],
 ['clash'],
 ['friedrich', 'schiller'],
 ['comedy', 'drama'],
 ['tiberias'],
 ['fc', 'basel'],
 ['new', 'york', 'knicks'],
 ['perm', 'krai'],
 ['dordogne'],
 ['dutch', 'west', 'india', 'company'],
 ['titian'],
 ['victorian', 'burlesque'],
 ['tvb'],
 ['muridae'],
 ['tvxq'],
 ['kenneth', 'cope'],
 ['london', 'borough', 'islington'],
 ['top', 'cow', 'production'],
 ['bradford', 'bull'],
 ['mike', 'oldfield'],
 ['shooter', 'game'],
 ['hull', 'kingston', 'rover'],
 ['national', 'science', 'foundation'],
 ['grau'],
 ['dannii', 'minogue'],
 ['christopher', 'nolan'],
 ['moscow', 'oblast'],
 ['british', 'national', 'party'],
 ['balochi', 'language'],
 ['benjamin', 'franklin'],
 ['big', 'south', 'conference'],
 ['cantabria'],
 ['alice', 'chain'],
 ['michigan'],
 ['soundgarden'],
 ['bermondsey'],
 ['2017', 'ncaa', 'division', 'fbs', 'football', 'season'],
 ['northwestern', 'united', 'state'],
 ['southeast', 'asia'],
 ['social', 'psychology'],
 ['john', 'coltrane'],
 ['roll', 'distinguished', 'philatelist'],
 ['restoration', 'movement'],
 ['danny', 'elfman'],
 ['konkani', 'language'],
 ['dungannon'],
 ['united', 'soccer', 'league'],
 ['chapter', 'verse', 'bible'],
 ['isle', 'man', 'tt'],
 ['eth', 'zurich'],
 ['emirate', 'abu', 'dhabi'],
 ['delaware', 'river'],
 ['black', 'sea'],
 ['antigua'],
 ['primary', 'school'],
 ['berber', 'language'],
 ['loch', 'lomond'],
 ['african', 'union'],
 ['north', 'american', 'numbering', 'plan'],
 ['ural', 'mountain'],
 ['utah'],
 ['algarve', 'cup'],
 ['mixed', 'martial', 'art'],
 ['jaxa'],
 ['plateau', 'state'],
 ['albanian', 'national', 'awakening'],
 ['unionidae'],
 ['mystery', 'fiction'],
 ['metropolitan', 'police', 'service'],
 ['bukovina'],
 ['wilbert', 'awdry'],
 ['american'],
 ['western', 'bulldog'],
 ['christian', 'theology'],
 ['patriarch'],
 ['skanderbeg'],
 ['korea', 'japanese', 'rule'],
 ['major', 'league', 'lacrosse'],
 ['perak'],
 ['graduate', 'school'],
 ['master', 'fine', 'art'],
 ['little', 'league', 'world', 'series'],
 ['tugboat'],
 ['2016', 'united', 'state', 'presidential', 'election'],
 ['united', 'state', 'national', 'rugby', 'union', 'team'],
 ['1906', 'intercalated', 'game'],
 ['bocas', 'del', 'toro', 'province'],
 ['inline', 'four', 'engine'],
 ['english', 'feudal', 'barony'],
 ['royal', 'guelphic', 'order'],
 ['bodybuilding'],
 ['dusty', 'springfield'],
 ['caserta'],
 ['northrop', 'grumman'],
 ['bourbon', 'restoration'],
 ['sql'],
 ['south', 'cambridgeshire'],
 ['alappuzha'],
 ['united', 'state', 'national', 'guard'],
 ['korean', 'drama'],
 ['thiruvananthapuram'],
 ['collecting'],
 ['uzbek'],
 ['vickers', 'limited'],
 ['luis', 'miguel'],
 ['ottoman', 'navy'],
 ['truman', 'capote'],
 ['arnold', 'schwarzenegger'],
 ['taurus', 'mountain'],
 ['easter', 'rising'],
 ['henry', 'david', 'thoreau'],
 ['george', 'jones'],
 ['bbc', 'radio', '1'],
 ['craven'],
 ['architecture'],
 ['sega'],
 ['second', 'sea', 'lord'],
 ['stena', 'line'],
 ['wingecarribee', 'shire'],
 ['fraser', 'coast', 'region'],
 ['intellivision'],
 ['gridiron', 'football'],
 ['moreton', 'bay', 'region'],
 ['ultimate', 'play', 'game'],
 ['literature'],
 ['podgorica'],
 ['lugano'],
 ['smokey', 'robinson'],
 ['major', 'league', 'soccer'],
 ['london', 'borough', 'redbridge'],
 ['roman', 'britain'],
 ['budapest'],
 ['rugby', 'football'],
 ['archbishop', 'york'],
 ['edward', 'ii', 'england'],
 ['ajmer'],
 ['yamaguchi', 'prefecture'],
 ['jaipur'],
 ['indonesian', 'cuisine'],
 ['port', 'los', 'angeles'],
 ['british', 'academy'],
 ['united', 'methodist', 'church'],
 ['independent', 'music'],
 ['chiswick'],
 ['celebrity'],
 ['ivy', 'league'],
 ['na'],
 ['province', 'massachusetts', 'bay'],
 ['christmas', 'carol'],
 ['aix', 'en', 'provence'],
 ['black', 'hill'],
 ['willamette', 'valley'],
 ['master', 'wine'],
 ['carl', 'reiner'],
 ['podlaskie', 'voivodeship'],
 ['princess'],
 ['collins', 'crime', 'club'],
 ['romanian', 'naval', 'force'],
 ['poxviridae'],
 ['koper'],
 ['limerick', 'gaa'],
 ['ancona'],
 ['mauritius'],
 ['clark', 'university'],
 ['ohio'],
 ['ludwigsburg'],
 ['province', 'chile'],
 ['right', 'wing', 'politics'],
 ['horticulture'],
 ['richard', 'nixon'],
 ['indie', 'rock'],
 ['samsung'],
 ['virginia', 'general', 'assembly'],
 ['schutzstaffel'],
 ['cloud', 'computing'],
 ['upper', 'carniola'],
 ['crown', 'colony'],
 ['metropolitan', 'borough', 'solihull'],
 ['valladolid'],
 ['william', 'goldman'],
 ['socialist', 'unity', 'party', 'germany'],
 ['irem'],
 ['turkic', 'people'],
 ['coldplay'],
 ['prunus'],
 ['odin'],
 ['vh1'],
 ['twelfth', 'grade'],
 ['faversham'],
 ['city', 'townsville'],
 ['trinity', 'college', 'dublin'],
 ['tasmanian', 'house', 'assembly'],
 ['kgb'],
 ['idaho'],
 ['liao', 'dynasty'],
 ['gascon', 'language'],
 ['luxembourg', 'city'],
 ['saddam', 'hussein'],
 ['ovid'],
 ['venus'],
 ['srikakulam', 'district'],
 ['vest', 'agder'],
 ['comedy'],
 ['megadeth'],
 ['sioux'],
 ['baie', 'james'],
 ['frontier', 'martial', 'art', 'wrestling'],
 ['east', 'lothian'],
 ['indomalayan', 'realm'],
 ['albacete'],
 ['richard', 'fleischer'],
 ['cincinnati', 'red'],
 ['vyborg'],
 ['provincial', 'assembly', 'punjab'],
 ['hamburg'],
 ['ku', 'ring', 'gai', 'council'],
 ['hanoi'],
 ['northern', 'england'],
 ['nonpartisanism'],
 ['reserve', 'bank', 'india'],
 ['tony', 'hatch'],
 ['joan', 'arc'],
 ['chinese', 'american'],
 ['fox', 'broadcasting', 'company'],
 ['parramatta', 'eel'],
 ['duisburg'],
 ['oxford', 'university', 'press'],
 ['yukon'],
 ['tenant', 'purchase', 'scheme'],
 ['cthulhu', 'mythos'],
 ['cape', 'town'],
 ['phoenicia'],
 ['equestrianism'],
 ['taunton'],
 ['1947', 'ceylonese', 'parliamentary', 'election'],
 ['triathlon'],
 ['west', 'coast', 'main', 'line'],
 ['ghana'],
 ['manchester', 'metrolink'],
 ['darfur'],
 ['jim', 'crockett', 'promotion'],
 ['antoninus', 'pius'],
 ['isle', 'dog'],
 ['smith'],
 ['dewan', 'rakyat'],
 ['jennifer', 'rowe'],
 ['kaduna', 'state'],
 ['dahomey'],
 ['nakskov'],
 ['ciutat', 'vella'],
 ['ohio', 'river'],
 ['civil', 'engineering'],
 ['kaluga', 'oblast'],
 ['london', 'borough', 'croydon'],
 ['guillermo', 'del', 'toro'],
 ['germany'],
 ['french', 'polynesia'],
 ['chvrches'],
 ['mark', 'twain'],
 ['shaheed', 'bhagat', 'singh', 'nagar', 'district'],
 ['cyclades'],
 ['strabo'],
 ['milton', 'bradley', 'company'],
 ['occitan', 'language'],
 ['yenisei', 'river'],
 ['bangladesh'],
 ['lake', 'tahoe'],
 ['brandenburg'],
 ['jacob'],
 ['france', 'national', 'football', 'team'],
 ['veikkausliiga'],
 ['2015', 'canadian', 'federal', 'election'],
 ['kurdistan', 'region'],
 ['snk'],
 ['bbc', 'television'],
 ['united', 'state', 'department', 'defense'],
 ['prince', 'elector'],
 ['new', 'england'],
 ['rca'],
 ['qinghai'],
 ['chilean', 'war', 'independence'],
 ['daft', 'punk'],
 ['ghana', 'national', 'football', 'team'],
 ['chinese', 'buddhism'],
 ['florence'],
 ['samara', 'oblast'],
 ['yekaterinburg'],
 ['connecticut', 'river'],
 ['indonesia'],
 ['vancouver'],
 ['miami', 'marlin'],
 ['joseph', 'stalin'],
 ['travel', 'literature'],
 ['christian', 'democratic', 'appeal'],
 ['detroit', 'piston'],
 ['taranto'],
 ['port', 'washington', 'branch'],
 ['yellowknife'],
 ['sahrawi', 'arab', 'democratic', 'republic'],
 ['derry', 'gaa'],
 ['unionism', 'ireland'],
 ['soviet', 'armed', 'force'],
 ['los', 'angeles'],
 ['thomas', 'jefferson'],
 ['hal', 'roach'],
 ['cardiff', 'rfc'],
 ['government', 'kerala'],
 ['regent'],
 ['british', 'people'],
 ['american'],
 ['bell', 'system'],
 ['sabrina', 'carpenter'],
 ['danielle', 'steel'],
 ['lincolnshire'],
 ['printmaking'],
 ['vicenza'],
 ['eric', 'clapton'],
 ['dj', 'khaled'],
 ['county', 'donegal'],
 ['lockheed', 'corporation'],
 ['southern', 'rock'],
 ['george', 'gershwin'],
 ['salvation', 'army'],
 ['bell', 'lab'],
 ['list', 'north', 'carolina', 'state', 'park'],
 ['falklands', 'war'],
 ['gustav', 'mahler'],
 ['monster', 'movie'],
 ['cheap', 'trick'],
 ['chinese', 'taipei'],
 ['liechtenstein'],
 ['daily', 'mail'],
 ['solan', 'district'],
 ['goth'],
 ['british', 'empire'],
 ['scholastic', 'corporation'],
 ['ten', 'pin', 'bowling'],
 ['city', 'university', 'new', 'york'],
 ['vinnytsia', 'oblast'],
 ['centre', 'national', 'de', 'la', 'recherche', 'scientifique'],
 ['opeth'],
 ['neuwied'],
 ['tampere'],
 ['international', 'brigade'],
 ['north', 'london'],
 ['serbian', 'cyrillic', 'alphabet'],
 ['northeastern', 'ontario'],
 ['hackensack', 'river'],
 ['old', 'world', 'warbler'],
 ['danish', 'superliga'],
 ['niue'],
 ['puducherry'],
 ['namibia'],
 ['royal', 'rumble'],
 ['atlantic', 'league', 'professional', 'baseball'],
 ['bornholm'],
 ['alappuzha', 'district'],
 ['spongebob', 'squarepants'],
 ['royal', 'caribbean', 'international'],
 ['kim', 'jong', 'il'],
 ['keanu', 'reef'],
 ['argentina', 'national', 'football', 'team'],
 ['lloyd', 'bacon'],
 ['annette', 'andre'],
 ['british', 'film', 'institute'],
 ['second', 'polish', 'republic'],
 ['geology'],
 ['adventure', 'film'],
 ['jeddah'],
 ['amitabh', 'bachchan'],
 ['london', 'school', 'economics'],
 ['buryatia'],
 ['great', 'purge'],
 ['bandai', 'namco', 'entertainment'],
 ['trojan', 'war'],
 ['katy', 'perry'],
 ['vincent', 'van', 'gogh'],
 ['disneyland', 'paris'],
 ['islamism'],
 ['thor'],
 ['mersin'],
 ['clint', 'eastwood'],
 ['bulgarian', 'cup'],
 ['gauteng'],
 ['team17'],
 ['babur'],
 ['dili'],
 ['arabic', 'literature'],
 ['traditional', 'chinese', 'character'],
 ['knight'],
 ['vadodara'],
 ['javanese', 'language'],
 ['pope'],
 ['botany'],
 ['limehouse'],
 ['international', 'security', 'assistance', 'force'],
 ['barranquilla'],
 ['met', 'mother'],
 ['long', 'island'],
 ['infantry'],
 ['developing', 'country'],
 ['carmarthenshire'],
 ['province', 'sweden'],
 ['minnesota', 'wild'],
 ['roll', 'royce', 'limited'],
 ['county', 'fermanagh'],
 ['steve', 'ditko'],
 ['parthian', 'empire'],
 ['toyota', 'corolla'],
 ['great', 'depression'],
 ['postage', 'stamp'],
 ['napoleon', 'iii'],
 ['university', 'leicester'],
 ['master', 'universe'],
 ['albert', 'einstein'],
 ['patriotism'],
 ['international', 'boxing', 'organization'],
 ['massif', 'central'],
 ['perennial', 'plant'],
 ['fredric', 'march'],
 ['malagasy', 'language'],
 ['torah', 'reading'],
 ['union', 'navy'],
 ['nascar', 'xfinity', 'series'],
 ['tahiti'],
 ['lahore'],
 ['galois', 'group'],
 ['key', 'west'],
 ['john', 'b'],
 ['nagoya'],
 ['surabaya'],
 ['ecumenical', 'patriarch', 'constantinople'],
 ['guadeloupe'],
 ['welsh', 'government'],
 ['yugoslavia'],
 ['plain', 'indian'],
 ['australian', 'hip', 'hop'],
 ['peerage', 'scotland'],
 ['gambino', 'crime', 'family'],
 ['ice', 'hockey'],
 ['australian', 'defence', 'force'],
 ['korean', 'state', 'railway'],
 ['monash', 'university'],
 ['television', 'channel'],
 ['italian', 'renaissance'],
 ['hell'],
 ['fc', 'porto'],
 ['south', 'india'],
 ['government', 'ireland'],
 ['legislative', 'assembly', 'ontario'],
 ['region', 'southern', 'denmark'],
 ['zagreb'],
 ['coahuila'],
 ['assyrian', 'people'],
 ['percussion', 'instrument'],
 ['tuam'],
 ['private', 'university'],
 ['alicia', 'key'],
 ['fox', 'news'],
 ['aramaic'],
 ['quebec', 'major', 'junior', 'hockey', 'league'],
 ['osun', 'state'],
 ['pablo', 'picasso'],
 ['bangkok'],
 ['adriatic', 'sea'],
 ['niger', 'river'],
 ['local', 'government', 'area', 'western', 'australia'],
 ['lao'],
 ['carnatic', 'music'],
 ['new', 'mexico'],
 ['bangalore'],
 ['donald', 'duck'],
 ['minister', 'state'],
 ['royal', 'college', 'surgeon', 'ireland'],
 ['3000', 'metre', 'steeplechase'],
 ['lenape'],
 ['david', 'weber'],
 ['tagalog', 'language'],
 ['oklahoma', 'sooner', 'football'],
 ['university', 'toronto'],
 ['paris', 'foreign', 'mission', 'society'],
 ['directv'],
 ['hawthorn', 'football', 'club'],
 ['bromsgrove'],
 ['durham', 'university'],
 ['badulla'],
 ['posix'],
 ['altai', 'krai'],
 ['hmong', 'people'],
 ['motown'],
 ['freestyle', 'swimming'],
 ['kutaisi'],
 ['futurama'],
 ['thane'],
 ['order', 'st', 'michael', 'st', 'george'],
 ['royal', 'college', 'physician', 'edinburgh'],
 ['20th', 'century', 'fox'],
 ['finland'],
 ['tina', 'arena'],
 ['internet', 'forum'],
 ['muromachi', 'period'],
 ['county', 'dublin'],
 ['meath', 'gaa'],
 ['latvian', 'higher', 'league'],
 ['ecclesiastical', 'latin'],
 ['spiritualism'],
 ['akb48'],
 ['vice', 'president', 'united', 'state'],
 ['west', 'germanic', 'language'],
 ['tauranga'],
 ['1500', 'metre'],
 ['chukchi', 'sea'],
 ['video', 'game', 'publisher'],
 ['al', 'anbar', 'governorate'],
 ['grozny'],
 ['bryan', 'adam'],
 ['wwe', 'network'],
 ['aube'],
 ['stephen', 'hillenburg'],
 ['gascony'],
 ['rashtriya', 'swayamsevak', 'sangh'],
 ['abbasid', 'caliphate'],
 ['bbc', 'america'],
 ['reba', 'mcentire'],
 ['singapore'],
 ['keio', 'university'],
 ['antioquia', 'department'],
 ['koine', 'greek'],
 ['northern', 'cyprus'],
 ['travel', 'channel'],
 ['slade'],
 ['eastern', 'europe'],
 ['university', 'nottingham'],
 ['cinema', 'philippine'],
 ['cumbernauld'],
 ['congregation', 'christian', 'brother'],
 ['montreux'],
 ['davis', 'cup'],
 ['ulyanovsk', 'oblast'],
 ['persian', 'gulf'],
 ['planetary', 'habitability'],
 ['centre', 'right', 'politics'],
 ['order', 'ontario'],
 ['role', 'playing', 'video', 'game'],
 ['dutch', 'golden', 'age', 'painting'],
 ['herbaceous', 'plant'],
 ['ba', 'rhin'],
 ['physician'],
 ['gros', 'de', 'vaud', 'district'],
 ['usb'],
 ['tom', 'jerry'],
 ['mendoza', 'province'],
 ['exeter', 'chief'],
 ['cupressaceae'],
 ['book', 'judge'],
 ['english', 'study'],
 ['mysticism'],
 ['moravian', 'silesian', 'region'],
 ['volvo'],
 ['belarusian'],
 ['philippine', 'basketball', 'association'],
 ['sui', 'dynasty'],
 ['dalai', 'lama'],
 ['tigris'],
 ['rigveda'],
 ['political', 'radicalism'],
 ['apocalyptic', 'post', 'apocalyptic', 'fiction'],
 ['chinese', 'folk', 'religion'],
 ['trajan'],
 ['mark', 'millar'],
 ['romeo', 'juliet'],
 ['grand', 'cayman'],
 ['witney'],
 ['palmerston', 'north'],
 ['college', 'board'],
 ['sam', 'raimi'],
 ['berber'],
 ['def', 'jam', 'recording'],
 ['bahamas'],
 ['old', 'irish'],
 ['stockholm', 'municipality'],
 ['szeged'],
 ['london', 'borough', 'haringey'],
 ['ahvaz'],
 ['vilnius'],
 ['nanchang'],
 ['sarawak'],
 ['mainland', 'china'],
 ['telugu', 'language'],
 ['amazon', 'river'],
 ['san', 'francisco', 'bay'],
 ['john', 'baptist'],
 ['civil', 'political', 'right'],
 ['gaeltacht'],
 ['palatine', 'hungary'],
 ['malacca'],
 ['sahara'],
 ['rascal', 'flatts'],
 ['eastern', 'wu'],
 ['steven', 'spielberg'],
 ['university', 'texas', 'austin'],
 ['subroutine'],
 ['nelson', 'rockefeller'],
 ['hiroshima'],
 ['w'],
 ['canterbury', 'bankstown', 'bulldog'],
 ['luhansk', 'oblast'],
 ['gracillariidae'],
 ['mendip', 'hill'],
 ['derbyshire'],
 ['free', 'state', 'prussia'],
 ['olympique', 'de', 'marseille'],
 ['la', 'palma'],
 ['smolensk'],
 ['cuban', 'revolution'],
 ['fa', 'cup', 'final'],
 ['distinguished', 'service', 'order'],
 ['luc', 'besson'],
 ['mid', 'north'],
 ['sarah', 'jane', 'adventure'],
 ['island', 'record'],
 ['rice', 'university'],
 ['thirteen', 'colony'],
 ['treat', 'williams'],
 ['riverside', 'record'],
 ['greater', 'western', 'sydney'],
 ['babylon'],
 ['lleida'],
 ['department', 'honduras'],
 ['volhynia'],
 ['guinness'],
 ['new', 'york', 'harbor'],
 ['gothic', 'fiction'],
 ['world', 'hockey', 'association'],
 ['ganges'],
 ['ypres', 'salient'],
 ['episcopal', 'polity'],
 ['royal', 'navy'],
 ['korn'],
 ['united', 'state', 'dollar'],
 ['minnesota', 'twin'],
 ['prussian', 'navy'],
 ['l'],
 ['vangelis'],
 ['virginia', 'military', 'institute'],
 ['northern', 'ireland', 'executive'],
 ['deccan', 'plateau'],
 ['akira', 'toriyama'],
 ['action', 'adventure', 'game'],
 ['progressive', 'conservative', 'party', 'canada'],
 ['morobe', 'province'],
 ['queensland'],
 ['miyagi', 'prefecture'],
 ['senate', 'philippine'],
 ['federico', 'fellini'],
 ['australian', 'national', 'university'],
 ['rebellion'],
 ['biographical', 'film'],
 ['lublin', 'voivodeship'],
 ['louis', 'xiv', 'france'],
 ['united', 'state', 'declaration', 'independence'],
 ['bremen'],
 ['duke', 'aquitaine'],
 ['plymouth'],
 ['ian', 'mcewan'],
 ['stephen', 'king'],
 ['professional', 'dart', 'corporation'],
 ['international', 'wrestling', 'revolution', 'group'],
 ['carnian'],
 ['tver', 'oblast'],
 ['bhutan'],
 ['ringo', 'starr'],
 ['algonquian', 'language'],
 ['double', 'bass'],
 ['ellesmere', 'island'],
 ['albert', 'pyun'],
 ['faith'],
 ['new', 'york', 'metropolitan', 'area'],
 ['fc', 'dallas'],
 ['olympique', 'lyonnais'],
 ['edmonton'],
 ['braunschweig'],
 ['cieszyn', 'county'],
 ['bill', 'murray'],
 ['kingdom', 'romania'],
 ['armoured', 'warfare'],
 ['jagiellonian', 'university'],
 ['swiss', 'air', 'force'],
 ['hawick'],
 ['poitier'],
 ['polish', 'language'],
 ['middle', 'tennessee'],
 ['jewish', 'philosophy'],
 ['greek', 'resistance'],
 ['mississauga'],
 ['south', 'los', 'angeles'],
 ['river', 'state'],
 ['binghamton', 'university'],
 ['boston', 'red', 'sox'],
 ['leeds', 'rhino'],
 ['altai', 'mountain'],
 ['piedmont', 'triad'],
 ['nairobi'],
 ['east', 'dunbartonshire'],
 ['hampton', 'road'],
 ['hungarian', 'revolution', '1956'],
 ['social', 'liberalism'],
 ['england', 'cricket', 'team'],
 ['actinopterygii'],
 ['downtown', 'calgary'],
 ['greyhound', 'racing', 'united', 'kingdom'],
 ['puntland'],
 ['sierra', 'madre', 'occidental'],
 ['parliament', 'england'],
 ['streatham'],
 ['tampa', 'bay', 'viper'],
 ['tristan', 'da', 'cunha'],
 ['charles', 'england'],
 ['president', 'colombia'],
 ['riemannian', 'geometry'],
 ['australian', 'rule', 'football'],
 ['english', 'rugby', 'union', 'system'],
 ['twickenham'],
 ['felix', 'cat'],
 ['university', 'denver'],
 ['epiphyte'],
 ['wall', 'street', 'journal'],
 ['daraa'],
 ['lepidoptera'],
 ['lusitania'],
 ['eerste', 'divisie'],
 ['columbidae'],
 ['cenozoic'],
 ['hillary', 'clinton'],
 ['woody', 'woodpecker'],
 ['oakland', 'athletics'],
 ['lake', 'district', 'national', 'park'],
 ['dnipropetrovsk', 'oblast'],
 ['chemistry'],

In [39]:
del most_related_3_dict_with_scores
del query_score_dict
del score_doc_dict
gc.collect()

20

In [40]:
query_id_vs_index = defaultdict(int)

for i, query_id in enumerate(query_ids):
    query_id_vs_index[query_id] = i

In [41]:
query_id_vs_index = dict(query_id_vs_index)

In [42]:
len(most_related_3_dict.keys())

1442

In [43]:
del lemmatized_docs
gc.collect()

0

In [44]:
queries_expanded = []

for query_id in query_ids:
    if query_id in dict_keys_set:
        doc_list = most_related_3_dict[query_id]
        query_list = lemmatized_tokenized_queries[query_id_vs_index[query_id]]
        query_list *= 2

        for doc_id in doc_list:
            added_word = get_top_word(tf_idf_matrix, tf_idf_vect, doc_id_vs_index[doc_id])

            if added_word is not None:
                query_list.append(added_word)

        queries_expanded.append(query_list)
    else:
        queries_expanded.append([])

In [45]:
new_scores = []

for query in queries_expanded:
    new_scores.append(bm25.get_scores(query))

In [46]:
import numpy as np
query_id_and_its_doc = defaultdict(list)

for i in range(len(query_ids)):
    found_doc_list = []
    similarity = new_scores[i]

    index_of_found_docs = np.where(similarity > 0)[0]

    for index in list(index_of_found_docs):
        found_doc_list.append((similarity[index], doc_dict[index]))

    if len(found_doc_list) <= 10:
        for mytuple in found_doc_list:
            query_id_and_its_doc[query_ids[i]].append(mytuple[1])
    else:
        for mytuple in sorted(found_doc_list, reverse=True):
            query_id_and_its_doc[query_ids[i]].append(mytuple[1])

            if len(query_id_and_its_doc[query_ids[i]]) == 10:
                break

In [47]:
query_doc_pairs = defaultdict(list)

for query_id in query_ids:
    for doc_id in query_id_and_its_doc[query_id]:
        query_doc_pairs[query_id].append((query_id_vs_text[query_id], doc_id_vs_text[doc_id]))

In [48]:
query_score_dict = defaultdict(list)

for query_id in query_ids:
    if query_id in dict_keys_set:
        query_score_dict[query_id] = list(model.predict(query_doc_pairs[query_id]))

In [49]:
most_related_5_dict = defaultdict(list)
most_related_5_dict_with_scores = defaultdict(list)

for query_id in query_ids:
    if query_id in dict_keys_set:
        related_10 = []

        for i, score in enumerate(query_score_dict[query_id]):
            related_10.append((score, i))

        for mytuple in sorted(related_10, reverse=True):
            most_related_5_dict[query_id].append(query_id_and_its_doc[query_id][mytuple[1]])
            most_related_5_dict_with_scores[query_id].append((query_id_and_its_doc[query_id][mytuple[1]], mytuple[0]))

            if len(most_related_5_dict[query_id]) == 5:
                break

In [50]:
most_related_10_dict = defaultdict(list)
most_related_10_dict_with_scores = defaultdict(list)

for query_id in query_ids:
    if query_id in dict_keys_set:
        related_10 = []

        for i, score in enumerate(query_score_dict[query_id]):
            related_10.append((score, i))

        for mytuple in sorted(related_10, reverse=True):
            most_related_10_dict[query_id].append(query_id_and_its_doc[query_id][mytuple[1]])
            most_related_10_dict_with_scores[query_id].append((query_id_and_its_doc[query_id][mytuple[1]], mytuple[0]))

            if len(most_related_10_dict[query_id]) == 10:
                break

In [51]:
def recall(found_docs: list, test_list: list) -> float:
    counter = 0
    test_set = set(test_list)

    for doc_id in found_docs:
        if doc_id in test_set:
            counter += 1

    return (counter / len(test_list)) * 100

def precision(found_docs: list, test_list: list) -> float:
    counter = 0
    test_set = set(test_list)

    for doc_id in found_docs:
        if doc_id in test_set:
            counter += 1

    return (counter / len(found_docs)) * 100

def precision_AP(found_docs: list, test_list: list) -> float:
    counter = 0

    test_set = set(test_list)

    for doc in found_docs:
        if doc in test_set:
            counter += 1

    return counter / len(found_docs)


def AP(found_docs: list, test_list: list) -> float:
    total = 0

    for i in range(1, 10 + 1):
        if i < len(found_docs):
            precision_k = precision_AP(found_docs[:i], test_list)
            total += precision_k * (found_docs[i - 1] in set(test_list))

    return total / len(test_list)

In [52]:
recall_5_list, precision_5_list, AP_5_list = [], [], []

for query_id in query_ids:
    if query_id in dict_keys_set:
        recall_5_value = recall(most_related_5_dict[query_id], qrels_dict[query_id])
        precision_5_value = precision(most_related_5_dict[query_id], qrels_dict[query_id])
        AP_5_value = AP(most_related_5_dict[query_id], qrels_dict[query_id])

        recall_5_list.append(recall_5_value)
        precision_5_list.append(precision_5_value)
        AP_5_list.append(AP_5_value)
    else:
        recall_5_list.append(0)
        precision_5_list.append(0)
        AP_5_list.append(0)

In [53]:
recall_10_list, precision_10_list, AP_10_list = [], [], []

for query_id in query_ids:
    if query_id in dict_keys_set:
        recall_10_value = recall(most_related_10_dict[query_id], qrels_dict[query_id])
        precision_10_value = precision(most_related_10_dict[query_id], qrels_dict[query_id])
        AP_10_value = AP(most_related_10_dict[query_id], qrels_dict[query_id])

        recall_10_list.append(recall_10_value)
        precision_10_list.append(precision_10_value)
        AP_10_list.append(AP_10_value)
    else:
        recall_10_list.append(0)
        precision_10_list.append(0)
        AP_10_list.append(0)

In [54]:
import pandas as pd

df = pd.DataFrame({
    "Query_ID": query_ids,
    "recall_10": recall_10_list,
    "precision_10": precision_10_list,
    "AP_10": AP_10_list
})

df

     Query_ID   recall_10  precision_10     AP_10
0      123839  100.000000          60.0  0.915079
1      188629   50.000000          30.0  0.388889
2       13898   33.333333          20.0  0.333333
3      316959   22.222222          20.0  0.222222
4      515031   21.428571          30.0  0.126786
...       ...         ...           ...       ...
1439   896124   12.500000          10.0  0.062500
1440    12319    4.545455          10.0  0.045455
1441     4421    0.000000           0.0  0.000000
1442   296526    0.000000           0.0  0.000000
1443   341793   14.285714          10.0  0.142857

[1444 rows x 4 columns]

In [56]:
import ir_datasets
dataset = ir_datasets.load("wikir/en1k/training")

score_doc_dict = defaultdict(list)

for scoreddoc in dataset.scoreddocs_iter():
    doc_id = scoreddoc.doc_id
    score = scoreddoc.score

    scoreddoc_object = Scoredoc(doc_id, score)

    score_doc_dict[scoreddoc.query_id].append(scoreddoc_object)

score_doc_dict = dict(score_doc_dict)

In [57]:
from sklearn.metrics import ndcg_score

doc_id_score_dict = defaultdict(float)
ndcg_10_list = []

for idx in range(len(df)):
    query_id = df.loc[idx, "Query_ID"]
    if query_id in dict_keys_set:
        scoredoc_object_list = score_doc_dict[query_id]

        for scoreddoc_object in scoredoc_object_list:
            doc_id_score_dict[scoreddoc_object.doc_id] = scoreddoc_object.score

        model_score_tuple_list = most_related_10_dict_with_scores[query_id]

        y_score, y_true = [], []

        for mytuple in model_score_tuple_list:
            doc_id = mytuple[0]
            score = mytuple[1]

            y_score.append(score)
            y_true.append(doc_id_score_dict[doc_id])

        if len(y_score) == 0:
            ndcg_10_list.append(0.0)
            continue

        if len(y_score) == 1:
            y_true.append(0.0)
            y_score.append(0.0)

        if len(y_true) == len(y_score):
            ndcg_10_list.append(ndcg_score(np.asarray([y_true]), np.asarray([y_score]), k=10))
        else:
            print("There is a problem with query", query_id)
    else:
        ndcg_10_list.append(0)

In [58]:
df["NDCG_10"] = ndcg_10_list
df

     Query_ID   recall_10  precision_10     AP_10   NDCG_10
0      123839  100.000000          60.0  0.915079  0.995386
1      188629   50.000000          30.0  0.388889  0.998432
2       13898   33.333333          20.0  0.333333  0.000000
3      316959   22.222222          20.0  0.222222  0.986344
4      515031   21.428571          30.0  0.126786  0.766278
...       ...         ...           ...       ...       ...
1439   896124   12.500000          10.0  0.062500  0.990022
1440    12319    4.545455          10.0  0.045455  0.911338
1441     4421    0.000000           0.0  0.000000  0.989373
1442   296526    0.000000           0.0  0.000000  0.651697
1443   341793   14.285714          10.0  0.142857  0.779010

[1444 rows x 5 columns]

In [59]:
df["f_score_10"] = 2 * df["recall_10"] * df["precision_10"] / (df["recall_10"] + df["precision_10"])
df

     Query_ID   recall_10  precision_10     AP_10   NDCG_10  f_score_10
0      123839  100.000000          60.0  0.915079  0.995386   75.000000
1      188629   50.000000          30.0  0.388889  0.998432   37.500000
2       13898   33.333333          20.0  0.333333  0.000000   25.000000
3      316959   22.222222          20.0  0.222222  0.986344   21.052632
4      515031   21.428571          30.0  0.126786  0.766278   25.000000
...       ...         ...           ...       ...       ...         ...
1439   896124   12.500000          10.0  0.062500  0.990022   11.111111
1440    12319    4.545455          10.0  0.045455  0.911338    6.250000
1441     4421    0.000000           0.0  0.000000  0.989373         NaN
1442   296526    0.000000           0.0  0.000000  0.651697         NaN
1443   341793   14.285714          10.0  0.142857  0.779010   11.764706

[1444 rows x 6 columns]

In [60]:
recall_5_list, precision_5_list, AP_5_list = [], [], []

for query_id in query_ids:
    if query_id in dict_keys_set:
        recall_5_value = recall(most_related_5_dict[query_id], qrels_dict[query_id])
        precision_5_value = precision(most_related_5_dict[query_id], qrels_dict[query_id])
        AP_5_value = AP(most_related_5_dict[query_id], qrels_dict[query_id])

        recall_5_list.append(recall_5_value)
        precision_5_list.append(precision_5_value)
        AP_5_list.append(AP_5_value)
    else:
        recall_5_list.append(0)
        precision_5_list.append(0)
        AP_5_list.append(0)

In [61]:
df["recall_5"] = recall_5_list
df["precision_5"] = precision_5_list
df["AP_5"] = AP_5_list

In [62]:
df["f_score_5"] = 2 * df["recall_5"] * df["precision_5"] / (df["recall_5"] + df["precision_5"])

In [63]:
from sklearn.metrics import ndcg_score

doc_id_score_dict = defaultdict(float)
ndcg_5_list = []

for idx in range(len(df)):
    query_id = df.loc[idx, "Query_ID"]
    if query_id in dict_keys_set:
        scoredoc_object_list = score_doc_dict[query_id]

        for scoreddoc_object in scoredoc_object_list:
            doc_id_score_dict[scoreddoc_object.doc_id] = scoreddoc_object.score

        model_score_tuple_list = most_related_5_dict_with_scores[query_id]

        y_score, y_true = [], []

        for mytuple in model_score_tuple_list:
            doc_id = mytuple[0]
            score = mytuple[1]

            y_score.append(score)
            y_true.append(doc_id_score_dict[doc_id])

        if len(y_score) == 0:
            ndcg_5_list.append(0.0)
            continue

        if len(y_score) == 1:
            y_true.append(0.0)
            y_score.append(0.0)

        if len(y_true) == len(y_score):
            ndcg_5_list.append(ndcg_score(np.asarray([y_true]), np.asarray([y_score]), k=5))
        else:
            print("There is a problem with query", query_id)
    else:
        ndcg_5_list.append(0)

In [64]:
df["NDCG_5"] = ndcg_5_list

In [65]:
mydict = {
    "Method": "BM25PseudoRelevanceFeedback",
    "recall_5_mean": df["recall_5"].mean(),
    "recall_5_std": df["recall_5"].std(),
    "recall_5_max": df["recall_5"].max(),
    "recall_5_min": df["recall_5"].min(),
    "recall_10_mean": df["recall_10"].mean(),
    "recall_10_std": df["recall_10"].std(),
    "recall_10_max": df["recall_10"].max(),
    "recall_10_min": df["recall_10"].min(),
    "precision_5_mean": df["precision_5"].mean(),
    "precision_5_std": df["precision_5"].std(),
    "precision_5_max": df["precision_5"].max(),
    "precision_5_min": df["precision_5"].min(),
    "precision_10_mean": df["precision_10"].mean(),
    "precision_10_std": df["precision_10"].std(),
    "precision_10_max": df["precision_10"].max(),
    "precision_10_min": df["precision_10"].min(),
    "f_score_5_mean": df["f_score_5"].mean(),
    "f_score_5_std": df["f_score_5"].std(),
    "f_score_5_max": df["f_score_5"].max(),
    "f_score_5_min": df["f_score_5"].min(),
    "f_score_10_mean": df["f_score_10"].mean(),
    "f_score_10_std": df["f_score_10"].std(),
    "f_score_10_max": df["f_score_10"].max(),
    "f_score_10_min": df["f_score_10"].min(),
    "MAP_5": df["AP_5"].mean(),
    "MAP_10": df["AP_10"].mean(),
    "NDCG_5_mean": df["NDCG_5"].mean(),
    "NDCG_5_std": df["NDCG_5"].std(),
    "NDCG_5_max": df["NDCG_5"].max(),
    "NDCG_5_min": df["NDCG_5"].min(),
    "NDCG_10_mean": df["NDCG_10"].mean(),
    "NDCG_10_std": df["NDCG_10"].std(),
    "NDCG_10_max": df["NDCG_10"].max(),
    "NDCG_10_min": df["NDCG_10"].min()
}

In [66]:
df_parquet = pd.DataFrame(mydict, index=[0])
df_parquet

,Method,recall_5_mean,recall_5_std,recall_5_max,recall_5_min,recall_10_mean,recall_10_std,recall_10_max,recall_10_min,precision_5_mean,...,MAP_5,MAP_10,NDCG_5_mean,NDCG_5_std,NDCG_5_max,NDCG_5_min,NDCG_10_mean,NDCG_10_std,NDCG_10_max,NDCG_10_min
0,BM25PseudoRelevanceFeedback,16.024472,14.739417,83.333333,0.0,21.604635,20.202779,100.0,0.0,33.067867,...,0.123887,0.157476,0.79951,0.331981,1.0,0.0,0.808502,0.291541,1.0,0.0

In [67]:
df_parquet.to_parquet("BM25PseudoRelevanceFeedback.parquet")