In [1]:
import pandas as pd

df_1 = pd.read_parquet("parquets/SentenceTransformer.parquet")
df_2 = pd.read_parquet("parquets/SenTransformerMulti_qa.parquet")
df_3 = pd.read_parquet("parquets/SenTransformerMinilm_l12.parquet")
df_4 = pd.read_parquet("parquets/minilm_l12_reranking.parquet")

df = pd.concat([df_1, df_2, df_3, df_4], ignore_index=True)

In [3]:
df.loc[0, "Method"] = "SenTransformer_minilm_l6"

In [4]:
df

,Method,recall_5_mean,recall_5_std,recall_5_max,recall_5_min,recall_10_mean,recall_10_std,recall_10_max,recall_10_min,precision_5_mean,...,MAP_5,MAP_10,NDCG_5_mean,NDCG_5_std,NDCG_5_max,NDCG_5_min,NDCG_10_mean,NDCG_10_std,NDCG_10_max,NDCG_10_min
0,SenTransformer_minilm_l6,12.089882,12.455515,66.666667,0.0,15.568538,15.745450,85.714286,0.0,27.049861,...,0.093745,0.111715,0.695169,0.365791,1.0,0.0,0.703160,0.310758,1.0,0.0
1,SenTransformer multi_qa,11.927286,11.864656,71.428571,0.0,15.364111,15.377768,100.000000,0.0,26.855956,...,0.093419,0.111127,0.715174,0.354878,1.0,0.0,0.714065,0.300219,1.0,0.0
2,SenTransformer minilm_l12,12.984136,12.349759,83.333333,0.0,16.480406,15.229594,100.000000,0.0,28.573407,...,0.099883,0.118783,0.708287,0.353963,1.0,0.0,0.709100,0.296196,1.0,0.0
3,minilm_l12_reranking,14.169270,12.872118,66.666667,0.0,17.231414,15.961054,100.000000,0.0,31.260388,...,0.114530,0.134332,0.750344,0.352292,1.0,0.0,0.752008,0.307466,1.0,0.0

In [6]:
df[["Method", "f_score_10_mean"]]

                      Method  f_score_10_mean
0   SenTransformer_minilm_l6        14.959802
1    SenTransformer multi_qa        14.739899
2  SenTransformer minilm_l12        15.786780
3       minilm_l12_reranking        16.588678

In [7]:
df[["Method", "f_score_5_mean"]]

                      Method  f_score_5_mean
0   SenTransformer_minilm_l6       15.339492
1    SenTransformer multi_qa       15.139652
2  SenTransformer minilm_l12       16.445309
3       minilm_l12_reranking       17.951978

In [8]:
df[["Method", "NDCG_5_mean"]]

                      Method  NDCG_5_mean
0   SenTransformer_minilm_l6     0.695169
1    SenTransformer multi_qa     0.715174
2  SenTransformer minilm_l12     0.708287
3       minilm_l12_reranking     0.750344

In [9]:
df[["Method", "NDCG_10_mean"]]

                      Method  NDCG_10_mean
0   SenTransformer_minilm_l6      0.703160
1    SenTransformer multi_qa      0.714065
2  SenTransformer minilm_l12      0.709100
3       minilm_l12_reranking      0.752008