In [1]:
import chromadb
chroma_client = chromadb.Client()

In [2]:

from chromadb.utils.embedding_functions import SentenceTransformerEmbeddingFunction

sentence_transformer_ef = SentenceTransformerEmbeddingFunction(
    model_name="all-MiniLM-L12-v2",
    device="cuda",
    normalize_embeddings=True
)

print("SenTransformer Ready")

/run/media/tahas44/Yeni Birim/Technarts/Intern/NLP/InformationRetrieval/.venv/lib64/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 735.53it/s]

SenTransformer Ready

In [3]:
collection = chroma_client.get_or_create_collection(
    name="l12_reranking",
    embedding_function=sentence_transformer_ef
)

In [4]:
import ir_datasets
dataset = ir_datasets.load("wikir/en1k/training")
print("Data set yüklendi")

Data set yüklendi

In [5]:
doc_texts = []
doc_ids = []

for doc in dataset.docs_iter():
    doc_texts.append(doc.text)
    doc_ids.append(doc.doc_id)

In [6]:
doc_texts

['it was used in landing craft during world war ii and is used today in private boats and training facilities the 6 71 is an inline six cylinder diesel engine the 71 refers to the displacement in cubic inches of each cylinder the firing order of the engine is 1 5 3 6 2 4 the engine s compression ratio is 18 7 1 with a 4 250 inch bore and a 5 00 inch stroke the engine weighs and is 54 inches long 29 inches wide and 41 inches tall at 2 100 revolutions per minute the engine is capable of producing 230 horse power 172 kilowatts v type versions of the 71 series were developed in 1957 the 6 71 is a two stroke engine as the engine will not naturally aspirate air is provided via a roots type blower however on the 6 71t models a turbocharger and a supercharger are utilized fuel is provided by unit injectors one per cylinder the amount of fuel injected into the engine is controlled by the engine s governor the engine cooling is via liquid in a water jacket in a boat cool external water is pumped into the engine',
 'after rejecting an offer from cambridge university she moved to london in 1954 working in a mayfair advertising agency while moonlighting as a hat check girl in the night club le club contemporain while working at the royal college of art she met the painter frank bowling when he was still a student there they married in 1960 and had one son kitchen was one of the women interviewed by nell dunn in talking to women 1965 after divorcing bowling in the late sixties kitchen went on to live with and later marry the writer dulan barber continuing to write novels she also began writing non fiction with biographies of patrick geddes and gerard manley hopkins in later life she bought a house in barnwell northamptonshire which became the subject of her book of the same name she died on 23 november 2005 the novelist bessie head was a close friend the pair corresponded from 1969 until head s death in 1986 on a range of subjects including head s novel a question of power',
 'mat zan coached kuala lumpur fa in 1999 and won malaysia fa cup in 1999 and charity cup in 2000 in 2001 mat zan then move as head coach of terengganu fa and he won the 2001 malaysia cup 2001 malaysia charity cup and second place in malaysia league with plus f c in 2008 he took 2nd place in premier league and automatically promoted to malaysia super league in 2012 he comeback with terengganu fa and go through to fa cup semi finals and round two in afc cup in 2015 mat zan move to melaka united and won 2015 malaysia fam league and won 2016 malaysia premier league after his contract was not renewed with melaka at the end of 2016 he was appointed as new head coach of airasia allstars fc which was renamed as petaling jaya rangers f c for the 2017 season he signed a 1 year contract with negeri sembilan form the 2019 season mat zan also coached the club side of malaysia u 21 squad harimau muda b who won plate winner singapore starhub league cup thanj nien newspaper cup vietnam 3rd place and hassanal bolkiah cup brunei 3rd place',
 'a barcode is a machine readable optical label that contains information about the item to which it is attached in practice qr codes often contain data for a locator identifier or tracker that points to a website or application a qr code uses four standardized encoding modes numeric alphanumeric byte binary and kanji to store data efficiently extensions may also be used the quick response system became popular outside the automotive industry due to its fast readability and greater storage capacity compared to standard upc barcodes applications include product tracking item identification time tracking document management and general marketing a qr code consists of black squares arranged in a square grid on a white background which can be read by an imaging device such as a camera and processed using reed solomon error correction until the image can be appropriately interpreted the required data is then extracted from patterns that are present in both horizontal and vertical components of the image the qr code system was invented in 1994 by the japanese company denso wave its purpose was to track vehicles during manufacturing it was designed to allow high speed component scanning qr codes are now used in a much',
 'since the subordination of the monarchy under parliament and the increasingly democratic methods of parliamentary government there have been the questions of whether parliament holds a supreme ability to legislate and whether or not it should the traditional view put forward by a v dicey is that parliament had the power to make any law except any law that bound its successors this has been reconsidered by constitutional theorists including sir william wade and trevor allan in light of the european communities act 1972 and other provisions relating to europe and the position of the human rights act 1998 and any attempts to make this or other legislation entrenched these issues remain contested parliamentary sovereignty is a description of to what extent the parliament of the united kingdom does have absolute and unlimited power it is framed in terms of the extent of authority that parliament holds and whether there are any sorts of law that it cannot pass in other countries a written constitution often binds the parliament to act in a certain way but there is no such written constitution in the united kingdom in the united kingdom parliament is central to the institutions of state the terms',
 'the tournament brought together club champions of many domestic beach soccer leagues across europe almost in the same vein as the uefa champions league twenty teams confirmed their participation in the inaugural tournament the first beach soccer winner cup was held in the sands of san benedetto del tronto rive delle palme which located in ascoli italy from 15 19 may 2013 this cup is involving all the champions in the different official national leagues all across the old continent 18 different countries will be represented in this tournament in the first stage the eighteen champions of the officially sanctioned beach soccer national championships plus the host and the italian runner up got distributed into five groups yet offering interesting battles with powerful teams having to compete for the head of the group only the sides topping the group will be granted a ticket to the quarterfinals stage accompanied by the three best second ranked teams the stadium that was used is called the umpi smart beach arena the new state of the art facility is intended to maximize the technology and the environmental consciousness directives to create a stadium that offers 360 degree amusement possibilities both for citizens and',
 'in january 1948 ballen acquired the interest of goode and became the sole owner he then moved the company to philadelphia pennsylvania where the label was based for the rest of its existence until 1956 the label specialized in rhythm and blues ivin ballen died in miami beach florida in february 1978 gotham s most notable contribution to american music was the release of recordings by the acoustic bluesman dan pickett originally recorded in 1949 another artist who recorded for gotham included doug quattlebaum his song lizzie lou was one of the last releases for the label doris browne was a singer who around the 1949 1950 period had she performed on a weekly show which was broadcast by wpen am in philadelphia the hour long show was called the parisian tailor kiddie hour in 1953 the label appeared to be keen to push browne s profile with her single please believe me bw oh baby she was backed by doc bagby on that recording he also backed her on her single until the end of time bw why don t you love me now now now gotham g 296 and another recording the game of love bw my cherie',
 'it is particularly notable for its association with several of canada s leading blues singers including richard hock walsh tony flaim and chuck jackson all of whom were also associated with the downchild blues band the band is named after the cameo lounge of toronto s hotel isabella as it then was in the 1970s and 1980s the cameo lounge featured primarily local blues artists and as of 1978 had a regular house band initially led by richard hock walsh during one of several periods when walsh was either fired or quit as the lead singer of the downchild blues band walsh was soon joined by former crowbar keyboard player rabbit ray harrison who along with guitarist john bride became the core of the group during its over three decade history other initial band members included billy bryans later of the parachute club on drums and omar tunnock later of the funk and blues band fathead on bass hock walsh soon left the band to return to downchild and was briefly replaced by fraser finlayson of the band cueball prior to the band finding a replacement in tony flaim whom hock walsh had replaced in downchild billy bryans was replaced',
 'they are also known as the wamba wamba wemba wemba bears strong similarities to woiwurrung when moravian missionaries came and started to learn a language in wembawemba territory at archibald macarthur camppbell s gannawarra station they quickly noted that the natives perceiving they were understood slipped into using another language not willing to allow this cultural conquest to enable the whitemen to learn of matters they wished to keep secret from outsiders before european settlement in the nineteenth century the wemba wemba occupied the area around the loddon river reaching northwards from kerang victoria to swan hill and including the area of the avoca river southwards towards quambatook in a northeasterly direction their territory ran up over the new south wales victorian border to boorrorban and moulamein and extended to the vicinity of barham lake boga and boora in victoria also fell within their domain the overall extension of their territory has been calculated by norman tindale to be roughly the wembawemba were registered as consisting of five hordes stone lists these hordes residing around towaninny meelool station with a name indicating they were thought to be quarrelsome lake boga gonn on the murray river called the dietjenbaluk always on',
 'they moved south to england to cannock staffordshire where they formed balaam and the angel initially the band self released a series of ep s and an album entitled sun family via their own chapter 22 label and played some tour dates opening for the cult this caught the attention of virgin records who signed them and released their debut album the greatest story ever told it peaked at no 67 in the uk albums chart in august 1986 they toured in the united states with the mission kiss and label mate iggy pop a second guitarist and the first non sibling ian mckean of twenty flight rockers was added to the band in 1988 the band began to move away from gothic rock music styles into a sound that had more in common with hard rock with their new found style they recorded the album live free or die this was soon followed up in similar style when they recorded days of madness before leaving virgin records their song i ll show you something special appeared on the soundtrack for the film planes trains and automobiles their presence was largely ignored by the time that their 1993 album prime',
 'farming and forestry remain central to rural economies and rural development also focuses on revitalising rural areas in other ways furthermore issues such as climate change renewable energy biodiversity and water management are becoming increasingly important aspects of the eu s rural development policy over 200 billion in funding is available to support the implementation of 94 rdps across the eu for the programming period 2007 2013 almost half of this money is provided by the eafrd overseen by the european commission s directorate general for agriculture and rural development eafrd budgets in the rdps are used to achieve a variety of rural development goals including improving the competitiveness of farm forest and agri food businesses helping protect the natural environment supporting rural economies and assisting quality of life in rural areas',
 'he died while working on the project during the great storm of 1703 he was born in saffron walden essex and baptised there on 31 march 1644 his father henry became land steward to the earl of suffolk owner of audley end house in 1652 and young henry also worked at audley end first as a porter and then as a secretary in 1666 audley end house was bought by charles ii for use as a base when attending newmarket races and it became effectively a royal palace winstanley developed an interest in engraving after a grand tour of europe between 1669 and 1674 where he was impressed by continental architecture and the engravings in which it was portrayed on his return he is believed to have studied engraving with wenceslas hollar and was employed at audley end house as assistant to the clerk of works in 1676 he embarked on a detailed set of architectural engravings of audley end house which took him ten years to complete and which survive as an important early record of english manor house architecture he also designed a set of playing cards which became very popular and sold well he was appointed clerk',
 'it is a grade i listed building the written history of denton goes back to at least 1253 when the then owner one athelstan not to be confused with the king of that name made the estate over to the see of york which already owned manorial rights in nearby otley it was subinfeuded sub let at an early date to the vavasours and in 1284 maugerus le vavasur held the town for a fourth part of a knight s fee of the archbishops of york who continued lords paramount in 1379 according to the poll tax returns one adam wayte appears to have been then farming the manor at which time denton had a more than ordinary reputation for clothes making and drapery goods the estate passed into the ownership of the thwaites family when elizabeth daughter of henry thwaites married john vavasour of weston who died in 1482 records show the thwaites family had been resident in denton village earlier than that time again through marriage in 1515 the estate passed to the fairfax family at the time of thomas fairfax 1st lord fairfax of cameron denton hall had repute as housing one of the best libraries in',
 'she was elected into the house of representatives of nigeria in 2007 to represent ebonyi ohaukwu federal constituency she was elected on the platform of the people s democratic party pdp hon elizabeth ogbaga was a member of the following committees in december 2009 hon elizabeth ogbaga expressed her dissatisfaction over what she called low level of implementation of projects contained in 2009 budget she sponsored numerous bills and motions and often decried the low participation of women in politics stating that it affected democracy hon elizabeth ogbaga attracted various projects such as oxygen plants and mammogram machines to federal medical centre abakaliki free antenatal care services to pregnant mothers from ebonyi ohaukwu federal constituency construction of several 3 classroom blocks hand pump boreholes at onuenyim ishieke ndiofia nkaleke igweledoha ogbala parish effenyim ongoing oterufie nkaleke ndiechi ndiugo isophumini mbeke isophumini st michael parish mbeke ishieke nwonuewo effium ohaukwu ogen ohaukwu and umugadu community secondary school she also constructed national health care centres at izenyi agbaja in izzi lga and ohagelode ongoing and trained more than 50 youths on ict as well as providing them with computers and accessories hon elizabeth ogbaga further constructed a bridge across ebonyi river at',
 'held annually since 2007 on the southern bank of lake balaton hungary it features live acts and djs from all around the world from established artists to new names the event was co created by the organizers of sziget festival as the festival gets more famous and popular each year tickets are usually sold out before they go on sale at the official ticket vendors this event sets new attendance records yearly the first balaton sound festival was held between 12 july and 15 july 2007 the fact that the event was held on the shore of the largest lake in central europe in mid summer its twenty hour music schedule and the line up gained it significant public interest the festival is located on the west part of zam rdi at the crossing of panor ma and z ldfa utca street inside the festival area variable stages lounges and tents are established for the performances the sponsors of the festival create luxurious chill out facilities with hammocks bean bags and easy chairs visitors to balaton sound can stay at a special campsite with several pubs cocktail bars and restaurants equipped with accoutrements absent from hungary s other summer music',
 'she co founded the phillips collection with her husband duncan phillips she was born marjorie acker in bourbon indiana she was the sister to six other siblings her parents were charles ernest acker and alice beal she was raised in ossining new york phillips started drawing as a child her uncles were reynolds beal and gifford beal both men noticed phillips artistic ability and suggested she pursue art as a career path she began attending the art students league in 1915 and graduated in 1918 she studied under boardman robinson marjorie phillips has the unmistakable style of the born painter duncan phillips phillips is quoted as stating that she didn t want to paint depressing pictures she painted primarily landscapes and still life works despite living a socialite lifestyle alongside her husband phillips made the effort to paint every morning in her washington d c studio she attended an art exhibition for duncan phillips at the century association in january 1921 she met duncan and the two married in october of that year duncan was an art collector and the couple expanded their collecting phillips moved to washington d c and into duncan s dupont circle mansion duncan s mother',
 '21 november 1811 d 21 may 1883 was a german born british botanist and zoologist preiss was born in herzberg am harz he obtained a doctorate probably at hamburg then emigrated to western australia he arrived at the swan river colony on board the britmart on 4 december 1838 remaining there until january 1842 during this time he became a british subject during his time in western australia preiss collected about 200 000 plant specimens containing from 3 000 to 4 000 species his collections together with those of james drummond formed the basis for early study of western australian flora in 1842 he left western australia for london where he broke up and sold his plant collection to recoup his costs various botanists published species based on his specimens and these were later collated by johann lehmann to form the multi volume plantae preissianae sive enumeratio plantarum quas in australasia occidentali et meridionale occidentali annis 1838 41 collegit l published in hamburg between 1844 and 1848 the specimens collected by preiss were not limited to plants they included birds reptiles insects and molluscs the molluscs were described by karl theodor menke and published in hanover in 1843 titled molluscorum',

### Vector Database Storage

In [7]:
from tqdm import tqdm

BATCH_SIZE = 5000
total_doc = len(doc_texts)

for i in tqdm(range(0, total_doc, BATCH_SIZE)):
    batch_texts = doc_texts[i: i + BATCH_SIZE]
    batch_ids = doc_ids[i: i + BATCH_SIZE]

    collection.add(
        documents=batch_texts,
        ids=batch_ids
    )

print("Vectorization!")

100%|██████████| 74/74 [1:12:09<00:00, 58.51s/it]

Vectorization!

In [8]:
queries = []

for query in dataset.queries_iter():
    queries.append(query.text)

In [11]:
results_15 = collection.query(
    query_texts=queries,
    n_results=15
)

In [15]:
import gc
del results_20
gc.collect()

0

In [13]:
from collections import defaultdict
query_id_vs_text = defaultdict(str)

for query in dataset.queries_iter():
    query_id_vs_text[query.query_id] = query.text

query_id_vs_text = dict(query_id_vs_text)

In [16]:
doc_id_vs_text = defaultdict(str)

for doc in dataset.docs_iter():
    doc_id_vs_text[doc.doc_id] = doc.text

In [17]:
results_15['ids']

[['516871',
  '647478',
  '2129172',
  '806300',
  '2357011',
  '1222510',
  '806263',
  '2433706',
  '708880',
  '775424',
  '434612',
  '2320659',
  '2356422',
  '1987805',
  '1423498'],
 ['188629',
  '251586',
  '2397950',
  '2061524',
  '272146',
  '1948304',
  '2437665',
  '1278316',
  '1614942',
  '1363774',
  '1399078',
  '1379412',
  '492051',
  '1936742',
  '1152359'],
 ['13898',
  '785960',
  '1382760',
  '941146',
  '802532',
  '1048798',
  '1989378',
  '1874948',
  '2031249',
  '462902',
  '1263356',
  '1334004',
  '166703',
  '1263194',
  '259523'],
 ['316959',
  '562691',
  '1326263',
  '2156815',
  '687712',
  '42143',
  '1639962',
  '1469362',
  '729083',
  '1422464',
  '1921875',
  '1999122',
  '714978',
  '1978987',
  '2224682'],
 ['515031',
  '706326',
  '780987',
  '832086',
  '842375',
  '860147',
  '828931',
  '833668',
  '754830',
  '823332',
  '843406',
  '837562',
  '1662828',
  '836749',
  '888195'],
 ['2267777',
  '421974',
  '1630942',
  '1209576',
  '2322923',
  '152040',
  '116684',
  '2117771',
  '1411855',
  '123783',
  '2429087',
  '579503',
  '2284994',
  '1077367',
  '1477184'],
 ['615358',
  '1712050',
  '2361455',
  '1297050',
  '1878340',
  '2342190',
  '774950',
  '1913962',
  '1474866',
  '829283',
  '2047087',
  '2408420',
  '1434893',
  '340748',
  '2137652'],
 ['9591',
  '143444',
  '1898638',
  '595391',
  '1445185',
  '2378793',
  '1472431',
  '494103',
  '2021787',
  '863960',
  '1089173',
  '228350',
  '359162',
  '1753249',
  '194433'],
 ['725799',
  '1454057',
  '1478113',
  '2304325',
  '294327',
  '2352224',
  '95752',
  '2352254',
  '102670',
  '2298231',
  '1494131',
  '1608962',
  '2192970',
  '1363388',
  '2170908'],
 ['251631',
  '12846',
  '273547',
  '563603',
  '840695',
  '2091601',
  '2307963',
  '2146572',
  '2152054',
  '1674515',
  '2121759',
  '2105744',
  '1233547',
  '2306015',
  '1068787'],
 ['480239',
  '1444646',
  '104018',
  '1972988',
  '2082579',
  '24476',
  '2176846',
  '2112778',
  '1330834',
  '2101113',
  '468506',
  '865657',
  '637016',
  '1828310',
  '1281151'],
 ['1375960',
  '258957',
  '62210',
  '47266',
  '1528857',
  '1736617',
  '1962581',
  '44994',
  '1709916',
  '65096',
  '1111019',
  '2373099',
  '1094053',
  '2093045',
  '1971870'],
 ['23678',
  '936323',
  '198918',
  '1799086',
  '342272',
  '1474293',
  '1248120',
  '18925',
  '150071',
  '593437',
  '1582044',
  '1771004',
  '8742',
  '349822',
  '973127'],
 ['37480',
  '316436',
  '305953',
  '667358',
  '2359021',
  '246157',
  '1242459',
  '1571906',
  '2281956',
  '324049',
  '2083893',
  '324052',
  '324056',
  '2359426',
  '704426'],
 ['109454',
  '99150',
  '1450531',
  '2387382',
  '2170879',
  '80519',
  '31197',
  '1521334',
  '2069260',
  '2380664',
  '362686',
  '305743',
  '546261',
  '85488',
  '2264659'],
 ['544250',
  '2095411',
  '1825034',
  '682657',
  '2347960',
  '630265',
  '1937433',
  '547913',
  '1320765',
  '2347517',
  '818499',
  '1526250',
  '612848',
  '350429',
  '2021507'],
 ['1091625',
  '1374322',
  '869618',
  '1005711',
  '1739665',
  '172843',
  '101187',
  '175050',
  '12519',
  '1741677',
  '2136213',
  '1640644',
  '82510',
  '1339377',
  '1551790'],
 ['115015',
  '1351327',
  '443278',
  '458160',
  '2202113',
  '509726',
  '2085509',
  '484126',
  '57467',
  '365856',
  '516035',
  '1665906',
  '1039826',
  '1290856',
  '1561723'],
 ['527077',
  '1540254',
  '1470924',
  '890655',
  '933294',
  '2314024',
  '1434451',
  '618398',
  '1497720',
  '1289573',
  '341187',
  '1737341',
  '1486438',
  '978186',
  '2063172'],
 ['2339264',
  '797556',
  '24998',
  '1782009',
  '1793098',
  '1273144',
  '26989',
  '550651',
  '2429942',
  '674239',
  '1648229',
  '721247',
  '1396610',
  '2279453',
  '441624'],
 ['805834',
  '11925',
  '761604',
  '1063548',
  '1822371',
  '645673',
  '33853',
  '33846',
  '1844434',
  '1920902',
  '33824',
  '74607',
  '1861419',
  '735427',
  '2184330'],
 ['643',
  '1892260',
  '1115256',
  '88810',
  '27862',
  '832816',
  '2246138',
  '2075490',
  '1672669',
  '806900',
  '2284071',
  '25699',
  '1008760',
  '205973',
  '176281'],
 ['113075',
  '572485',
  '46442',
  '625621',
  '1108946',
  '60048',
  '1672942',
  '363175',
  '1039826',
  '769187',
  '20213',
  '798582',
  '11726',
  '1039211',
  '1690334'],
 ['1250387',
  '95283',
  '297902',
  '1268901',
  '1732479',
  '2217046',
  '707898',
  '599253',
  '1794130',
  '79211',
  '602556',
  '1683108',
  '2021655',
  '185621',
  '748335'],
 ['111938',
  '111442',
  '72012',
  '111443',
  '88775',
  '103174',
  '941306',
  '2371473',
  '727793',
  '661128',
  '1806360',
  '818663',
  '147416',
  '165002',
  '162840'],
 ['167865',
  '995221',
  '1155889',
  '1469500',
  '1730916',
  '410277',
  '1469315',
  '2006878',
  '2345059',
  '461641',
  '415355',
  '1720028',
  '857512',
  '1930463',
  '2366479'],
 ['2316655',
  '735915',
  '1737940',
  '1641422',
  '1083694',
  '1425120',
  '242943',
  '12523',
  '2428438',
  '179529',
  '627072',
  '1192652',
  '836205',
  '360464',
  '2260761'],
 ['982243',
  '1346094',
  '1472358',
  '1048454',
  '1357456',
  '2366040',
  '370467',
  '689411',
  '2200660',
  '1297674',
  '766667',
  '280180',
  '1332226',
  '647047',
  '2003372'],
 ['27200',
  '143487',
  '2389598',
  '353797',
  '1834661',
  '621974',
  '1570665',
  '1536243',
  '821177',
  '1409420',
  '1863100',
  '1865855',
  '881168',
  '923643',
  '1217284'],
 ['136856',
  '2429792',
  '1045080',
  '12030',
  '2398412',
  '1714638',
  '817838',
  '1018623',
  '1041737',
  '1505618',
  '199322',
  '22018',
  '631857',
  '425788',
  '1428103'],
 ['6031',
  '23531',
  '123675',
  '801082',
  '157645',
  '2026699',
  '978358',
  '825709',
  '268',
  '241657',
  '1794304',
  '306801',
  '157426',
  '561790',
  '390992'],
 ['1355235',
  '765953',
  '2183271',
  '1276710',
  '1599139',
  '66335',
  '521794',
  '624381',
  '871901',
  '1211578',
  '983764',
  '649770',
  '2278396',
  '1585371',
  '1766105'],
 ['142017',
  '187115',
  '964393',
  '1909942',
  '962337',
  '16835',
  '70941',
  '123472',
  '117796',
  '1287179',
  '2187891',
  '1134448',
  '952276',
  '1012100',
  '867611'],
 ['84110',
  '350478',
  '309827',
  '1395090',
  '669700',
  '1463965',
  '1673329',
  '2087053',
  '2114632',
  '417446',
  '446428',
  '830879',
  '784975',
  '1773435',
  '2217789'],
 ['208234',
  '1376164',
  '265774',
  '263328',
  '1399530',
  '39823',
  '2448203',
  '1278779',
  '647439',
  '273912',
  '14293',
  '752432',
  '1686554',
  '625455',
  '1177302'],
 ['6431',
  '273681',
  '5400',
  '8',
  '872358',
  '1096749',
  '713517',
  '991561',
  '1675838',
  '603672',
  '556999',
  '900838',
  '956464',
  '1663849',
  '510840'],
 ['10799',
  '242372',
  '1439685',
  '1359168',
  '1556106',
  '833682',
  '333322',
  '2092963',
  '56434',
  '1405679',
  '470956',
  '1318179',
  '1531830',
  '1522518',
  '248591'],
 ['1417144',
  '2218374',
  '796351',
  '2200958',
  '2387555',
  '2101949',
  '491879',
  '484084',
  '2168362',
  '1582438',
  '498995',
  '494005',
  '1479971',
  '1087520',
  '494032'],
 ['32512',
  '1975061',
  '1459193',
  '1782752',
  '741188',
  '151376',
  '497527',
  '104813',
  '265938',
  '182986',
  '1172814',
  '966630',
  '663742',
  '84379',
  '32644'],
 ['1733122',
  '1364109',
  '311557',
  '1599798',
  '677637',
  '2098366',
  '1657377',
  '122359',
  '2193147',
  '913365',
  '424385',
  '1577989',
  '1262604',
  '1797233',
  '322640'],
 ['2130224',
  '1885628',
  '902154',
  '402550',
  '1353089',
  '1037196',
  '1604490',
  '730062',
  '2431881',
  '1096276',
  '97937',
  '1178619',
  '183169',
  '246138',
  '2108591'],
 ['113765',
  '1807222',
  '2404665',
  '387811',
  '2063339',
  '2102073',
  '777764',
  '1837408',
  '1665770',
  '2096784',
  '1727802',
  '1605922',
  '2248728',
  '889665',
  '1806721'],
 ['12900',
  '1813838',
  '2022703',
  '1295954',
  '2047334',
  '1527855',
  '1804869',
  '1137896',
  '1865255',
  '171087',
  '2101142',
  '1685875',
  '226878',
  '1656383',
  '1300894'],
 ['1294909',
  '1437752',
  '8862',
  '833430',
  '140477',
  '75643',
  '2094069',
  '2243892',
  '366256',
  '2430513',
  '1858670',
  '734795',
  '2413308',
  '20558',
  '20555'],
 ['73745',
  '80609',
  '224167',
  '144080',
  '157380',
  '2158109',
  '55300',
  '154217',
  '272325',
  '2237867',
  '336629',
  '129610',
  '533230',
  '1457034',
  '1641164'],
 ['11692',
  '419310',
  '178257',
  '1239138',
  '1682640',
  '1309170',
  '1929375',
  '38525',
  '419322',
  '447802',
  '1789375',
  '1182265',
  '1739586',
  '1073421',
  '211478'],
 ['1405463',
  '1652701',
  '1996894',
  '22173',
  '444826',
  '2076257',
  '1126500',
  '2072406',
  '1481423',
  '2171030',
  '364171',
  '1409669',
  '2333975',
  '2293010',
  '2039503'],
 ['995154',
  '76662',
  '1503801',
  '1499333',
  '1949558',
  '1229486',
  '1676360',
  '1293257',
  '2381328',
  '1340271',
  '2257821',
  '1849148',
  '1144722',
  '509280',
  '566601'],
 ['163054',
  '135280',
  '144056',
  '5491',
  '1893964',
  '1703851',
  '1761034',
  '1654745',
  '13150',
  '2268032',
  '2306723',
  '38215',
  '498937',
  '2200362',
  '1389117'],
 ['2390262',
  '138596',
  '1735064',
  '1198234',
  '2035569',
  '575641',
  '2275705',
  '2426389',
  '2289215',
  '1921663',
  '1290643',
  '1946565',
  '1193872',
  '502262',
  '2304171'],
 ['9367',
  '1080010',
  '2413145',
  '1156962',
  '2317161',
  '1014015',
  '1849621',
  '1179901',
  '2131530',
  '2355068',
  '1255895',
  '436388',
  '1996632',
  '1947407',
  '1942436'],
 ['592217',
  '1526250',
  '202512',
  '1374804',
  '2105943',
  '782565',
  '729115',
  '1552189',
  '566177',
  '1585728',
  '628624',
  '545389',
  '917501',
  '513994',
  '513989'],
 ['688437',
  '1705561',
  '2251287',
  '2164008',
  '1357226',
  '630445',
  '2382643',
  '2166187',
  '1245418',
  '566833',
  '1265756',
  '2016946',
  '1551582',
  '1948361',
  '2214686'],
 ['98175',
  '2291538',
  '1377542',
  '341318',
  '554281',
  '162573',
  '761863',
  '16237',
  '1056911',
  '1120588',
  '112887',
  '266949',
  '131189',
  '2395456',
  '227716'],
 ['15189',
  '1777723',
  '1727246',
  '928666',
  '191409',
  '2402251',
  '527181',
  '281820',
  '1525124',
  '1125029',
  '84799',
  '296518',
  '427910',
  '124228',
  '1877576'],
 ['1256',
  '532622',
  '2212594',
  '538932',
  '219523',
  '26532',
  '1205962',
  '1921240',
  '643234',
  '113333',
  '1614821',
  '1235263',
  '2440176',
  '528076',
  '797163'],
 ['1815937',
  '802932',
  '1682867',
  '1275085',
  '817255',
  '1623992',
  '893788',
  '1967676',
  '328484',
  '519967',
  '177699',
  '452395',
  '1034539',
  '123961',
  '675613'],
 ['1249076',
  '543243',
  '1273024',
  '4516',
  '271134',
  '81952',
  '1952393',
  '1714047',
  '1104061',
  '514424',
  '1086104',
  '2439302',
  '488554',
  '2354640',
  '899835'],
 ['80274',
  '176330',
  '176295',
  '443948',
  '176310',
  '1154100',
  '1641604',
  '303249',
  '849215',
  '262955',
  '1061716',
  '145260',
  '150130',
  '871038',
  '176417'],
 ['580313',
  '392923',
  '180488',
  '923348',
  '1518152',
  '1752197',
  '1949111',
  '342955',
  '2264502',
  '723725',
  '1867064',
  '611772',
  '591976',
  '2025590',
  '2100481'],
 ['494005',
  '11311',
  '1552610',
  '2445017',
  '1628890',
  '1639377',
  '26989',
  '1294830',
  '76828',
  '77619',
  '721247',
  '1447017',
  '662221',
  '1978435',
  '479851'],
 ['4754',
  '2149205',
  '1096243',
  '1656412',
  '1724048',
  '691585',
  '1800345',
  '721162',
  '2329167',
  '1588010',
  '744387',
  '720376',
  '2128150',
  '1301454',
  '740512'],
 ['1904837',
  '1813554',
  '1625568',
  '1248468',
  '237513',
  '1143686',
  '1644104',
  '535261',
  '775788',
  '701383',
  '905032',
  '948342',
  '1297837',
  '719773',
  '2102308'],
 ['141668',
  '2427210',
  '943985',
  '1238621',
  '1722747',
  '244879',
  '1149634',
  '906680',
  '12419',
  '1281844',
  '2454330',
  '943164',
  '938235',
  '2148663',
  '462718'],
 ['100895',
  '2077781',
  '1673670',
  '551090',
  '414800',
  '2280676',
  '1547597',
  '729921',
  '151737',
  '106926',
  '1598700',
  '2085044',
  '77853',
  '2260385',
  '412453'],
 ['32945',
  '860527',
  '521426',
  '1523162',
  '1166470',
  '529346',
  '1148123',
  '605804',
  '1091835',
  '1649268',
  '1417564',
  '1701000',
  '900108',
  '1469155',
  '592590'],
 ['747403',
  '671277',
  '2035341',
  '1917841',
  '1268381',
  '1440113',
  '430583',
  '1862090',
  '801085',
  '931871',
  '1873058',
  '2279523',
  '1747674',
  '975954',
  '1173238'],
 ['133725',
  '6502',
  '415845',
  '2131799',
  '422942',
  '1364208',
  '1036333',
  '856455',
  '273576',
  '1434526',
  '73573',
  '2246495',
  '1442392',
  '150151',
  '2162400'],
 ['1021566',
  '1642494',
  '2307338',
  '1308897',
  '1528190',
  '1523812',
  '2388054',
  '2145092',
  '754554',
  '2145066',
  '323909',
  '2410624',
  '2169579',
  '2127453',
  '696224'],
 ['523456',
  '371437',
  '4531',
  '414850',
  '962670',
  '12895',
  '437614',
  '1405040',
  '336506',
  '1097635',
  '1124756',
  '1472868',
  '29298',
  '325379',
  '183637'],
 ['2288752',
  '952949',
  '2394262',
  '2194210',
  '1826480',
  '1781178',
  '1926176',
  '2369430',
  '1776753',
  '1327515',
  '989174',
  '2246771',
  '1537119',
  '2416301',
  '1633475'],
 ['1308339',
  '1148028',
  '1647153',
  '2250978',
  '1751100',
  '2274548',
  '990503',
  '722326',
  '2125911',
  '645811',
  '1236195',
  '1646831',
  '1218462',
  '1524582',
  '1595401'],
 ['994027',
  '9739',
  '370163',
  '606214',
  '19501',
  '625110',
  '217707',
  '473870',
  '481',
  '32789',
  '1096838',
  '561714',
  '141960',
  '112395',
  '963157'],
 ['76212',
  '367496',
  '617486',
  '477329',
  '825207',
  '404557',
  '1817678',
  '75662',
  '35538',
  '2842',
  '1183507',
  '369859',
  '151403',
  '1053206',
  '177582'],
 ['143444',
  '390102',
  '1445185',
  '654690',
  '599764',
  '2384417',
  '1214633',
  '228350',
  '422171',
  '1657289',
  '614004',
  '1622870',
  '1848954',
  '2381440',
  '1078263'],
 ['287226',
  '1225575',
  '129940',
  '1780424',
  '619960',
  '1879214',
  '466726',
  '286085',
  '169117',
  '1739638',
  '147983',
  '810694',
  '1761522',
  '1006027',
  '841669'],
 ['12527',
  '578427',
  '1555649',
  '2428193',
  '2212190',
  '1658551',
  '1577005',
  '75097',
  '10554',
  '1004492',
  '1964437',
  '333513',
  '745568',
  '297588',
  '108457'],
 ['327199',
  '2108737',
  '1356318',
  '1745143',
  '252331',
  '1438227',
  '807731',
  '2121476',
  '1305366',
  '983967',
  '1104707',
  '238060',
  '774359',
  '2422418',
  '1937219'],
 ['7707',
  '2082736',
  '1137865',
  '1304560',
  '75292',
  '197853',
  '1351538',
  '38280',
  '73982',
  '1814547',
  '1720118',
  '1037038',
  '76076',
  '119190',
  '1198733'],
 ['366421',
  '668912',
  '1769581',
  '2192685',
  '216755',
  '1760580',
  '436500',
  '977826',
  '1840369',
  '1661626',
  '1726671',
  '1655837',
  '1033188',
  '374208',
  '2339438'],
 ['1262433',
  '138787',
  '835238',
  '178965',
  '195536',
  '1173765',
  '1027074',
  '2096993',
  '780086',
  '1125799',
  '1564204',
  '563013',
  '570514',
  '1220453',
  '1872594'],
 ['1574239',
  '216004',
  '487985',
  '1853525',
  '228427',
  '862571',
  '805510',
  '1825258',
  '1808302',
  '2437187',
  '1916934',
  '2103052',
  '787436',
  '2438463',
  '613043'],
 ['74026',
  '1692185',
  '1939981',
  '2008559',
  '1024603',
  '2239263',
  '2026089',
  '876989',
  '1917430',
  '2051645',
  '2433387',
  '1292862',
  '1210483',
  '1901680',
  '37939'],
 ['358108',
  '385779',
  '641464',
  '2347962',
  '327516',
  '2399039',
  '1415140',
  '2399027',
  '1900940',
  '655751',
  '77900',
  '262927',
  '2156651',
  '2373591',
  '1012889'],
 ['215045',
  '792398',
  '221767',
  '95179',
  '1524724',
  '1985516',
  '1106008',
  '1172357',
  '1431105',
  '1281897',
  '977774',
  '163049',
  '640992',
  '825742',
  '1377075'],
 ['7862',
  '31959',
  '2105881',
  '1790915',
  '1837372',
  '158608',
  '2112520',
  '1420052',
  '2297661',
  '1431449',
  '331357',
  '1436152',
  '2038979',
  '1105866',
  '2364008'],
 ['2410505',
  '1026962',
  '1466638',
  '151797',
  '945975',
  '1122564',
  '308871',
  '733772',
  '2347862',
  '2093995',
  '2361104',
  '1221012',
  '1535185',
  '2216413',
  '1405532'],
 ['1885740',
  '2449764',
  '1557037',
  '92980',
  '1332097',
  '926663',
  '959739',
  '2013157',
  '1323222',
  '2379955',
  '2126656',
  '1194762',
  '1008879',
  '1601808',
  '1150936'],
 ['100876',
  '364463',
  '623213',
  '1084783',
  '1557927',
  '128662',
  '1716699',
  '1207967',
  '170881',
  '329782',
  '1350444',
  '1556106',
  '1093240',
  '970308',
  '1457821'],
 ['238228',
  '1663108',
  '1571094',
  '1379427',
  '1959375',
  '1228649',
  '892994',
  '1217535',
  '1831032',
  '1896156',
  '205482',
  '1170848',
  '1125114',
  '395690',
  '784641'],
 ['1573135',
  '107755',
  '1675831',
  '44834',
  '152013',
  '1668820',
  '1580406',
  '694729',
  '1660355',
  '1879372',
  '1231050',
  '1668011',
  '646023',
  '1573767',
  '2036287'],
 ['1435368',
  '2998',
  '32539',
  '1303795',
  '90245',
  '1890891',
  '2149417',
  '2350366',
  '2205542',
  '2146369',
  '995970',
  '708041',
  '1317487',
  '2263704',
  '835475'],
 ['12953',
  '352291',
  '1287354',
  '1521266',
  '1325306',
  '2412918',
  '970982',
  '1892789',
  '904039',
  '2284958',
  '1677820',
  '2246805',
  '795409',
  '381420',
  '525221'],
 ['1627516',
  '24843',
  '2408273',
  '2035157',
  '1642342',
  '2363725',
  '593689',
  '1257572',
  '350217',
  '1477570',
  '24678',
  '1878188',
  '1087179',
  '2027259',
  '1585346'],
 ['119528',
  '1375736',
  '1324050',
  '1290126',
  '941800',
  '608901',
  '2175',
  '1392123',
  '1809692',
  '617723',
  '2217579',
  '1240135',
  '32770',
  '1561165',
  '1187264'],
 ['30765',
  '1940739',
  '2414011',
  '2448630',
  '2033877',
  '2195412',
  '1663392',
  '2388837',
  '2266511',
  '1734071',
  '1425659',
  '1246307',
  '1716440',
  '164539',
  '2277945'],
 ['1747453',
  '2324553',
  '1859748',
  '2277222',
  '2402212',
  '1715223',
  '2329579',
  '1225873',
  '694614',
  '1035144',
  '1802790',
  '2185539',
  '1728163',
  '2053756',
  '134772'],
 ['27711',
  '1159074',
  '1970676',
  '1298753',
  '1208186',
  '1856373',
  '1595287',
  '1295906',
  '846186',
  '1461132',
  '1392846',
  '1297405',
  '918899',
  '2275890',
  '666061'],
 ['361260',
  '789008',
  '1139701',
  '1315714',
  '1167923',
  '2379122',
  '1829711',
  '1965844',
  '1059092',
  '1518226',
  '1390753',
  '1868087',
  '730062',
  '1020307',
  '159298'],
 ['1155816',
  '1069124',
  '1401923',
  '1523152',
  '2286924',
  '1836905',
  '1355138',
  '1120763',
  '1854954',
  '2320439',
  '17874',
  '339200',
  '1149186',
  '1029884',
  '1960512'],
 ['646810',
  '1858670',
  '2331665',
  '1049435',
  '1803263',
  '1008048',
  '1859727',
  '1872578',
  '3524',
  '1897038',
  '1587367',
  '580665',
  '1611299',
  '2433541',
  '471206'],
 ['1707214',
  '1701932',
  '174555',
  '2301158',
  '201350',
  '75902',
  '2326180',
  '2406930',
  '1551388',
  '2190516',
  '2266511',
  '474735',
  '912496',
  '570883',
  '828472'],
 ['809894',
  '2137903',
  '465836',
  '1983965',
  '1727670',
  '396020',
  '1811486',
  '101951',
  '1105126',
  '2447763',
  '1990611',
  '180468',
  '191056',
  '1614656',
  '1153877'],
 ['126362',
  '2017386',
  '1502762',
  '1516131',
  '1788275',
  '1243370',
  '441844',
  '2048835',
  '298712',
  '1982200',
  '1876557',
  '1600899',
  '794533',
  '811195',
  '335565'],
 ['1929606',
  '288208',
  '156297',
  '2354105',
  '2183996',
  '88289',
  '1818426',
  '2180582',
  '2051963',
  '1739349',
  '2179770',
  '693688',
  '2187775',
  '1460865',
  '309801'],
 ['1826790',
  '1329692',
  '2085523',
  '406254',
  '2054691',
  '733103',
  '494427',
  '1030741',
  '722995',
  '126362',
  '702532',
  '1401256',
  '441844',
  '1115248',
  '464402'],
 ['659452',
  '1402356',
  '1251186',
  '453222',
  '542740',
  '255841',
  '1669108',
  '728656',
  '2024416',

In [20]:
query_ids = [query.query_id for query in dataset.queries_iter()]

In [22]:
query_doc_pairs = defaultdict(list)

for idx in range(len(query_ids)):
    for doc_id in results_15['ids'][idx]:
        query_id = query_ids[idx]
        query_doc_pairs[query_id].append((query_id_vs_text[query_id], doc_id_vs_text[doc_id]))

query_doc_pairs = dict(query_doc_pairs)

### CrossEncoder

In [25]:
from sentence_transformers import CrossEncoder
model = CrossEncoder('cross-encoder/ms-marco-MiniLM-L6-v2')

Loading weights: 100%|██████████| 105/105 [00:00<00:00, 1966.98it/s]

In [26]:
query_score_dict = defaultdict(list)

for query_id in query_ids:
    query_score_dict[query_id] = list(model.predict(query_doc_pairs[query_id]))

In [27]:
query_score_dict["123839"]

[np.float32(-0.45067456),
 np.float32(-0.17859712),
 np.float32(-0.33984625),
 np.float32(6.4627924),
 np.float32(0.458524),
 np.float32(2.2397873),
 np.float32(4.384878),
 np.float32(1.5397115),
 np.float32(-2.3310945),
 np.float32(-1.3943533),
 np.float32(-0.76778865),
 np.float32(1.908722),
 np.float32(0.89662874),
 np.float32(-9.491181),
 np.float32(-9.244002)]

In [31]:
retrieved_docs_with_scores = defaultdict(list)

for query_idx in range(len(query_ids)):
    tuple_list = []
    query_id = query_ids[query_idx]

    for doc_idx in range(15):
        tuple_list.append((query_score_dict[query_id][doc_idx], results_15['ids'][query_idx][doc_idx]))

    retrieved_docs_with_scores[query_id] = sorted(tuple_list, reverse=True)

retrieved_docs_with_scores = dict(retrieved_docs_with_scores)

In [32]:
retrieved_docs_with_scores

{'123839': [(np.float32(6.4627924), '806300'),
  (np.float32(4.384878), '806263'),
  (np.float32(2.2397873), '1222510'),
  (np.float32(1.908722), '2320659'),
  (np.float32(1.5397115), '2433706'),
  (np.float32(0.89662874), '2356422'),
  (np.float32(0.458524), '2357011'),
  (np.float32(-0.17859712), '647478'),
  (np.float32(-0.33984625), '2129172'),
  (np.float32(-0.45067456), '516871'),
  (np.float32(-0.76778865), '434612'),
  (np.float32(-1.3943533), '775424'),
  (np.float32(-2.3310945), '708880'),
  (np.float32(-9.244002), '1423498'),
  (np.float32(-9.491181), '1987805')],
 '188629': [(np.float32(8.445473), '188629'),
  (np.float32(3.8551636), '2437665'),
  (np.float32(0.7997365), '251586'),
  (np.float32(-0.66893935), '2061524'),
  (np.float32(-0.7973872), '1948304'),
  (np.float32(-0.8317001), '1379412'),
  (np.float32(-2.1443884), '1936742'),
  (np.float32(-2.170946), '1399078'),
  (np.float32(-2.263849), '492051'),
  (np.float32(-2.370374), '2397950'),
  (np.float32(-2.9040346), '272146'),
  (np.float32(-3.394856), '1152359'),
  (np.float32(-5.0114965), '1363774'),
  (np.float32(-7.424327), '1278316'),
  (np.float32(-7.819533), '1614942')],
 '13898': [(np.float32(8.505053), '13898'),
  (np.float32(6.991241), '785960'),
  (np.float32(4.1102757), '1874948'),
  (np.float32(2.5988164), '259523'),
  (np.float32(2.5885808), '1382760'),
  (np.float32(1.3634877), '1989378'),
  (np.float32(0.87422943), '1048798'),
  (np.float32(-0.272156), '1263356'),
  (np.float32(-0.7390934), '462902'),
  (np.float32(-0.95281583), '166703'),
  (np.float32(-2.3296618), '1263194'),
  (np.float32(-2.3394446), '2031249'),
  (np.float32(-2.5317385), '802532'),
  (np.float32(-3.2556376), '941146'),
  (np.float32(-5.345992), '1334004')],
 '316959': [(np.float32(7.5384083), '316959'),
  (np.float32(3.3230155), '1326263'),
  (np.float32(2.686766), '2156815'),
  (np.float32(0.6588752), '687712'),
  (np.float32(0.6002609), '714978'),
  (np.float32(0.18752973), '1422464'),
  (np.float32(0.13480444), '1921875'),
  (np.float32(-1.2698994), '729083'),
  (np.float32(-1.4036429), '42143'),
  (np.float32(-1.5449772), '562691'),
  (np.float32(-1.943208), '1469362'),
  (np.float32(-2.3442206), '1639962'),
  (np.float32(-2.71428), '1999122'),
  (np.float32(-4.1779146), '1978987'),
  (np.float32(-5.236841), '2224682')],
 '515031': [(np.float32(7.0172744), '515031'),
  (np.float32(6.441485), '888195'),
  (np.float32(6.305478), '832086'),
  (np.float32(5.5589447), '828931'),
  (np.float32(5.29062), '860147'),
  (np.float32(5.195225), '842375'),
  (np.float32(5.007304), '833668'),
  (np.float32(4.819082), '780987'),
  (np.float32(4.8109307), '754830'),
  (np.float32(4.7335076), '837562'),
  (np.float32(4.613569), '1662828'),
  (np.float32(4.600378), '843406'),
  (np.float32(4.503656), '836749'),
  (np.float32(4.3684835), '823332'),
  (np.float32(4.080241), '706326')],
 '123783': [(np.float32(7.361398), '1411855'),
  (np.float32(7.3440332), '1209576'),
  (np.float32(7.3166122), '123783'),
  (np.float32(7.3123627), '2267777'),
  (np.float32(6.6826234), '579503'),
  (np.float32(6.176649), '421974'),
  (np.float32(5.147932), '1630942'),
  (np.float32(4.1697965), '2429087'),
  (np.float32(1.9926157), '2117771'),
  (np.float32(1.6480004), '116684'),
  (np.float32(0.9691361), '2284994'),
  (np.float32(0.7662761), '2322923'),
  (np.float32(-0.03381005), '1477184'),
  (np.float32(-2.7349148), '1077367'),
  (np.float32(-3.7399848), '152040')],
 '4332': [(np.float32(-0.67307127), '615358'),
  (np.float32(-2.5485861), '1712050'),
  (np.float32(-5.047935), '1913962'),
  (np.float32(-5.7642922), '2342190'),
  (np.float32(-6.9728966), '1878340'),
  (np.float32(-7.79452), '2361455'),
  (np.float32(-7.9287696), '1474866'),
  (np.float32(-8.1458435), '1297050'),
  (np.float32(-8.2491665), '829283'),
  (np.float32(-8.857561), '774950'),
  (np.float32(-8.955076), '2047087'),
  (np.float32(-9.000991), '1434893'),
  (np.float32(-9.270627), '2408420'),
  (np.float32(-9.640118), '2137652'),
  (np.float32(-9.846839), '340748')],
 '9591': [(np.float32(8.093671), '9591'),
  (np.float32(7.285639), '2021787'),
  (np.float32(6.7252126), '863960'),
  (np.float32(6.085355), '143444'),
  (np.float32(5.4777946), '1898638'),
  (np.float32(5.1751575), '1753249'),
  (np.float32(3.9607406), '494103'),
  (np.float32(2.8800144), '194433'),
  (np.float32(2.7365532), '1472431'),
  (np.float32(2.336104), '1445185'),
  (np.float32(2.3229673), '359162'),
  (np.float32(1.7415823), '2378793'),
  (np.float32(1.6241543), '1089173'),
  (np.float32(0.5158462), '228350'),
  (np.float32(-0.267469), '595391')],
 '114982': [(np.float32(-0.11408083), '2304325'),
  (np.float32(-1.3551772), '95752'),
  (np.float32(-2.583476), '725799'),
  (np.float32(-2.8245916), '2192970'),
  (np.float32(-2.9240932), '2352224'),
  (np.float32(-3.1097927), '2352254'),
  (np.float32(-3.5708878), '1478113'),
  (np.float32(-3.6146078), '1494131'),
  (np.float32(-3.8186212), '1608962'),
  (np.float32(-3.9595733), '294327'),
  (np.float32(-4.492327), '2298231'),
  (np.float32(-6.214917), '102670'),
  (np.float32(-7.087176), '2170908'),
  (np.float32(-7.687881), '1363388'),
  (np.float32(-7.914377), '1454057')],
 '563603': [(np.float32(8.440907), '12846'),
  (np.float32(7.512452), '563603'),
  (np.float32(4.21857), '2146572'),
  (np.float32(3.5420852), '2307963'),
  (np.float32(2.9807315), '251631'),
  (np.float32(2.7247293), '1068787'),
  (np.float32(2.2369268), '2152054'),
  (np.float32(2.0908422), '1233547'),
  (np.float32(1.277432), '2121759'),
  (np.float32(1.2653439), '2091601'),
  (np.float32(0.67430353), '273547'),
  (np.float32(0.205955), '840695'),
  (np.float32(-5.934019), '2105744'),
  (np.float32(-6.211226), '1674515'),
  (np.float32(-10.794085), '2306015')],
 '104206': [(np.float32(6.9972305), '480239'),
  (np.float32(5.107546), '2101113'),
  (np.float32(4.9170837), '1281151'),
  (np.float32(4.8274446), '865657'),
  (np.float32(4.719736), '1972988'),
  (np.float32(4.423123), '1444646'),
  (np.float32(4.335867), '104018'),
  (np.float32(3.7791958), '468506'),
  (np.float32(0.96102166), '2176846'),
  (np.float32(-0.03162273), '24476'),
  (np.float32(-0.70525396), '1330834'),
  (np.float32(-0.7456948), '2112778'),
  (np.float32(-0.8279002), '637016'),
  (np.float32(-1.447032), '1828310'),
  (np.float32(-2.0057044), '2082579')],
 '1580851': [(np.float32(1.2473059), '258957'),
  (np.float32(0.5025361), '44994'),
  (np.float32(0.35696012), '1375960'),
  (np.float32(0.22211896), '47266'),
  (np.float32(-0.028798249), '1736617'),
  (np.float32(-0.100702), '1111019'),
  (np.float32(-0.34489584), '65096'),
  (np.float32(-0.64338243), '2093045'),
  (np.float32(-0.8511424), '62210'),
  (np.float32(-1.3012929), '1962581'),
  (np.float32(-1.9665277), '1971870'),
  (np.float32(-1.974794), '1094053'),
  (np.float32(-2.0214627), '1528857'),
  (np.float32(-2.9213731), '1709916'),
  (np.float32(-2.9249225), '2373099')],
 '23678': [(np.float32(6.922985), '23678'),
  (np.float32(5.1238556), '936323'),
  (np.float32(4.364574), '342272'),
  (np.float32(1.9035077), '1771004'),
  (np.float32(-1.9556682), '349822'),
  (np.float32(-2.2364311), '1799086'),
  (np.float32(-2.3776348), '593437'),
  (np.float32(-5.576817), '198918'),
  (np.float32(-5.798986), '18925'),
  (np.float32(-6.597494), '8742'),
  (np.float32(-6.6031094), '1582044'),
  (np.float32(-7.9371357), '1248120'),
  (np.float32(-9.528365), '150071'),
  (np.float32(-10.138006), '1474293'),
  (np.float32(-10.513862), '973127')],
 '37480': [(np.float32(6.66774), '37480'),
  (np.float32(5.961956), '316436'),
  (np.float32(5.3737354), '305953'),
  (np.float32(4.1969733), '246157'),
  (np.float32(3.9027386), '1571906'),
  (np.float32(3.2587986), '667358'),
  (np.float32(2.584536), '2359021'),
  (np.float32(0.8471861), '2083893'),
  (np.float32(0.37792623), '1242459'),
  (np.float32(0.32897088), '324052'),
  (np.float32(-0.34697184), '2281956'),
  (np.float32(-3.110367), '324056'),
  (np.float32(-3.8180783), '2359426'),
  (np.float32(-3.9371452), '324049'),
  (np.float32(-8.136456), '704426')],
 '109454': [(np.float32(7.4676104), '109454'),
  (np.float32(7.1964364), '2069260'),
  (np.float32(6.1303887), '2264659'),
  (np.float32(3.551186), '1450531'),
  (np.float32(2.5006485), '305743'),
  (np.float32(1.6802591), '2170879'),
  (np.float32(0.77338946), '80519'),
  (np.float32(0.7545598), '362686'),
  (np.float32(-0.1522347), '85488'),
  (np.float32(-0.49151075), '31197'),
  (np.float32(-1.1545398), '99150'),
  (np.float32(-1.7916546), '546261'),
  (np.float32(-1.8279102), '2387382'),
  (np.float32(-2.9415495), '2380664'),
  (np.float32(-4.903555), '1521334')],
 '544250': [(np.float32(9.539725), '544250'),
  (np.float32(7.212086), '2095411'),
  (np.float32(4.773056), '630265'),
  (np.float32(4.616335), '2347517'),
  (np.float32(4.4284124), '2347960'),
  (np.float32(3.5625548), '1937433'),
  (np.float32(3.5579205), '682657'),
  (np.float32(0.6127166), '1825034'),
  (np.float32(-2.288736), '547913'),
  (np.float32(-4.8823338), '1526250'),
  (np.float32(-6.1580076), '818499'),
  (np.float32(-6.7183905), '1320765'),
  (np.float32(-7.1456976), '2021507'),
  (np.float32(-8.0673895), '612848'),
  (np.float32(-8.333918), '350429')],
 '12519': [(np.float32(8.645937), '1091625'),
  (np.float32(7.616864), '1739665'),
  (np.float32(6.2943063), '1005711'),
  (np.float32(4.3199005), '869618'),
  (np.float32(4.2258024), '12519'),
  (np.float32(3.7614856), '172843'),
  (np.float32(3.5413814), '1741677'),
  (np.float32(3.4602253), '1374322'),
  (np.float32(3.0676847), '101187'),
  (np.float32(2.2128909), '175050'),
  (np.float32(1.9076138), '82510'),
  (np.float32(0.9212301), '1339377'),
  (np.float32(0.8603492), '1551790'),
  (np.float32(-2.677586), '1640644'),
  (np.float32(-6.15995), '2136213')],
 '115015': [(np.float32(8.787551), '115015'),
  (np.float32(8.211536), '1351327'),
  (np.float32(8.1244755), '2202113'),
  (np.float32(5.6432786), '1290856'),
  (np.float32(4.769822), '458160'),
  (np.float32(4.616287), '443278'),
  (np.float32(1.8278849), '509726'),
  (np.float32(0.98343223), '57467'),
  (np.float32(0.5812487), '1665906'),
  (np.float32(0.51725805), '365856'),
  (np.float32(0.12063372), '2085509'),
  (np.float32(-0.11564841), '1561723'),
  (np.float32(-0.19954874), '484126'),
  (np.float32(-2.0176616), '1039826'),
  (np.float32(-8.36347), '516035')],
 '84287': [(np.float32(1.2784978), '527077'),
  (np.float32(0.5231483), '1737341'),
  (np.float32(0.35873154), '1470924'),
  (np.float32(0.18555129), '2063172'),
  (np.float32(-0.3910175), '1497720'),
  (np.float32(-0.450324), '890655'),
  (np.float32(-1.2296897), '1486438'),
  (np.float32(-1.3364887), '978186'),
  (np.float32(-1.511069), '618398'),
  (np.float32(-2.1053224), '1540254'),
  (np.float32(-2.4748747), '2314024'),
  (np.float32(-2.530202), '1434451'),
  (np.float32(-3.155911), '341187'),
  (np.float32(-3.5763855), '933294'),
  (np.float32(-6.296094), '1289573')],
 '24998': [(np.float32(7.653126), '24998'),
  (np.float32(6.6925597), '2429942'),
  (np.float32(5.611789), '1273144'),
  (np.float32(5.593391), '797556'),
  (np.float32(5.265285), '2339264'),
  (np.float32(1.9179645), '1782009'),
  (np.float32(-6.399542), '441624'),
  (np.float32(-6.4987226), '26989'),
  (np.float32(-6.7368917), '674239'),
  (np.float32(-7.162103), '1793098'),
  (np.float32(-7.7024817), '1396610'),
  (np.float32(-7.7377124), '721247'),
  (np.float32(-8.322127), '2279453'),
  (np.float32(-8.571629), '550651'),
  (np.float32(-8.674732), '1648229')],
 '11925': [(np.float32(8.77301), '11925'),
  (np.float32(6.5762024), '1844434'),
  (np.float32(6.162888), '33846'),
  (np.float32(4.7776427), '1920902'),
  (np.float32(4.361703), '645673'),
  (np.float32(4.3143797), '33853'),
  (np.float32(4.3016524), '761604'),
  (np.float32(4.2911043), '735427'),
  (np.float32(4.0940204), '1861419'),
  (np.float32(3.9269395), '1822371'),
  (np.float32(3.896177), '33824'),
  (np.float32(3.4473948), '805834'),
  (np.float32(3.3388083), '2184330'),
  (np.float32(3.0191417), '74607'),
  (np.float32(2.9678042), '1063548')],
 '643': [(np.float32(7.0474877), '2075490'),
  (np.float32(5.989518), '1115256'),
  (np.float32(5.636318), '643'),
  (np.float32(5.2648053), '2246138'),
  (np.float32(3.9603622), '88810'),
  (np.float32(3.8035936), '1892260'),
  (np.float32(1.4266269), '832816'),
  (np.float32(-1.091138), '1672669'),
  (np.float32(-1.2244544), '806900'),
  (np.float32(-2.1207032), '25699'),
  (np.float32(-2.1419477), '2284071'),
  (np.float32(-6.19158), '27862'),
  (np.float32(-9.380987), '1008760'),
  (np.float32(-10.502002), '205973'),
  (np.float32(-10.845321), '176281')],
 '113075': [(np.float32(8.778809), '113075'),
  (np.float32(4.6506786), '572485'),
  (np.float32(1.0471172), '20213'),
  (np.float32(-0.5005561), '46442'),
  (np.float32(-0.7553558), '60048'),
  (np.float32(-1.0922126), '1108946'),
  (np.float32(-1.310644), '625621'),
  (np.float32(-1.730262), '769187'),
  (np.float32(-1.940428), '1672942'),
  (np.float32(-2.2682896), '1690334'),
  (np.float32(-2.613553), '1039211'),
  (np.float32(-3.4474487), '11726'),
  (np.float32(-3.4914708), '1039826'),
  (np.float32(-3.7642815), '363175'),
  (np.float32(-9.911598), '798582')],
 '1250387': [(np.float32(9.64417), '1250387'),
  (np.float32(6.7097893), '2217046'),
  (np.float32(5.627881), '297902'),
  (np.float32(4.2914615), '1683108'),
  (np.float32(4.134131), '599253'),
  (np.float32(3.7051113), '95283'),
  (np.float32(3.0041957), '1268901'),
  (np.float32(1.1638005), '1794130'),
  (np.float32(0.47894633), '1732479'),
  (np.float32(-1.4004384), '748335'),
  (np.float32(-5.7348967), '185621'),
  (np.float32(-6.865045), '707898'),
  (np.float32(-7.316322), '602556'),
  (np.float32(-8.872982), '79211'),
  (np.float32(-8.95344), '2021655')],
 '72012': [(np.float32(6.7744384), '111938'),
  (np.float32(6.676139), '111443'),
  (np.float32(6.569304), '72012'),
  (np.float32(4.1388283), '2371473'),
  (np.float32(4.060516), '1806360'),
  (np.float32(3.2614026), '103174'),
  (np.float32(3.2561383), '88775'),
  (np.float32(2.4539223), '111442'),
  (np.float32(1.4240186), '661128'),
  (np.float32(-0.63569987), '941306'),
  (np.float32(-1.2564422), '147416'),
  (np.float32(-1.3042362), '727793'),
  (np.float32(-2.72857), '818663'),
  (np.float32(-4.2152495), '162840'),
  (np.float32(-8.500817), '165002')],
 '167865': [(np.float32(9.380089), '167865'),
  (np.float32(3.2629962), '1730916'),
  (np.float32(1.9035349), '1469500'),
  (np.float32(1.580163), '1155889'),
  (np.float32(1.4893199), '2006878'),
  (np.float32(1.3879458), '2366479'),
  (np.float32(1.216454), '995221'),
  (np.float32(-1.2722656), '415355'),
  (np.float32(-1.4551518), '410277'),
  (np.float32(-2.025529), '1720028'),
  (np.float32(-2.3167746), '857512'),
  (np.float32(-3.1520734), '1469315'),
  (np.float32(-3.3433447), '2345059'),
  (np.float32(-3.487946), '1930463'),
  (np.float32(-4.198592), '461641')],
 '1425120': [(np.float32(6.341257), '2316655'),
  (np.float32(5.9242454), '1425120'),
  (np.float32(5.531848), '1083694'),
  (np.float32(3.465325), '1737940'),
  (np.float32(3.119658), '735915'),
  (np.float32(2.4015975), '1641422'),
  (np.float32(2.1053374), '836205'),
  (np.float32(2.0830615), '1192652'),
  (np.float32(1.3361012), '12523'),
  (np.float32(0.43261155), '242943'),
  (np.float32(-0.8585278), '2260761'),
  (np.float32(-7.402404), '2428438'),
  (np.float32(-8.053423), '627072'),
  (np.float32(-8.209037), '360464'),
  (np.float32(-9.574913), '179529')],
 '24883': [(np.float32(4.658955), '647047'),
  (np.float32(-1.588129), '2200660'),
  (np.float32(-2.9097757), '2366040'),
  (np.float32(-2.9370425), '2003372'),
  (np.float32(-3.106535), '982243'),
  (np.float32(-3.1636007), '1346094'),
  (np.float32(-3.444951), '1357456'),
  (np.float32(-3.7140753), '1472358'),
  (np.float32(-4.6378145), '766667'),
  (np.float32(-4.8101373), '1048454'),
  (np.float32(-4.8657684), '1297674'),
  (np.float32(-5.6276827), '689411'),
  (np.float32(-5.791404), '280180'),
  (np.float32(-6.1590996), '1332226'),
  (np.float32(-6.223958), '370467')],
 '27200': [(np.float32(5.440899), '353797'),
  (np.float32(4.370307), '1865855'),
  (np.float32(3.297635), '2389598'),
  (np.float32(2.5340285), '1570665'),
  (np.float32(2.3310924), '821177'),
  (np.float32(2.0533447), '27200'),
  (np.float32(1.6370378), '1217284'),
  (np.float32(1.1308069), '621974'),
  (np.float32(0.14584763), '1863100'),
  (np.float32(0.09489678), '143487'),
  (np.float32(-0.8008351), '923643'),
  (np.float32(-0.85431767), '1834661'),
  (np.float32(-1.8220954), '881168'),
  (np.float32(-3.200779), '1409420'),
  (np.float32(-8.681524), '1536243')],
 '136856': [(np.float32(8.55061), '136856'),
  (np.float32(5.496963), '817838'),
  (np.float32(2.703748), '1045080'),
  (np.float32(1.0373611), '1505618'),
  (np.float32(0.89051926), '12030'),
  (np.float32(0.3471143), '631857'),
  (np.float32(-0.22574343), '425788'),
  (np.float32(-0.7376379), '2429792'),
  (np.float32(-1.1777024), '199322'),
  (np.float32(-1.7732441), '1714638'),
  (np.float32(-2.351679), '2398412'),
  (np.float32(-2.8643835), '1018623'),
  (np.float32(-6.3192396), '1428103'),
  (np.float32(-6.828658), '1041737'),
  (np.float32(-7.773716), '22018')],
 '6031': [(np.float32(7.022687), '6031'),
  (np.float32(6.5571666), '241657'),
  (np.float32(5.444343), '123675'),
  (np.float32(5.1069016), '23531'),
  (np.float32(4.9201145), '157645'),
  (np.float32(3.5848804), '157426'),
  (np.float32(3.0576434), '801082'),
  (np.float32(1.6556382), '978358'),
  (np.float32(1.6228244), '825709'),
  (np.float32(0.013784844), '306801'),
  (np.float32(-4.6871476), '390992'),
  (np.float32(-5.0288057), '2026699'),
  (np.float32(-5.9848804), '268'),
  (np.float32(-8.204795), '1794304'),
  (np.float32(-9.52471), '561790')],
 '1313191': [(np.float32(-10.865708), '983764'),
  (np.float32(-10.912621), '1276710'),
  (np.float32(-10.971339), '2278396'),
  (np.float32(-11.017012), '765953'),
  (np.float32(-11.063301), '1355235'),
  (np.float32(-11.065779), '2183271'),
  (np.float32(-11.09914), '1766105'),
  (np.float32(-11.118529), '66335'),
  (np.float32(-11.134766), '649770'),
  (np.float32(-11.140522), '624381'),
  (np.float32(-11.142708), '1599139'),
  (np.float32(-11.205965), '1211578'),
  (np.float32(-11.209633), '871901'),
  (np.float32(-11.249869), '521794'),
  (np.float32(-11.280727), '1585371')],
 '187115': [(np.float32(7.1999025), '187115'),
  (np.float32(4.5783443), '142017'),
  (np.float32(3.372583), '962337'),
  (np.float32(2.8244781), '964393'),
  (np.float32(2.3826487), '16835'),
  (np.float32(2.1432743), '70941'),
  (np.float32(1.7005625), '1909942'),
  (np.float32(1.6881456), '1012100'),
  (np.float32(1.1837877), '1134448'),
  (np.float32(0.13080509), '1287179'),
  (np.float32(-0.16206665), '123472'),
  (np.float32(-0.27810314), '867611'),
  (np.float32(-0.9215881), '952276'),
  (np.float32(-5.844488), '117796'),
  (np.float32(-9.28598), '2187891')],
 '84110': [(np.float32(8.23933), '84110'),
  (np.float32(5.5281773), '1463965'),
  (np.float32(4.0301456), '1395090'),
  (np.float32(3.6438484), '309827'),
  (np.float32(3.3927023), '669700'),
  (np.float32(3.153724), '2087053'),
  (np.float32(2.7611403), '350478'),
  (np.float32(1.4068153), '1673329'),
  (np.float32(1.0665182), '784975'),
  (np.float32(0.13285533), '446428'),
  (np.float32(-2.0661697), '2114632'),
  (np.float32(-7.1505165), '1773435'),
  (np.float32(-7.3118668), '830879'),
  (np.float32(-7.662636), '2217789'),
  (np.float32(-9.398382), '417446')],
 '208234': [(np.float32(7.0874786), '208234'),
  (np.float32(2.7872066), '1278779'),
  (np.float32(0.8637764), '1376164'),
  (np.float32(0.10212192), '39823'),
  (np.float32(-0.7612212), '625455'),
  (np.float32(-0.79332364), '263328'),
  (np.float32(-1.1152456), '1399530'),
  (np.float32(-1.117697), '1686554'),
  (np.float32(-2.253616), '265774'),
  (np.float32(-2.8150284), '14293'),
  (np.float32(-3.3509827), '273912'),
  (np.float32(-3.5885885), '2448203'),

In [33]:
most_related_10_with_scores = defaultdict(list)

for query_id in query_ids:
    most_related_10_with_scores[query_id] = retrieved_docs_with_scores[query_id][:10]

most_related_10_with_scores = dict(most_related_10_with_scores)

In [35]:
most_related_5_with_scores = defaultdict(list)

for query_id in query_ids:
    most_related_5_with_scores[query_id] = retrieved_docs_with_scores[query_id][:5]

most_related_5_with_scores = dict(most_related_5_with_scores)

In [37]:
qrels_dict = defaultdict(list)

for qrel in dataset.qrels_iter():
    qrels_dict[qrel.query_id].append(qrel.doc_id)

qrels_dict = dict(qrels_dict)

query_ids = [query.query_id for query in dataset.queries_iter()]

class Scoredoc:
    def __init__(self, doc_id, score):
        self.doc_id = doc_id
        self.score = score

score_doc_dict = defaultdict(list)

for scoreddoc in dataset.scoreddocs_iter():
    doc_id = scoreddoc.doc_id
    score = scoreddoc.score

    scoreddoc_object = Scoredoc(doc_id, score)

    score_doc_dict[scoreddoc.query_id].append(scoreddoc_object)

In [38]:
del dataset
del queries
del doc_texts
del doc_ids
del model
gc.collect()

2006

In [39]:
from collections import defaultdict
from sklearn.metrics import ndcg_score
import numpy as np
import pandas as pd

def recall(found_list: list, test_list: list) -> float:
    counter = 0

    test_set = set(test_list)

    for mytuple in found_list:
        if mytuple[1] in test_set:
            counter += 1

    return (counter / len(test_list)) * 100

def precision(found_list: list, test_list: list) -> float:
    if len(found_list) == 0:
        return 0

    counter = 0

    test_set = set(test_list)

    for mytuple in found_list:
        if mytuple[1] in test_set:
            counter += 1

    return (counter / len(found_list)) * 100

def precision_AP(found_docs: list, test_list: list) -> float:
    counter = 0

    test_set = set(test_list)

    for mytuple in found_docs:
        if mytuple[1] in test_set:
            counter += 1

    return counter / len(found_docs)

def AP(found_docs: list, test_list: list, value: int) -> float:
    total = 0

    for i in range(1, value + 1):
        if i < len(found_docs):
            precision_k = precision_AP(found_docs[:i], test_list)
            total += precision_k * (found_docs[i - 1][1] in set(test_list))

    return total / len(test_list)

def get_ndcg_list(most_dict: dict, value: int, query_ids: list, score_doc_dict: dict) -> list:
    doc_id_score_dict = defaultdict(float)
    ndcg_list = []

    for query_id in query_ids:
        scoredoc_object_list = score_doc_dict[query_id]

        for scoreddoc_object in scoredoc_object_list:
            doc_id_score_dict[scoreddoc_object.doc_id] = scoreddoc_object.score

        model_score_tuple_list = most_dict[query_id]
        y_score, y_true = [], []

        for mytuple in model_score_tuple_list:
            doc_id = mytuple[1]
            score = mytuple[0]

            y_score.append(score)
            y_true.append(doc_id_score_dict[doc_id])

        if len(y_score) == 0:
            ndcg_list.append(0.0)
            continue

        if len(y_score) == 1:
            y_true.append(0.0)
            y_score.append(0.0)

        if len(y_true) == len(y_score):
            ndcg_list.append(ndcg_score(np.asarray([y_true]), np.asarray([y_score]), k=value))
        else:
            print("There is a problem with query", query_id)

    return ndcg_list

- for top 10

In [40]:
recall_10_list = []

for query_id in query_ids:
    recall_10_list.append(recall(most_related_10_with_scores[query_id], qrels_dict[query_id]))

In [46]:
precision_10_list = []

for query_id in query_ids:
    precision_10_list.append(precision(most_related_10_with_scores[query_id], qrels_dict[query_id]))

In [48]:
AP_10_list = []

for query_id in query_ids:
    AP_10_list.append(AP(most_related_10_with_scores[query_id], qrels_dict[query_id], 10))

In [50]:
NDCG_10_list = get_ndcg_list(most_related_10_with_scores, 10, query_ids, score_doc_dict)

In [53]:
recall_5_list = []

for query_id in query_ids:
    recall_5_list.append(recall(most_related_5_with_scores[query_id], qrels_dict[query_id]))

precision_5_list = []

for query_id in query_ids:
    precision_5_list.append(precision(most_related_5_with_scores[query_id], qrels_dict[query_id]))

AP_5_list = []

for query_id in query_ids:
    AP_5_list.append(AP(most_related_5_with_scores[query_id], qrels_dict[query_id], 5))

NDCG_5_list = get_ndcg_list(most_related_5_with_scores, 5, query_ids, score_doc_dict)

In [54]:
def base_df(
        query_ids: list,
        recall_5: list,
        precision_5: list,
        AP_5: list,
        NDCG_5: list,
        recall_10: list,
        precision_10: list,
        AP_10: list,
        NDCG_10: list
) -> pd.DataFrame:

    df = pd.DataFrame({
        "Query_ID": query_ids,
        "recall_5": recall_5,
        "precision_5": precision_5,
        "AP_5": AP_5,
        "NDCG_5": NDCG_5,
        "recall_10": recall_10,
        "precision_10": precision_10,
        "AP_10": AP_10,
        "NDCG_10": NDCG_10
    })

    df["f_score_5"] = 2 * df["recall_5"] * df["precision_5"] / (df["recall_5"] + df["precision_5"])
    df["f_score_10"] = 2 * df["recall_10"] * df["precision_10"] / (df["recall_10"] + df["precision_10"])

    df["f_score_5"] = df["f_score_5"].fillna(0)
    df["f_score_10"] = df["f_score_10"].fillna(0)

    return df

In [55]:
df = base_df(
    query_ids=query_ids,
    recall_5=recall_5_list,
    precision_5=precision_5_list,
    AP_5=AP_5_list,
    NDCG_5=NDCG_5_list,
    recall_10=recall_10_list,
    precision_10=precision_10_list,
    AP_10=AP_10_list,
    NDCG_10=NDCG_10_list
)

df

,Query_ID,recall_5,precision_5,AP_5,NDCG_5,recall_10,precision_10,AP_10,NDCG_10,f_score_5,f_score_10
0,123839,33.333333,40.0,0.333333,1.000000,33.333333,20.0,0.333333,1.000000,36.363636,25.000000
1,188629,16.666667,20.0,0.166667,1.000000,16.666667,10.0,0.166667,0.941792,18.181818,12.500000
2,13898,33.333333,40.0,0.333333,0.000000,33.333333,20.0,0.333333,0.000000,36.363636,25.000000
3,316959,22.222222,40.0,0.222222,0.997278,22.222222,20.0,0.222222,0.997278,28.571429,21.052632
4,515031,7.142857,20.0,0.071429,0.688473,7.142857,10.0,0.071429,0.689304,10.526316,8.333333
...,...,...,...,...,...,...,...,...,...,...,...
1439,896124,12.500000,20.0,0.125000,0.957719,12.500000,10.0,0.125000,0.968451,15.384615,11.111111
1440,12319,4.545455,20.0,0.045455,0.886219,4.545455,10.0,0.045455,0.800051,7.407407,6.250000
1441,4421,0.000000,0.0,0.000000,0.897969,0.000000,0.0,0.000000,0.676304,0.000000,0.000000
1442,296526,10.000000,20.0,0.033333,0.903982,20.000000,20.0,0.055556,0.886751,13.333333,20.000000
1443,341793,14.285714,20.0,0.142857,0.998183,14.285714,10.0,0.142857,0.906891,16.666667,11.764706

In [56]:
df.isna().sum()

Query_ID        0
recall_5        0
precision_5     0
AP_5            0
NDCG_5          0
recall_10       0
precision_10    0
AP_10           0
NDCG_10         0
f_score_5       0
f_score_10      0
dtype: int64

In [57]:
def create_parquet_df(method_name: str, df: pd.DataFrame) -> pd.DataFrame:
    mydict = {
        "Method": method_name,
        "recall_5_mean": df["recall_5"].mean(),
        "recall_5_std": df["recall_5"].std(),
        "recall_5_max": df["recall_5"].max(),
        "recall_5_min": df["recall_5"].min(),
        "recall_10_mean": df["recall_10"].mean(),
        "recall_10_std": df["recall_10"].std(),
        "recall_10_max": df["recall_10"].max(),
        "recall_10_min": df["recall_10"].min(),
        "precision_5_mean": df["precision_5"].mean(),
        "precision_5_std": df["precision_5"].std(),
        "precision_5_max": df["precision_5"].max(),
        "precision_5_min": df["precision_5"].min(),
        "precision_10_mean": df["precision_10"].mean(),
        "precision_10_std": df["precision_10"].std(),
        "precision_10_max": df["precision_10"].max(),
        "precision_10_min": df["precision_10"].min(),
        "f_score_5_mean": df["f_score_5"].mean(),
        "f_score_5_std": df["f_score_5"].std(),
        "f_score_5_max": df["f_score_5"].max(),
        "f_score_5_min": df["f_score_5"].min(),
        "f_score_10_mean": df["f_score_10"].mean(),
        "f_score_10_std": df["f_score_10"].std(),
        "f_score_10_max": df["f_score_10"].max(),
        "f_score_10_min": df["f_score_10"].min(),
        "MAP_5": df["AP_5"].mean(),
        "MAP_10": df["AP_10"].mean(),
        "NDCG_5_mean": df["NDCG_5"].mean(),
        "NDCG_5_std": df["NDCG_5"].std(),
        "NDCG_5_max": df["NDCG_5"].max(),
        "NDCG_5_min": df["NDCG_5"].min(),
        "NDCG_10_mean": df["NDCG_10"].mean(),
        "NDCG_10_std": df["NDCG_10"].std(),
        "NDCG_10_max": df["NDCG_10"].max(),
        "NDCG_10_min": df["NDCG_10"].min()
    }

    df_parquet = pd.DataFrame(mydict, index=[0])

    return df_parquet

In [58]:
df_parquet = create_parquet_df("minilm_l12_reranking", df)

In [59]:
df_parquet

,Method,recall_5_mean,recall_5_std,recall_5_max,recall_5_min,recall_10_mean,recall_10_std,recall_10_max,recall_10_min,precision_5_mean,...,MAP_5,MAP_10,NDCG_5_mean,NDCG_5_std,NDCG_5_max,NDCG_5_min,NDCG_10_mean,NDCG_10_std,NDCG_10_max,NDCG_10_min
0,minilm_l12_reranking,14.16927,12.872118,66.666667,0.0,17.231414,15.961054,100.0,0.0,31.260388,...,0.11453,0.134332,0.750344,0.352292,1.0,0.0,0.752008,0.307466,1.0,0.0

In [60]:
df_parquet.to_parquet("minilm_l12_reranking.parquet")