In [1]:
import chromadb
chroma_client = chromadb.Client()

In [2]:
from chromadb.utils.embedding_functions import SentenceTransformerEmbeddingFunction

sentence_transformer_ef = SentenceTransformerEmbeddingFunction(
    model_name="all-MiniLM-L6-v2",
    device="cuda",
    normalize_embeddings=True   # unit vector
)

print("Sentence transformer hazir!")

/run/media/tahas44/Yeni Birim/Technarts/Intern/NLP/InformationRetrieval/.venv/lib64/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 13488.61it/s]

Sentence transformer hazir!

In [4]:
collection = chroma_client.get_or_create_collection(
    name="IR_System_Collection",
    embedding_function=sentence_transformer_ef
)

In [31]:
import ir_datasets
dataset = ir_datasets.load("wikir/en1k/training")
print("Data set yüklendi")

Data set yüklendi

In [6]:
doc_texts = []
doc_ids = []

for doc in dataset.docs_iter():
    doc_texts.append(doc.text)
    doc_ids.append(doc.doc_id)

### Vector Database Storage

In [10]:
from tqdm import tqdm

# ChromaDB'nin maksimum batch limitini (5461) aşmamak için 5000 seçiyoruz
BATCH_SIZE = 5000 
toplam_veri_sayisi = len(doc_texts)

print(f"Toplam {toplam_veri_sayisi} doküman, {BATCH_SIZE}'lik paketler halinde ekleniyor...")

chroma_client.delete_collection("IR_System_Collection")     # Hata alınan eski koleksiyon silindi
collection = chroma_client.create_collection("IR_System_Collection", embedding_function=sentence_transformer_ef)

for i in tqdm(range(0, toplam_veri_sayisi, BATCH_SIZE)):
    
    # Listeleri 5000'lik parçalara bölüyoruz
    batch_texts = doc_texts[i : i + BATCH_SIZE]
    batch_ids = doc_ids[i : i + BATCH_SIZE]
    
    collection.add(
        documents=batch_texts,
        ids=batch_ids
    )

print("\nTüm veriler başarıyla vektörleştirildi ve kaydedildi!")

Toplam 369721 doküman, 5000'lik paketler halinde ekleniyor...

100%|██████████| 74/74 [1:16:24<00:00, 61.95s/it]

Tüm veriler başarıyla vektörleştirildi ve kaydedildi!

In [71]:
queries = []

for query in dataset.queries_iter():
    queries.append(query.text)

### Top 10

In [13]:
results = collection.query(
    query_texts=queries,
    n_results=10
)

print("En iyi 10 doküman!")

En iyi 10 doküman!

In [21]:
qrels_dict = defaultdict(list)

for qrel in dataset.qrels_iter():
    qrels_dict[qrel.query_id].append(qrel.doc_id)

qrels_dict = dict(qrels_dict)

In [22]:
def recall(found_list: list, test_list: list) -> float:
    counter = 0

    test_set = set(test_list)

    for doc_id in found_list:
        if doc_id in test_set:
            counter += 1

    return (counter / len(test_list)) * 100

In [23]:
def precision(found_list: list, test_list: list) -> float:
    if len(found_list) == 0:
        return 0.0

    counter = 0

    test_set = set(test_list)

    for doc_id in found_list:
        if doc_id in test_set:
            counter += 1

    return (counter / len(found_list)) * 100

In [24]:
import gc
del queries
del doc_texts
del doc_ids
gc.collect()

30

In [26]:
del dataset
gc.collect()

150

In [32]:
query_ids = [query.query_id for query in dataset.queries_iter()]

In [34]:
del dataset
gc.collect()

0

In [35]:
results.keys()

dict_keys(['ids', 'embeddings', 'documents', 'uris', 'included', 'data', 'metadatas', 'distances'])

In [47]:
recall_10_list, precison_10_list = [], []

for idx in range(len(query_ids)):
    query_id = query_ids[idx]
    found_list = results['ids'][idx]
    test_list = qrels_dict[query_id]

    recall_10_list.append(recall(found_list, test_list))
    precison_10_list.append(precision(found_list, test_list))

In [50]:
def precision_AP(found_docs: list, test_list: list) -> float:
    counter = 0

    test_set = set(test_list)

    for doc in found_docs:
        if doc in test_set:
            counter += 1

    return counter / len(found_docs)


def AP(found_docs: list, test_list: list, value: int) -> float:
    total = 0

    for i in range(1, value + 1):
        if i < len(found_docs):
            precision_k = precision_AP(found_docs[:i], test_list)
            total += precision_k * (found_docs[i - 1] in set(test_list))

    return total / len(test_list)

In [51]:
AP_10_list = []

for idx in range(len(query_ids)):
    query_id = query_ids[idx]
    found_list = results['ids'][idx]
    test_list = qrels_dict[query_id]

    AP_10_list.append(AP(found_list, test_list, 10))

In [53]:
len(AP_10_list)

1444

In [54]:
import pandas as pd

df_10 = pd.DataFrame({
    "Query_ID": query_ids,
    "recall_10": recall_10_list,
    "precision_10": precison_10_list,
    "AP_10": AP_10_list
})

df_10

     Query_ID  recall_10  precision_10     AP_10
0      123839  33.333333          20.0  0.333333
1      188629  16.666667          10.0  0.166667
2       13898  16.666667          10.0  0.166667
3      316959  22.222222          20.0  0.129630
4      515031   7.142857          10.0  0.035714
...       ...        ...           ...       ...
1439   896124  25.000000          20.0  0.060714
1440    12319   4.545455          10.0  0.022727
1441     4421   6.666667          10.0  0.016667
1442   296526   0.000000           0.0  0.000000
1443   341793  14.285714          10.0  0.142857

[1444 rows x 4 columns]

In [55]:
results.keys()

dict_keys(['ids', 'embeddings', 'documents', 'uris', 'included', 'data', 'metadatas', 'distances'])

In [56]:
results['distances']

[[0.4268239736557007,
  0.5009554624557495,
  0.5429425239562988,
  0.5572776794433594,
  0.5657732486724854,
  0.5676313638687134,
  0.5693140625953674,
  0.5703406929969788,
  0.5746500492095947,
  0.5792882442474365],
 [0.3844454288482666,
  0.4175373315811157,
  0.47837793827056885,
  0.481809139251709,
  0.4850879907608032,
  0.48882514238357544,
  0.48890072107315063,
  0.49097347259521484,
  0.49315208196640015,
  0.4977993369102478],
 [0.2145460844039917,
  0.35361188650131226,
  0.3784744143486023,
  0.39791548252105713,
  0.41265302896499634,
  0.416978120803833,
  0.4171130657196045,
  0.41884851455688477,
  0.42180335521698,
  0.42187267541885376],
 [0.37485504150390625,
  0.4067419171333313,
  0.4177553653717041,
  0.4263297915458679,
  0.4300188422203064,
  0.43280458450317383,
  0.4351937770843506,
  0.4448416233062744,
  0.45565325021743774,
  0.45706331729888916],
 [0.3709142208099365,
  0.39169609546661377,
  0.4057389497756958,
  0.4109640121459961,
  0.41672980785369873,
  0.4493684768676758,
  0.460246741771698,
  0.46103668212890625,
  0.4631919860839844,
  0.4699873924255371],
 [0.38048774003982544,
  0.38224339485168457,
  0.4130074977874756,
  0.423775315284729,
  0.4259066581726074,
  0.42630714178085327,
  0.4270576238632202,
  0.4304236173629761,
  0.43148869276046753,
  0.43326836824417114],
 [0.45892393589019775,
  0.46833324432373047,
  0.5172921419143677,
  0.5248613953590393,
  0.532392144203186,
  0.539071798324585,
  0.5455441474914551,
  0.5484865307807922,
  0.5490762591362,
  0.5498425960540771],
 [0.3427697420120239,
  0.4170767068862915,
  0.4492059350013733,
  0.4509432911872864,
  0.45534759759902954,
  0.45600074529647827,
  0.45966047048568726,
  0.459710955619812,
  0.4665079116821289,
  0.4680408239364624],
 [0.3889630436897278,
  0.4116863012313843,
  0.4316931366920471,
  0.45302706956863403,
  0.4673053026199341,
  0.46953141689300537,
  0.47418272495269775,
  0.4754244089126587,
  0.4847061038017273,
  0.4857527017593384],
 [0.43703097105026245,
  0.45337414741516113,
  0.4572126269340515,
  0.4640676975250244,
  0.4681040048599243,
  0.48436468839645386,
  0.4936133027076721,
  0.49542099237442017,
  0.49774837493896484,
  0.5110102295875549],
 [0.34747934341430664,
  0.37058013677597046,
  0.3782394528388977,
  0.409878671169281,
  0.4281827211380005,
  0.444355309009552,
  0.44497358798980713,
  0.44589024782180786,
  0.450145423412323,
  0.45263415575027466],
 [0.4533233642578125,
  0.4553358554840088,
  0.4786565899848938,
  0.49935829639434814,
  0.5056881308555603,
  0.5064063668251038,
  0.5146210193634033,
  0.517656683921814,
  0.5207247734069824,
  0.5210951566696167],
 [0.3400483727455139,
  0.4174196720123291,
  0.449487566947937,
  0.4737355709075928,
  0.5176563262939453,
  0.5274851322174072,
  0.5337158441543579,
  0.5452245473861694,
  0.5467687845230103,
  0.5505592226982117],
 [0.4560434818267822,
  0.46068060398101807,
  0.46549904346466064,
  0.494625449180603,
  0.5106972455978394,
  0.5199099779129028,
  0.5342801809310913,
  0.5367203950881958,
  0.5391755700111389,
  0.5456870794296265],
 [0.35213732719421387,
  0.3755403161048889,
  0.3928534984588623,
  0.3977741003036499,
  0.4165005683898926,
  0.4166945219039917,
  0.4248819947242737,
  0.4315422773361206,
  0.4389033317565918,
  0.44735002517700195],
 [0.319222092628479,
  0.41764211654663086,
  0.48453831672668457,
  0.4959549903869629,
  0.5083795785903931,
  0.508558988571167,
  0.5093816518783569,
  0.5166828632354736,
  0.5200480818748474,
  0.5248911380767822],
 [0.29836374521255493,
  0.4099828004837036,
  0.4248969554901123,
  0.4520474672317505,
  0.45540547370910645,
  0.4605390429496765,
  0.47847336530685425,
  0.49206650257110596,
  0.502269983291626,
  0.5353101491928101],
 [0.39729905128479004,
  0.4204867482185364,
  0.43445295095443726,
  0.44309401512145996,
  0.46704113483428955,
  0.4758613705635071,
  0.4926355481147766,
  0.49590158462524414,
  0.5040302872657776,
  0.5066372156143188],
 [0.3942990303039551,
  0.3981611728668213,
  0.3999534845352173,
  0.40326035022735596,
  0.4113900661468506,
  0.4205690622329712,
  0.42075639963150024,
  0.4314865469932556,
  0.43544119596481323,
  0.43546420335769653],
 [0.34116673469543457,
  0.41084009408950806,
  0.504095733165741,
  0.5074192881584167,
  0.5092568397521973,
  0.5131980776786804,
  0.5225436687469482,
  0.531782865524292,
  0.5320611596107483,
  0.5379041433334351],
 [0.4166613221168518,
  0.4512638449668884,
  0.4677554965019226,
  0.4715690612792969,
  0.4732092022895813,
  0.4736814498901367,
  0.4881213903427124,
  0.4899476170539856,
  0.49277788400650024,
  0.4934424161911011],
 [0.3940010070800781,
  0.49065840244293213,
  0.5188379287719727,
  0.5330730676651001,
  0.5438759922981262,
  0.5453817248344421,
  0.5705470442771912,
  0.5706504583358765,
  0.5864211320877075,
  0.5895549654960632],
 [0.27642756700515747,
  0.40136873722076416,
  0.4024010896682739,
  0.45170772075653076,
  0.4850045442581177,
  0.49109798669815063,
  0.4945273995399475,
  0.49641144275665283,
  0.5019676685333252,
  0.5023221373558044],
 [0.34284472465515137,
  0.4207024574279785,
  0.46948593854904175,
  0.4823295474052429,
  0.5025913715362549,
  0.5048918724060059,
  0.5183370113372803,
  0.5186969637870789,
  0.5240511298179626,
  0.5240978002548218],
 [0.7047860622406006,
  0.7171444296836853,
  0.7291581630706787,
  0.7374096512794495,
  0.739209771156311,
  0.742741048336029,
  0.744849443435669,
  0.746459424495697,
  0.7499523162841797,
  0.7516926527023315],
 [0.49949896335601807,
  0.5460395812988281,
  0.5653674602508545,
  0.5670083165168762,
  0.576682984828949,
  0.5838996171951294,
  0.5901885032653809,
  0.5944808721542358,
  0.5966888070106506,
  0.599860668182373],
 [0.4143766164779663,
  0.44470733404159546,
  0.4671396017074585,
  0.5210509300231934,
  0.5288098454475403,
  0.5340304374694824,
  0.5429757833480835,
  0.5446526408195496,
  0.545039176940918,
  0.5559641122817993],
 [0.5627820491790771,
  0.5945453643798828,
  0.6029000282287598,
  0.6144983172416687,
  0.61501145362854,
  0.6166917085647583,
  0.6273815631866455,
  0.634081244468689,
  0.6372897624969482,
  0.6403912901878357],
 [0.36562466621398926,
  0.3737853765487671,
  0.3807775378227234,
  0.38532328605651855,
  0.407396137714386,
  0.410406231880188,
  0.41924893856048584,
  0.4211697578430176,
  0.4215080738067627,
  0.42561018466949463],
 [0.3708770275115967,
  0.4252205491065979,
  0.45376479625701904,
  0.45458441972732544,
  0.45762401819229126,
  0.4587721824645996,
  0.4653419852256775,
  0.46821653842926025,
  0.4696151614189148,
  0.4710637331008911],
 [0.43541771173477173,
  0.47417497634887695,
  0.4767758846282959,
  0.4875905513763428,
  0.49591201543807983,
  0.49818652868270874,
  0.5000491738319397,
  0.5047427415847778,
  0.5118243098258972,
  0.516708493232727],
 [0.6935135126113892,
  0.6948792338371277,
  0.6958292126655579,
  0.6971087455749512,
  0.7054474353790283,
  0.714475154876709,
  0.7151371240615845,
  0.7192187309265137,
  0.7194952964782715,
  0.7205324769020081],
 [0.37361466884613037,
  0.4638350009918213,
  0.5012074708938599,
  0.5217406153678894,
  0.52881920337677,
  0.5309928059577942,
  0.5615977048873901,
  0.5634540319442749,
  0.5662487149238586,
  0.5675832033157349],
 [0.2998899221420288,
  0.3434596657752991,
  0.37415987253189087,
  0.4270550012588501,
  0.4617490768432617,
  0.49190646409988403,
  0.4979044198989868,
  0.4986385703086853,
  0.5043824911117554,
  0.5119785070419312],
 [0.3873746991157532,
  0.40436995029449463,
  0.42547518014907837,
  0.429284930229187,
  0.4347658157348633,
  0.4366306662559509,
  0.4453425407409668,
  0.4528200626373291,
  0.4542982578277588,
  0.46076852083206177],
 [0.3136765956878662,
  0.3494742512702942,
  0.4303675889968872,
  0.4731820821762085,
  0.49107885360717773,
  0.49857234954833984,
  0.49957484006881714,
  0.5059828162193298,
  0.5221796035766602,
  0.5238130688667297],
 [0.41462385654449463,
  0.4215826392173767,
  0.4228252172470093,
  0.4635385274887085,
  0.4689173698425293,
  0.48039519786834717,
  0.4934077858924866,
  0.5093230605125427,
  0.5123316049575806,
  0.5142596364021301],
 [0.3825545310974121,
  0.40003836154937744,
  0.40396058559417725,
  0.40809035301208496,
  0.41042202711105347,
  0.4152282476425171,
  0.42146265506744385,
  0.43247783184051514,
  0.4328797459602356,
  0.4361121654510498],
 [0.3632230758666992,
  0.4920477867126465,
  0.49314987659454346,
  0.511902391910553,
  0.5140805840492249,
  0.5150216817855835,
  0.5245976448059082,
  0.5281071066856384,
  0.5313376784324646,
  0.5313725471496582],
 [0.4141426682472229,
  0.4552503228187561,
  0.4622613787651062,
  0.5018904805183411,
  0.5185577869415283,
  0.5207896828651428,
  0.5244482159614563,
  0.5319057703018188,
  0.5415551662445068,
  0.5461830496788025],
 [0.3486250638961792,
  0.4591829776763916,
  0.524493932723999,
  0.545904278755188,
  0.5672746896743774,
  0.5762134194374084,
  0.5765490531921387,
  0.5953052043914795,
  0.5966820120811462,
  0.5975677967071533],
 [0.3803200125694275,
  0.3984910845756531,
  0.4161664843559265,
  0.43087446689605713,
  0.4360494613647461,
  0.44807350635528564,
  0.46377038955688477,
  0.4697713851928711,
  0.4728797674179077,
  0.47372734546661377],
 [0.36925560235977173,
  0.4856892228126526,
  0.491524875164032,
  0.5005415678024292,
  0.5233955979347229,
  0.5405200719833374,
  0.5578525066375732,
  0.5635315775871277,
  0.5664087533950806,
  0.5665751695632935],
 [0.30224835872650146,
  0.3406715393066406,
  0.4024880528450012,
  0.4255322217941284,
  0.4461073875427246,
  0.45981091260910034,
  0.46910566091537476,
  0.4702610969543457,
  0.48193293809890747,
  0.492239773273468],
 [0.2597913146018982,
  0.29854512214660645,
  0.31243830919265747,
  0.3400641083717346,
  0.34411370754241943,
  0.3706088662147522,
  0.3877626061439514,
  0.3933168649673462,
  0.3943147659301758,
  0.41063791513442993],
 [0.33585667610168457,
  0.457136869430542,
  0.46304160356521606,
  0.4641824960708618,
  0.47285205125808716,
  0.4839802384376526,
  0.48546600341796875,
  0.486080527305603,
  0.4916508197784424,
  0.49286192655563354],
 [0.31824231147766113,
  0.3718119263648987,
  0.37657415866851807,
  0.3816409111022949,
  0.3953688144683838,
  0.417730450630188,
  0.4214319586753845,
  0.43830132484436035,
  0.44534993171691895,
  0.44762206077575684],
 [0.35284751653671265,
  0.3636356592178345,
  0.3846239447593689,
  0.3991166353225708,
  0.4188999533653259,
  0.4272072911262512,
  0.43220025300979614,
  0.436087965965271,
  0.44302672147750854,
  0.44645804166793823],
 [0.3609861135482788,
  0.3665151000022888,
  0.3880307674407959,
  0.3944130539894104,
  0.4005998373031616,
  0.40404701232910156,
  0.42220771312713623,
  0.43671876192092896,
  0.4455367922782898,
  0.4537871479988098],
 [0.4647277593612671,
  0.4915647506713867,
  0.5010985732078552,
  0.5064283609390259,
  0.5132368206977844,
  0.522284746170044,
  0.5230526924133301,
  0.5271304845809937,
  0.5354275703430176,
  0.5355848073959351],
 [0.3880346417427063,
  0.40811312198638916,
  0.4117991328239441,
  0.42124056816101074,
  0.4339931607246399,
  0.4498118758201599,
  0.4577897787094116,
  0.46718692779541016,
  0.47388947010040283,
  0.4838274121284485],
 [0.27657508850097656,
  0.3834981322288513,
  0.39087897539138794,
  0.3962467908859253,
  0.4221321940422058,
  0.4447336792945862,
  0.45024049282073975,
  0.4507814049720764,
  0.45218491554260254,
  0.45685964822769165],
 [0.5175188779830933,
  0.5195198059082031,
  0.528389036655426,
  0.5427628755569458,
  0.5532426834106445,
  0.5532910227775574,
  0.557026207447052,
  0.5578570365905762,
  0.5666453242301941,
  0.5715440511703491],
 [0.6478526592254639,
  0.6545504331588745,
  0.6565138101577759,
  0.657660186290741,
  0.6577683687210083,
  0.6587789058685303,
  0.6627919673919678,
  0.6648594737052917,
  0.6687518954277039,
  0.6703436374664307],
 [0.35337454080581665,
  0.3604455590248108,
  0.4013988971710205,
  0.4166213870048523,
  0.42304080724716187,
  0.4244287610054016,
  0.4340600371360779,
  0.438263475894928,
  0.4384613633155823,
  0.44475996494293213],
 [0.4092920422554016,
  0.45897454023361206,
  0.48090648651123047,
  0.4980025887489319,
  0.5236722826957703,
  0.5238670706748962,
  0.5427517890930176,
  0.5588397979736328,
  0.5614680647850037,
  0.5689760446548462],
 [0.4880797266960144,
  0.4974680542945862,
  0.5688759684562683,
  0.587380051612854,
  0.593346357345581,
  0.6032949090003967,
  0.6049007177352905,
  0.6121063232421875,
  0.6185154318809509,
  0.6193303465843201],
 [0.45968401432037354,
  0.5038931965827942,
  0.5054667592048645,
  0.52178555727005,
  0.5279853343963623,
  0.5381373167037964,
  0.542940616607666,
  0.5431350469589233,
  0.5454545021057129,
  0.5464212894439697],
 [0.3682745099067688,
  0.3725963830947876,
  0.38404035568237305,
  0.38875114917755127,
  0.3948322534561157,
  0.399161159992218,
  0.4017828106880188,
  0.4066997170448303,
  0.4190692901611328,
  0.4243186116218567],
 [0.4506770372390747,
  0.4520096182823181,
  0.47340893745422363,
  0.49430137872695923,
  0.49689167737960815,
  0.49922478199005127,
  0.5036925077438354,
  0.5041610598564148,
  0.505333423614502,
  0.5060586929321289],
 [0.4678277373313904,
  0.4966747760772705,
  0.4986995458602905,
  0.5011816024780273,
  0.5018288493156433,
  0.5307334661483765,
  0.5336459875106812,
  0.5353424549102783,
  0.5361165404319763,
  0.5372735261917114],
 [0.32492631673812866,
  0.4419745206832886,
  0.4581547975540161,
  0.4816588759422302,
  0.5501261949539185,
  0.5770107507705688,
  0.5773485898971558,
  0.5780702829360962,
  0.582319974899292,
  0.5872581601142883],
 [0.45529377460479736,
  0.45750516653060913,
  0.46182167530059814,
  0.47611260414123535,
  0.47685134410858154,
  0.47853922843933105,
  0.479367733001709,
  0.4811215400695801,
  0.4815041422843933,
  0.4848124384880066],
 [0.35077452659606934,
  0.3927130699157715,
  0.40656596422195435,
  0.41347765922546387,
  0.41359901428222656,
  0.4406163692474365,
  0.442446768283844,
  0.44738006591796875,
  0.45281630754470825,
  0.46940797567367554],
 [0.40067338943481445,
  0.4872073531150818,
  0.5099964141845703,
  0.5117453336715698,
  0.5268893837928772,
  0.5274966955184937,
  0.5314652323722839,
  0.5352147817611694,
  0.5360965728759766,
  0.5373756885528564],
 [0.4384204149246216,
  0.4467471241950989,
  0.45620405673980713,
  0.4577864408493042,
  0.4887097477912903,
  0.5034061670303345,
  0.5047118663787842,
  0.5050696134567261,
  0.5197728872299194,
  0.5213378667831421],
 [0.4493156671524048,
  0.5714653730392456,
  0.578877329826355,
  0.580085039138794,
  0.5924893617630005,
  0.5925165414810181,
  0.5931601524353027,
  0.6144989728927612,
  0.618080735206604,
  0.6216731071472168],
 [0.26145505905151367,
  0.4761476516723633,
  0.4789121747016907,
  0.4845201373100281,
  0.4877983331680298,
  0.4879530072212219,
  0.4963338375091553,
  0.4978317618370056,
  0.5159610509872437,
  0.5401344299316406],
 [0.4179675579071045,
  0.45470309257507324,
  0.46191197633743286,
  0.47254478931427,
  0.4777413606643677,
  0.49639225006103516,
  0.5094195604324341,
  0.5101950764656067,
  0.5239244699478149,
  0.5289944410324097],
 [0.42090940475463867,
  0.4646611213684082,
  0.4741107225418091,
  0.47600942850112915,
  0.4794917106628418,
  0.4846721887588501,
  0.49569714069366455,
  0.5084052085876465,
  0.5098455548286438,
  0.5280465483665466],
 [0.4831937551498413,
  0.5419451594352722,
  0.5720841884613037,
  0.591492235660553,
  0.6052634716033936,
  0.6093799471855164,
  0.6132844686508179,
  0.6172928810119629,
  0.6192880868911743,
  0.6201328039169312],
 [0.5020495057106018,
  0.5531312227249146,
  0.5563890933990479,
  0.5755594968795776,
  0.5815514922142029,
  0.582054615020752,
  0.5845714807510376,
  0.5845774412155151,
  0.5886496305465698,
  0.5895456075668335],
 [0.42278677225112915,
  0.43696659803390503,
  0.4453803300857544,
  0.44700348377227783,
  0.4558213949203491,
  0.4600678086280823,
  0.4757903814315796,
  0.49591755867004395,
  0.49676597118377686,
  0.4968564510345459],
 [0.3648298978805542,
  0.4851420521736145,
  0.4956316351890564,
  0.5093565583229065,
  0.5105990171432495,
  0.513740062713623,
  0.5164759159088135,
  0.5195682048797607,
  0.5227208137512207,
  0.5232054591178894],
 [0.2785017490386963,
  0.30283641815185547,
  0.354250967502594,
  0.3717503547668457,
  0.3884736895561218,
  0.393021821975708,
  0.40076208114624023,
  0.40431565046310425,
  0.4130379557609558,
  0.41837257146835327],
 [0.5426010489463806,
  0.6547960042953491,
  0.6699520349502563,
  0.6861228942871094,
  0.688066840171814,
  0.6886559724807739,
  0.6955638527870178,
  0.6977788209915161,
  0.7101799845695496,
  0.7115575075149536],
 [0.3378831744194031,
  0.42747968435287476,
  0.434863805770874,
  0.4479144215583801,
  0.4535655379295349,
  0.46254605054855347,
  0.468796968460083,
  0.47123074531555176,
  0.4769308567047119,
  0.485008180141449],
 [0.3563880920410156,
  0.43330681324005127,
  0.45903152227401733,
  0.47106868028640747,
  0.476665735244751,
  0.4771572947502136,
  0.4844464063644409,
  0.4859205484390259,
  0.49133867025375366,
  0.49476367235183716],
 [0.36699992418289185,
  0.3990364670753479,
  0.4149234890937805,
  0.4469689726829529,
  0.45809072256088257,
  0.46937042474746704,
  0.4710361957550049,
  0.4718855619430542,
  0.4725329279899597,
  0.4761401414871216],
 [0.534310519695282,
  0.5441845059394836,
  0.5786492824554443,
  0.5845106244087219,
  0.5904251337051392,
  0.5962281227111816,
  0.5962304472923279,
  0.613939642906189,
  0.6143434047698975,
  0.6187316179275513],
 [0.36598682403564453,
  0.44932985305786133,
  0.4504915475845337,
  0.45614689588546753,
  0.4644862413406372,
  0.47409588098526,
  0.48071062564849854,
  0.500210165977478,
  0.5035735368728638,
  0.506775975227356],
 [0.38873720169067383,
  0.40834325551986694,
  0.4132142663002014,
  0.4133830666542053,
  0.41495561599731445,
  0.41533786058425903,
  0.41572248935699463,
  0.42347943782806396,
  0.4236096739768982,
  0.4257131814956665],
 [0.4528964161872864,
  0.4990077614784241,
  0.505790114402771,
  0.5182060599327087,
  0.5245842933654785,
  0.5269292593002319,
  0.5306167602539062,
  0.5407308340072632,
  0.5445533990859985,
  0.5465396642684937],
 [0.3336690664291382,
  0.42665767669677734,
  0.4310753345489502,
  0.4423239231109619,
  0.4446178674697876,
  0.4508718252182007,
  0.4579259157180786,
  0.45814889669418335,
  0.4675784707069397,
  0.4677138924598694],
 [0.4038323760032654,
  0.449019193649292,
  0.49368298053741455,
  0.5032340288162231,
  0.5160849094390869,
  0.5164155960083008,
  0.5210696458816528,
  0.5280646085739136,
  0.5283473134040833,
  0.5294514894485474],
 [0.4460979700088501,
  0.4946921467781067,
  0.498307466506958,
  0.5135765671730042,
  0.5176243782043457,
  0.5254555940628052,
  0.5374299883842468,
  0.5413312911987305,
  0.5437188148498535,
  0.5443518757820129],
 [0.378126859664917,
  0.40556061267852783,
  0.4260599613189697,
  0.43319129943847656,
  0.4360297918319702,
  0.43832069635391235,
  0.44046396017074585,
  0.45219308137893677,
  0.45337241888046265,
  0.4569515585899353],
 [0.43512260913848877,
  0.43742555379867554,
  0.4431741237640381,
  0.4757436513900757,
  0.4999021291732788,
  0.5019431710243225,
  0.5302987098693848,
  0.5320333242416382,
  0.5333595275878906,
  0.5340010523796082],
 [0.3691359758377075,
  0.41675591468811035,
  0.4404534101486206,
  0.4851651191711426,
  0.4867464303970337,
  0.4876441955566406,
  0.48775267601013184,
  0.4878687262535095,
  0.4884881377220154,
  0.49124622344970703],
 [0.45576417446136475,
  0.47654104232788086,
  0.4991565942764282,
  0.5026900768280029,
  0.5233080387115479,
  0.5282702445983887,
  0.532268762588501,
  0.5324028730392456,
  0.5354670286178589,

In [57]:
scores = []

for score_list in results['distances']:
    sub_scores = []

    for score in score_list:
        sub_scores.append(1 - score)

    scores.append(sub_scores)

In [59]:
from collections import defaultdict
import ir_datasets
dataset = ir_datasets.load("wikir/en1k/training")

class Scoredoc:
    def __init__(self, doc_id, score):
        self.doc_id = doc_id
        self.score = score

score_doc_dict = defaultdict(list)

for scoreddoc in dataset.scoreddocs_iter():
    doc_id = scoreddoc.doc_id
    score = scoreddoc.score

    scoreddoc_object = Scoredoc(doc_id, score)

    score_doc_dict[scoreddoc.query_id].append(scoreddoc_object)

In [63]:
most_related_10_dict_with_scores = defaultdict(list)

for idx in range(len(query_ids)):
    for i in range(10):
        doc_id = results['ids'][idx][i]
        score = scores[idx][i]

        most_related_10_dict_with_scores[query_ids[idx]].append((doc_id, score))

In [65]:
from collections import defaultdict
from sklearn.metrics import ndcg_score
import numpy as np

doc_id_score_dict = defaultdict(float)
ndcg_10_list = []

for idx in range(len(df_10)):
    query_id = df_10.loc[idx, "Query_ID"]
    scoredoc_object_list = score_doc_dict[query_id]

    for scoreddoc_object in scoredoc_object_list:
        doc_id_score_dict[scoreddoc_object.doc_id] = scoreddoc_object.score

    model_score_tuple_list = most_related_10_dict_with_scores[query_id]

    y_score, y_true = [], []

    for mytuple in model_score_tuple_list:
        doc_id = mytuple[0]
        score = mytuple[1]

        y_score.append(score)
        y_true.append(doc_id_score_dict[doc_id])

    if len(y_score) == 0:
        ndcg_10_list.append(0.0)
        continue

    if len(y_score) == 1:
        y_true.append(0.0)
        y_score.append(0.0)

    if len(y_true) == len(y_score):
        ndcg_10_list.append(ndcg_score(np.asarray([y_true]), np.asarray([y_score]), k=10))
    else:
        print("There is a problem with query", query_id)

In [67]:
len(ndcg_10_list)

1444

In [68]:
for value in ndcg_10_list:
    try:
        myvalue = int(value)
    except:
        print("Problem")

In [69]:
df_10["NDCG_10"] = ndcg_10_list
df_10

     Query_ID  recall_10  precision_10     AP_10   NDCG_10
0      123839  33.333333          20.0  0.333333  0.918645
1      188629  16.666667          10.0  0.166667  0.847578
2       13898  16.666667          10.0  0.166667  0.000000
3      316959  22.222222          20.0  0.129630  0.693762
4      515031   7.142857          10.0  0.035714  0.859700
...       ...        ...           ...       ...       ...
1439   896124  25.000000          20.0  0.060714  0.900632
1440    12319   4.545455          10.0  0.022727  0.922079
1441     4421   6.666667          10.0  0.016667  0.596932
1442   296526   0.000000           0.0  0.000000  0.753443
1443   341793  14.285714          10.0  0.142857  0.952835

[1444 rows x 5 columns]

In [70]:
df_10.isna().sum()

Query_ID        0
recall_10       0
precision_10    0
AP_10           0
NDCG_10         0
dtype: int64

### Top 5

In [72]:
results_5 = collection.query(
    query_texts=queries,
    n_results=5
)

print("En iyi 5 doküman!")

En iyi 5 doküman!

In [73]:
recall_5_list, precison_5_list = [], []

for idx in range(len(query_ids)):
    query_id = query_ids[idx]
    found_list = results_5['ids'][idx]
    test_list = qrels_dict[query_id]

    recall_5_list.append(recall(found_list, test_list))
    precison_5_list.append(precision(found_list, test_list))

In [76]:
AP_5_list = []

for idx in range(len(query_ids)):
    query_id = query_ids[idx]
    found_list = results_5['ids'][idx]
    test_list = qrels_dict[query_id]

    AP_5_list.append(AP(found_list, test_list, 5))

In [79]:
scores_5 = []

for score_list in results_5['distances']:
    sub_scores_5 = []

    for score in score_list:
        sub_scores_5.append(1 - score)

    scores_5.append(sub_scores)

In [80]:
most_related_5_dict_with_scores = defaultdict(list)

for idx in range(len(query_ids)):
    for i in range(5):
        doc_id = results_5['ids'][idx][i]
        score = scores_5[idx][i]

        most_related_5_dict_with_scores[query_ids[idx]].append((doc_id, score))

In [81]:
from collections import defaultdict
from sklearn.metrics import ndcg_score
import numpy as np

doc_id_score_dict = defaultdict(float)
ndcg_5_list = []

for idx in range(len(df_10)):
    query_id = df_10.loc[idx, "Query_ID"]
    scoredoc_object_list = score_doc_dict[query_id]

    for scoreddoc_object in scoredoc_object_list:
        doc_id_score_dict[scoreddoc_object.doc_id] = scoreddoc_object.score

    model_score_tuple_list = most_related_5_dict_with_scores[query_id]

    y_score, y_true = [], []

    for mytuple in model_score_tuple_list:
        doc_id = mytuple[0]
        score = mytuple[1]

        y_score.append(score)
        y_true.append(doc_id_score_dict[doc_id])

    if len(y_score) == 0:
        ndcg_5_list.append(0.0)
        continue

    if len(y_score) == 1:
        y_true.append(0.0)
        y_score.append(0.0)

    if len(y_true) == len(y_score):
        ndcg_5_list.append(ndcg_score(np.asarray([y_true]), np.asarray([y_score]), k=5))
    else:
        print("There is a problem with query", query_id)

In [84]:
df_10["recall_5"] = recall_5_list
df_10["precision_5"] = precison_5_list
df_10["AP_5"] = AP_5_list
df_10["NDCG_5"] = ndcg_5_list

df_10["f_score_5"] = 2 * df_10["recall_5"] * df_10["precision_5"] / (df_10["recall_5"] + df_10["precision_5"])
df_10["f_score_10"] = 2 * df_10["recall_10"] * df_10["precision_10"] / (df_10["recall_10"] + df_10["precision_10"])

df_10

,Query_ID,recall_10,precision_10,AP_10,NDCG_10,recall_5,precision_5,AP_5,NDCG_5,f_score_5,f_score_10
0,123839,33.333333,20.0,0.333333,0.918645,33.333333,40.0,0.333333,1.000000,36.363636,25.000000
1,188629,16.666667,10.0,0.166667,0.847578,16.666667,20.0,0.166667,0.946333,18.181818,12.500000
2,13898,16.666667,10.0,0.166667,0.000000,16.666667,20.0,0.166667,0.000000,18.181818,12.500000
3,316959,22.222222,20.0,0.129630,0.693762,22.222222,40.0,0.129630,0.684296,28.571429,21.052632
4,515031,7.142857,10.0,0.035714,0.859700,7.142857,20.0,0.035714,0.898585,10.526316,8.333333
...,...,...,...,...,...,...,...,...,...,...,...
1439,896124,25.000000,20.0,0.060714,0.900632,12.500000,20.0,0.000000,0.937155,15.384615,22.222222
1440,12319,4.545455,10.0,0.022727,0.922079,4.545455,20.0,0.022727,0.980419,7.407407,6.250000
1441,4421,6.666667,10.0,0.016667,0.596932,6.666667,20.0,0.016667,0.540791,10.000000,8.000000
1442,296526,0.000000,0.0,0.000000,0.753443,0.000000,0.0,0.000000,0.693954,NaN,NaN
1443,341793,14.285714,10.0,0.142857,0.952835,14.285714,20.0,0.142857,0.976276,16.666667,11.764706

In [85]:
mydict = {
    "Method": "Sentence Transformer",
    "recall_5_mean": df_10["recall_5"].mean(),
    "recall_5_std": df_10["recall_5"].std(),
    "recall_5_max": df_10["recall_5"].max(),
    "recall_5_min": df_10["recall_5"].min(),
    "recall_10_mean": df_10["recall_10"].mean(),
    "recall_10_std": df_10["recall_10"].std(),
    "recall_10_max": df_10["recall_10"].max(),
    "recall_10_min": df_10["recall_10"].min(),
    "precision_5_mean": df_10["precision_5"].mean(),
    "precision_5_std": df_10["precision_5"].std(),
    "precision_5_max": df_10["precision_5"].max(),
    "precision_5_min": df_10["precision_5"].min(),
    "precision_10_mean": df_10["precision_10"].mean(),
    "precision_10_std": df_10["precision_10"].std(),
    "precision_10_max": df_10["precision_10"].max(),
    "precision_10_min": df_10["precision_10"].min(),
    "f_score_5_mean": df_10["f_score_5"].mean(),
    "f_score_5_std": df_10["f_score_5"].std(),
    "f_score_5_max": df_10["f_score_5"].max(),
    "f_score_5_min": df_10["f_score_5"].min(),
    "f_score_10_mean": df_10["f_score_10"].mean(),
    "f_score_10_std": df_10["f_score_10"].std(),
    "f_score_10_max": df_10["f_score_10"].max(),
    "f_score_10_min": df_10["f_score_10"].min(),
    "MAP_5": df_10["AP_5"].mean(),
    "MAP_10": df_10["AP_10"].mean(),
    "NDCG_5_mean": df_10["NDCG_5"].mean(),
    "NDCG_5_std": df_10["NDCG_5"].std(),
    "NDCG_5_max": df_10["NDCG_5"].max(),
    "NDCG_5_min": df_10["NDCG_5"].min(),
    "NDCG_10_mean": df_10["NDCG_10"].mean(),
    "NDCG_10_std": df_10["NDCG_10"].std(),
    "NDCG_10_max": df_10["NDCG_10"].max(),
    "NDCG_10_min": df_10["NDCG_10"].min()
}

In [86]:
df_parquet = pd.DataFrame(mydict, index=[0])
df_parquet

,Method,recall_5_mean,recall_5_std,recall_5_max,recall_5_min,recall_10_mean,recall_10_std,recall_10_max,recall_10_min,precision_5_mean,...,MAP_5,MAP_10,NDCG_5_mean,NDCG_5_std,NDCG_5_max,NDCG_5_min,NDCG_10_mean,NDCG_10_std,NDCG_10_max,NDCG_10_min
0,Sentence Transformer,12.190058,12.517122,66.666667,0.0,15.646733,15.715276,85.714286,0.0,27.202216,...,0.094242,0.112406,0.6981,0.363412,1.0,0.0,0.70553,0.307505,1.0,0.0

In [87]:
df_parquet.to_parquet("SentenceTransformer.parquet")